#!/bin/bash

echo "computing slice for ExtendedCategoryAxisTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/axis_slices/ExtendedCategoryAxisTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/ExtendedCategoryAxisTest.trace org.jfree.chart.axis.ExtendedCategoryAxisTest.testEquals:68:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/ExtendedCategoryAxisTest/ExtendedCategoryAxisTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/ExtendedCategoryAxisTest.trace org.jfree.chart.axis.ExtendedCategoryAxisTest.testEquals:71:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/ExtendedCategoryAxisTest/ExtendedCategoryAxisTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/ExtendedCategoryAxisTest.trace org.jfree.chart.axis.ExtendedCategoryAxisTest.testEquals:73:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/ExtendedCategoryAxisTest/ExtendedCategoryAxisTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/ExtendedCategoryAxisTest.trace org.jfree.chart.axis.ExtendedCategoryAxisTest.testEquals:76:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/ExtendedCategoryAxisTest/ExtendedCategoryAxisTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/ExtendedCategoryAxisTest.trace org.jfree.chart.axis.ExtendedCategoryAxisTest.testEquals:78:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/ExtendedCategoryAxisTest/ExtendedCategoryAxisTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/ExtendedCategoryAxisTest.trace org.jfree.chart.axis.ExtendedCategoryAxisTest.testEquals:81:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/ExtendedCategoryAxisTest/ExtendedCategoryAxisTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/ExtendedCategoryAxisTest.trace org.jfree.chart.axis.ExtendedCategoryAxisTest.testEquals:83:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/ExtendedCategoryAxisTest/ExtendedCategoryAxisTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/ExtendedCategoryAxisTest.trace org.jfree.chart.axis.ExtendedCategoryAxisTest.testHashCode:93:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/ExtendedCategoryAxisTest/ExtendedCategoryAxisTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/ExtendedCategoryAxisTest.trace org.jfree.chart.axis.ExtendedCategoryAxisTest.testHashCode:96:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/ExtendedCategoryAxisTest/ExtendedCategoryAxisTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/ExtendedCategoryAxisTest.trace org.jfree.chart.axis.ExtendedCategoryAxisTest.testCloning:106:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/ExtendedCategoryAxisTest/ExtendedCategoryAxisTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/ExtendedCategoryAxisTest.trace org.jfree.chart.axis.ExtendedCategoryAxisTest.testCloning:107:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/ExtendedCategoryAxisTest/ExtendedCategoryAxisTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/ExtendedCategoryAxisTest.trace org.jfree.chart.axis.ExtendedCategoryAxisTest.testCloning:108:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/ExtendedCategoryAxisTest/ExtendedCategoryAxisTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/ExtendedCategoryAxisTest.trace org.jfree.chart.axis.ExtendedCategoryAxisTest.testCloning:112:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/ExtendedCategoryAxisTest/ExtendedCategoryAxisTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/ExtendedCategoryAxisTest.trace org.jfree.chart.axis.ExtendedCategoryAxisTest.testCloning:114:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/ExtendedCategoryAxisTest/ExtendedCategoryAxisTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/ExtendedCategoryAxisTest.trace org.jfree.chart.axis.ExtendedCategoryAxisTest.testCloning2:128:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/ExtendedCategoryAxisTest/ExtendedCategoryAxisTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/ExtendedCategoryAxisTest.trace org.jfree.chart.axis.ExtendedCategoryAxisTest.testCloning2:129:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/ExtendedCategoryAxisTest/ExtendedCategoryAxisTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/ExtendedCategoryAxisTest.trace org.jfree.chart.axis.ExtendedCategoryAxisTest.testCloning2:130:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/ExtendedCategoryAxisTest/ExtendedCategoryAxisTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/ExtendedCategoryAxisTest.trace org.jfree.chart.axis.ExtendedCategoryAxisTest.testCloning2:134:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/ExtendedCategoryAxisTest/ExtendedCategoryAxisTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/ExtendedCategoryAxisTest.trace org.jfree.chart.axis.ExtendedCategoryAxisTest.testCloning2:136:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/ExtendedCategoryAxisTest/ExtendedCategoryAxisTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/ExtendedCategoryAxisTest.trace org.jfree.chart.axis.ExtendedCategoryAxisTest.testCloning2:140:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/ExtendedCategoryAxisTest/ExtendedCategoryAxisTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/ExtendedCategoryAxisTest.trace org.jfree.chart.axis.ExtendedCategoryAxisTest.testCloning2:142:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/ExtendedCategoryAxisTest/ExtendedCategoryAxisTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/ExtendedCategoryAxisTest.trace org.jfree.chart.axis.ExtendedCategoryAxisTest.testCloning2:146:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/ExtendedCategoryAxisTest/ExtendedCategoryAxisTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/ExtendedCategoryAxisTest.trace org.jfree.chart.axis.ExtendedCategoryAxisTest.testCloning2:148:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/ExtendedCategoryAxisTest/ExtendedCategoryAxisTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/ExtendedCategoryAxisTest.trace org.jfree.chart.axis.ExtendedCategoryAxisTest.testSerialization:161:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/ExtendedCategoryAxisTest/ExtendedCategoryAxisTest24.txt

#Total Asserts in org.jfree.chart.axis/ExtendedCategoryAxisTest=============24
#Total Tests in org.jfree.chart.axis/ExtendedCategoryAxisTest=============0
