#!/bin/bash

echo "computing slice for MonthDateFormatTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/axis_slices/MonthDateFormatTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/MonthDateFormatTest.trace org.jfree.chart.axis.MonthDateFormatTest.testEquals:66:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/MonthDateFormatTest/MonthDateFormatTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/MonthDateFormatTest.trace org.jfree.chart.axis.MonthDateFormatTest.testEquals:67:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/MonthDateFormatTest/MonthDateFormatTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/MonthDateFormatTest.trace org.jfree.chart.axis.MonthDateFormatTest.testEquals:77:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/MonthDateFormatTest/MonthDateFormatTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/MonthDateFormatTest.trace org.jfree.chart.axis.MonthDateFormatTest.testEquals:80:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/MonthDateFormatTest/MonthDateFormatTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/MonthDateFormatTest.trace org.jfree.chart.axis.MonthDateFormatTest.testEquals:85:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/MonthDateFormatTest/MonthDateFormatTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/MonthDateFormatTest.trace org.jfree.chart.axis.MonthDateFormatTest.testEquals:88:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/MonthDateFormatTest/MonthDateFormatTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/MonthDateFormatTest.trace org.jfree.chart.axis.MonthDateFormatTest.testEquals:93:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/MonthDateFormatTest/MonthDateFormatTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/MonthDateFormatTest.trace org.jfree.chart.axis.MonthDateFormatTest.testEquals:96:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/MonthDateFormatTest/MonthDateFormatTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/MonthDateFormatTest.trace org.jfree.chart.axis.MonthDateFormatTest.testEquals:101:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/MonthDateFormatTest/MonthDateFormatTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/MonthDateFormatTest.trace org.jfree.chart.axis.MonthDateFormatTest.testEquals:104:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/MonthDateFormatTest/MonthDateFormatTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/MonthDateFormatTest.trace org.jfree.chart.axis.MonthDateFormatTest.testEquals:109:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/MonthDateFormatTest/MonthDateFormatTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/MonthDateFormatTest.trace org.jfree.chart.axis.MonthDateFormatTest.testEquals:112:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/MonthDateFormatTest/MonthDateFormatTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/MonthDateFormatTest.trace org.jfree.chart.axis.MonthDateFormatTest.testHashCode:123:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/MonthDateFormatTest/MonthDateFormatTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/MonthDateFormatTest.trace org.jfree.chart.axis.MonthDateFormatTest.testHashCode:126:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/MonthDateFormatTest/MonthDateFormatTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/MonthDateFormatTest.trace org.jfree.chart.axis.MonthDateFormatTest.testCloning:137:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/MonthDateFormatTest/MonthDateFormatTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/MonthDateFormatTest.trace org.jfree.chart.axis.MonthDateFormatTest.testCloning:138:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/MonthDateFormatTest/MonthDateFormatTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/MonthDateFormatTest.trace org.jfree.chart.axis.MonthDateFormatTest.testCloning:139:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/MonthDateFormatTest/MonthDateFormatTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/MonthDateFormatTest.trace org.jfree.chart.axis.MonthDateFormatTest.testSerialization:149:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/MonthDateFormatTest/MonthDateFormatTest18.txt

#Total Asserts in org.jfree.chart.axis/MonthDateFormatTest=============18
#Total Tests in org.jfree.chart.axis/MonthDateFormatTest=============0
