#!/bin/bash

echo "computing slice for DateTickTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/axis_slices/DateTickTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/DateTickTest.trace org.jfree.chart.axis.DateTickTest.testEquals:73:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/DateTickTest/DateTickTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/DateTickTest.trace org.jfree.chart.axis.DateTickTest.testEquals:76:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/DateTickTest/DateTickTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/DateTickTest.trace org.jfree.chart.axis.DateTickTest.testEquals:78:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/DateTickTest/DateTickTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/DateTickTest.trace org.jfree.chart.axis.DateTickTest.testEquals:81:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/DateTickTest/DateTickTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/DateTickTest.trace org.jfree.chart.axis.DateTickTest.testEquals:83:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/DateTickTest/DateTickTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/DateTickTest.trace org.jfree.chart.axis.DateTickTest.testEquals:86:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/DateTickTest/DateTickTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/DateTickTest.trace org.jfree.chart.axis.DateTickTest.testEquals:88:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/DateTickTest/DateTickTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/DateTickTest.trace org.jfree.chart.axis.DateTickTest.testEquals:91:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/DateTickTest/DateTickTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/DateTickTest.trace org.jfree.chart.axis.DateTickTest.testEquals:93:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/DateTickTest/DateTickTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/DateTickTest.trace org.jfree.chart.axis.DateTickTest.testEquals:96:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/DateTickTest/DateTickTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/DateTickTest.trace org.jfree.chart.axis.DateTickTest.testEquals:98:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/DateTickTest/DateTickTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/DateTickTest.trace org.jfree.chart.axis.DateTickTest.testEquals:102:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/DateTickTest/DateTickTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/DateTickTest.trace org.jfree.chart.axis.DateTickTest.testEquals:104:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/DateTickTest/DateTickTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/DateTickTest.trace org.jfree.chart.axis.DateTickTest.testHashCode:118:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/DateTickTest/DateTickTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/DateTickTest.trace org.jfree.chart.axis.DateTickTest.testHashCode:121:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/DateTickTest/DateTickTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/DateTickTest.trace org.jfree.chart.axis.DateTickTest.testCloning:132:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/DateTickTest/DateTickTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/DateTickTest.trace org.jfree.chart.axis.DateTickTest.testCloning:133:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/DateTickTest/DateTickTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/DateTickTest.trace org.jfree.chart.axis.DateTickTest.testCloning:134:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/DateTickTest/DateTickTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/DateTickTest.trace org.jfree.chart.axis.DateTickTest.testSerialization:145:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/DateTickTest/DateTickTest19.txt

#Total Asserts in org.jfree.chart.axis/DateTickTest=============19
#Total Tests in org.jfree.chart.axis/DateTickTest=============0
