#!/bin/bash

echo "computing slice for LogarithmicAxisTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/axis_slices/LogarithmicAxisTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/LogarithmicAxisTest.trace org.jfree.chart.axis.LogarithmicAxisTest.testSerialization:109:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/LogarithmicAxisTest/LogarithmicAxisTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/LogarithmicAxisTest.trace org.jfree.chart.axis.LogarithmicAxisTest.checkLogPowRoundTrip:128:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/LogarithmicAxisTest/LogarithmicAxisTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/LogarithmicAxisTest.trace org.jfree.chart.axis.LogarithmicAxisTest.checkLogPowRoundTrip:130:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/LogarithmicAxisTest/LogarithmicAxisTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/LogarithmicAxisTest.trace org.jfree.chart.axis.LogarithmicAxisTest.testSwitchedLog10:139:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/LogarithmicAxisTest/LogarithmicAxisTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/LogarithmicAxisTest.trace org.jfree.chart.axis.LogarithmicAxisTest.testSwitchedLog10:142:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/LogarithmicAxisTest/LogarithmicAxisTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/LogarithmicAxisTest.trace org.jfree.chart.axis.LogarithmicAxisTest.checkSwitchedLogPowRoundTrip:155:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/LogarithmicAxisTest/LogarithmicAxisTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/LogarithmicAxisTest.trace org.jfree.chart.axis.LogarithmicAxisTest.checkSwitchedLogPowRoundTrip:157:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/LogarithmicAxisTest/LogarithmicAxisTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/LogarithmicAxisTest.trace org.jfree.chart.axis.LogarithmicAxisTest.checkPointsToJava2D:213:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/LogarithmicAxisTest/LogarithmicAxisTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/LogarithmicAxisTest.trace org.jfree.chart.axis.LogarithmicAxisTest.checkPointsToJava2D:216:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/LogarithmicAxisTest/LogarithmicAxisTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/LogarithmicAxisTest.trace org.jfree.chart.axis.LogarithmicAxisTest.checkPointsToJava2D:220:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/LogarithmicAxisTest/LogarithmicAxisTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/LogarithmicAxisTest.trace org.jfree.chart.axis.LogarithmicAxisTest.checkPointsToValue:233:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/LogarithmicAxisTest/LogarithmicAxisTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/LogarithmicAxisTest.trace org.jfree.chart.axis.LogarithmicAxisTest.checkPointsToValue:238:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/LogarithmicAxisTest/LogarithmicAxisTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/LogarithmicAxisTest.trace org.jfree.chart.axis.LogarithmicAxisTest.checkPointsToValue:243:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/LogarithmicAxisTest/LogarithmicAxisTest13.txt

#Total Asserts in org.jfree.chart.axis/LogarithmicAxisTest=============13
#Total Tests in org.jfree.chart.axis/LogarithmicAxisTest=============0
