#!/bin/bash

echo "computing slice for AxisTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testCloning:76:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testCloning:77:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testCloning:78:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testEquals:88:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testEquals:94:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testEquals:100:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testEquals:106:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testEquals:114:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testEquals:120:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testEquals:131:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testEquals:137:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testEquals:143:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testEquals:149:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testEquals:155:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testEquals:162:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testEquals:170:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testEquals:176:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testEquals:182:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testEquals:190:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testEquals:196:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testEquals:202:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testEquals:208:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testEquals:214:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testEquals:220:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testEquals:228:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testEquals:234:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testEquals:239:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testEquals:244:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testEquals:249:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testHashCode:259:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testHashCode:262:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/AxisTest.trace org.jfree.chart.axis.AxisTest.testSerialization:276:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/AxisTest/AxisTest32.txt

#Total Asserts in org.jfree.chart.axis/AxisTest=============32
#Total Tests in org.jfree.chart.axis/AxisTest=============0
