#!/bin/bash

echo "computing slice for NumberAxisTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testCloning:83:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testCloning:84:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testCloning:85:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testEquals:96:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testEquals:100:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testEquals:102:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testEquals:106:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testEquals:108:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testEquals:112:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testEquals:114:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testEquals:118:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testEquals:120:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testEquals:123:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testEquals:125:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testHashCode:136:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testHashCode:139:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testTranslateJava2DToValue:153:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testTranslateJava2DToValue:155:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testTranslateJava2DToValue:157:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testTranslateJava2DToValue:159:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testTranslateJava2DToValue:162:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testTranslateJava2DToValue:164:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testTranslateJava2DToValue:166:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testTranslateJava2DToValue:168:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testSerialization:178:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testAutoRange1:194:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testAutoRange1:195:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testAutoRange2:214:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testAutoRange2:215:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testAutoRange3:235:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testAutoRange3:236:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testAutoRange3:243:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest32.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testAutoRange3:244:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest33.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testAutoRange4:264:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest34.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testAutoRange4:265:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest35.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testAutoRange4:268:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest36.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testAutoRange4:269:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest37.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testAutoRange4:272:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest38.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testAutoRange4:273:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest39.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testAutoRange4:276:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest40.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testAutoRange4:277:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest41.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testAutoRange4:284:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest42.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testAutoRange4:285:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest43.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testAutoRange4:288:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest44.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testAutoRange4:289:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest45.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testAutoRange4:292:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest46.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testAutoRange4:293:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest47.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testXYAutoRange1:313:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest48.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testXYAutoRange1:314:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest49.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testXYAutoRange2:334:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest50.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testXYAutoRange2:335:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest51.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testSetLowerBound:390:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest52.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testSetLowerBound:392:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest53.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/axis_traces/NumberAxisTest.trace org.jfree.chart.axis.NumberAxisTest.testSetLowerBound:393:*>/home/stg/omc_experiments/slices/jfreechart/axis_slices/NumberAxisTest/NumberAxisTest54.txt

#Total Asserts in org.jfree.chart.axis/NumberAxisTest=============54
#Total Tests in org.jfree.chart.axis/NumberAxisTest=============0
