#!/bin/bash

echo "computing slice for XStreamTest"

mkdir -p /home/stg/omc_experiments/slices/xstream/xstream_slices/XStreamTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xstream_traces/XStreamTest.trace com.thoughtworks.xstream.XStreamTest.testUnmarshalsObjectFromXmlWithUnderscores:78:*>/home/stg/omc_experiments/slices/xstream/xstream_slices/XStreamTest/XStreamTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xstream_traces/XStreamTest.trace com.thoughtworks.xstream.XStreamTest.testUnmarshalsObjectFromXmlWithUnderscores:79:*>/home/stg/omc_experiments/slices/xstream/xstream_slices/XStreamTest/XStreamTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xstream_traces/XStreamTest.trace com.thoughtworks.xstream.XStreamTest.testUnmarshalsObjectFromXmlWithClassContainingUnderscores:90:*>/home/stg/omc_experiments/slices/xstream/xstream_slices/XStreamTest/XStreamTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xstream_traces/XStreamTest.trace com.thoughtworks.xstream.XStreamTest.testUnmarshalsObjectFromXmlWithUnderscoresWithoutAliasingFields:104:*>/home/stg/omc_experiments/slices/xstream/xstream_slices/XStreamTest/XStreamTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xstream_traces/XStreamTest.trace com.thoughtworks.xstream.XStreamTest.testUnmarshalsObjectFromXml:124:*>/home/stg/omc_experiments/slices/xstream/xstream_slices/XStreamTest/XStreamTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xstream_traces/XStreamTest.trace com.thoughtworks.xstream.XStreamTest.testUnmarshalsObjectFromXml:125:*>/home/stg/omc_experiments/slices/xstream/xstream_slices/XStreamTest/XStreamTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xstream_traces/XStreamTest.trace com.thoughtworks.xstream.XStreamTest.testUnmarshalsObjectFromXml:126:*>/home/stg/omc_experiments/slices/xstream/xstream_slices/XStreamTest/XStreamTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xstream_traces/XStreamTest.trace com.thoughtworks.xstream.XStreamTest.testMarshalsObjectToXml:145:*>/home/stg/omc_experiments/slices/xstream/xstream_slices/XStreamTest/XStreamTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xstream_traces/XStreamTest.trace com.thoughtworks.xstream.XStreamTest.testUnmarshalsClassWithoutDefaultConstructor:158:*>/home/stg/omc_experiments/slices/xstream/xstream_slices/XStreamTest/XStreamTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xstream_traces/XStreamTest.trace com.thoughtworks.xstream.XStreamTest.testHandlesLists:186:*>/home/stg/omc_experiments/slices/xstream/xstream_slices/XStreamTest/XStreamTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xstream_traces/XStreamTest.trace com.thoughtworks.xstream.XStreamTest.testHandlesLists:189:*>/home/stg/omc_experiments/slices/xstream/xstream_slices/XStreamTest/XStreamTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xstream_traces/XStreamTest.trace com.thoughtworks.xstream.XStreamTest.testCanHandleNonStaticPrivateInnerClass:211:*>/home/stg/omc_experiments/slices/xstream/xstream_slices/XStreamTest/XStreamTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xstream_traces/XStreamTest.trace com.thoughtworks.xstream.XStreamTest.testCanHandleNonStaticPrivateInnerClass:214:*>/home/stg/omc_experiments/slices/xstream/xstream_slices/XStreamTest/XStreamTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xstream_traces/XStreamTest.trace com.thoughtworks.xstream.XStreamTest.testClassWithoutMappingUsesFullyQualifiedName:224:*>/home/stg/omc_experiments/slices/xstream/xstream_slices/XStreamTest/XStreamTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xstream_traces/XStreamTest.trace com.thoughtworks.xstream.XStreamTest.testClassWithoutMappingUsesFullyQualifiedName:227:*>/home/stg/omc_experiments/slices/xstream/xstream_slices/XStreamTest/XStreamTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xstream_traces/XStreamTest.trace com.thoughtworks.xstream.XStreamTest.testCanBeBeUsedMultipleTimesWithSameInstance:238:*>/home/stg/omc_experiments/slices/xstream/xstream_slices/XStreamTest/XStreamTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xstream_traces/XStreamTest.trace com.thoughtworks.xstream.XStreamTest.testAccessToUnderlyingDom4JImplementation:259:*>/home/stg/omc_experiments/slices/xstream/xstream_slices/XStreamTest/XStreamTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xstream_traces/XStreamTest.trace com.thoughtworks.xstream.XStreamTest.testAccessToUnderlyingDom4JImplementation:260:*>/home/stg/omc_experiments/slices/xstream/xstream_slices/XStreamTest/XStreamTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xstream_traces/XStreamTest.trace com.thoughtworks.xstream.XStreamTest.testAccessToUnderlyingDom4JImplementation:261:*>/home/stg/omc_experiments/slices/xstream/xstream_slices/XStreamTest/XStreamTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xstream_traces/XStreamTest.trace com.thoughtworks.xstream.XStreamTest.testAccessToUnderlyingDom4JImplementation:262:*>/home/stg/omc_experiments/slices/xstream/xstream_slices/XStreamTest/XStreamTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xstream_traces/XStreamTest.trace com.thoughtworks.xstream.XStreamTest.testPopulationOfAnObjectGraphStartingWithALiveRootObject:307:*>/home/stg/omc_experiments/slices/xstream/xstream_slices/XStreamTest/XStreamTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xstream_traces/XStreamTest.trace com.thoughtworks.xstream.XStreamTest.testPopulationOfAnObjectGraphStartingWithALiveRootObject:308:*>/home/stg/omc_experiments/slices/xstream/xstream_slices/XStreamTest/XStreamTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xstream_traces/XStreamTest.trace com.thoughtworks.xstream.XStreamTest.testPopulationOfAnObjectGraphStartingWithALiveRootObject:309:*>/home/stg/omc_experiments/slices/xstream/xstream_slices/XStreamTest/XStreamTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xstream_traces/XStreamTest.trace com.thoughtworks.xstream.XStreamTest.testPopulationOfThisAsRootObject:330:*>/home/stg/omc_experiments/slices/xstream/xstream_slices/XStreamTest/XStreamTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xstream_traces/XStreamTest.trace com.thoughtworks.xstream.XStreamTest.testPopulationOfThisAsRootObject:334:*>/home/stg/omc_experiments/slices/xstream/xstream_slices/XStreamTest/XStreamTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xstream_traces/XStreamTest.trace com.thoughtworks.xstream.XStreamTest.testPopulationOfThisAsRootObject:335:*>/home/stg/omc_experiments/slices/xstream/xstream_slices/XStreamTest/XStreamTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xstream_traces/XStreamTest.trace com.thoughtworks.xstream.XStreamTest.testUnmarshalsWhenAllImplementationsAreSpecifiedUsingAClassIdentifier:364:*>/home/stg/omc_experiments/slices/xstream/xstream_slices/XStreamTest/XStreamTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xstream_traces/XStreamTest.trace com.thoughtworks.xstream.XStreamTest.testUnmarshalsFromFile:403:*>/home/stg/omc_experiments/slices/xstream/xstream_slices/XStreamTest/XStreamTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xstream_traces/XStreamTest.trace com.thoughtworks.xstream.XStreamTest.testUnmarshalsFromURL:410:*>/home/stg/omc_experiments/slices/xstream/xstream_slices/XStreamTest/XStreamTest29.txt

#Total Asserts in com.thoughtworks.xstream/XStreamTest=============29
#Total Tests in com.thoughtworks.xstream/XStreamTest=============0
