#!/bin/bash

echo "computing slice for DateConverterTest"

mkdir -p /home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testRetainsDetailDownToMillisecondLevel:61:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testRetainsDetailDownToMillisecondLevel:62:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testRetainsDetailDownToMillisecondLevel:63:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testUnmarshalsOldXStreamDatesThatLackMillisecond:70:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testUnmarshalsOldXStreamDatesThatLackMillisecond:71:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testUnmarshalsOldXStreamDatesThatLackMillisecond:72:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testUnmarshalsOldXStreamDatesThatLackMillisecond:75:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testUnmarshalsOldXStreamDatesThatLackMillisecond:76:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testUnmarshalsDatesWithDifferentTimeZones:83:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testUnmarshalsDatesWithDifferentTimeZones:84:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testUnmarshalsDatesWithDifferentTimeZones:85:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testUnmarshalsDatesWithDifferentTimeZones:86:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testUnmarshalsDatesWithDifferentTimeZones:87:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testUnmarshalsDatesWithDifferentTimeZones:91:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testUnmarshalsDatesWithDifferentTimeZones:92:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testUnmarshalsDatesWithDifferentTimeZones:93:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testUnmarshalsDatesWithDifferentTimeZones:95:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testUnmarshalsDateWithDifferentDefaultTimeZones:106:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testUnmarshalsDateWithDifferentDefaultTimeZones:113:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testUnmarshalsDateWithDifferentDefaultTimeZones:117:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testUnmarshalsDateWithDifferentDefaultTimeZones:121:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testUnmarshalsDateWithDifferentDefaultTimeZones:122:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testUnmarshalsDateWithDifferentDefaultTimeZones:126:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testUnmarshalsDateWithDifferentDefaultTimeZones:127:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.run:165:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.run:166:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testDatesInNonLenientMode:173:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testDatesInLenientMode:179:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testDatesIn70sInTimeZoneGMT:206:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testDatesWithAmbiguous3LetterTimeZones:212:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testDatesWithEpoche:218:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testDatesWithEpoche:223:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest32.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testDatesWithEpoche:224:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest33.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testDatesWithEpoche:226:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest34.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testDatesWithEnglishLocaleOfDefault:237:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest35.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testDatesWithEnglishLocaleOfDefault:238:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest36.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testDatesWithGermanLocale:249:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest37.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/basic_traces/DateConverterTest.trace com.thoughtworks.xstream.converters.basic.DateConverterTest.testDatesWithGermanLocale:250:*>/home/stg/omc_experiments/slices/xstream/basic_slices/DateConverterTest/DateConverterTest38.txt

#Total Asserts in com.thoughtworks.xstream.converters.basic/DateConverterTest=============38
#Total Tests in com.thoughtworks.xstream.converters.basic/DateConverterTest=============0
