#!/bin/bash

echo "computing slice for WeakCacheTest"

mkdir -p /home/stg/omc_experiments/slices/xstream/util_slices/WeakCacheTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/util_traces/WeakCacheTest.trace com.thoughtworks.xstream.core.util.WeakCacheTest.testIsAMap:36:*>/home/stg/omc_experiments/slices/xstream/util_slices/WeakCacheTest/WeakCacheTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/util_traces/WeakCacheTest.trace com.thoughtworks.xstream.core.util.WeakCacheTest.testIsAMap:37:*>/home/stg/omc_experiments/slices/xstream/util_slices/WeakCacheTest/WeakCacheTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/util_traces/WeakCacheTest.trace com.thoughtworks.xstream.core.util.WeakCacheTest.testIsAMap:38:*>/home/stg/omc_experiments/slices/xstream/util_slices/WeakCacheTest/WeakCacheTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/util_traces/WeakCacheTest.trace com.thoughtworks.xstream.core.util.WeakCacheTest.testIsAMap:39:*>/home/stg/omc_experiments/slices/xstream/util_slices/WeakCacheTest/WeakCacheTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/util_traces/WeakCacheTest.trace com.thoughtworks.xstream.core.util.WeakCacheTest.testIsAMap:40:*>/home/stg/omc_experiments/slices/xstream/util_slices/WeakCacheTest/WeakCacheTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/util_traces/WeakCacheTest.trace com.thoughtworks.xstream.core.util.WeakCacheTest.testIsAMap:41:*>/home/stg/omc_experiments/slices/xstream/util_slices/WeakCacheTest/WeakCacheTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/util_traces/WeakCacheTest.trace com.thoughtworks.xstream.core.util.WeakCacheTest.testIsAMap:42:*>/home/stg/omc_experiments/slices/xstream/util_slices/WeakCacheTest/WeakCacheTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/util_traces/WeakCacheTest.trace com.thoughtworks.xstream.core.util.WeakCacheTest.testIsAMap:43:*>/home/stg/omc_experiments/slices/xstream/util_slices/WeakCacheTest/WeakCacheTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/util_traces/WeakCacheTest.trace com.thoughtworks.xstream.core.util.WeakCacheTest.testIsAMap:44:*>/home/stg/omc_experiments/slices/xstream/util_slices/WeakCacheTest/WeakCacheTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/util_traces/WeakCacheTest.trace com.thoughtworks.xstream.core.util.WeakCacheTest.testIsAMap:45:*>/home/stg/omc_experiments/slices/xstream/util_slices/WeakCacheTest/WeakCacheTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/util_traces/WeakCacheTest.trace com.thoughtworks.xstream.core.util.WeakCacheTest.testIsAMap:46:*>/home/stg/omc_experiments/slices/xstream/util_slices/WeakCacheTest/WeakCacheTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/util_traces/WeakCacheTest.trace com.thoughtworks.xstream.core.util.WeakCacheTest.testIsAMap:48:*>/home/stg/omc_experiments/slices/xstream/util_slices/WeakCacheTest/WeakCacheTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/util_traces/WeakCacheTest.trace com.thoughtworks.xstream.core.util.WeakCacheTest.testIsAMap:49:*>/home/stg/omc_experiments/slices/xstream/util_slices/WeakCacheTest/WeakCacheTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/util_traces/WeakCacheTest.trace com.thoughtworks.xstream.core.util.WeakCacheTest.testIsAMap:51:*>/home/stg/omc_experiments/slices/xstream/util_slices/WeakCacheTest/WeakCacheTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/util_traces/WeakCacheTest.trace com.thoughtworks.xstream.core.util.WeakCacheTest.testIsAMap:52:*>/home/stg/omc_experiments/slices/xstream/util_slices/WeakCacheTest/WeakCacheTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/util_traces/WeakCacheTest.trace com.thoughtworks.xstream.core.util.WeakCacheTest.testIsAMap:54:*>/home/stg/omc_experiments/slices/xstream/util_slices/WeakCacheTest/WeakCacheTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/util_traces/WeakCacheTest.trace com.thoughtworks.xstream.core.util.WeakCacheTest.testEntriesAreRemovedIfKeyIsGarbageCollected:69:*>/home/stg/omc_experiments/slices/xstream/util_slices/WeakCacheTest/WeakCacheTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/util_traces/WeakCacheTest.trace com.thoughtworks.xstream.core.util.WeakCacheTest.testEntriesAreRemovedIfKeyIsGarbageCollected:73:*>/home/stg/omc_experiments/slices/xstream/util_slices/WeakCacheTest/WeakCacheTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/util_traces/WeakCacheTest.trace com.thoughtworks.xstream.core.util.WeakCacheTest.testSelfReferencingEntriesAreRemovedIfKeyIsGarbageCollected:88:*>/home/stg/omc_experiments/slices/xstream/util_slices/WeakCacheTest/WeakCacheTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/util_traces/WeakCacheTest.trace com.thoughtworks.xstream.core.util.WeakCacheTest.testSelfReferencingEntriesAreRemovedIfKeyIsGarbageCollected:92:*>/home/stg/omc_experiments/slices/xstream/util_slices/WeakCacheTest/WeakCacheTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/util_traces/WeakCacheTest.trace com.thoughtworks.xstream.core.util.WeakCacheTest.testEntriesAreRemovedIfValueIsGarbageCollected:107:*>/home/stg/omc_experiments/slices/xstream/util_slices/WeakCacheTest/WeakCacheTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/util_traces/WeakCacheTest.trace com.thoughtworks.xstream.core.util.WeakCacheTest.testEntriesAreRemovedIfValueIsGarbageCollected:111:*>/home/stg/omc_experiments/slices/xstream/util_slices/WeakCacheTest/WeakCacheTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/util_traces/WeakCacheTest.trace com.thoughtworks.xstream.core.util.WeakCacheTest.testSelfReferencingEntriesAreRemovedIfValueIsGarbageCollected:127:*>/home/stg/omc_experiments/slices/xstream/util_slices/WeakCacheTest/WeakCacheTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/util_traces/WeakCacheTest.trace com.thoughtworks.xstream.core.util.WeakCacheTest.testSelfReferencingEntriesAreRemovedIfValueIsGarbageCollected:131:*>/home/stg/omc_experiments/slices/xstream/util_slices/WeakCacheTest/WeakCacheTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/util_traces/WeakCacheTest.trace com.thoughtworks.xstream.core.util.WeakCacheTest.testSelfReferencingEntriesWithObjectsFromPermSpace:161:*>/home/stg/omc_experiments/slices/xstream/util_slices/WeakCacheTest/WeakCacheTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/util_traces/WeakCacheTest.trace com.thoughtworks.xstream.core.util.WeakCacheTest.testCanUseDifferentMapImplementation:176:*>/home/stg/omc_experiments/slices/xstream/util_slices/WeakCacheTest/WeakCacheTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/util_traces/WeakCacheTest.trace com.thoughtworks.xstream.core.util.WeakCacheTest.testCanUseDifferentMapImplementation:180:*>/home/stg/omc_experiments/slices/xstream/util_slices/WeakCacheTest/WeakCacheTest27.txt

#Total Asserts in com.thoughtworks.xstream.core.util/WeakCacheTest=============27
#Total Tests in com.thoughtworks.xstream.core.util/WeakCacheTest=============0
