#!/bin/bash

echo "computing slice for FieldTest"

mkdir -p /home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testEmptyArgs:67:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testDefaultPositionImplied:79:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testDefaultPositionImplied:80:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testDefaultPositionImplied:81:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testDefaultPositionImplied:82:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testDefaultUsingPositions:95:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testDefaultUsingPositions:96:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testDefaultUsingPositions:97:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testDefaultUsingPositions:98:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testDefaultOnePosition:111:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testDefaultOnePosition:112:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testDefaultOnePosition:113:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testDefaultOnePosition:114:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testDefaultOnePosition:115:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testDefaultSomePositions:129:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testDefaultSomePositions:130:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testDefaultSomePositions:131:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testDefaultSomePositions:132:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testDefaultSomePositions:133:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverrideUsingPositionA:148:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverrideUsingPositionA:149:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverrideUsingPositionA:152:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverrideUsingPositionA:153:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverrideUsingPositionA:156:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverrideUsingPositionB:172:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverrideUsingPositionB:173:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverrideUsingPositionB:174:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverrideUsingPositionB:175:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverrideUsingPositionB:176:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverrideUsingPositionB:179:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverrideUsingPositionB:180:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverrideUsingPositionB:181:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest32.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverrideUsingPositionB:182:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest33.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverrideUsingPositionB:183:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest34.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverridePositionImplied:198:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest35.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverridePositionImplied:199:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest36.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverridePositionImplied:200:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest37.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverridePositionImplied:201:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest38.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverridePositionImplied:204:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest39.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverridePositionImplied:205:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest40.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverridePositionImplied:206:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest41.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverridePositionImplied:207:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest42.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverridePositionImplied:210:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest43.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverridePositionImplied:211:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest44.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverridePositionImplied:212:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest45.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverrideSomePosition:229:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest46.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverrideSomePosition:230:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest47.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverrideSomePosition:231:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest48.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverrideSomePosition:232:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest49.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverrideSomePosition:233:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest50.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverrideSomePosition:236:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest51.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverrideSomePosition:237:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest52.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverrideSomePosition:238:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest53.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverrideSomePosition:239:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest54.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverrideSomePosition:240:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest55.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverrideSomePosition:243:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest56.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverrideSomePosition:244:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest57.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverrideSomePosition:245:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest58.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/FieldTest.trace org.apache.commons.validator.FieldTest.testOverrideSomePosition:246:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/FieldTest/FieldTest59.txt

#Total Asserts in org.apache.commons.validator/FieldTest=============59
#Total Tests in org.apache.commons.validator/FieldTest=============0
