#!/bin/bash

echo "computing slice for RequiredNameTest"

mkdir -p /home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequired:83:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequired:88:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequired:89:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequired:90:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequired:92:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequired:93:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequired:94:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredFirstNameBlank:117:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredFirstNameBlank:122:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredFirstNameBlank:123:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredFirstNameBlank:124:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredFirstNameBlank:126:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredFirstNameBlank:127:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredFirstNameBlank:128:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredFirstName:151:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredFirstName:156:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredFirstName:157:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredFirstName:158:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredFirstName:160:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredFirstName:161:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredFirstName:162:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredLastNameBlank:185:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredLastNameBlank:190:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredLastNameBlank:191:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredLastNameBlank:192:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredLastNameBlank:194:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredLastNameBlank:195:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredLastNameBlank:196:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredLastName:219:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredLastName:224:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredLastName:225:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredLastName:226:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest32.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredLastName:228:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest33.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredLastName:229:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest34.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredLastName:230:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest35.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredName:255:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest36.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredName:260:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest37.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredName:261:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest38.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredName:262:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest39.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredName:264:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest40.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredName:265:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest41.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/RequiredNameTest.trace org.apache.commons.validator.RequiredNameTest.testRequiredName:266:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/RequiredNameTest/RequiredNameTest42.txt

#Total Asserts in org.apache.commons.validator/RequiredNameTest=============42
#Total Tests in org.apache.commons.validator/RequiredNameTest=============0
