#!/bin/bash

echo "computing slice for MultipleTest"

mkdir -p /home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testBothBlank:84:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testBothBlank:89:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testBothBlank:90:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testBothBlank:91:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testBothBlank:93:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testBothBlank:94:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testBothBlank:95:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testBothBlank:96:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testRequiredFirstNameBlankLastNameShort:120:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testRequiredFirstNameBlankLastNameShort:125:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testRequiredFirstNameBlankLastNameShort:126:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testRequiredFirstNameBlankLastNameShort:127:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testRequiredFirstNameBlankLastNameShort:129:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testRequiredFirstNameBlankLastNameShort:130:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testRequiredFirstNameBlankLastNameShort:131:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testRequiredLastNameShort:155:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testRequiredLastNameShort:160:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testRequiredLastNameShort:161:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testRequiredLastNameShort:162:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testRequiredLastNameShort:164:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testRequiredLastNameShort:165:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testRequiredLastNameShort:166:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testRequiredLastNameLong:190:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testRequiredLastNameLong:195:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testRequiredLastNameLong:196:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testRequiredLastNameLong:197:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testRequiredLastNameLong:199:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testRequiredLastNameLong:200:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testRequiredLastNameLong:201:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testFailingFirstDependentValidator:226:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testFailingFirstDependentValidator:230:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testFailingFirstDependentValidator:232:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest32.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testFailingFirstDependentValidator:233:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest33.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testFailingFirstDependentValidator:235:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest34.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testFailingFirstDependentValidator:237:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest35.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testFailingNextDependentValidator:264:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest36.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testFailingNextDependentValidator:268:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest37.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testFailingNextDependentValidator:270:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest38.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testFailingNextDependentValidator:271:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest39.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testFailingNextDependentValidator:273:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest40.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testFailingNextDependentValidator:274:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest41.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testFailingNextDependentValidator:276:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest42.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testPassingDependentsFailingMain:302:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest43.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testPassingDependentsFailingMain:306:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest44.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testPassingDependentsFailingMain:308:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest45.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testPassingDependentsFailingMain:309:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest46.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testPassingDependentsFailingMain:311:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest47.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testPassingDependentsFailingMain:312:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest48.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testPassingDependentsFailingMain:314:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest49.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testPassingDependentsFailingMain:315:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest50.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testPassingDependentsPassingMain:341:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest51.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testPassingDependentsPassingMain:345:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest52.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testPassingDependentsPassingMain:347:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest53.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testPassingDependentsPassingMain:348:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest54.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testPassingDependentsPassingMain:350:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest55.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testPassingDependentsPassingMain:351:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest56.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testPassingDependentsPassingMain:353:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest57.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/MultipleTest.trace org.apache.commons.validator.MultipleTest.testPassingDependentsPassingMain:354:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/MultipleTest/MultipleTest58.txt

#Total Asserts in org.apache.commons.validator/MultipleTest=============58
#Total Tests in org.apache.commons.validator/MultipleTest=============0
