#!/bin/bash

echo "computing slice for GenericTypeValidatorTest"

mkdir -p /home/stg/omc_experiments/slices/commons-validator/validator_slices/GenericTypeValidatorTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/GenericTypeValidatorTest.trace org.apache.commons.validator.GenericTypeValidatorTest.testType:92:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/GenericTypeValidatorTest/GenericTypeValidatorTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/GenericTypeValidatorTest.trace org.apache.commons.validator.GenericTypeValidatorTest.testType:96:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/GenericTypeValidatorTest/GenericTypeValidatorTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/GenericTypeValidatorTest.trace org.apache.commons.validator.GenericTypeValidatorTest.testType:97:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/GenericTypeValidatorTest/GenericTypeValidatorTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/GenericTypeValidatorTest.trace org.apache.commons.validator.GenericTypeValidatorTest.testType:98:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/GenericTypeValidatorTest/GenericTypeValidatorTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/GenericTypeValidatorTest.trace org.apache.commons.validator.GenericTypeValidatorTest.testType:99:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/GenericTypeValidatorTest/GenericTypeValidatorTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/GenericTypeValidatorTest.trace org.apache.commons.validator.GenericTypeValidatorTest.testType:100:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/GenericTypeValidatorTest/GenericTypeValidatorTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/GenericTypeValidatorTest.trace org.apache.commons.validator.GenericTypeValidatorTest.testType:101:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/GenericTypeValidatorTest/GenericTypeValidatorTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/GenericTypeValidatorTest.trace org.apache.commons.validator.GenericTypeValidatorTest.testType:107:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/GenericTypeValidatorTest/GenericTypeValidatorTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/GenericTypeValidatorTest.trace org.apache.commons.validator.GenericTypeValidatorTest.testFRLocale:148:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/GenericTypeValidatorTest/GenericTypeValidatorTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/GenericTypeValidatorTest.trace org.apache.commons.validator.GenericTypeValidatorTest.testFRLocale:149:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/GenericTypeValidatorTest/GenericTypeValidatorTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/GenericTypeValidatorTest.trace org.apache.commons.validator.GenericTypeValidatorTest.localeTest:174:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/GenericTypeValidatorTest/GenericTypeValidatorTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/GenericTypeValidatorTest.trace org.apache.commons.validator.GenericTypeValidatorTest.localeTest:178:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/GenericTypeValidatorTest/GenericTypeValidatorTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/GenericTypeValidatorTest.trace org.apache.commons.validator.GenericTypeValidatorTest.localeTest:179:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/GenericTypeValidatorTest/GenericTypeValidatorTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/GenericTypeValidatorTest.trace org.apache.commons.validator.GenericTypeValidatorTest.localeTest:180:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/GenericTypeValidatorTest/GenericTypeValidatorTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/GenericTypeValidatorTest.trace org.apache.commons.validator.GenericTypeValidatorTest.localeTest:181:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/GenericTypeValidatorTest/GenericTypeValidatorTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/GenericTypeValidatorTest.trace org.apache.commons.validator.GenericTypeValidatorTest.localeTest:182:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/GenericTypeValidatorTest/GenericTypeValidatorTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/GenericTypeValidatorTest.trace org.apache.commons.validator.GenericTypeValidatorTest.localeTest:183:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/GenericTypeValidatorTest/GenericTypeValidatorTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/GenericTypeValidatorTest.trace org.apache.commons.validator.GenericTypeValidatorTest.localeTest:184:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/GenericTypeValidatorTest/GenericTypeValidatorTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/validator_traces/GenericTypeValidatorTest.trace org.apache.commons.validator.GenericTypeValidatorTest.localeTest:190:*>/home/stg/omc_experiments/slices/commons-validator/validator_slices/GenericTypeValidatorTest/GenericTypeValidatorTest19.txt

#Total Asserts in org.apache.commons.validator/GenericTypeValidatorTest=============19
#Total Tests in org.apache.commons.validator/GenericTypeValidatorTest=============0
