#!/bin/bash

echo "computing slice for StandardPieSectionLabelGeneratorTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/labels_slices/StandardPieSectionLabelGeneratorTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/StandardPieSectionLabelGeneratorTest.trace org.jfree.chart.labels.StandardPieSectionLabelGeneratorTest.testEquals:74:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/StandardPieSectionLabelGeneratorTest/StandardPieSectionLabelGeneratorTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/StandardPieSectionLabelGeneratorTest.trace org.jfree.chart.labels.StandardPieSectionLabelGeneratorTest.testEquals:75:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/StandardPieSectionLabelGeneratorTest/StandardPieSectionLabelGeneratorTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/StandardPieSectionLabelGeneratorTest.trace org.jfree.chart.labels.StandardPieSectionLabelGeneratorTest.testEquals:80:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/StandardPieSectionLabelGeneratorTest/StandardPieSectionLabelGeneratorTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/StandardPieSectionLabelGeneratorTest.trace org.jfree.chart.labels.StandardPieSectionLabelGeneratorTest.testEquals:84:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/StandardPieSectionLabelGeneratorTest/StandardPieSectionLabelGeneratorTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/StandardPieSectionLabelGeneratorTest.trace org.jfree.chart.labels.StandardPieSectionLabelGeneratorTest.testEquals:89:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/StandardPieSectionLabelGeneratorTest/StandardPieSectionLabelGeneratorTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/StandardPieSectionLabelGeneratorTest.trace org.jfree.chart.labels.StandardPieSectionLabelGeneratorTest.testEquals:93:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/StandardPieSectionLabelGeneratorTest/StandardPieSectionLabelGeneratorTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/StandardPieSectionLabelGeneratorTest.trace org.jfree.chart.labels.StandardPieSectionLabelGeneratorTest.testEquals:97:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/StandardPieSectionLabelGeneratorTest/StandardPieSectionLabelGeneratorTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/StandardPieSectionLabelGeneratorTest.trace org.jfree.chart.labels.StandardPieSectionLabelGeneratorTest.testEquals:100:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/StandardPieSectionLabelGeneratorTest/StandardPieSectionLabelGeneratorTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/StandardPieSectionLabelGeneratorTest.trace org.jfree.chart.labels.StandardPieSectionLabelGeneratorTest.testEquals:104:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/StandardPieSectionLabelGeneratorTest/StandardPieSectionLabelGeneratorTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/StandardPieSectionLabelGeneratorTest.trace org.jfree.chart.labels.StandardPieSectionLabelGeneratorTest.testEquals:107:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/StandardPieSectionLabelGeneratorTest/StandardPieSectionLabelGeneratorTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/StandardPieSectionLabelGeneratorTest.trace org.jfree.chart.labels.StandardPieSectionLabelGeneratorTest.testEquals:111:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/StandardPieSectionLabelGeneratorTest/StandardPieSectionLabelGeneratorTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/StandardPieSectionLabelGeneratorTest.trace org.jfree.chart.labels.StandardPieSectionLabelGeneratorTest.testEquals:113:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/StandardPieSectionLabelGeneratorTest/StandardPieSectionLabelGeneratorTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/StandardPieSectionLabelGeneratorTest.trace org.jfree.chart.labels.StandardPieSectionLabelGeneratorTest.testHashCode:125:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/StandardPieSectionLabelGeneratorTest/StandardPieSectionLabelGeneratorTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/StandardPieSectionLabelGeneratorTest.trace org.jfree.chart.labels.StandardPieSectionLabelGeneratorTest.testHashCode:126:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/StandardPieSectionLabelGeneratorTest/StandardPieSectionLabelGeneratorTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/StandardPieSectionLabelGeneratorTest.trace org.jfree.chart.labels.StandardPieSectionLabelGeneratorTest.testCloning:138:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/StandardPieSectionLabelGeneratorTest/StandardPieSectionLabelGeneratorTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/StandardPieSectionLabelGeneratorTest.trace org.jfree.chart.labels.StandardPieSectionLabelGeneratorTest.testCloning:139:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/StandardPieSectionLabelGeneratorTest/StandardPieSectionLabelGeneratorTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/StandardPieSectionLabelGeneratorTest.trace org.jfree.chart.labels.StandardPieSectionLabelGeneratorTest.testCloning:140:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/StandardPieSectionLabelGeneratorTest/StandardPieSectionLabelGeneratorTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/StandardPieSectionLabelGeneratorTest.trace org.jfree.chart.labels.StandardPieSectionLabelGeneratorTest.testPublicCloneable:150:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/StandardPieSectionLabelGeneratorTest/StandardPieSectionLabelGeneratorTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/StandardPieSectionLabelGeneratorTest.trace org.jfree.chart.labels.StandardPieSectionLabelGeneratorTest.testSerialization:162:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/StandardPieSectionLabelGeneratorTest/StandardPieSectionLabelGeneratorTest19.txt

#Total Asserts in org.jfree.chart.labels/StandardPieSectionLabelGeneratorTest=============19
#Total Tests in org.jfree.chart.labels/StandardPieSectionLabelGeneratorTest=============0
