#!/bin/bash

echo "computing slice for BubbleXYItemLabelGeneratorTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/labels_slices/BubbleXYItemLabelGeneratorTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BubbleXYItemLabelGeneratorTest.trace org.jfree.chart.labels.BubbleXYItemLabelGeneratorTest.testEquals:86:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BubbleXYItemLabelGeneratorTest/BubbleXYItemLabelGeneratorTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BubbleXYItemLabelGeneratorTest.trace org.jfree.chart.labels.BubbleXYItemLabelGeneratorTest.testEquals:87:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BubbleXYItemLabelGeneratorTest/BubbleXYItemLabelGeneratorTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BubbleXYItemLabelGeneratorTest.trace org.jfree.chart.labels.BubbleXYItemLabelGeneratorTest.testEquals:90:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BubbleXYItemLabelGeneratorTest/BubbleXYItemLabelGeneratorTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BubbleXYItemLabelGeneratorTest.trace org.jfree.chart.labels.BubbleXYItemLabelGeneratorTest.testEquals:92:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BubbleXYItemLabelGeneratorTest/BubbleXYItemLabelGeneratorTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BubbleXYItemLabelGeneratorTest.trace org.jfree.chart.labels.BubbleXYItemLabelGeneratorTest.testEquals:95:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BubbleXYItemLabelGeneratorTest/BubbleXYItemLabelGeneratorTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BubbleXYItemLabelGeneratorTest.trace org.jfree.chart.labels.BubbleXYItemLabelGeneratorTest.testEquals:97:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BubbleXYItemLabelGeneratorTest/BubbleXYItemLabelGeneratorTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BubbleXYItemLabelGeneratorTest.trace org.jfree.chart.labels.BubbleXYItemLabelGeneratorTest.testEquals:100:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BubbleXYItemLabelGeneratorTest/BubbleXYItemLabelGeneratorTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BubbleXYItemLabelGeneratorTest.trace org.jfree.chart.labels.BubbleXYItemLabelGeneratorTest.testEquals:102:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BubbleXYItemLabelGeneratorTest/BubbleXYItemLabelGeneratorTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BubbleXYItemLabelGeneratorTest.trace org.jfree.chart.labels.BubbleXYItemLabelGeneratorTest.testEquals:105:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BubbleXYItemLabelGeneratorTest/BubbleXYItemLabelGeneratorTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BubbleXYItemLabelGeneratorTest.trace org.jfree.chart.labels.BubbleXYItemLabelGeneratorTest.testEquals:107:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BubbleXYItemLabelGeneratorTest/BubbleXYItemLabelGeneratorTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BubbleXYItemLabelGeneratorTest.trace org.jfree.chart.labels.BubbleXYItemLabelGeneratorTest.testEquals:118:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BubbleXYItemLabelGeneratorTest/BubbleXYItemLabelGeneratorTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BubbleXYItemLabelGeneratorTest.trace org.jfree.chart.labels.BubbleXYItemLabelGeneratorTest.testEquals:119:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BubbleXYItemLabelGeneratorTest/BubbleXYItemLabelGeneratorTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BubbleXYItemLabelGeneratorTest.trace org.jfree.chart.labels.BubbleXYItemLabelGeneratorTest.testEquals:122:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BubbleXYItemLabelGeneratorTest/BubbleXYItemLabelGeneratorTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BubbleXYItemLabelGeneratorTest.trace org.jfree.chart.labels.BubbleXYItemLabelGeneratorTest.testEquals:124:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BubbleXYItemLabelGeneratorTest/BubbleXYItemLabelGeneratorTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BubbleXYItemLabelGeneratorTest.trace org.jfree.chart.labels.BubbleXYItemLabelGeneratorTest.testEquals:127:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BubbleXYItemLabelGeneratorTest/BubbleXYItemLabelGeneratorTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BubbleXYItemLabelGeneratorTest.trace org.jfree.chart.labels.BubbleXYItemLabelGeneratorTest.testEquals:129:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BubbleXYItemLabelGeneratorTest/BubbleXYItemLabelGeneratorTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BubbleXYItemLabelGeneratorTest.trace org.jfree.chart.labels.BubbleXYItemLabelGeneratorTest.testEquals:132:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BubbleXYItemLabelGeneratorTest/BubbleXYItemLabelGeneratorTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BubbleXYItemLabelGeneratorTest.trace org.jfree.chart.labels.BubbleXYItemLabelGeneratorTest.testEquals:134:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BubbleXYItemLabelGeneratorTest/BubbleXYItemLabelGeneratorTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BubbleXYItemLabelGeneratorTest.trace org.jfree.chart.labels.BubbleXYItemLabelGeneratorTest.testHashCode:146:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BubbleXYItemLabelGeneratorTest/BubbleXYItemLabelGeneratorTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BubbleXYItemLabelGeneratorTest.trace org.jfree.chart.labels.BubbleXYItemLabelGeneratorTest.testHashCode:147:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BubbleXYItemLabelGeneratorTest/BubbleXYItemLabelGeneratorTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BubbleXYItemLabelGeneratorTest.trace org.jfree.chart.labels.BubbleXYItemLabelGeneratorTest.testCloning:157:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BubbleXYItemLabelGeneratorTest/BubbleXYItemLabelGeneratorTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BubbleXYItemLabelGeneratorTest.trace org.jfree.chart.labels.BubbleXYItemLabelGeneratorTest.testCloning:158:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BubbleXYItemLabelGeneratorTest/BubbleXYItemLabelGeneratorTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BubbleXYItemLabelGeneratorTest.trace org.jfree.chart.labels.BubbleXYItemLabelGeneratorTest.testCloning:159:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BubbleXYItemLabelGeneratorTest/BubbleXYItemLabelGeneratorTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BubbleXYItemLabelGeneratorTest.trace org.jfree.chart.labels.BubbleXYItemLabelGeneratorTest.testPublicCloneable:168:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BubbleXYItemLabelGeneratorTest/BubbleXYItemLabelGeneratorTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BubbleXYItemLabelGeneratorTest.trace org.jfree.chart.labels.BubbleXYItemLabelGeneratorTest.testSerialization:179:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BubbleXYItemLabelGeneratorTest/BubbleXYItemLabelGeneratorTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BubbleXYItemLabelGeneratorTest.trace org.jfree.chart.labels.BubbleXYItemLabelGeneratorTest.testGenerateLabel:194:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BubbleXYItemLabelGeneratorTest/BubbleXYItemLabelGeneratorTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BubbleXYItemLabelGeneratorTest.trace org.jfree.chart.labels.BubbleXYItemLabelGeneratorTest.testGenerateLabel:195:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BubbleXYItemLabelGeneratorTest/BubbleXYItemLabelGeneratorTest27.txt

#Total Asserts in org.jfree.chart.labels/BubbleXYItemLabelGeneratorTest=============27
#Total Tests in org.jfree.chart.labels/BubbleXYItemLabelGeneratorTest=============0
