#!/bin/bash

echo "computing slice for BoxAndWhiskerToolTipGeneratorTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/labels_slices/BoxAndWhiskerToolTipGeneratorTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BoxAndWhiskerToolTipGeneratorTest.trace org.jfree.chart.labels.BoxAndWhiskerToolTipGeneratorTest.testEquals:69:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BoxAndWhiskerToolTipGeneratorTest/BoxAndWhiskerToolTipGeneratorTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BoxAndWhiskerToolTipGeneratorTest.trace org.jfree.chart.labels.BoxAndWhiskerToolTipGeneratorTest.testEquals:70:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BoxAndWhiskerToolTipGeneratorTest/BoxAndWhiskerToolTipGeneratorTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BoxAndWhiskerToolTipGeneratorTest.trace org.jfree.chart.labels.BoxAndWhiskerToolTipGeneratorTest.testEquals:77:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BoxAndWhiskerToolTipGeneratorTest/BoxAndWhiskerToolTipGeneratorTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BoxAndWhiskerToolTipGeneratorTest.trace org.jfree.chart.labels.BoxAndWhiskerToolTipGeneratorTest.testEquals:80:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BoxAndWhiskerToolTipGeneratorTest/BoxAndWhiskerToolTipGeneratorTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BoxAndWhiskerToolTipGeneratorTest.trace org.jfree.chart.labels.BoxAndWhiskerToolTipGeneratorTest.testEquals:87:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BoxAndWhiskerToolTipGeneratorTest/BoxAndWhiskerToolTipGeneratorTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BoxAndWhiskerToolTipGeneratorTest.trace org.jfree.chart.labels.BoxAndWhiskerToolTipGeneratorTest.testHashCode:97:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BoxAndWhiskerToolTipGeneratorTest/BoxAndWhiskerToolTipGeneratorTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BoxAndWhiskerToolTipGeneratorTest.trace org.jfree.chart.labels.BoxAndWhiskerToolTipGeneratorTest.testHashCode:98:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BoxAndWhiskerToolTipGeneratorTest/BoxAndWhiskerToolTipGeneratorTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BoxAndWhiskerToolTipGeneratorTest.trace org.jfree.chart.labels.BoxAndWhiskerToolTipGeneratorTest.testCloning:108:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BoxAndWhiskerToolTipGeneratorTest/BoxAndWhiskerToolTipGeneratorTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BoxAndWhiskerToolTipGeneratorTest.trace org.jfree.chart.labels.BoxAndWhiskerToolTipGeneratorTest.testCloning:109:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BoxAndWhiskerToolTipGeneratorTest/BoxAndWhiskerToolTipGeneratorTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BoxAndWhiskerToolTipGeneratorTest.trace org.jfree.chart.labels.BoxAndWhiskerToolTipGeneratorTest.testCloning:110:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BoxAndWhiskerToolTipGeneratorTest/BoxAndWhiskerToolTipGeneratorTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BoxAndWhiskerToolTipGeneratorTest.trace org.jfree.chart.labels.BoxAndWhiskerToolTipGeneratorTest.testPublicCloneable:119:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BoxAndWhiskerToolTipGeneratorTest/BoxAndWhiskerToolTipGeneratorTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/labels_traces/BoxAndWhiskerToolTipGeneratorTest.trace org.jfree.chart.labels.BoxAndWhiskerToolTipGeneratorTest.testSerialization:130:*>/home/stg/omc_experiments/slices/jfreechart/labels_slices/BoxAndWhiskerToolTipGeneratorTest/BoxAndWhiskerToolTipGeneratorTest12.txt

#Total Asserts in org.jfree.chart.labels/BoxAndWhiskerToolTipGeneratorTest=============12
#Total Tests in org.jfree.chart.labels/BoxAndWhiskerToolTipGeneratorTest=============0
