#!/bin/bash

echo "computing slice for ReferenceByXPathMarshallingStrategyTest"

mkdir -p /home/stg/omc_experiments/slices/xstream/core_slices/ReferenceByXPathMarshallingStrategyTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/core_traces/ReferenceByXPathMarshallingStrategyTest.trace com.thoughtworks.xstream.core.ReferenceByXPathMarshallingStrategyTest.createUnmarshallingContext:116:*>/home/stg/omc_experiments/slices/xstream/core_slices/ReferenceByXPathMarshallingStrategyTest/ReferenceByXPathMarshallingStrategyTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/core_traces/ReferenceByXPathMarshallingStrategyTest.trace com.thoughtworks.xstream.core.ReferenceByXPathMarshallingStrategyTest.createMarshallingContext:125:*>/home/stg/omc_experiments/slices/xstream/core_slices/ReferenceByXPathMarshallingStrategyTest/ReferenceByXPathMarshallingStrategyTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/core_traces/ReferenceByXPathMarshallingStrategyTest.trace com.thoughtworks.xstream.core.ReferenceByXPathMarshallingStrategyTest.testDoNotKeepXPathMapForImmutablesOnMarshall:148:*>/home/stg/omc_experiments/slices/xstream/core_slices/ReferenceByXPathMarshallingStrategyTest/ReferenceByXPathMarshallingStrategyTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/core_traces/ReferenceByXPathMarshallingStrategyTest.trace com.thoughtworks.xstream.core.ReferenceByXPathMarshallingStrategyTest.testDoNotKeepXPathMapForImmutablesOnMarshall:149:*>/home/stg/omc_experiments/slices/xstream/core_slices/ReferenceByXPathMarshallingStrategyTest/ReferenceByXPathMarshallingStrategyTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/core_traces/ReferenceByXPathMarshallingStrategyTest.trace com.thoughtworks.xstream.core.ReferenceByXPathMarshallingStrategyTest.testDoNotKeepXPathMapForImmutablesOnUnmarshall:170:*>/home/stg/omc_experiments/slices/xstream/core_slices/ReferenceByXPathMarshallingStrategyTest/ReferenceByXPathMarshallingStrategyTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/core_traces/ReferenceByXPathMarshallingStrategyTest.trace com.thoughtworks.xstream.core.ReferenceByXPathMarshallingStrategyTest.testDoNotKeepXPathMapForImmutablesOnUnmarshall:171:*>/home/stg/omc_experiments/slices/xstream/core_slices/ReferenceByXPathMarshallingStrategyTest/ReferenceByXPathMarshallingStrategyTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/core_traces/ReferenceByXPathMarshallingStrategyTest.trace com.thoughtworks.xstream.core.ReferenceByXPathMarshallingStrategyTest.testDoesKeepXPathMapForBackwardsCompatibleImmutablesOnUnmarshall:205:*>/home/stg/omc_experiments/slices/xstream/core_slices/ReferenceByXPathMarshallingStrategyTest/ReferenceByXPathMarshallingStrategyTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/core_traces/ReferenceByXPathMarshallingStrategyTest.trace com.thoughtworks.xstream.core.ReferenceByXPathMarshallingStrategyTest.testDoesKeepXPathMapForBackwardsCompatibleImmutablesOnUnmarshall:206:*>/home/stg/omc_experiments/slices/xstream/core_slices/ReferenceByXPathMarshallingStrategyTest/ReferenceByXPathMarshallingStrategyTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/core_traces/ReferenceByXPathMarshallingStrategyTest.trace com.thoughtworks.xstream.core.ReferenceByXPathMarshallingStrategyTest.testDoesKeepXPathMapForBackwardsCompatibleImmutablesOnUnmarshall:207:*>/home/stg/omc_experiments/slices/xstream/core_slices/ReferenceByXPathMarshallingStrategyTest/ReferenceByXPathMarshallingStrategyTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/core_traces/ReferenceByXPathMarshallingStrategyTest.trace com.thoughtworks.xstream.core.ReferenceByXPathMarshallingStrategyTest.testDoesKeepXPathMapForBackwardsCompatibleImmutablesOnUnmarshall:208:*>/home/stg/omc_experiments/slices/xstream/core_slices/ReferenceByXPathMarshallingStrategyTest/ReferenceByXPathMarshallingStrategyTest10.txt

#Total Asserts in com.thoughtworks.xstream.core/ReferenceByXPathMarshallingStrategyTest=============10
#Total Tests in com.thoughtworks.xstream.core/ReferenceByXPathMarshallingStrategyTest=============0
