#!/bin/bash

echo "computing slice for TokenTest"

mkdir -p /home/stg/omc_experiments/slices/xstream/binary_slices/TokenTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/binary_traces/TokenTest.trace com.thoughtworks.xstream.io.binary.TokenTest.testUsesOneExtraByteForIdsThatCanBeRepresentedAsByte:49:*>/home/stg/omc_experiments/slices/xstream/binary_slices/TokenTest/TokenTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/binary_traces/TokenTest.trace com.thoughtworks.xstream.io.binary.TokenTest.testUsesOneExtraByteForIdsThatCanBeRepresentedAsByte:50:*>/home/stg/omc_experiments/slices/xstream/binary_slices/TokenTest/TokenTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/binary_traces/TokenTest.trace com.thoughtworks.xstream.io.binary.TokenTest.testUsesTwoExtraBytesForIdsThatCanBeRepresentedAsShort:56:*>/home/stg/omc_experiments/slices/xstream/binary_slices/TokenTest/TokenTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/binary_traces/TokenTest.trace com.thoughtworks.xstream.io.binary.TokenTest.testUsesTwoExtraBytesForIdsThatCanBeRepresentedAsShort:57:*>/home/stg/omc_experiments/slices/xstream/binary_slices/TokenTest/TokenTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/binary_traces/TokenTest.trace com.thoughtworks.xstream.io.binary.TokenTest.testUsesFourExtraBytesForIdsThatCanBeRepresentedAsShort:63:*>/home/stg/omc_experiments/slices/xstream/binary_slices/TokenTest/TokenTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/binary_traces/TokenTest.trace com.thoughtworks.xstream.io.binary.TokenTest.testUsesFourExtraBytesForIdsThatCanBeRepresentedAsShort:64:*>/home/stg/omc_experiments/slices/xstream/binary_slices/TokenTest/TokenTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/binary_traces/TokenTest.trace com.thoughtworks.xstream.io.binary.TokenTest.testUsesEightExtraBytesForIdsThatCanBeRepresentedAsLong:70:*>/home/stg/omc_experiments/slices/xstream/binary_slices/TokenTest/TokenTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/binary_traces/TokenTest.trace com.thoughtworks.xstream.io.binary.TokenTest.testUsesEightExtraBytesForIdsThatCanBeRepresentedAsLong:71:*>/home/stg/omc_experiments/slices/xstream/binary_slices/TokenTest/TokenTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/binary_traces/TokenTest.trace com.thoughtworks.xstream.io.binary.TokenTest.testUsesOneExtraByteForUtf8StringsWith1ByteCharacters:77:*>/home/stg/omc_experiments/slices/xstream/binary_slices/TokenTest/TokenTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/binary_traces/TokenTest.trace com.thoughtworks.xstream.io.binary.TokenTest.testUsesOneExtraByteForUtf8StringsWith1ByteCharacters:78:*>/home/stg/omc_experiments/slices/xstream/binary_slices/TokenTest/TokenTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/binary_traces/TokenTest.trace com.thoughtworks.xstream.io.binary.TokenTest.testUsesOneExtraByteForUtf8StringsWith2ByteCharacters:84:*>/home/stg/omc_experiments/slices/xstream/binary_slices/TokenTest/TokenTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/binary_traces/TokenTest.trace com.thoughtworks.xstream.io.binary.TokenTest.testUsesOneExtraByteForUtf8StringsWith2ByteCharacters:85:*>/home/stg/omc_experiments/slices/xstream/binary_slices/TokenTest/TokenTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/binary_traces/TokenTest.trace com.thoughtworks.xstream.io.binary.TokenTest.testUsesIdForStringsWithMoreThen64KBytes:94:*>/home/stg/omc_experiments/slices/xstream/binary_slices/TokenTest/TokenTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/binary_traces/TokenTest.trace com.thoughtworks.xstream.io.binary.TokenTest.testUsesIdForStringsWithMoreThen64KBytes:97:*>/home/stg/omc_experiments/slices/xstream/binary_slices/TokenTest/TokenTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/binary_traces/TokenTest.trace com.thoughtworks.xstream.io.binary.TokenTest.testUsesIdForStringsWithMoreThen64KBytes:98:*>/home/stg/omc_experiments/slices/xstream/binary_slices/TokenTest/TokenTest15.txt

#Total Asserts in com.thoughtworks.xstream.io.binary/TokenTest=============15
#Total Tests in com.thoughtworks.xstream.io.binary/TokenTest=============0
