#!/bin/bash

echo "computing slice for TestLenientChronology"

mkdir -p /home/stg/omc_experiments/slices/fse-joda-time/chrono_slices/TestLenientChronology

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/chrono_traces/TestLenientChronology.trace org.joda.time.chrono.TestLenientChronology.test_setYear:75:*>/home/stg/omc_experiments/slices/fse-joda-time/chrono_slices/TestLenientChronology/TestLenientChronology1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/chrono_traces/TestLenientChronology.trace org.joda.time.chrono.TestLenientChronology.test_setYear:77:*>/home/stg/omc_experiments/slices/fse-joda-time/chrono_slices/TestLenientChronology/TestLenientChronology2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/chrono_traces/TestLenientChronology.trace org.joda.time.chrono.TestLenientChronology.test_setMonthOfYear:85:*>/home/stg/omc_experiments/slices/fse-joda-time/chrono_slices/TestLenientChronology/TestLenientChronology3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/chrono_traces/TestLenientChronology.trace org.joda.time.chrono.TestLenientChronology.test_setMonthOfYear:87:*>/home/stg/omc_experiments/slices/fse-joda-time/chrono_slices/TestLenientChronology/TestLenientChronology4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/chrono_traces/TestLenientChronology.trace org.joda.time.chrono.TestLenientChronology.test_setMonthOfYear:89:*>/home/stg/omc_experiments/slices/fse-joda-time/chrono_slices/TestLenientChronology/TestLenientChronology5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/chrono_traces/TestLenientChronology.trace org.joda.time.chrono.TestLenientChronology.test_setDayOfMonth:97:*>/home/stg/omc_experiments/slices/fse-joda-time/chrono_slices/TestLenientChronology/TestLenientChronology6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/chrono_traces/TestLenientChronology.trace org.joda.time.chrono.TestLenientChronology.test_setDayOfMonth:99:*>/home/stg/omc_experiments/slices/fse-joda-time/chrono_slices/TestLenientChronology/TestLenientChronology7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/chrono_traces/TestLenientChronology.trace org.joda.time.chrono.TestLenientChronology.test_setDayOfMonth:101:*>/home/stg/omc_experiments/slices/fse-joda-time/chrono_slices/TestLenientChronology/TestLenientChronology8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/chrono_traces/TestLenientChronology.trace org.joda.time.chrono.TestLenientChronology.test_setHourOfDay:109:*>/home/stg/omc_experiments/slices/fse-joda-time/chrono_slices/TestLenientChronology/TestLenientChronology9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/chrono_traces/TestLenientChronology.trace org.joda.time.chrono.TestLenientChronology.test_setHourOfDay:111:*>/home/stg/omc_experiments/slices/fse-joda-time/chrono_slices/TestLenientChronology/TestLenientChronology10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/chrono_traces/TestLenientChronology.trace org.joda.time.chrono.TestLenientChronology.test_setHourOfDay:113:*>/home/stg/omc_experiments/slices/fse-joda-time/chrono_slices/TestLenientChronology/TestLenientChronology11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/chrono_traces/TestLenientChronology.trace org.joda.time.chrono.TestLenientChronology.testNearDstTransition:128:*>/home/stg/omc_experiments/slices/fse-joda-time/chrono_slices/TestLenientChronology/TestLenientChronology12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/chrono_traces/TestLenientChronology.trace org.joda.time.chrono.TestLenientChronology.testNearDstTransition:133:*>/home/stg/omc_experiments/slices/fse-joda-time/chrono_slices/TestLenientChronology/TestLenientChronology13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/chrono_traces/TestLenientChronology.trace org.joda.time.chrono.TestLenientChronology.testNearDstTransition:139:*>/home/stg/omc_experiments/slices/fse-joda-time/chrono_slices/TestLenientChronology/TestLenientChronology14.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/chrono_traces/TestLenientChronology.trace org.joda.time.chrono.TestLenientChronology.test_MockTurkIsCorrect:154:*>/home/stg/omc_experiments/slices/fse-joda-time/chrono_slices/TestLenientChronology/TestLenientChronology15.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/chrono_traces/TestLenientChronology.trace org.joda.time.chrono.TestLenientChronology.test_MockTurkIsCorrect:156:*>/home/stg/omc_experiments/slices/fse-joda-time/chrono_slices/TestLenientChronology/TestLenientChronology16.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/chrono_traces/TestLenientChronology.trace org.joda.time.chrono.TestLenientChronology.test_MockTurkIsCorrect:158:*>/home/stg/omc_experiments/slices/fse-joda-time/chrono_slices/TestLenientChronology/TestLenientChronology17.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/chrono_traces/TestLenientChronology.trace org.joda.time.chrono.TestLenientChronology.test_lenientChrononolgy_Chicago:165:*>/home/stg/omc_experiments/slices/fse-joda-time/chrono_slices/TestLenientChronology/TestLenientChronology18.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/chrono_traces/TestLenientChronology.trace org.joda.time.chrono.TestLenientChronology.test_lenientChrononolgy_Turk:171:*>/home/stg/omc_experiments/slices/fse-joda-time/chrono_slices/TestLenientChronology/TestLenientChronology19.txt

#Total Asserts in org.joda.time.chrono/TestLenientChronology=============19
#Total Tests in org.joda.time.chrono/TestLenientChronology=============0
