#!/bin/bash

echo "computing slice for W3CDomTest"

mkdir -p /home/stg/omc_experiments/slices/jsoup-1.10.1/helper_slices/W3CDomTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/helper_traces/W3CDomTest.trace org.jsoup.helper.W3CDomTest.simpleConversion:26:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/helper_slices/W3CDomTest/W3CDomTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/helper_traces/W3CDomTest.trace org.jsoup.helper.W3CDomTest.convertsGoogle:50:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/helper_slices/W3CDomTest/W3CDomTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/helper_traces/W3CDomTest.trace org.jsoup.helper.W3CDomTest.convertsGoogle:51:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/helper_slices/W3CDomTest/W3CDomTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/helper_traces/W3CDomTest.trace org.jsoup.helper.W3CDomTest.convertsGoogle:52:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/helper_slices/W3CDomTest/W3CDomTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/helper_traces/W3CDomTest.trace org.jsoup.helper.W3CDomTest.convertsGoogle:55:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/helper_slices/W3CDomTest/W3CDomTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/helper_traces/W3CDomTest.trace org.jsoup.helper.W3CDomTest.namespacePreservation:69:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/helper_slices/W3CDomTest/W3CDomTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/helper_traces/W3CDomTest.trace org.jsoup.helper.W3CDomTest.namespacePreservation:70:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/helper_slices/W3CDomTest/W3CDomTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/helper_traces/W3CDomTest.trace org.jsoup.helper.W3CDomTest.namespacePreservation:71:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/helper_slices/W3CDomTest/W3CDomTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/helper_traces/W3CDomTest.trace org.jsoup.helper.W3CDomTest.namespacePreservation:74:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/helper_slices/W3CDomTest/W3CDomTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/helper_traces/W3CDomTest.trace org.jsoup.helper.W3CDomTest.namespacePreservation:75:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/helper_slices/W3CDomTest/W3CDomTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/helper_traces/W3CDomTest.trace org.jsoup.helper.W3CDomTest.namespacePreservation:76:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/helper_slices/W3CDomTest/W3CDomTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/helper_traces/W3CDomTest.trace org.jsoup.helper.W3CDomTest.namespacePreservation:79:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/helper_slices/W3CDomTest/W3CDomTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/helper_traces/W3CDomTest.trace org.jsoup.helper.W3CDomTest.namespacePreservation:80:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/helper_slices/W3CDomTest/W3CDomTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/helper_traces/W3CDomTest.trace org.jsoup.helper.W3CDomTest.namespacePreservation:81:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/helper_slices/W3CDomTest/W3CDomTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/helper_traces/W3CDomTest.trace org.jsoup.helper.W3CDomTest.handlesInvalidAttributeNames:90:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/helper_slices/W3CDomTest/W3CDomTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/helper_traces/W3CDomTest.trace org.jsoup.helper.W3CDomTest.handlesInvalidAttributeNames:91:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/helper_slices/W3CDomTest/W3CDomTest16.txt

#Total Asserts in org.jsoup.helper/W3CDomTest=============16
#Total Tests in org.jsoup.helper/W3CDomTest=============0
