#!/bin/bash

echo "computing slice for FormatDetectionTest"

mkdir -p /home/stg/omc_experiments/slices/jackson-dataformat-xml/stream_slices/FormatDetectionTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/stream_traces/FormatDetectionTest.trace com.fasterxml.jackson.dataformat.xml.stream.FormatDetectionTest.testSimpleValidXmlDecl:44:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/stream_slices/FormatDetectionTest/FormatDetectionTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/stream_traces/FormatDetectionTest.trace com.fasterxml.jackson.dataformat.xml.stream.FormatDetectionTest.testSimpleValidXmlDecl:45:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/stream_slices/FormatDetectionTest/FormatDetectionTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/stream_traces/FormatDetectionTest.trace com.fasterxml.jackson.dataformat.xml.stream.FormatDetectionTest.testSimpleValidXmlDecl:46:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/stream_slices/FormatDetectionTest/FormatDetectionTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/stream_traces/FormatDetectionTest.trace com.fasterxml.jackson.dataformat.xml.stream.FormatDetectionTest.testSimpleValidXmlDecl:47:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/stream_slices/FormatDetectionTest/FormatDetectionTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/stream_traces/FormatDetectionTest.trace com.fasterxml.jackson.dataformat.xml.stream.FormatDetectionTest.testSimpleValidRoot:60:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/stream_slices/FormatDetectionTest/FormatDetectionTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/stream_traces/FormatDetectionTest.trace com.fasterxml.jackson.dataformat.xml.stream.FormatDetectionTest.testSimpleValidRoot:61:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/stream_slices/FormatDetectionTest/FormatDetectionTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/stream_traces/FormatDetectionTest.trace com.fasterxml.jackson.dataformat.xml.stream.FormatDetectionTest.testSimpleValidRoot:62:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/stream_slices/FormatDetectionTest/FormatDetectionTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/stream_traces/FormatDetectionTest.trace com.fasterxml.jackson.dataformat.xml.stream.FormatDetectionTest.testSimpleValidRoot:63:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/stream_slices/FormatDetectionTest/FormatDetectionTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/stream_traces/FormatDetectionTest.trace com.fasterxml.jackson.dataformat.xml.stream.FormatDetectionTest.testSimpleValidDoctype:76:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/stream_slices/FormatDetectionTest/FormatDetectionTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/stream_traces/FormatDetectionTest.trace com.fasterxml.jackson.dataformat.xml.stream.FormatDetectionTest.testSimpleValidDoctype:77:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/stream_slices/FormatDetectionTest/FormatDetectionTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/stream_traces/FormatDetectionTest.trace com.fasterxml.jackson.dataformat.xml.stream.FormatDetectionTest.testSimpleValidDoctype:78:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/stream_slices/FormatDetectionTest/FormatDetectionTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/stream_traces/FormatDetectionTest.trace com.fasterxml.jackson.dataformat.xml.stream.FormatDetectionTest.testSimpleValidDoctype:79:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/stream_slices/FormatDetectionTest/FormatDetectionTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/stream_traces/FormatDetectionTest.trace com.fasterxml.jackson.dataformat.xml.stream.FormatDetectionTest.testSimpleValidComment:92:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/stream_slices/FormatDetectionTest/FormatDetectionTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/stream_traces/FormatDetectionTest.trace com.fasterxml.jackson.dataformat.xml.stream.FormatDetectionTest.testSimpleValidComment:93:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/stream_slices/FormatDetectionTest/FormatDetectionTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/stream_traces/FormatDetectionTest.trace com.fasterxml.jackson.dataformat.xml.stream.FormatDetectionTest.testSimpleValidComment:94:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/stream_slices/FormatDetectionTest/FormatDetectionTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/stream_traces/FormatDetectionTest.trace com.fasterxml.jackson.dataformat.xml.stream.FormatDetectionTest.testSimpleValidComment:95:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/stream_slices/FormatDetectionTest/FormatDetectionTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/stream_traces/FormatDetectionTest.trace com.fasterxml.jackson.dataformat.xml.stream.FormatDetectionTest.testSimpleValidPI:108:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/stream_slices/FormatDetectionTest/FormatDetectionTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/stream_traces/FormatDetectionTest.trace com.fasterxml.jackson.dataformat.xml.stream.FormatDetectionTest.testSimpleValidPI:109:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/stream_slices/FormatDetectionTest/FormatDetectionTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/stream_traces/FormatDetectionTest.trace com.fasterxml.jackson.dataformat.xml.stream.FormatDetectionTest.testSimpleValidPI:110:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/stream_slices/FormatDetectionTest/FormatDetectionTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/stream_traces/FormatDetectionTest.trace com.fasterxml.jackson.dataformat.xml.stream.FormatDetectionTest.testSimpleValidPI:111:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/stream_slices/FormatDetectionTest/FormatDetectionTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/stream_traces/FormatDetectionTest.trace com.fasterxml.jackson.dataformat.xml.stream.FormatDetectionTest.testSimpleViaObjectReader:127:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/stream_slices/FormatDetectionTest/FormatDetectionTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/stream_traces/FormatDetectionTest.trace com.fasterxml.jackson.dataformat.xml.stream.FormatDetectionTest.testSimpleViaObjectReader:128:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/stream_slices/FormatDetectionTest/FormatDetectionTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/stream_traces/FormatDetectionTest.trace com.fasterxml.jackson.dataformat.xml.stream.FormatDetectionTest.testSimpleViaObjectReader:129:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/stream_slices/FormatDetectionTest/FormatDetectionTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/stream_traces/FormatDetectionTest.trace com.fasterxml.jackson.dataformat.xml.stream.FormatDetectionTest.testListViaObjectReader:145:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/stream_slices/FormatDetectionTest/FormatDetectionTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/stream_traces/FormatDetectionTest.trace com.fasterxml.jackson.dataformat.xml.stream.FormatDetectionTest.testListViaObjectReader:146:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/stream_slices/FormatDetectionTest/FormatDetectionTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/stream_traces/FormatDetectionTest.trace com.fasterxml.jackson.dataformat.xml.stream.FormatDetectionTest.testSimpleInvalid:161:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/stream_slices/FormatDetectionTest/FormatDetectionTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/stream_traces/FormatDetectionTest.trace com.fasterxml.jackson.dataformat.xml.stream.FormatDetectionTest.testSimpleInvalid:163:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/stream_slices/FormatDetectionTest/FormatDetectionTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/stream_traces/FormatDetectionTest.trace com.fasterxml.jackson.dataformat.xml.stream.FormatDetectionTest.testSimpleInvalid:165:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/stream_slices/FormatDetectionTest/FormatDetectionTest28.txt

#Total Asserts in com.fasterxml.jackson.dataformat.xml.stream/FormatDetectionTest=============28
#Total Tests in com.fasterxml.jackson.dataformat.xml.stream/FormatDetectionTest=============0
