#!/bin/bash

echo "computing slice for JsonReaderPathTest"

mkdir -p /home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.path:48:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.path:50:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.path:52:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.path:54:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.path:56:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.path:58:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.path:60:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.path:62:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.path:64:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.path:66:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.path:68:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.path:70:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.path:72:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.path:74:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest14.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.path:76:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest15.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.path:78:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest16.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.path:80:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest17.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.path:82:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest18.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.objectPath:87:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest19.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.objectPath:90:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest20.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.objectPath:92:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest21.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.objectPath:95:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest22.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.objectPath:97:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest23.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.objectPath:100:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest24.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.objectPath:102:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest25.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.objectPath:105:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest26.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.objectPath:107:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest27.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.objectPath:110:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest28.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.objectPath:112:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest29.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.objectPath:115:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest30.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.objectPath:117:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest31.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.objectPath:120:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest32.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.objectPath:122:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest33.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.arrayPath:127:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest34.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.arrayPath:130:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest35.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.arrayPath:132:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest36.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.arrayPath:135:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest37.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.arrayPath:137:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest38.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.arrayPath:140:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest39.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.arrayPath:142:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest40.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.arrayPath:145:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest41.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.arrayPath:147:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest42.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.arrayPath:150:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest43.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.arrayPath:152:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest44.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.multipleTopLevelValuesInOneDocument:162:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest45.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.multipleTopLevelValuesInOneDocument:165:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest46.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.skipArrayElements:173:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest47.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.skipObjectNames:180:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest48.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.skipObjectValues:186:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest49.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.skipObjectValues:189:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest50.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.skipObjectValues:191:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest51.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.skipNestedStructures:198:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest52.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.arrayOfObjects:204:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest53.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.arrayOfObjects:206:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest54.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.arrayOfObjects:208:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest55.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.arrayOfObjects:210:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest56.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.arrayOfObjects:212:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest57.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.arrayOfObjects:214:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest58.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.arrayOfObjects:216:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest59.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.arrayOfObjects:218:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest60.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.arrayOfArrays:224:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest61.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.arrayOfArrays:226:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest62.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.arrayOfArrays:228:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest63.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.arrayOfArrays:230:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest64.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.arrayOfArrays:232:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest65.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.arrayOfArrays:234:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest66.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.arrayOfArrays:236:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest67.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/stream_traces/JsonReaderPathTest.trace com.google.gson.stream.JsonReaderPathTest.arrayOfArrays:238:*>/home/stg/omc_experiments/slices/gson/stream_slices/JsonReaderPathTest/JsonReaderPathTest68.txt

#Total Asserts in com.google.gson.stream/JsonReaderPathTest=============68
#Total Tests in com.google.gson.stream/JsonReaderPathTest=============0
