#!/bin/bash

echo "computing slice for NullConversionsSkipTest"

mkdir -p /home/stg/omc_experiments/slices/jackson-dataformat-xml/deser_slices/NullConversionsSkipTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/deser_traces/NullConversionsSkipTest.trace com.fasterxml.jackson.dataformat.xml.deser.NullConversionsSkipTest.testSkipNullField1:56:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/deser_slices/NullConversionsSkipTest/NullConversionsSkipTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/deser_traces/NullConversionsSkipTest.trace com.fasterxml.jackson.dataformat.xml.deser.NullConversionsSkipTest.testSkipNullField1:57:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/deser_slices/NullConversionsSkipTest/NullConversionsSkipTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/deser_traces/NullConversionsSkipTest.trace com.fasterxml.jackson.dataformat.xml.deser.NullConversionsSkipTest.testSkipNullField2:65:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/deser_slices/NullConversionsSkipTest/NullConversionsSkipTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/deser_traces/NullConversionsSkipTest.trace com.fasterxml.jackson.dataformat.xml.deser.NullConversionsSkipTest.testSkipNullField2:66:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/deser_slices/NullConversionsSkipTest/NullConversionsSkipTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/deser_traces/NullConversionsSkipTest.trace com.fasterxml.jackson.dataformat.xml.deser.NullConversionsSkipTest.testSkipNullMethod1:75:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/deser_slices/NullConversionsSkipTest/NullConversionsSkipTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/deser_traces/NullConversionsSkipTest.trace com.fasterxml.jackson.dataformat.xml.deser.NullConversionsSkipTest.testSkipNullMethod1:76:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/deser_slices/NullConversionsSkipTest/NullConversionsSkipTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/deser_traces/NullConversionsSkipTest.trace com.fasterxml.jackson.dataformat.xml.deser.NullConversionsSkipTest.testSkipNullMethod2:83:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/deser_slices/NullConversionsSkipTest/NullConversionsSkipTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/deser_traces/NullConversionsSkipTest.trace com.fasterxml.jackson.dataformat.xml.deser.NullConversionsSkipTest.testSkipNullMethod2:84:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/deser_slices/NullConversionsSkipTest/NullConversionsSkipTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/deser_traces/NullConversionsSkipTest.trace com.fasterxml.jackson.dataformat.xml.deser.NullConversionsSkipTest.testSkipNullWithDefaults:98:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/deser_slices/NullConversionsSkipTest/NullConversionsSkipTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/deser_traces/NullConversionsSkipTest.trace com.fasterxml.jackson.dataformat.xml.deser.NullConversionsSkipTest.testSkipNullWithDefaults:104:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/deser_slices/NullConversionsSkipTest/NullConversionsSkipTest10.txt

#Total Asserts in com.fasterxml.jackson.dataformat.xml.deser/NullConversionsSkipTest=============10
#Total Tests in com.fasterxml.jackson.dataformat.xml.deser/NullConversionsSkipTest=============0
