#!/bin/bash

echo "computing slice for JsonToStringStyleTest"

mkdir -p /home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/JsonToStringStyleTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/JsonToStringStyleTest.trace org.apache.commons.lang3.builder.JsonToStringStyleTest.testNull:68:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/JsonToStringStyleTest/JsonToStringStyleTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/JsonToStringStyleTest.trace org.apache.commons.lang3.builder.JsonToStringStyleTest.testBlank:73:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/JsonToStringStyleTest/JsonToStringStyleTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/JsonToStringStyleTest.trace org.apache.commons.lang3.builder.JsonToStringStyleTest.testAppendSuper:78:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/JsonToStringStyleTest/JsonToStringStyleTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/JsonToStringStyleTest.trace org.apache.commons.lang3.builder.JsonToStringStyleTest.testAppendSuper:83:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/JsonToStringStyleTest/JsonToStringStyleTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/JsonToStringStyleTest.trace org.apache.commons.lang3.builder.JsonToStringStyleTest.testAppendSuper:88:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/JsonToStringStyleTest/JsonToStringStyleTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/JsonToStringStyleTest.trace org.apache.commons.lang3.builder.JsonToStringStyleTest.testAppendSuper:94:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/JsonToStringStyleTest/JsonToStringStyleTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/JsonToStringStyleTest.trace org.apache.commons.lang3.builder.JsonToStringStyleTest.testAppendSuper:101:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/JsonToStringStyleTest/JsonToStringStyleTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/JsonToStringStyleTest.trace org.apache.commons.lang3.builder.JsonToStringStyleTest.testAppendSuper:104:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/JsonToStringStyleTest/JsonToStringStyleTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/JsonToStringStyleTest.trace org.apache.commons.lang3.builder.JsonToStringStyleTest.testChar:116:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/JsonToStringStyleTest/JsonToStringStyleTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/JsonToStringStyleTest.trace org.apache.commons.lang3.builder.JsonToStringStyleTest.testChar:118:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/JsonToStringStyleTest/JsonToStringStyleTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/JsonToStringStyleTest.trace org.apache.commons.lang3.builder.JsonToStringStyleTest.testDate:133:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/JsonToStringStyleTest/JsonToStringStyleTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/JsonToStringStyleTest.trace org.apache.commons.lang3.builder.JsonToStringStyleTest.testDate:135:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/JsonToStringStyleTest/JsonToStringStyleTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/JsonToStringStyleTest.trace org.apache.commons.lang3.builder.JsonToStringStyleTest.testObject:157:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/JsonToStringStyleTest/JsonToStringStyleTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/JsonToStringStyleTest.trace org.apache.commons.lang3.builder.JsonToStringStyleTest.testObject:159:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/JsonToStringStyleTest/JsonToStringStyleTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/JsonToStringStyleTest.trace org.apache.commons.lang3.builder.JsonToStringStyleTest.testObject:161:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/JsonToStringStyleTest/JsonToStringStyleTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/JsonToStringStyleTest.trace org.apache.commons.lang3.builder.JsonToStringStyleTest.testObject:177:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/JsonToStringStyleTest/JsonToStringStyleTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/JsonToStringStyleTest.trace org.apache.commons.lang3.builder.JsonToStringStyleTest.testObject:188:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/JsonToStringStyleTest/JsonToStringStyleTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/JsonToStringStyleTest.trace org.apache.commons.lang3.builder.JsonToStringStyleTest.testObject:199:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/JsonToStringStyleTest/JsonToStringStyleTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/JsonToStringStyleTest.trace org.apache.commons.lang3.builder.JsonToStringStyleTest.testObject:211:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/JsonToStringStyleTest/JsonToStringStyleTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/JsonToStringStyleTest.trace org.apache.commons.lang3.builder.JsonToStringStyleTest.testObject:223:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/JsonToStringStyleTest/JsonToStringStyleTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/JsonToStringStyleTest.trace org.apache.commons.lang3.builder.JsonToStringStyleTest.testPerson:237:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/JsonToStringStyleTest/JsonToStringStyleTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/JsonToStringStyleTest.trace org.apache.commons.lang3.builder.JsonToStringStyleTest.toString:262:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/JsonToStringStyleTest/JsonToStringStyleTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/JsonToStringStyleTest.trace org.apache.commons.lang3.builder.JsonToStringStyleTest.testLong:278:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/JsonToStringStyleTest/JsonToStringStyleTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/JsonToStringStyleTest.trace org.apache.commons.lang3.builder.JsonToStringStyleTest.testLong:280:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/JsonToStringStyleTest/JsonToStringStyleTest24.txt

#Total Asserts in org.apache.commons.lang3.builder/JsonToStringStyleTest=============24
#Total Tests in org.apache.commons.lang3.builder/JsonToStringStyleTest=============0
