#!/bin/bash

echo "computing slice for ShortPrefixToStringStyleTest"

mkdir -p /home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testBlank:63:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testAppendSuper:68:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testAppendSuper:69:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testAppendSuper:71:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testAppendSuper:72:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testAppendSuper:73:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testObject:80:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testObject:81:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testObject:82:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testObject:83:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testObject:84:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testObject:85:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testObject:86:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testObject:87:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testObject:88:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testObject:89:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testObject:90:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testObject:91:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testPerson:101:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testLong:106:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testLong:107:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testLong:108:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testObjectArray:114:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testObjectArray:115:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testObjectArray:117:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testObjectArray:118:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testLongArray:124:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testLongArray:125:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testLongArray:127:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testLongArray:128:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testLongArrayArray:134:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testLongArrayArray:135:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest32.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testLongArrayArray:137:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest33.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/ShortPrefixToStringStyleTest.trace org.apache.commons.lang3.builder.ShortPrefixToStringStyleTest.testLongArrayArray:138:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/ShortPrefixToStringStyleTest/ShortPrefixToStringStyleTest34.txt

#Total Asserts in org.apache.commons.lang3.builder/ShortPrefixToStringStyleTest=============34
#Total Tests in org.apache.commons.lang3.builder/ShortPrefixToStringStyleTest=============0
