#!/bin/bash

echo "computing slice for SimpleToStringStyleTest"

mkdir -p /home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testBlank:62:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testAppendSuper:67:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testAppendSuper:68:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testAppendSuper:70:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testAppendSuper:71:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testAppendSuper:72:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testObject:79:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testObject:80:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testObject:81:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testObject:82:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testObject:83:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testObject:84:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testObject:85:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testObject:86:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testObject:87:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testObject:88:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testObject:89:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testObject:90:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testPerson:99:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testLong:104:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testLong:105:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testLong:106:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testObjectArray:112:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testObjectArray:113:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testObjectArray:115:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testObjectArray:116:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testLongArray:122:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testLongArray:123:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testLongArray:125:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testLongArray:126:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testLongArrayArray:132:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testLongArrayArray:133:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest32.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testLongArrayArray:135:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest33.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/builder_traces/SimpleToStringStyleTest.trace org.apache.commons.lang3.builder.SimpleToStringStyleTest.testLongArrayArray:136:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/builder_slices/SimpleToStringStyleTest/SimpleToStringStyleTest34.txt

#Total Asserts in org.apache.commons.lang3.builder/SimpleToStringStyleTest=============34
#Total Tests in org.apache.commons.lang3.builder/SimpleToStringStyleTest=============0
