#!/bin/bash

echo "computing slice for RefinedSoundexTest"

mkdir -p /home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/RefinedSoundexTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/RefinedSoundexTest.trace org.apache.commons.codec.language.RefinedSoundexTest.testDifference:41:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/RefinedSoundexTest/RefinedSoundexTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/RefinedSoundexTest.trace org.apache.commons.codec.language.RefinedSoundexTest.testDifference:42:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/RefinedSoundexTest/RefinedSoundexTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/RefinedSoundexTest.trace org.apache.commons.codec.language.RefinedSoundexTest.testDifference:43:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/RefinedSoundexTest/RefinedSoundexTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/RefinedSoundexTest.trace org.apache.commons.codec.language.RefinedSoundexTest.testDifference:45:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/RefinedSoundexTest/RefinedSoundexTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/RefinedSoundexTest.trace org.apache.commons.codec.language.RefinedSoundexTest.testDifference:46:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/RefinedSoundexTest/RefinedSoundexTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/RefinedSoundexTest.trace org.apache.commons.codec.language.RefinedSoundexTest.testDifference:47:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/RefinedSoundexTest/RefinedSoundexTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/RefinedSoundexTest.trace org.apache.commons.codec.language.RefinedSoundexTest.testDifference:48:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/RefinedSoundexTest/RefinedSoundexTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/RefinedSoundexTest.trace org.apache.commons.codec.language.RefinedSoundexTest.testDifference:51:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/RefinedSoundexTest/RefinedSoundexTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/RefinedSoundexTest.trace org.apache.commons.codec.language.RefinedSoundexTest.testDifference:52:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/RefinedSoundexTest/RefinedSoundexTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/RefinedSoundexTest.trace org.apache.commons.codec.language.RefinedSoundexTest.testDifference:55:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/RefinedSoundexTest/RefinedSoundexTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/RefinedSoundexTest.trace org.apache.commons.codec.language.RefinedSoundexTest.testDifference:56:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/RefinedSoundexTest/RefinedSoundexTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/RefinedSoundexTest.trace org.apache.commons.codec.language.RefinedSoundexTest.testDifference:57:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/RefinedSoundexTest/RefinedSoundexTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/RefinedSoundexTest.trace org.apache.commons.codec.language.RefinedSoundexTest.testEncode:62:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/RefinedSoundexTest/RefinedSoundexTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/RefinedSoundexTest.trace org.apache.commons.codec.language.RefinedSoundexTest.testEncode:63:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/RefinedSoundexTest/RefinedSoundexTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/RefinedSoundexTest.trace org.apache.commons.codec.language.RefinedSoundexTest.testEncode:64:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/RefinedSoundexTest/RefinedSoundexTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/RefinedSoundexTest.trace org.apache.commons.codec.language.RefinedSoundexTest.testEncode:65:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/RefinedSoundexTest/RefinedSoundexTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/RefinedSoundexTest.trace org.apache.commons.codec.language.RefinedSoundexTest.testEncode:66:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/RefinedSoundexTest/RefinedSoundexTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/RefinedSoundexTest.trace org.apache.commons.codec.language.RefinedSoundexTest.testEncode:67:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/RefinedSoundexTest/RefinedSoundexTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/RefinedSoundexTest.trace org.apache.commons.codec.language.RefinedSoundexTest.testEncode:68:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/RefinedSoundexTest/RefinedSoundexTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/RefinedSoundexTest.trace org.apache.commons.codec.language.RefinedSoundexTest.testEncode:69:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/RefinedSoundexTest/RefinedSoundexTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/RefinedSoundexTest.trace org.apache.commons.codec.language.RefinedSoundexTest.testEncode:70:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/RefinedSoundexTest/RefinedSoundexTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/RefinedSoundexTest.trace org.apache.commons.codec.language.RefinedSoundexTest.testEncode:71:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/RefinedSoundexTest/RefinedSoundexTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/RefinedSoundexTest.trace org.apache.commons.codec.language.RefinedSoundexTest.testEncode:72:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/RefinedSoundexTest/RefinedSoundexTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/RefinedSoundexTest.trace org.apache.commons.codec.language.RefinedSoundexTest.testEncode:75:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/RefinedSoundexTest/RefinedSoundexTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/RefinedSoundexTest.trace org.apache.commons.codec.language.RefinedSoundexTest.testGetMappingCodeNonLetter:81:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/RefinedSoundexTest/RefinedSoundexTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/RefinedSoundexTest.trace org.apache.commons.codec.language.RefinedSoundexTest.testNewInstance:86:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/RefinedSoundexTest/RefinedSoundexTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/RefinedSoundexTest.trace org.apache.commons.codec.language.RefinedSoundexTest.testNewInstance2:91:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/RefinedSoundexTest/RefinedSoundexTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/RefinedSoundexTest.trace org.apache.commons.codec.language.RefinedSoundexTest.testNewInstance3:96:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/RefinedSoundexTest/RefinedSoundexTest28.txt

#Total Asserts in org.apache.commons.codec.language/RefinedSoundexTest=============28
#Total Tests in org.apache.commons.codec.language/RefinedSoundexTest=============0
