#!/bin/bash

echo "computing slice for MetaphoneTest"

mkdir -p /home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.assertIsMetaphoneEqual:35:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.assertIsMetaphoneEqual:41:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.assertMetaphoneEqual:52:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.assertMetaphoneEqual:53:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testMetaphone:363:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testMetaphone:364:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testMetaphone:365:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testMetaphone:366:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testMetaphone:367:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testMetaphone:368:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testMetaphone:369:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testMetaphone:370:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testMetaphone:371:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testMetaphone:372:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testMetaphone:373:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testWordEndingInMB:378:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testWordEndingInMB:379:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testWordEndingInMB:380:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testDiscardOfSCEOrSCIOrSCY:385:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testDiscardOfSCEOrSCIOrSCY:386:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testDiscardOfSCEOrSCIOrSCY:387:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testWhy:396:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testWordsWithCIA:401:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testTranslateOfSCHAndCH:406:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testTranslateOfSCHAndCH:407:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testTranslateOfSCHAndCH:409:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testTranslateOfSCHAndCH:410:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testTranslateToJOfDGEOrDGIOrDGY:415:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testTranslateToJOfDGEOrDGIOrDGY:416:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testTranslateToJOfDGEOrDGIOrDGY:417:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testDiscardOfSilentHAfterG:422:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testDiscardOfSilentHAfterG:423:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest32.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testDiscardOfSilentGN:429:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest33.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testDiscardOfSilentGN:432:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest34.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testPHTOF:437:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest35.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testSHAndSIOAndSIAToX:442:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest36.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testSHAndSIOAndSIAToX:443:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest37.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testSHAndSIOAndSIAToX:444:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest38.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testTIOAndTIAToX:449:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest39.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testTIOAndTIAToX:450:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest40.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testTCH:455:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest41.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testTCH:456:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest42.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testExceedLength:462:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest43.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/language_traces/MetaphoneTest.trace org.apache.commons.codec.language.MetaphoneTest.testSetMaxLengthWithTruncation:469:*>/home/stg/omc_experiments/slices/commons-codec-1.12/language_slices/MetaphoneTest/MetaphoneTest44.txt

#Total Asserts in org.apache.commons.codec.language/MetaphoneTest=============44
#Total Tests in org.apache.commons.codec.language/MetaphoneTest=============0
