#!/bin/bash

echo "computing slice for DialBackgroundTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/dial_slices/DialBackgroundTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialBackgroundTest.trace org.jfree.chart.plot.dial.DialBackgroundTest.testEquals:68:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialBackgroundTest/DialBackgroundTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialBackgroundTest.trace org.jfree.chart.plot.dial.DialBackgroundTest.testEquals:73:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialBackgroundTest/DialBackgroundTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialBackgroundTest.trace org.jfree.chart.plot.dial.DialBackgroundTest.testEquals:76:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialBackgroundTest/DialBackgroundTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialBackgroundTest.trace org.jfree.chart.plot.dial.DialBackgroundTest.testEquals:81:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialBackgroundTest/DialBackgroundTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialBackgroundTest.trace org.jfree.chart.plot.dial.DialBackgroundTest.testEquals:84:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialBackgroundTest/DialBackgroundTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialBackgroundTest.trace org.jfree.chart.plot.dial.DialBackgroundTest.testEquals:88:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialBackgroundTest/DialBackgroundTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialBackgroundTest.trace org.jfree.chart.plot.dial.DialBackgroundTest.testEquals:90:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialBackgroundTest/DialBackgroundTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialBackgroundTest.trace org.jfree.chart.plot.dial.DialBackgroundTest.testHashCode:101:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialBackgroundTest/DialBackgroundTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialBackgroundTest.trace org.jfree.chart.plot.dial.DialBackgroundTest.testHashCode:104:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialBackgroundTest/DialBackgroundTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialBackgroundTest.trace org.jfree.chart.plot.dial.DialBackgroundTest.testCloning:115:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialBackgroundTest/DialBackgroundTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialBackgroundTest.trace org.jfree.chart.plot.dial.DialBackgroundTest.testCloning:116:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialBackgroundTest/DialBackgroundTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialBackgroundTest.trace org.jfree.chart.plot.dial.DialBackgroundTest.testCloning:117:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialBackgroundTest/DialBackgroundTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialBackgroundTest.trace org.jfree.chart.plot.dial.DialBackgroundTest.testCloning:126:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialBackgroundTest/DialBackgroundTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialBackgroundTest.trace org.jfree.chart.plot.dial.DialBackgroundTest.testCloning:127:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialBackgroundTest/DialBackgroundTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialBackgroundTest.trace org.jfree.chart.plot.dial.DialBackgroundTest.testCloning:128:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialBackgroundTest/DialBackgroundTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialBackgroundTest.trace org.jfree.chart.plot.dial.DialBackgroundTest.testCloning:133:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialBackgroundTest/DialBackgroundTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialBackgroundTest.trace org.jfree.chart.plot.dial.DialBackgroundTest.testCloning:134:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialBackgroundTest/DialBackgroundTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialBackgroundTest.trace org.jfree.chart.plot.dial.DialBackgroundTest.testSerialization:145:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialBackgroundTest/DialBackgroundTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialBackgroundTest.trace org.jfree.chart.plot.dial.DialBackgroundTest.testSerialization:155:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialBackgroundTest/DialBackgroundTest19.txt

#Total Asserts in org.jfree.chart.plot.dial/DialBackgroundTest=============19
#Total Tests in org.jfree.chart.plot.dial/DialBackgroundTest=============0
