#!/bin/bash

echo "computing slice for DialPlotTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testEquals:83:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testEquals:87:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testEquals:89:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testEquals:92:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testEquals:94:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testEquals:100:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testEquals:104:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testEquals:107:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testEquals:109:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testEquals:116:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testEquals:121:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testEquals:125:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testEquals:127:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testEquals:131:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testEquals:133:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testHashCode:143:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testHashCode:146:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testCloning:156:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testCloning:157:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testCloning:158:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testSerialization:169:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testBackgroundListener:183:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testBackgroundListener:189:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testBackgroundListener:191:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testCapListener:205:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testCapListener:211:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testCapListener:213:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testFrameListener:227:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testFrameListener:233:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testFrameListener:235:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testScaleListener:249:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testScaleListener:255:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest32.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testScaleListener:257:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest33.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testLayerListener:271:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest34.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testLayerListener:277:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest35.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testLayerListener:279:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest36.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/DialPlotTest.trace org.jfree.chart.plot.dial.DialPlotTest.testLayerListener:284:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/DialPlotTest/DialPlotTest37.txt

#Total Asserts in org.jfree.chart.plot.dial/DialPlotTest=============37
#Total Tests in org.jfree.chart.plot.dial/DialPlotTest=============0
