#!/bin/bash

echo "computing slice for AbstractDialLayerTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/dial_slices/AbstractDialLayerTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/AbstractDialLayerTest.trace org.jfree.chart.plot.dial.AbstractDialLayerTest.testEquals:62:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/AbstractDialLayerTest/AbstractDialLayerTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/AbstractDialLayerTest.trace org.jfree.chart.plot.dial.AbstractDialLayerTest.testEquals:66:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/AbstractDialLayerTest/AbstractDialLayerTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/AbstractDialLayerTest.trace org.jfree.chart.plot.dial.AbstractDialLayerTest.testEquals:68:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/AbstractDialLayerTest/AbstractDialLayerTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/AbstractDialLayerTest.trace org.jfree.chart.plot.dial.AbstractDialLayerTest.testCloning:79:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/AbstractDialLayerTest/AbstractDialLayerTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/AbstractDialLayerTest.trace org.jfree.chart.plot.dial.AbstractDialLayerTest.testCloning:80:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/AbstractDialLayerTest/AbstractDialLayerTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/AbstractDialLayerTest.trace org.jfree.chart.plot.dial.AbstractDialLayerTest.testCloning:81:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/AbstractDialLayerTest/AbstractDialLayerTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/AbstractDialLayerTest.trace org.jfree.chart.plot.dial.AbstractDialLayerTest.testCloning:86:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/AbstractDialLayerTest/AbstractDialLayerTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/AbstractDialLayerTest.trace org.jfree.chart.plot.dial.AbstractDialLayerTest.testCloning:87:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/AbstractDialLayerTest/AbstractDialLayerTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/AbstractDialLayerTest.trace org.jfree.chart.plot.dial.AbstractDialLayerTest.testSerialization:98:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/AbstractDialLayerTest/AbstractDialLayerTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/AbstractDialLayerTest.trace org.jfree.chart.plot.dial.AbstractDialLayerTest.testSerialization:103:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/AbstractDialLayerTest/AbstractDialLayerTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/AbstractDialLayerTest.trace org.jfree.chart.plot.dial.AbstractDialLayerTest.testSerialization:104:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/AbstractDialLayerTest/AbstractDialLayerTest11.txt

#Total Asserts in org.jfree.chart.plot.dial/AbstractDialLayerTest=============11
#Total Tests in org.jfree.chart.plot.dial/AbstractDialLayerTest=============0
