#!/bin/bash

echo "computing slice for StandardDialRangeTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/dial_slices/StandardDialRangeTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/StandardDialRangeTest.trace org.jfree.chart.plot.dial.StandardDialRangeTest.testEquals:65:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/StandardDialRangeTest/StandardDialRangeTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/StandardDialRangeTest.trace org.jfree.chart.plot.dial.StandardDialRangeTest.testEquals:69:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/StandardDialRangeTest/StandardDialRangeTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/StandardDialRangeTest.trace org.jfree.chart.plot.dial.StandardDialRangeTest.testEquals:71:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/StandardDialRangeTest/StandardDialRangeTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/StandardDialRangeTest.trace org.jfree.chart.plot.dial.StandardDialRangeTest.testEquals:75:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/StandardDialRangeTest/StandardDialRangeTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/StandardDialRangeTest.trace org.jfree.chart.plot.dial.StandardDialRangeTest.testEquals:77:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/StandardDialRangeTest/StandardDialRangeTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/StandardDialRangeTest.trace org.jfree.chart.plot.dial.StandardDialRangeTest.testEquals:82:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/StandardDialRangeTest/StandardDialRangeTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/StandardDialRangeTest.trace org.jfree.chart.plot.dial.StandardDialRangeTest.testEquals:85:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/StandardDialRangeTest/StandardDialRangeTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/StandardDialRangeTest.trace org.jfree.chart.plot.dial.StandardDialRangeTest.testEquals:89:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/StandardDialRangeTest/StandardDialRangeTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/StandardDialRangeTest.trace org.jfree.chart.plot.dial.StandardDialRangeTest.testEquals:91:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/StandardDialRangeTest/StandardDialRangeTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/StandardDialRangeTest.trace org.jfree.chart.plot.dial.StandardDialRangeTest.testHashCode:101:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/StandardDialRangeTest/StandardDialRangeTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/StandardDialRangeTest.trace org.jfree.chart.plot.dial.StandardDialRangeTest.testHashCode:104:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/StandardDialRangeTest/StandardDialRangeTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/StandardDialRangeTest.trace org.jfree.chart.plot.dial.StandardDialRangeTest.testCloning:114:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/StandardDialRangeTest/StandardDialRangeTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/StandardDialRangeTest.trace org.jfree.chart.plot.dial.StandardDialRangeTest.testCloning:115:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/StandardDialRangeTest/StandardDialRangeTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/StandardDialRangeTest.trace org.jfree.chart.plot.dial.StandardDialRangeTest.testCloning:116:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/StandardDialRangeTest/StandardDialRangeTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/StandardDialRangeTest.trace org.jfree.chart.plot.dial.StandardDialRangeTest.testCloning:121:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/StandardDialRangeTest/StandardDialRangeTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/StandardDialRangeTest.trace org.jfree.chart.plot.dial.StandardDialRangeTest.testCloning:122:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/StandardDialRangeTest/StandardDialRangeTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/dial_traces/StandardDialRangeTest.trace org.jfree.chart.plot.dial.StandardDialRangeTest.testSerialization:132:*>/home/stg/omc_experiments/slices/jfreechart/dial_slices/StandardDialRangeTest/StandardDialRangeTest17.txt

#Total Asserts in org.jfree.chart.plot.dial/StandardDialRangeTest=============17
#Total Tests in org.jfree.chart.plot.dial/StandardDialRangeTest=============0
