#!/bin/bash

echo "computing slice for JavaBeanConverterTest"

mkdir -p /home/stg/omc_experiments/slices/xstream/javabean_slices/JavaBeanConverterTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/javabean_traces/JavaBeanConverterTest.trace com.thoughtworks.xstream.converters.javabean.JavaBeanConverterTest.testSerializesAllPrimitiveFieldsInACustomObject:207:*>/home/stg/omc_experiments/slices/xstream/javabean_slices/JavaBeanConverterTest/JavaBeanConverterTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/javabean_traces/JavaBeanConverterTest.trace com.thoughtworks.xstream.converters.javabean.JavaBeanConverterTest.testSerializesNullValue:240:*>/home/stg/omc_experiments/slices/xstream/javabean_slices/JavaBeanConverterTest/JavaBeanConverterTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/javabean_traces/JavaBeanConverterTest.trace com.thoughtworks.xstream.converters.javabean.JavaBeanConverterTest.testSerializesNullValue:243:*>/home/stg/omc_experiments/slices/xstream/javabean_slices/JavaBeanConverterTest/JavaBeanConverterTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/javabean_traces/JavaBeanConverterTest.trace com.thoughtworks.xstream.converters.javabean.JavaBeanConverterTest.testDoesNotSerializeStaticFields:301:*>/home/stg/omc_experiments/slices/xstream/javabean_slices/JavaBeanConverterTest/JavaBeanConverterTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/javabean_traces/JavaBeanConverterTest.trace com.thoughtworks.xstream.converters.javabean.JavaBeanConverterTest.testSupportsTypeAlias:335:*>/home/stg/omc_experiments/slices/xstream/javabean_slices/JavaBeanConverterTest/JavaBeanConverterTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/javabean_traces/JavaBeanConverterTest.trace com.thoughtworks.xstream.converters.javabean.JavaBeanConverterTest.testDoesNotSerializeOmittedFields:350:*>/home/stg/omc_experiments/slices/xstream/javabean_slices/JavaBeanConverterTest/JavaBeanConverterTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/javabean_traces/JavaBeanConverterTest.trace com.thoughtworks.xstream.converters.javabean.JavaBeanConverterTest.testDoesNotDeserializeOmittedFields:368:*>/home/stg/omc_experiments/slices/xstream/javabean_slices/JavaBeanConverterTest/JavaBeanConverterTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/javabean_traces/JavaBeanConverterTest.trace com.thoughtworks.xstream.converters.javabean.JavaBeanConverterTest.testIgnoresUnknownFieldsMatchingPattern:386:*>/home/stg/omc_experiments/slices/xstream/javabean_slices/JavaBeanConverterTest/JavaBeanConverterTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/javabean_traces/JavaBeanConverterTest.trace com.thoughtworks.xstream.converters.javabean.JavaBeanConverterTest.testDoesNotGetValueOfOmittedFields:408:*>/home/stg/omc_experiments/slices/xstream/javabean_slices/JavaBeanConverterTest/JavaBeanConverterTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/javabean_traces/JavaBeanConverterTest.trace com.thoughtworks.xstream.converters.javabean.JavaBeanConverterTest.testDoesNotSerializeOmittedInheritedFields:467:*>/home/stg/omc_experiments/slices/xstream/javabean_slices/JavaBeanConverterTest/JavaBeanConverterTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/javabean_traces/JavaBeanConverterTest.trace com.thoughtworks.xstream.converters.javabean.JavaBeanConverterTest.testUseAliasInheritedFields:486:*>/home/stg/omc_experiments/slices/xstream/javabean_slices/JavaBeanConverterTest/JavaBeanConverterTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/javabean_traces/JavaBeanConverterTest.trace com.thoughtworks.xstream.converters.javabean.JavaBeanConverterTest.testFailsFastIfPropertyIsDefinedTwice:506:*>/home/stg/omc_experiments/slices/xstream/javabean_slices/JavaBeanConverterTest/JavaBeanConverterTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/javabean_traces/JavaBeanConverterTest.trace com.thoughtworks.xstream.converters.javabean.JavaBeanConverterTest.testCanConvertDoesNotThrowException:512:*>/home/stg/omc_experiments/slices/xstream/javabean_slices/JavaBeanConverterTest/JavaBeanConverterTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/javabean_traces/JavaBeanConverterTest.trace com.thoughtworks.xstream.converters.javabean.JavaBeanConverterTest.testCanConvertDoesNotThrowException:513:*>/home/stg/omc_experiments/slices/xstream/javabean_slices/JavaBeanConverterTest/JavaBeanConverterTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/javabean_traces/JavaBeanConverterTest.trace com.thoughtworks.xstream.converters.javabean.JavaBeanConverterTest.testCanConvertDoesNotThrowException:514:*>/home/stg/omc_experiments/slices/xstream/javabean_slices/JavaBeanConverterTest/JavaBeanConverterTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/javabean_traces/JavaBeanConverterTest.trace com.thoughtworks.xstream.converters.javabean.JavaBeanConverterTest.testCanConvertDoesNotThrowException:515:*>/home/stg/omc_experiments/slices/xstream/javabean_slices/JavaBeanConverterTest/JavaBeanConverterTest16.txt

#Total Asserts in com.thoughtworks.xstream.converters.javabean/JavaBeanConverterTest=============16
#Total Tests in com.thoughtworks.xstream.converters.javabean/JavaBeanConverterTest=============0
