#!/bin/bash

echo "computing slice for TestISOPeriodFormat"

mkdir -p /home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testSubclassableConstructor:108:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatStandard:114:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatStandard:116:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatStandard:119:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatStandard:121:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatStandard:123:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatStandard:124:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatStandard:125:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatStandard:126:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatStandard_negative:131:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatStandard_negative:134:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatStandard_negative:137:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatStandard_negative:140:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatStandard_negative:143:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat14.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatStandard_negative:146:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat15.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternate:152:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat16.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternate:154:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat17.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternate:157:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat18.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternate:159:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat19.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternate:161:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat20.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternate:162:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat21.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternate:163:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat22.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternate:164:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat23.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternateExtended:170:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat24.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternateExtended:172:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat25.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternateExtended:175:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat26.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternateExtended:177:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat27.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternateExtended:179:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat28.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternateExtended:180:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat29.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternateExtended:181:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat30.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternateExtended:182:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat31.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternateWithWeeks:188:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat32.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternateWithWeeks:190:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat33.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternateWithWeeks:193:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat34.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternateWithWeeks:195:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat35.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternateWithWeeks:197:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat36.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternateWithWeeks:198:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat37.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternateWithWeeks:199:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat38.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternateWithWeeks:200:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat39.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternateExtendedWithWeeks:206:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat40.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternateExtendedWithWeeks:208:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat41.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternateExtendedWithWeeks:211:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat42.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternateExtendedWithWeeks:213:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat43.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternateExtendedWithWeeks:215:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat44.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternateExtendedWithWeeks:216:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat45.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternateExtendedWithWeeks:217:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat46.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestISOPeriodFormat.trace org.joda.time.format.TestISOPeriodFormat.testFormatAlternateExtendedWithWeeks:218:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestISOPeriodFormat/TestISOPeriodFormat47.txt

#Total Asserts in org.joda.time.format/TestISOPeriodFormat=============47
#Total Tests in org.joda.time.format/TestISOPeriodFormat=============0
