#!/bin/bash

echo "computing slice for TestPeriodFormatter"

mkdir -p /home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testPrint_simple:113:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testPrint_bufferMethods:121:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testPrint_writerMethods:135:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testWithGetLocaleMethods:147:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testWithGetLocaleMethods:148:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testWithGetLocaleMethods:151:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testWithGetLocaleMethods:152:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testWithGetParseTypeMethods:157:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testWithGetParseTypeMethods:158:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testWithGetParseTypeMethods:161:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testWithGetParseTypeMethods:162:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testPrinterParserMethods:168:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testPrinterParserMethods:169:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testPrinterParserMethods:170:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter14.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testPrinterParserMethods:171:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter15.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testPrinterParserMethods:172:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter16.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testPrinterParserMethods:173:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter17.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testPrinterParserMethods:176:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter18.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testPrinterParserMethods:177:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter19.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testPrinterParserMethods:178:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter20.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testPrinterParserMethods:179:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter21.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testPrinterParserMethods:180:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter22.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testPrinterParserMethods:182:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter23.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testPrinterParserMethods:187:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter24.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testPrinterParserMethods:188:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter25.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testPrinterParserMethods:189:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter26.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testPrinterParserMethods:190:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter27.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testPrinterParserMethods:195:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter28.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testParsePeriod_simple:201:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter29.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testParsePeriod_parseType:211:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter30.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testParseMutablePeriod_simple:221:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter31.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testParseInto_simple:233:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter32.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testParseInto_simple:234:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter33.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/format_traces/TestPeriodFormatter.trace org.joda.time.format.TestPeriodFormatter.testParseInto_simple:241:*>/home/stg/omc_experiments/slices/fse-joda-time/format_slices/TestPeriodFormatter/TestPeriodFormatter34.txt

#Total Asserts in org.joda.time.format/TestPeriodFormatter=============34
#Total Tests in org.joda.time.format/TestPeriodFormatter=============0
