#!/bin/bash

echo "computing slice for StackedXYAreaRendererTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/xy_slices/StackedXYAreaRendererTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/StackedXYAreaRendererTest.trace org.jfree.chart.renderer.xy.StackedXYAreaRendererTest.testEquals:83:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/StackedXYAreaRendererTest/StackedXYAreaRendererTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/StackedXYAreaRendererTest.trace org.jfree.chart.renderer.xy.StackedXYAreaRendererTest.testEquals:84:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/StackedXYAreaRendererTest/StackedXYAreaRendererTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/StackedXYAreaRendererTest.trace org.jfree.chart.renderer.xy.StackedXYAreaRendererTest.testEquals:88:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/StackedXYAreaRendererTest/StackedXYAreaRendererTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/StackedXYAreaRendererTest.trace org.jfree.chart.renderer.xy.StackedXYAreaRendererTest.testEquals:91:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/StackedXYAreaRendererTest/StackedXYAreaRendererTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/StackedXYAreaRendererTest.trace org.jfree.chart.renderer.xy.StackedXYAreaRendererTest.testEquals:95:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/StackedXYAreaRendererTest/StackedXYAreaRendererTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/StackedXYAreaRendererTest.trace org.jfree.chart.renderer.xy.StackedXYAreaRendererTest.testEquals:97:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/StackedXYAreaRendererTest/StackedXYAreaRendererTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/StackedXYAreaRendererTest.trace org.jfree.chart.renderer.xy.StackedXYAreaRendererTest.testHashcode:107:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/StackedXYAreaRendererTest/StackedXYAreaRendererTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/StackedXYAreaRendererTest.trace org.jfree.chart.renderer.xy.StackedXYAreaRendererTest.testHashcode:110:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/StackedXYAreaRendererTest/StackedXYAreaRendererTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/StackedXYAreaRendererTest.trace org.jfree.chart.renderer.xy.StackedXYAreaRendererTest.testCloning:120:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/StackedXYAreaRendererTest/StackedXYAreaRendererTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/StackedXYAreaRendererTest.trace org.jfree.chart.renderer.xy.StackedXYAreaRendererTest.testCloning:121:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/StackedXYAreaRendererTest/StackedXYAreaRendererTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/StackedXYAreaRendererTest.trace org.jfree.chart.renderer.xy.StackedXYAreaRendererTest.testCloning:122:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/StackedXYAreaRendererTest/StackedXYAreaRendererTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/StackedXYAreaRendererTest.trace org.jfree.chart.renderer.xy.StackedXYAreaRendererTest.testPublicCloneable:131:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/StackedXYAreaRendererTest/StackedXYAreaRendererTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/StackedXYAreaRendererTest.trace org.jfree.chart.renderer.xy.StackedXYAreaRendererTest.testSerialization:144:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/StackedXYAreaRendererTest/StackedXYAreaRendererTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/StackedXYAreaRendererTest.trace org.jfree.chart.renderer.xy.StackedXYAreaRendererTest.testFindRangeBounds:160:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/StackedXYAreaRendererTest/StackedXYAreaRendererTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/StackedXYAreaRendererTest.trace org.jfree.chart.renderer.xy.StackedXYAreaRendererTest.testFindRangeBounds:161:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/StackedXYAreaRendererTest/StackedXYAreaRendererTest15.txt

#Total Asserts in org.jfree.chart.renderer.xy/StackedXYAreaRendererTest=============15
#Total Tests in org.jfree.chart.renderer.xy/StackedXYAreaRendererTest=============0
