#!/bin/bash

echo "computing slice for XYAreaRendererTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testEquals:80:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testEquals:83:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testEquals:85:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testEquals:88:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testEquals:90:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testEquals:93:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testEquals:95:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testEquals:98:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testEquals:100:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testEquals:103:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testEquals:105:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testEquals:108:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testEquals:110:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testEquals:113:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testEquals:115:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testEquals:118:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testEquals:120:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testEquals:124:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testEquals:127:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testHashcode:137:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testHashcode:140:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testHashcode:143:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testCloning:155:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testCloning:156:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testCloning:157:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testCloning:161:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testCloning:163:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testPublicCloneable:172:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testSerialization:182:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testGetLegendItemSeriesIndex:250:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testGetLegendItemSeriesIndex:251:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYAreaRendererTest.trace org.jfree.chart.renderer.xy.XYAreaRendererTest.testGetLegendItemSeriesIndex:252:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYAreaRendererTest/XYAreaRendererTest32.txt

#Total Asserts in org.jfree.chart.renderer.xy/XYAreaRendererTest=============32
#Total Tests in org.jfree.chart.renderer.xy/XYAreaRendererTest=============0
