#!/bin/bash

echo "computing slice for XYLineAndShapeRendererTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testEquals:82:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testEquals:83:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testEquals:86:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testEquals:88:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testEquals:91:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testEquals:93:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testEquals:96:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testEquals:98:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testEquals:101:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testEquals:103:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testEquals:106:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testEquals:108:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testEquals:111:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testEquals:113:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testEquals:116:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testEquals:118:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testEquals:121:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testEquals:123:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testEquals:126:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testEquals:128:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testEquals:131:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testEquals:133:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testEquals:136:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testEquals:138:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testEquals2:148:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testEquals2:149:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testEquals2:152:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testEquals2:154:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testHashcode:165:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testHashcode:168:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testCloning:180:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testCloning:181:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest32.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testCloning:182:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest33.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testCloning:185:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest34.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testCloning:187:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest35.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testCloning:190:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest36.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testCloning:192:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest37.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testCloning:195:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest38.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testCloning:197:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest39.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testCloning:200:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest40.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testCloning:202:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest41.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testPublicCloneable:211:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest42.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testSerialization:222:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest43.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testFindDomainBounds:239:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest44.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testFindDomainBounds:240:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest45.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testFindDomainBounds:241:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest46.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testFindDomainBounds:242:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest47.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testFindRangeBounds:259:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest48.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testFindRangeBounds:260:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest49.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testFindRangeBounds:261:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest50.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testFindRangeBounds:262:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest51.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testGetLegendItemSeriesIndex:296:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest52.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testGetLegendItemSeriesIndex:297:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest53.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYLineAndShapeRendererTest.trace org.jfree.chart.renderer.xy.XYLineAndShapeRendererTest.testGetLegendItemSeriesIndex:298:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYLineAndShapeRendererTest/XYLineAndShapeRendererTest54.txt

#Total Asserts in org.jfree.chart.renderer.xy/XYLineAndShapeRendererTest=============54
#Total Tests in org.jfree.chart.renderer.xy/XYLineAndShapeRendererTest=============0
