#!/bin/bash

echo "computing slice for CandlestickRendererTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testConstructor:82:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testConstructor:83:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testConstructor:84:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testConstructor:85:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testConstructor:86:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testConstructor:87:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testEquals:97:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testEquals:102:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testEquals:105:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testEquals:110:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testEquals:113:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testEquals:117:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testEquals:119:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testEquals:123:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testEquals:125:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testEquals:129:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testEquals:131:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testEquals:135:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testEquals:137:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testEquals:141:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testEquals:143:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testEquals:147:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testEquals:149:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testEquals:152:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testEquals:154:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testEquals:157:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testEquals:159:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testHashcode:169:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testHashcode:172:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testCloning:182:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testCloning:183:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testCloning:184:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest32.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testPublicCloneable:193:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest33.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testSerialization:204:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest34.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testFindRangeBounds:219:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest35.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testFindRangeBounds:226:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest36.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testFindRangeBounds:231:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest37.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/CandlestickRendererTest.trace org.jfree.chart.renderer.xy.CandlestickRendererTest.testFindRangeBounds:235:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/CandlestickRendererTest/CandlestickRendererTest38.txt

#Total Asserts in org.jfree.chart.renderer.xy/CandlestickRendererTest=============38
#Total Tests in org.jfree.chart.renderer.xy/CandlestickRendererTest=============0
