#!/bin/bash

echo "computing slice for XYErrorRendererTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/xy_slices/XYErrorRendererTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYErrorRendererTest.trace org.jfree.chart.renderer.xy.XYErrorRendererTest.testEquals:71:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYErrorRendererTest/XYErrorRendererTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYErrorRendererTest.trace org.jfree.chart.renderer.xy.XYErrorRendererTest.testEquals:75:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYErrorRendererTest/XYErrorRendererTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYErrorRendererTest.trace org.jfree.chart.renderer.xy.XYErrorRendererTest.testEquals:77:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYErrorRendererTest/XYErrorRendererTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYErrorRendererTest.trace org.jfree.chart.renderer.xy.XYErrorRendererTest.testEquals:81:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYErrorRendererTest/XYErrorRendererTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYErrorRendererTest.trace org.jfree.chart.renderer.xy.XYErrorRendererTest.testEquals:83:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYErrorRendererTest/XYErrorRendererTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYErrorRendererTest.trace org.jfree.chart.renderer.xy.XYErrorRendererTest.testEquals:87:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYErrorRendererTest/XYErrorRendererTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYErrorRendererTest.trace org.jfree.chart.renderer.xy.XYErrorRendererTest.testEquals:89:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYErrorRendererTest/XYErrorRendererTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYErrorRendererTest.trace org.jfree.chart.renderer.xy.XYErrorRendererTest.testEquals:94:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYErrorRendererTest/XYErrorRendererTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYErrorRendererTest.trace org.jfree.chart.renderer.xy.XYErrorRendererTest.testEquals:97:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYErrorRendererTest/XYErrorRendererTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYErrorRendererTest.trace org.jfree.chart.renderer.xy.XYErrorRendererTest.testEquals:101:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYErrorRendererTest/XYErrorRendererTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYErrorRendererTest.trace org.jfree.chart.renderer.xy.XYErrorRendererTest.testEquals:103:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYErrorRendererTest/XYErrorRendererTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYErrorRendererTest.trace org.jfree.chart.renderer.xy.XYErrorRendererTest.testHashcode:114:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYErrorRendererTest/XYErrorRendererTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYErrorRendererTest.trace org.jfree.chart.renderer.xy.XYErrorRendererTest.testHashcode:117:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYErrorRendererTest/XYErrorRendererTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYErrorRendererTest.trace org.jfree.chart.renderer.xy.XYErrorRendererTest.testCloning:129:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYErrorRendererTest/XYErrorRendererTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYErrorRendererTest.trace org.jfree.chart.renderer.xy.XYErrorRendererTest.testCloning:130:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYErrorRendererTest/XYErrorRendererTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYErrorRendererTest.trace org.jfree.chart.renderer.xy.XYErrorRendererTest.testCloning:131:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYErrorRendererTest/XYErrorRendererTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYErrorRendererTest.trace org.jfree.chart.renderer.xy.XYErrorRendererTest.testCloning2:142:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYErrorRendererTest/XYErrorRendererTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYErrorRendererTest.trace org.jfree.chart.renderer.xy.XYErrorRendererTest.testCloning2:143:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYErrorRendererTest/XYErrorRendererTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYErrorRendererTest.trace org.jfree.chart.renderer.xy.XYErrorRendererTest.testCloning2:144:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYErrorRendererTest/XYErrorRendererTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYErrorRendererTest.trace org.jfree.chart.renderer.xy.XYErrorRendererTest.testPublicCloneable:153:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYErrorRendererTest/XYErrorRendererTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYErrorRendererTest.trace org.jfree.chart.renderer.xy.XYErrorRendererTest.testSerialization:165:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYErrorRendererTest/XYErrorRendererTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYErrorRendererTest.trace org.jfree.chart.renderer.xy.XYErrorRendererTest.testSerialization2:176:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYErrorRendererTest/XYErrorRendererTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYErrorRendererTest.trace org.jfree.chart.renderer.xy.XYErrorRendererTest.testFindDomainBounds:185:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYErrorRendererTest/XYErrorRendererTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYErrorRendererTest.trace org.jfree.chart.renderer.xy.XYErrorRendererTest.testFindRangeBounds:195:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYErrorRendererTest/XYErrorRendererTest24.txt

#Total Asserts in org.jfree.chart.renderer.xy/XYErrorRendererTest=============24
#Total Tests in org.jfree.chart.renderer.xy/XYErrorRendererTest=============0
