#!/bin/bash

echo "computing slice for XYStepAreaRendererTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/xy_slices/XYStepAreaRendererTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYStepAreaRendererTest.trace org.jfree.chart.renderer.xy.XYStepAreaRendererTest.testEquals:74:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYStepAreaRendererTest/XYStepAreaRendererTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYStepAreaRendererTest.trace org.jfree.chart.renderer.xy.XYStepAreaRendererTest.testEquals:77:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYStepAreaRendererTest/XYStepAreaRendererTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYStepAreaRendererTest.trace org.jfree.chart.renderer.xy.XYStepAreaRendererTest.testEquals:79:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYStepAreaRendererTest/XYStepAreaRendererTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYStepAreaRendererTest.trace org.jfree.chart.renderer.xy.XYStepAreaRendererTest.testEquals:82:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYStepAreaRendererTest/XYStepAreaRendererTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYStepAreaRendererTest.trace org.jfree.chart.renderer.xy.XYStepAreaRendererTest.testEquals:84:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYStepAreaRendererTest/XYStepAreaRendererTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYStepAreaRendererTest.trace org.jfree.chart.renderer.xy.XYStepAreaRendererTest.testEquals:87:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYStepAreaRendererTest/XYStepAreaRendererTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYStepAreaRendererTest.trace org.jfree.chart.renderer.xy.XYStepAreaRendererTest.testEquals:89:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYStepAreaRendererTest/XYStepAreaRendererTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYStepAreaRendererTest.trace org.jfree.chart.renderer.xy.XYStepAreaRendererTest.testEquals:92:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYStepAreaRendererTest/XYStepAreaRendererTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYStepAreaRendererTest.trace org.jfree.chart.renderer.xy.XYStepAreaRendererTest.testEquals:94:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYStepAreaRendererTest/XYStepAreaRendererTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYStepAreaRendererTest.trace org.jfree.chart.renderer.xy.XYStepAreaRendererTest.testEquals:97:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYStepAreaRendererTest/XYStepAreaRendererTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYStepAreaRendererTest.trace org.jfree.chart.renderer.xy.XYStepAreaRendererTest.testEquals:99:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYStepAreaRendererTest/XYStepAreaRendererTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYStepAreaRendererTest.trace org.jfree.chart.renderer.xy.XYStepAreaRendererTest.testEquals:102:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYStepAreaRendererTest/XYStepAreaRendererTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYStepAreaRendererTest.trace org.jfree.chart.renderer.xy.XYStepAreaRendererTest.testEquals:104:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYStepAreaRendererTest/XYStepAreaRendererTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYStepAreaRendererTest.trace org.jfree.chart.renderer.xy.XYStepAreaRendererTest.testHashcode:115:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYStepAreaRendererTest/XYStepAreaRendererTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYStepAreaRendererTest.trace org.jfree.chart.renderer.xy.XYStepAreaRendererTest.testHashcode:118:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYStepAreaRendererTest/XYStepAreaRendererTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYStepAreaRendererTest.trace org.jfree.chart.renderer.xy.XYStepAreaRendererTest.testCloning:128:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYStepAreaRendererTest/XYStepAreaRendererTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYStepAreaRendererTest.trace org.jfree.chart.renderer.xy.XYStepAreaRendererTest.testCloning:129:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYStepAreaRendererTest/XYStepAreaRendererTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYStepAreaRendererTest.trace org.jfree.chart.renderer.xy.XYStepAreaRendererTest.testCloning:130:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYStepAreaRendererTest/XYStepAreaRendererTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYStepAreaRendererTest.trace org.jfree.chart.renderer.xy.XYStepAreaRendererTest.testPublicCloneable:139:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYStepAreaRendererTest/XYStepAreaRendererTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/xy_traces/XYStepAreaRendererTest.trace org.jfree.chart.renderer.xy.XYStepAreaRendererTest.testSerialization:150:*>/home/stg/omc_experiments/slices/jfreechart/xy_slices/XYStepAreaRendererTest/XYStepAreaRendererTest20.txt

#Total Asserts in org.jfree.chart.renderer.xy/XYStepAreaRendererTest=============20
#Total Tests in org.jfree.chart.renderer.xy/XYStepAreaRendererTest=============0
