#!/bin/bash

echo "computing slice for XppDomComparatorTest"

mkdir -p /home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testEqualsEmptyDocuments:56:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testEqualsEmptyDocuments:57:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsElementsWithDifferentValue:68:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsElementsWithDifferentValue:69:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsElementsWithDifferentValue:70:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsElementsWithDifferentValue:71:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsElementsWithValueAndNull:82:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsElementsWithValueAndNull:83:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsElementsWithValueAndNull:84:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsElementsWithValueAndNull:85:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testEqualsAttributes:97:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testEqualsAttributes:98:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testEqualsAttributesInDifferentOrder:109:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testEqualsAttributesInDifferentOrder:110:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsSameAttributes:121:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsSameAttributes:122:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsSameAttributes:123:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsSameAttributes:124:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsDifferentAttributes:135:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsDifferentAttributes:136:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsDifferentAttributes:137:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsDifferentAttributes:138:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsAccordingNumberOfAttributes:149:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsAccordingNumberOfAttributes:150:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsAccordingNumberOfAttributes:151:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsAccordingNumberOfAttributes:152:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testEqualsDocumentsWithChildren:164:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testEqualsDocumentsWithChildren:165:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsAccordingNumberOfChildren:176:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsAccordingNumberOfChildren:177:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsAccordingNumberOfChildren:178:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsAccordingNumberOfChildren:179:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest32.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsElementsByName:190:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest33.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsElementsByName:191:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest34.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsElementsByName:192:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest35.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsElementsByName:193:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest36.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsElementsByNthName:204:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest37.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsElementsByNthName:205:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest38.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsElementsByNthName:206:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest39.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsElementsByNthName:207:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest40.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsAttributesBeforeElements:218:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest41.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsAttributesBeforeElements:219:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest42.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsAttributesBeforeElements:220:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest43.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testSortsAttributesBeforeElements:221:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest44.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testWillResetXPathAfterRecursion:232:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest45.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testWillResetXPathAfterRecursion:233:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest46.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testWillResetXPathAfterRecursion:234:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest47.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testWillResetXPathAfterRecursion:235:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest48.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testCompareWithoutReference:248:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest49.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/xppdom_traces/XppDomComparatorTest.trace com.thoughtworks.xstream.io.xml.xppdom.XppDomComparatorTest.testCompareWithoutReference:249:*>/home/stg/omc_experiments/slices/xstream/xppdom_slices/XppDomComparatorTest/XppDomComparatorTest50.txt

#Total Asserts in com.thoughtworks.xstream.io.xml.xppdom/XppDomComparatorTest=============50
#Total Tests in com.thoughtworks.xstream.io.xml.xppdom/XppDomComparatorTest=============0
