#!/bin/bash

echo "computing slice for CategoryItemEntityTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/entity_slices/CategoryItemEntityTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/CategoryItemEntityTest.trace org.jfree.chart.entity.CategoryItemEntityTest.testEquals:73:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/CategoryItemEntityTest/CategoryItemEntityTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/CategoryItemEntityTest.trace org.jfree.chart.entity.CategoryItemEntityTest.testEquals:76:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/CategoryItemEntityTest/CategoryItemEntityTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/CategoryItemEntityTest.trace org.jfree.chart.entity.CategoryItemEntityTest.testEquals:78:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/CategoryItemEntityTest/CategoryItemEntityTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/CategoryItemEntityTest.trace org.jfree.chart.entity.CategoryItemEntityTest.testEquals:81:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/CategoryItemEntityTest/CategoryItemEntityTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/CategoryItemEntityTest.trace org.jfree.chart.entity.CategoryItemEntityTest.testEquals:83:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/CategoryItemEntityTest/CategoryItemEntityTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/CategoryItemEntityTest.trace org.jfree.chart.entity.CategoryItemEntityTest.testEquals:86:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/CategoryItemEntityTest/CategoryItemEntityTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/CategoryItemEntityTest.trace org.jfree.chart.entity.CategoryItemEntityTest.testEquals:88:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/CategoryItemEntityTest/CategoryItemEntityTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/CategoryItemEntityTest.trace org.jfree.chart.entity.CategoryItemEntityTest.testCloning:104:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/CategoryItemEntityTest/CategoryItemEntityTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/CategoryItemEntityTest.trace org.jfree.chart.entity.CategoryItemEntityTest.testCloning:105:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/CategoryItemEntityTest/CategoryItemEntityTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/CategoryItemEntityTest.trace org.jfree.chart.entity.CategoryItemEntityTest.testCloning:106:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/CategoryItemEntityTest/CategoryItemEntityTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/CategoryItemEntityTest.trace org.jfree.chart.entity.CategoryItemEntityTest.testSerialization:122:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/CategoryItemEntityTest/CategoryItemEntityTest11.txt

#Total Asserts in org.jfree.chart.entity/CategoryItemEntityTest=============11
#Total Tests in org.jfree.chart.entity/CategoryItemEntityTest=============0
