#!/bin/bash

echo "computing slice for LegendItemEntityTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/entity_slices/LegendItemEntityTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/LegendItemEntityTest.trace org.jfree.chart.entity.LegendItemEntityTest.testEquals:69:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/LegendItemEntityTest/LegendItemEntityTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/LegendItemEntityTest.trace org.jfree.chart.entity.LegendItemEntityTest.testEquals:72:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/LegendItemEntityTest/LegendItemEntityTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/LegendItemEntityTest.trace org.jfree.chart.entity.LegendItemEntityTest.testEquals:74:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/LegendItemEntityTest/LegendItemEntityTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/LegendItemEntityTest.trace org.jfree.chart.entity.LegendItemEntityTest.testEquals:77:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/LegendItemEntityTest/LegendItemEntityTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/LegendItemEntityTest.trace org.jfree.chart.entity.LegendItemEntityTest.testEquals:79:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/LegendItemEntityTest/LegendItemEntityTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/LegendItemEntityTest.trace org.jfree.chart.entity.LegendItemEntityTest.testEquals:82:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/LegendItemEntityTest/LegendItemEntityTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/LegendItemEntityTest.trace org.jfree.chart.entity.LegendItemEntityTest.testEquals:84:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/LegendItemEntityTest/LegendItemEntityTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/LegendItemEntityTest.trace org.jfree.chart.entity.LegendItemEntityTest.testEquals:87:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/LegendItemEntityTest/LegendItemEntityTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/LegendItemEntityTest.trace org.jfree.chart.entity.LegendItemEntityTest.testEquals:89:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/LegendItemEntityTest/LegendItemEntityTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/LegendItemEntityTest.trace org.jfree.chart.entity.LegendItemEntityTest.testEquals:92:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/LegendItemEntityTest/LegendItemEntityTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/LegendItemEntityTest.trace org.jfree.chart.entity.LegendItemEntityTest.testEquals:94:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/LegendItemEntityTest/LegendItemEntityTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/LegendItemEntityTest.trace org.jfree.chart.entity.LegendItemEntityTest.testCloning:106:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/LegendItemEntityTest/LegendItemEntityTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/LegendItemEntityTest.trace org.jfree.chart.entity.LegendItemEntityTest.testCloning:107:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/LegendItemEntityTest/LegendItemEntityTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/LegendItemEntityTest.trace org.jfree.chart.entity.LegendItemEntityTest.testCloning:108:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/LegendItemEntityTest/LegendItemEntityTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/LegendItemEntityTest.trace org.jfree.chart.entity.LegendItemEntityTest.testSerialization:119:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/LegendItemEntityTest/LegendItemEntityTest15.txt

#Total Asserts in org.jfree.chart.entity/LegendItemEntityTest=============15
#Total Tests in org.jfree.chart.entity/LegendItemEntityTest=============0
