#!/bin/bash

echo "computing slice for PieSectionEntityTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/entity_slices/PieSectionEntityTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/PieSectionEntityTest.trace org.jfree.chart.entity.PieSectionEntityTest.testEquals:70:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/PieSectionEntityTest/PieSectionEntityTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/PieSectionEntityTest.trace org.jfree.chart.entity.PieSectionEntityTest.testEquals:73:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/PieSectionEntityTest/PieSectionEntityTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/PieSectionEntityTest.trace org.jfree.chart.entity.PieSectionEntityTest.testEquals:75:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/PieSectionEntityTest/PieSectionEntityTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/PieSectionEntityTest.trace org.jfree.chart.entity.PieSectionEntityTest.testEquals:78:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/PieSectionEntityTest/PieSectionEntityTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/PieSectionEntityTest.trace org.jfree.chart.entity.PieSectionEntityTest.testEquals:80:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/PieSectionEntityTest/PieSectionEntityTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/PieSectionEntityTest.trace org.jfree.chart.entity.PieSectionEntityTest.testEquals:83:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/PieSectionEntityTest/PieSectionEntityTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/PieSectionEntityTest.trace org.jfree.chart.entity.PieSectionEntityTest.testEquals:85:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/PieSectionEntityTest/PieSectionEntityTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/PieSectionEntityTest.trace org.jfree.chart.entity.PieSectionEntityTest.testEquals:88:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/PieSectionEntityTest/PieSectionEntityTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/PieSectionEntityTest.trace org.jfree.chart.entity.PieSectionEntityTest.testEquals:90:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/PieSectionEntityTest/PieSectionEntityTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/PieSectionEntityTest.trace org.jfree.chart.entity.PieSectionEntityTest.testEquals:93:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/PieSectionEntityTest/PieSectionEntityTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/PieSectionEntityTest.trace org.jfree.chart.entity.PieSectionEntityTest.testEquals:95:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/PieSectionEntityTest/PieSectionEntityTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/PieSectionEntityTest.trace org.jfree.chart.entity.PieSectionEntityTest.testEquals:98:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/PieSectionEntityTest/PieSectionEntityTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/PieSectionEntityTest.trace org.jfree.chart.entity.PieSectionEntityTest.testEquals:100:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/PieSectionEntityTest/PieSectionEntityTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/PieSectionEntityTest.trace org.jfree.chart.entity.PieSectionEntityTest.testEquals:103:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/PieSectionEntityTest/PieSectionEntityTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/PieSectionEntityTest.trace org.jfree.chart.entity.PieSectionEntityTest.testEquals:105:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/PieSectionEntityTest/PieSectionEntityTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/PieSectionEntityTest.trace org.jfree.chart.entity.PieSectionEntityTest.testCloning:117:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/PieSectionEntityTest/PieSectionEntityTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/PieSectionEntityTest.trace org.jfree.chart.entity.PieSectionEntityTest.testCloning:118:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/PieSectionEntityTest/PieSectionEntityTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/PieSectionEntityTest.trace org.jfree.chart.entity.PieSectionEntityTest.testCloning:119:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/PieSectionEntityTest/PieSectionEntityTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/entity_traces/PieSectionEntityTest.trace org.jfree.chart.entity.PieSectionEntityTest.testSerialization:131:*>/home/stg/omc_experiments/slices/jfreechart/entity_slices/PieSectionEntityTest/PieSectionEntityTest19.txt

#Total Asserts in org.jfree.chart.entity/PieSectionEntityTest=============19
#Total Tests in org.jfree.chart.entity/PieSectionEntityTest=============0
