#!/bin/bash

echo "computing slice for FilePersistenceStrategyTest"

mkdir -p /home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testConcatenatesXmlExtensionWhileGettingAFilename:70:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testConcatenatesXmlExtensionWhileExtractingAKey:75:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testEscapesNonAcceptableCharacterWhileExtractingAKey:80:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testEscapesNonAcceptableCharacterWhileGettingAFilename:85:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testEscapesUTF8NonAcceptableCharacterWhileGettingAFilename:90:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testEscapesUTF8NonAcceptableCharacterWhileExtractingAKey:95:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testEscapesPercentageWhileGettingAFilename:100:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testEscapesPercentageWhileExtractingAKey:105:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testEscapesNullKeyWhileGettingAFileName:110:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testRestoresTypeOfKey:115:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testEscapesNullKeyWhileExtractingKey:121:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testWritesASingleFile:128:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testWritesTwoFiles:135:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testWritesTwoFiles:136:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testRemovesAWrittenFile:142:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testRemovesAWrittenFile:144:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testRemovesAWrittenFile:145:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testRemovesAnInvalidFile:151:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testHasZeroLength:156:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testHasOneItem:162:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testHasTwoItems:169:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testIsNotEmpty:175:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testDoesNotContainKey:180:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testContainsKey:186:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testGetsAFile:192:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testGetsAFile:194:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testGetsAnInvalidFile:200:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testRewritesASingleFile:207:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testRewritesASingleFile:209:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testIsEmpty:214:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testContainsAllItems:225:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testIteratesOverEntryAndChecksItsKeyWithAnotherInstance:236:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest32.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testRemovesAnItemThroughIteration:250:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest33.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testRewritesAFile:257:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest34.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/persistence_traces/FilePersistenceStrategyTest.trace com.thoughtworks.xstream.persistence.FilePersistenceStrategyTest.testPutReturnsTheOldValueWhenRewritingAFile:263:*>/home/stg/omc_experiments/slices/xstream/persistence_slices/FilePersistenceStrategyTest/FilePersistenceStrategyTest35.txt

#Total Asserts in com.thoughtworks.xstream.persistence/FilePersistenceStrategyTest=============35
#Total Tests in com.thoughtworks.xstream.persistence/FilePersistenceStrategyTest=============0
