#!/bin/bash

echo "computing slice for ElementsTest"

mkdir -p /home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.filter:23:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.filter:24:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.filter:25:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.attributes:32:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.attributes:33:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.attributes:34:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.attributes:35:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.attributes:38:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.attributes:39:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.attributes:42:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.attributes:43:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.attributes:44:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.hasAttr:50:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.hasAttr:51:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.hasAbsAttr:59:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.hasAbsAttr:60:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.hasAbsAttr:61:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.attr:67:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.absAttr:76:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.absAttr:77:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.absAttr:78:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.classes:85:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.classes:86:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.classes:91:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.classes:92:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.text:98:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.hasText:104:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.hasText:105:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.html:111:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.outerHtml:117:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.setHtml:125:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.setHtml:128:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest32.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.val:134:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest33.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.val:135:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest34.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.val:136:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest35.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.val:139:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest36.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.val:140:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest37.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.val:141:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest38.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.before:147:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest39.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.after:153:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest40.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.wrap:160:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest41.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.wrapDiv:167:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest42.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.unwrap:175:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest43.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.unwrapP:182:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest44.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.unwrapKeepsSpace:189:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest45.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.empty:197:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest46.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.remove:205:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest47.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.eq:211:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest48.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.eq:212:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest49.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.is:219:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest50.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.is:220:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest51.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.parents:227:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest52.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.parents:228:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest53.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.parents:229:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest54.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.parents:230:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest55.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.not:237:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest56.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.not:238:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest57.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.not:241:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest58.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.not:242:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest59.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.tagNameSet:249:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest60.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.traverse:264:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest61.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.forms:270:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest62.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.forms:273:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest63.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.forms:274:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest64.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.forms:275:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest65.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.forms:276:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest66.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.forms:277:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest67.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.classWithHyphen:283:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest68.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jsoup-1.10.1/select_traces/ElementsTest.trace org.jsoup.select.ElementsTest.classWithHyphen:284:*>/home/stg/omc_experiments/slices/jsoup-1.10.1/select_slices/ElementsTest/ElementsTest69.txt

#Total Asserts in org.jsoup.select/ElementsTest=============69
#Total Tests in org.jsoup.select/ElementsTest=============0
