#!/bin/bash

echo "computing slice for NodesetEqualityTest"

mkdir -p /home/stg/omc_experiments/slices/fse-jaxen-1.2.0/test_slices/NodesetEqualityTest

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-jaxen-1.2.0/test_traces/NodesetEqualityTest.trace org.jaxen.test.NodesetEqualityTest.testEqualsTwoNodesets:117:*>/home/stg/omc_experiments/slices/fse-jaxen-1.2.0/test_slices/NodesetEqualityTest/NodesetEqualityTest1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-jaxen-1.2.0/test_traces/NodesetEqualityTest.trace org.jaxen.test.NodesetEqualityTest.testNotEqualsTwoNodesets:124:*>/home/stg/omc_experiments/slices/fse-jaxen-1.2.0/test_slices/NodesetEqualityTest/NodesetEqualityTest2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-jaxen-1.2.0/test_traces/NodesetEqualityTest.trace org.jaxen.test.NodesetEqualityTest.testEqualsStringNodeset:131:*>/home/stg/omc_experiments/slices/fse-jaxen-1.2.0/test_slices/NodesetEqualityTest/NodesetEqualityTest3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-jaxen-1.2.0/test_traces/NodesetEqualityTest.trace org.jaxen.test.NodesetEqualityTest.testNotEqualsStringNodeset:138:*>/home/stg/omc_experiments/slices/fse-jaxen-1.2.0/test_slices/NodesetEqualityTest/NodesetEqualityTest4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-jaxen-1.2.0/test_traces/NodesetEqualityTest.trace org.jaxen.test.NodesetEqualityTest.testEqualsNumberNodeset:145:*>/home/stg/omc_experiments/slices/fse-jaxen-1.2.0/test_slices/NodesetEqualityTest/NodesetEqualityTest5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-jaxen-1.2.0/test_traces/NodesetEqualityTest.trace org.jaxen.test.NodesetEqualityTest.testNotEqualsNumberNodeset:152:*>/home/stg/omc_experiments/slices/fse-jaxen-1.2.0/test_slices/NodesetEqualityTest/NodesetEqualityTest6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-jaxen-1.2.0/test_traces/NodesetEqualityTest.trace org.jaxen.test.NodesetEqualityTest.testEqualsBooleanNodeset1:159:*>/home/stg/omc_experiments/slices/fse-jaxen-1.2.0/test_slices/NodesetEqualityTest/NodesetEqualityTest7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-jaxen-1.2.0/test_traces/NodesetEqualityTest.trace org.jaxen.test.NodesetEqualityTest.testEqualsBooleanNodeset2:167:*>/home/stg/omc_experiments/slices/fse-jaxen-1.2.0/test_slices/NodesetEqualityTest/NodesetEqualityTest8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-jaxen-1.2.0/test_traces/NodesetEqualityTest.trace org.jaxen.test.NodesetEqualityTest.testNotEqualsBooleanNodeset1:175:*>/home/stg/omc_experiments/slices/fse-jaxen-1.2.0/test_slices/NodesetEqualityTest/NodesetEqualityTest9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-jaxen-1.2.0/test_traces/NodesetEqualityTest.trace org.jaxen.test.NodesetEqualityTest.testNotEqualsBooleanNodeset2:183:*>/home/stg/omc_experiments/slices/fse-jaxen-1.2.0/test_slices/NodesetEqualityTest/NodesetEqualityTest10.txt

#Total Asserts in org.jaxen.test/NodesetEqualityTest=============10
#Total Tests in org.jaxen.test/NodesetEqualityTest=============0
