#!/bin/bash

echo "computing slice for CommandlineTest"

mkdir -p /home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testCommandlineWithoutCommandInConstructor:67:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testCommandlineWithCommandInConstructor:83:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testExecute:125:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testExecute:129:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testSetLine:148:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testCreateCommandInReverseOrder:166:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testSetFile:190:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testGetShellCommandLineWindows:206:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testGetShellCommandLineWindows:208:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testGetShellCommandLineWindows:209:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testGetShellCommandLineWindows:210:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testGetShellCommandLineWindows:213:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testGetShellCommandLineWindowsWithSeveralQuotes:224:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testGetShellCommandLineWindowsWithSeveralQuotes:226:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest14.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testGetShellCommandLineWindowsWithSeveralQuotes:227:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest15.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testGetShellCommandLineWindowsWithSeveralQuotes:228:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest16.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testGetShellCommandLineWindowsWithSeveralQuotes:232:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest17.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testGetShellCommandLineBash:249:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest18.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testGetShellCommandLineBash:251:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest19.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testGetShellCommandLineBash:252:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest20.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testGetShellCommandLineBash:258:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest21.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testGetShellCommandLineBash_WithWorkingDirectory:278:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest22.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testGetShellCommandLineBash_WithWorkingDirectory:280:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest23.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testGetShellCommandLineBash_WithWorkingDirectory:281:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest24.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testGetShellCommandLineBash_WithWorkingDirectory:287:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest25.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testGetShellCommandLineBash_WithSingleQuotedArg:304:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest26.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testGetShellCommandLineBash_WithSingleQuotedArg:306:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest27.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testGetShellCommandLineBash_WithSingleQuotedArg:307:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest28.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testGetShellCommandLineBash_WithSingleQuotedArg:313:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest29.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testGetShellCommandLineNonWindows:324:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest30.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testGetShellCommandLineNonWindows:326:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest31.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testGetShellCommandLineNonWindows:327:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest32.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testGetShellCommandLineNonWindows:335:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest33.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testGetShellCommandLineNonWindows:331:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest34.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testEnvironment:344:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest35.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.testDollarSignInArgumentPath:477:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest36.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/cli_traces/CommandlineTest.trace org.codehaus.plexus.util.cli.CommandlineTest.createAndCallScript:590:*>/home/stg/omc_experiments/slices/plexus-utils/cli_slices/CommandlineTest/CommandlineTest37.txt

#Total Asserts in org.codehaus.plexus.util.cli/CommandlineTest=============37
#Total Tests in org.codehaus.plexus.util.cli/CommandlineTest=============0
