#!/bin/bash


echo "skipping slice for CSVRecordTest"
exit 0

echo "computing slice for CSVRecordTest"

mkdir -p /home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.testGetInt:58:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.testGetInt:59:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.testGetInt:60:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.testGetString:65:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.testGetString:66:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.testGetString:67:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.testGetUnmappedEnum:83:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.testGetUnmappedName:88:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.testGetUnmappedNegativeInt:93:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.testGetUnmappedPositiveInt:98:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.testIsConsistent:103:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.testIsConsistent:104:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.testIsConsistent:107:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.testIsMapped:112:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.testIsMapped:113:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.testIsMapped:114:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.testIsSet:119:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.testIsSet:120:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.testIsSet:121:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.testIterator:128:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.testRemoveAndAddColumns:154:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.testToMapWithNoHeader:177:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.testToMapWithNoHeader:178:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.validateMap:183:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.validateMap:184:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.validateMap:185:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.validateMap:186:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.validateMap:188:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.validateMap:190:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.validateMap:191:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.validateMap:192:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-csv/csv_traces/CSVRecordTest.trace org.apache.commons.csv.CSVRecordTest.validateMap:193:*>/home/stg/omc_experiments/slices/commons-csv/csv_slices/CSVRecordTest/CSVRecordTest32.txt

#Total Asserts in org.apache.commons.csv/CSVRecordTest=============32
#Total Tests in org.apache.commons.csv/CSVRecordTest=============0
