#!/bin/bash

echo "computing slice for OctalUnescaperTest"

mkdir -p /home/stg/omc_experiments/slices/fse-commons-lang-3.6/translate_slices/OctalUnescaperTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/translate_traces/OctalUnescaperTest.trace org.apache.commons.lang3.text.translate.OctalUnescaperTest.testBetween:40:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/translate_slices/OctalUnescaperTest/OctalUnescaperTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/translate_traces/OctalUnescaperTest.trace org.apache.commons.lang3.text.translate.OctalUnescaperTest.testBetween:44:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/translate_slices/OctalUnescaperTest/OctalUnescaperTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/translate_traces/OctalUnescaperTest.trace org.apache.commons.lang3.text.translate.OctalUnescaperTest.testBetween:48:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/translate_slices/OctalUnescaperTest/OctalUnescaperTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/translate_traces/OctalUnescaperTest.trace org.apache.commons.lang3.text.translate.OctalUnescaperTest.testBetween:52:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/translate_slices/OctalUnescaperTest/OctalUnescaperTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/translate_traces/OctalUnescaperTest.trace org.apache.commons.lang3.text.translate.OctalUnescaperTest.testBetween:56:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/translate_slices/OctalUnescaperTest/OctalUnescaperTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/translate_traces/OctalUnescaperTest.trace org.apache.commons.lang3.text.translate.OctalUnescaperTest.testBetween:60:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/translate_slices/OctalUnescaperTest/OctalUnescaperTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/translate_traces/OctalUnescaperTest.trace org.apache.commons.lang3.text.translate.OctalUnescaperTest.testBetween:64:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/translate_slices/OctalUnescaperTest/OctalUnescaperTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/translate_traces/OctalUnescaperTest.trace org.apache.commons.lang3.text.translate.OctalUnescaperTest.testBetween:68:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/translate_slices/OctalUnescaperTest/OctalUnescaperTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/translate_traces/OctalUnescaperTest.trace org.apache.commons.lang3.text.translate.OctalUnescaperTest.testBetween:72:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/translate_slices/OctalUnescaperTest/OctalUnescaperTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/translate_traces/OctalUnescaperTest.trace org.apache.commons.lang3.text.translate.OctalUnescaperTest.testBetween:76:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/translate_slices/OctalUnescaperTest/OctalUnescaperTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/translate_traces/OctalUnescaperTest.trace org.apache.commons.lang3.text.translate.OctalUnescaperTest.testBetween:80:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/translate_slices/OctalUnescaperTest/OctalUnescaperTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/translate_traces/OctalUnescaperTest.trace org.apache.commons.lang3.text.translate.OctalUnescaperTest.testBetween:84:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/translate_slices/OctalUnescaperTest/OctalUnescaperTest12.txt

#Total Asserts in org.apache.commons.lang3.text.translate/OctalUnescaperTest=============12
#Total Tests in org.apache.commons.lang3.text.translate/OctalUnescaperTest=============0
