#!/bin/bash

echo "computing slice for SerializationCallbackOrderTest"

mkdir -p /home/stg/omc_experiments/slices/xstream/acceptance_slices/SerializationCallbackOrderTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/acceptance_traces/SerializationCallbackOrderTest.trace com.thoughtworks.acceptance.SerializationCallbackOrderTest.testCallsReadObjectEvenWithoutNonTransientFields:696:*>/home/stg/omc_experiments/slices/xstream/acceptance_slices/SerializationCallbackOrderTest/SerializationCallbackOrderTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/acceptance_traces/SerializationCallbackOrderTest.trace com.thoughtworks.acceptance.SerializationCallbackOrderTest.testCallsReadObjectEvenWithoutNonTransientFields:700:*>/home/stg/omc_experiments/slices/xstream/acceptance_slices/SerializationCallbackOrderTest/SerializationCallbackOrderTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/acceptance_traces/SerializationCallbackOrderTest.trace com.thoughtworks.acceptance.SerializationCallbackOrderTest.testCallsReadObjectEvenWithoutNonTransientFields:701:*>/home/stg/omc_experiments/slices/xstream/acceptance_slices/SerializationCallbackOrderTest/SerializationCallbackOrderTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/acceptance_traces/SerializationCallbackOrderTest.trace com.thoughtworks.acceptance.SerializationCallbackOrderTest.testFieldsOfUnserializableParentsArePreserved:831:*>/home/stg/omc_experiments/slices/xstream/acceptance_slices/SerializationCallbackOrderTest/SerializationCallbackOrderTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/acceptance_traces/SerializationCallbackOrderTest.trace com.thoughtworks.acceptance.SerializationCallbackOrderTest.testFieldsOfUnserializableParentsArePreserved:832:*>/home/stg/omc_experiments/slices/xstream/acceptance_slices/SerializationCallbackOrderTest/SerializationCallbackOrderTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/acceptance_traces/SerializationCallbackOrderTest.trace com.thoughtworks.acceptance.SerializationCallbackOrderTest.testUnserializableParentsAreWrittenOnlyOnce:868:*>/home/stg/omc_experiments/slices/xstream/acceptance_slices/SerializationCallbackOrderTest/SerializationCallbackOrderTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/acceptance_traces/SerializationCallbackOrderTest.trace com.thoughtworks.acceptance.SerializationCallbackOrderTest.testUnserializableParentsAreWrittenOnlyOnce:869:*>/home/stg/omc_experiments/slices/xstream/acceptance_slices/SerializationCallbackOrderTest/SerializationCallbackOrderTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/acceptance_traces/SerializationCallbackOrderTest.trace com.thoughtworks.acceptance.SerializationCallbackOrderTest.testUnserializableParentsAreWrittenOnlyOnce:870:*>/home/stg/omc_experiments/slices/xstream/acceptance_slices/SerializationCallbackOrderTest/SerializationCallbackOrderTest8.txt

#Total Asserts in com.thoughtworks.acceptance/SerializationCallbackOrderTest=============8
#Total Tests in com.thoughtworks.acceptance/SerializationCallbackOrderTest=============0
