#!/bin/bash

echo "computing slice for XStream12CompatibilityTest"

mkdir -p /home/stg/omc_experiments/slices/xstream/acceptance_slices/XStream12CompatibilityTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/acceptance_traces/XStream12CompatibilityTest.trace com.thoughtworks.acceptance.XStream12CompatibilityTest.testCanDeserializeHiddenFieldsWithSameTypeWrittenWithXStream11:71:*>/home/stg/omc_experiments/slices/xstream/acceptance_slices/XStream12CompatibilityTest/XStream12CompatibilityTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/acceptance_traces/XStream12CompatibilityTest.trace com.thoughtworks.acceptance.XStream12CompatibilityTest.testCanDeserializeHiddenFieldsWithDifferentTypeWrittenWithXStream11:107:*>/home/stg/omc_experiments/slices/xstream/acceptance_slices/XStream12CompatibilityTest/XStream12CompatibilityTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/acceptance_traces/XStream12CompatibilityTest.trace com.thoughtworks.acceptance.XStream12CompatibilityTest.testCanDeserializeHiddenFieldsWithDifferentTypeWrittenWithXStream11:108:*>/home/stg/omc_experiments/slices/xstream/acceptance_slices/XStream12CompatibilityTest/XStream12CompatibilityTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/acceptance_traces/XStream12CompatibilityTest.trace com.thoughtworks.acceptance.XStream12CompatibilityTest.testCanWriteInheritanceHierarchiesInOldOrder:122:*>/home/stg/omc_experiments/slices/xstream/acceptance_slices/XStream12CompatibilityTest/XStream12CompatibilityTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/acceptance_traces/XStream12CompatibilityTest.trace com.thoughtworks.acceptance.XStream12CompatibilityTest.testCanReadXmlUnfriendlyXPathReferences:155:*>/home/stg/omc_experiments/slices/xstream/acceptance_slices/XStream12CompatibilityTest/XStream12CompatibilityTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/acceptance_traces/XStream12CompatibilityTest.trace com.thoughtworks.acceptance.XStream12CompatibilityTest.testCanReadXmlUnfriendlyXPathReferences:156:*>/home/stg/omc_experiments/slices/xstream/acceptance_slices/XStream12CompatibilityTest/XStream12CompatibilityTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/acceptance_traces/XStream12CompatibilityTest.trace com.thoughtworks.acceptance.XStream12CompatibilityTest.testCanReadXmlUnfriendlyXPathReferences:157:*>/home/stg/omc_experiments/slices/xstream/acceptance_slices/XStream12CompatibilityTest/XStream12CompatibilityTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/acceptance_traces/XStream12CompatibilityTest.trace com.thoughtworks.acceptance.XStream12CompatibilityTest.testCanReadXmlUnfriendlyXPathReferences:158:*>/home/stg/omc_experiments/slices/xstream/acceptance_slices/XStream12CompatibilityTest/XStream12CompatibilityTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/acceptance_traces/XStream12CompatibilityTest.trace com.thoughtworks.acceptance.XStream12CompatibilityTest.testCanReadXmlUnfriendlyXPathReferences:159:*>/home/stg/omc_experiments/slices/xstream/acceptance_slices/XStream12CompatibilityTest/XStream12CompatibilityTest9.txt

#Total Asserts in com.thoughtworks.acceptance/XStream12CompatibilityTest=============9
#Total Tests in com.thoughtworks.acceptance/XStream12CompatibilityTest=============0
