#!/bin/bash

echo "computing slice for MixedStreamTest"

mkdir -p /home/stg/omc_experiments/slices/gson/gson_slices/MixedStreamTest

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/MixedStreamTest.trace com.google.gson.MixedStreamTest.testWriteMixedStreamed:62:*>/home/stg/omc_experiments/slices/gson/gson_slices/MixedStreamTest/MixedStreamTest1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/MixedStreamTest.trace com.google.gson.MixedStreamTest.testReadMixedStreamed:71:*>/home/stg/omc_experiments/slices/gson/gson_slices/MixedStreamTest/MixedStreamTest2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/MixedStreamTest.trace com.google.gson.MixedStreamTest.testReadMixedStreamed:72:*>/home/stg/omc_experiments/slices/gson/gson_slices/MixedStreamTest/MixedStreamTest3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/MixedStreamTest.trace com.google.gson.MixedStreamTest.testReadMixedStreamed:73:*>/home/stg/omc_experiments/slices/gson/gson_slices/MixedStreamTest/MixedStreamTest4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/MixedStreamTest.trace com.google.gson.MixedStreamTest.testReaderDoesNotMutateState:84:*>/home/stg/omc_experiments/slices/gson/gson_slices/MixedStreamTest/MixedStreamTest5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/MixedStreamTest.trace com.google.gson.MixedStreamTest.testReaderDoesNotMutateState:88:*>/home/stg/omc_experiments/slices/gson/gson_slices/MixedStreamTest/MixedStreamTest6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/MixedStreamTest.trace com.google.gson.MixedStreamTest.testWriteDoesNotMutateState:99:*>/home/stg/omc_experiments/slices/gson/gson_slices/MixedStreamTest/MixedStreamTest7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/MixedStreamTest.trace com.google.gson.MixedStreamTest.testWriteDoesNotMutateState:100:*>/home/stg/omc_experiments/slices/gson/gson_slices/MixedStreamTest/MixedStreamTest8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/MixedStreamTest.trace com.google.gson.MixedStreamTest.testWriteDoesNotMutateState:105:*>/home/stg/omc_experiments/slices/gson/gson_slices/MixedStreamTest/MixedStreamTest9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/MixedStreamTest.trace com.google.gson.MixedStreamTest.testWriteDoesNotMutateState:106:*>/home/stg/omc_experiments/slices/gson/gson_slices/MixedStreamTest/MixedStreamTest10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/MixedStreamTest.trace com.google.gson.MixedStreamTest.testWriteNulls:166:*>/home/stg/omc_experiments/slices/gson/gson_slices/MixedStreamTest/MixedStreamTest11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/MixedStreamTest.trace com.google.gson.MixedStreamTest.testWriteHtmlSafe:189:*>/home/stg/omc_experiments/slices/gson/gson_slices/MixedStreamTest/MixedStreamTest12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/MixedStreamTest.trace com.google.gson.MixedStreamTest.testWriteHtmlSafe:195:*>/home/stg/omc_experiments/slices/gson/gson_slices/MixedStreamTest/MixedStreamTest13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/MixedStreamTest.trace com.google.gson.MixedStreamTest.testWriteLenient:208:*>/home/stg/omc_experiments/slices/gson/gson_slices/MixedStreamTest/MixedStreamTest14.txt

#Total Asserts in com.google.gson/MixedStreamTest=============14
#Total Tests in com.google.gson/MixedStreamTest=============0
