#!/bin/bash

echo "computing slice for JsonStreamParserTest"

mkdir -p /home/stg/omc_experiments/slices/gson/gson_slices/JsonStreamParserTest

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/JsonStreamParserTest.trace com.google.gson.JsonStreamParserTest.testParseTwoStrings:38:*>/home/stg/omc_experiments/slices/gson/gson_slices/JsonStreamParserTest/JsonStreamParserTest1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/JsonStreamParserTest.trace com.google.gson.JsonStreamParserTest.testParseTwoStrings:40:*>/home/stg/omc_experiments/slices/gson/gson_slices/JsonStreamParserTest/JsonStreamParserTest2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/JsonStreamParserTest.trace com.google.gson.JsonStreamParserTest.testIterator:44:*>/home/stg/omc_experiments/slices/gson/gson_slices/JsonStreamParserTest/JsonStreamParserTest3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/JsonStreamParserTest.trace com.google.gson.JsonStreamParserTest.testIterator:45:*>/home/stg/omc_experiments/slices/gson/gson_slices/JsonStreamParserTest/JsonStreamParserTest4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/JsonStreamParserTest.trace com.google.gson.JsonStreamParserTest.testIterator:46:*>/home/stg/omc_experiments/slices/gson/gson_slices/JsonStreamParserTest/JsonStreamParserTest5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/JsonStreamParserTest.trace com.google.gson.JsonStreamParserTest.testIterator:47:*>/home/stg/omc_experiments/slices/gson/gson_slices/JsonStreamParserTest/JsonStreamParserTest6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/JsonStreamParserTest.trace com.google.gson.JsonStreamParserTest.testIterator:48:*>/home/stg/omc_experiments/slices/gson/gson_slices/JsonStreamParserTest/JsonStreamParserTest7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/JsonStreamParserTest.trace com.google.gson.JsonStreamParserTest.testNoSideEffectForHasNext:52:*>/home/stg/omc_experiments/slices/gson/gson_slices/JsonStreamParserTest/JsonStreamParserTest8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/JsonStreamParserTest.trace com.google.gson.JsonStreamParserTest.testNoSideEffectForHasNext:53:*>/home/stg/omc_experiments/slices/gson/gson_slices/JsonStreamParserTest/JsonStreamParserTest9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/JsonStreamParserTest.trace com.google.gson.JsonStreamParserTest.testNoSideEffectForHasNext:54:*>/home/stg/omc_experiments/slices/gson/gson_slices/JsonStreamParserTest/JsonStreamParserTest10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/JsonStreamParserTest.trace com.google.gson.JsonStreamParserTest.testNoSideEffectForHasNext:55:*>/home/stg/omc_experiments/slices/gson/gson_slices/JsonStreamParserTest/JsonStreamParserTest11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/JsonStreamParserTest.trace com.google.gson.JsonStreamParserTest.testNoSideEffectForHasNext:57:*>/home/stg/omc_experiments/slices/gson/gson_slices/JsonStreamParserTest/JsonStreamParserTest12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/JsonStreamParserTest.trace com.google.gson.JsonStreamParserTest.testNoSideEffectForHasNext:58:*>/home/stg/omc_experiments/slices/gson/gson_slices/JsonStreamParserTest/JsonStreamParserTest13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/JsonStreamParserTest.trace com.google.gson.JsonStreamParserTest.testNoSideEffectForHasNext:59:*>/home/stg/omc_experiments/slices/gson/gson_slices/JsonStreamParserTest/JsonStreamParserTest14.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/JsonStreamParserTest.trace com.google.gson.JsonStreamParserTest.testNoSideEffectForHasNext:61:*>/home/stg/omc_experiments/slices/gson/gson_slices/JsonStreamParserTest/JsonStreamParserTest15.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/JsonStreamParserTest.trace com.google.gson.JsonStreamParserTest.testNoSideEffectForHasNext:62:*>/home/stg/omc_experiments/slices/gson/gson_slices/JsonStreamParserTest/JsonStreamParserTest16.txt

#Total Asserts in com.google.gson/JsonStreamParserTest=============16
#Total Tests in com.google.gson/JsonStreamParserTest=============0
