#!/bin/bash

echo "computing slice for LongSerializationPolicyTest"

mkdir -p /home/stg/omc_experiments/slices/gson/gson_slices/LongSerializationPolicyTest

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/LongSerializationPolicyTest.trace com.google.gson.LongSerializationPolicyTest.testDefaultLongSerialization:31:*>/home/stg/omc_experiments/slices/gson/gson_slices/LongSerializationPolicyTest/LongSerializationPolicyTest1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/LongSerializationPolicyTest.trace com.google.gson.LongSerializationPolicyTest.testDefaultLongSerialization:34:*>/home/stg/omc_experiments/slices/gson/gson_slices/LongSerializationPolicyTest/LongSerializationPolicyTest2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/LongSerializationPolicyTest.trace com.google.gson.LongSerializationPolicyTest.testDefaultLongSerialization:35:*>/home/stg/omc_experiments/slices/gson/gson_slices/LongSerializationPolicyTest/LongSerializationPolicyTest3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/LongSerializationPolicyTest.trace com.google.gson.LongSerializationPolicyTest.testDefaultLongSerialization:36:*>/home/stg/omc_experiments/slices/gson/gson_slices/LongSerializationPolicyTest/LongSerializationPolicyTest4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/LongSerializationPolicyTest.trace com.google.gson.LongSerializationPolicyTest.testDefaultLongSerializationIntegration:43:*>/home/stg/omc_experiments/slices/gson/gson_slices/LongSerializationPolicyTest/LongSerializationPolicyTest5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/LongSerializationPolicyTest.trace com.google.gson.LongSerializationPolicyTest.testDefaultLongSerializationIntegration:44:*>/home/stg/omc_experiments/slices/gson/gson_slices/LongSerializationPolicyTest/LongSerializationPolicyTest6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/LongSerializationPolicyTest.trace com.google.gson.LongSerializationPolicyTest.testStringLongSerialization:49:*>/home/stg/omc_experiments/slices/gson/gson_slices/LongSerializationPolicyTest/LongSerializationPolicyTest7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/LongSerializationPolicyTest.trace com.google.gson.LongSerializationPolicyTest.testStringLongSerialization:52:*>/home/stg/omc_experiments/slices/gson/gson_slices/LongSerializationPolicyTest/LongSerializationPolicyTest8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/LongSerializationPolicyTest.trace com.google.gson.LongSerializationPolicyTest.testStringLongSerialization:53:*>/home/stg/omc_experiments/slices/gson/gson_slices/LongSerializationPolicyTest/LongSerializationPolicyTest9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/LongSerializationPolicyTest.trace com.google.gson.LongSerializationPolicyTest.testStringLongSerialization:54:*>/home/stg/omc_experiments/slices/gson/gson_slices/LongSerializationPolicyTest/LongSerializationPolicyTest10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/LongSerializationPolicyTest.trace com.google.gson.LongSerializationPolicyTest.testStringLongSerializationIntegration:61:*>/home/stg/omc_experiments/slices/gson/gson_slices/LongSerializationPolicyTest/LongSerializationPolicyTest11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/LongSerializationPolicyTest.trace com.google.gson.LongSerializationPolicyTest.testStringLongSerializationIntegration:62:*>/home/stg/omc_experiments/slices/gson/gson_slices/LongSerializationPolicyTest/LongSerializationPolicyTest12.txt

#Total Asserts in com.google.gson/LongSerializationPolicyTest=============12
#Total Tests in com.google.gson/LongSerializationPolicyTest=============0
