#!/bin/bash

echo "computing slice for FieldAttributesTest"

mkdir -p /home/stg/omc_experiments/slices/gson/gson_slices/FieldAttributesTest

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/FieldAttributesTest.trace com.google.gson.FieldAttributesTest.testDeclaringClass:50:*>/home/stg/omc_experiments/slices/gson/gson_slices/FieldAttributesTest/FieldAttributesTest1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/FieldAttributesTest.trace com.google.gson.FieldAttributesTest.testModifiers:54:*>/home/stg/omc_experiments/slices/gson/gson_slices/FieldAttributesTest/FieldAttributesTest2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/FieldAttributesTest.trace com.google.gson.FieldAttributesTest.testModifiers:55:*>/home/stg/omc_experiments/slices/gson/gson_slices/FieldAttributesTest/FieldAttributesTest3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/FieldAttributesTest.trace com.google.gson.FieldAttributesTest.testModifiers:56:*>/home/stg/omc_experiments/slices/gson/gson_slices/FieldAttributesTest/FieldAttributesTest4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/FieldAttributesTest.trace com.google.gson.FieldAttributesTest.testModifiers:57:*>/home/stg/omc_experiments/slices/gson/gson_slices/FieldAttributesTest/FieldAttributesTest5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/FieldAttributesTest.trace com.google.gson.FieldAttributesTest.testModifiers:58:*>/home/stg/omc_experiments/slices/gson/gson_slices/FieldAttributesTest/FieldAttributesTest6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/FieldAttributesTest.trace com.google.gson.FieldAttributesTest.testModifiers:60:*>/home/stg/omc_experiments/slices/gson/gson_slices/FieldAttributesTest/FieldAttributesTest7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/FieldAttributesTest.trace com.google.gson.FieldAttributesTest.testModifiers:61:*>/home/stg/omc_experiments/slices/gson/gson_slices/FieldAttributesTest/FieldAttributesTest8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/FieldAttributesTest.trace com.google.gson.FieldAttributesTest.testIsSynthetic:65:*>/home/stg/omc_experiments/slices/gson/gson_slices/FieldAttributesTest/FieldAttributesTest9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/FieldAttributesTest.trace com.google.gson.FieldAttributesTest.testName:69:*>/home/stg/omc_experiments/slices/gson/gson_slices/FieldAttributesTest/FieldAttributesTest10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/FieldAttributesTest.trace com.google.gson.FieldAttributesTest.testDeclaredTypeAndClass:74:*>/home/stg/omc_experiments/slices/gson/gson_slices/FieldAttributesTest/FieldAttributesTest11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/gson_traces/FieldAttributesTest.trace com.google.gson.FieldAttributesTest.testDeclaredTypeAndClass:75:*>/home/stg/omc_experiments/slices/gson/gson_slices/FieldAttributesTest/FieldAttributesTest12.txt

#Total Asserts in com.google.gson/FieldAttributesTest=============12
#Total Tests in com.google.gson/FieldAttributesTest=============0
