#!/bin/bash

echo "computing slice for Sha512CryptTest"

mkdir -p /home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha512CryptTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha512CryptTest.trace org.apache.commons.codec.digest.Sha512CryptTest.testSha512CryptStrings:34:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha512CryptTest/Sha512CryptTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha512CryptTest.trace org.apache.commons.codec.digest.Sha512CryptTest.testSha512CryptStrings:36:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha512CryptTest/Sha512CryptTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha512CryptTest.trace org.apache.commons.codec.digest.Sha512CryptTest.testSha512CryptStrings:37:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha512CryptTest/Sha512CryptTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha512CryptTest.trace org.apache.commons.codec.digest.Sha512CryptTest.testSha512CryptStrings:38:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha512CryptTest/Sha512CryptTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha512CryptTest.trace org.apache.commons.codec.digest.Sha512CryptTest.testSha512CryptStrings:40:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha512CryptTest/Sha512CryptTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha512CryptTest.trace org.apache.commons.codec.digest.Sha512CryptTest.testSha512CryptStrings:41:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha512CryptTest/Sha512CryptTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha512CryptTest.trace org.apache.commons.codec.digest.Sha512CryptTest.testSha512CryptBytes:47:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha512CryptTest/Sha512CryptTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha512CryptTest.trace org.apache.commons.codec.digest.Sha512CryptTest.testSha512CryptBytes:49:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha512CryptTest/Sha512CryptTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha512CryptTest.trace org.apache.commons.codec.digest.Sha512CryptTest.testSha512CryptBytes:51:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha512CryptTest/Sha512CryptTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha512CryptTest.trace org.apache.commons.codec.digest.Sha512CryptTest.testSha512CryptExplicitCall:56:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha512CryptTest/Sha512CryptTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha512CryptTest.trace org.apache.commons.codec.digest.Sha512CryptTest.testSha512CryptExplicitCall:57:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha512CryptTest/Sha512CryptTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha512CryptTest.trace org.apache.commons.codec.digest.Sha512CryptTest.testSha512CryptExplicitCallThreadLocalRandom:63:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha512CryptTest/Sha512CryptTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha512CryptTest.trace org.apache.commons.codec.digest.Sha512CryptTest.testSha2CryptRounds:80:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha512CryptTest/Sha512CryptTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha512CryptTest.trace org.apache.commons.codec.digest.Sha512CryptTest.testSha2CryptRounds:81:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha512CryptTest/Sha512CryptTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha512CryptTest.trace org.apache.commons.codec.digest.Sha512CryptTest.testSha2CryptRounds:82:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha512CryptTest/Sha512CryptTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha512CryptTest.trace org.apache.commons.codec.digest.Sha512CryptTest.testSha256LargetThanBlocksize:99:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha512CryptTest/Sha512CryptTest16.txt

#Total Asserts in org.apache.commons.codec.digest/Sha512CryptTest=============16
#Total Tests in org.apache.commons.codec.digest/Sha512CryptTest=============0
