#!/bin/bash

echo "computing slice for Sha256CryptTest"

mkdir -p /home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha256CryptTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha256CryptTest.trace org.apache.commons.codec.digest.Sha256CryptTest.testSha256CryptStrings:33:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha256CryptTest/Sha256CryptTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha256CryptTest.trace org.apache.commons.codec.digest.Sha256CryptTest.testSha256CryptStrings:35:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha256CryptTest/Sha256CryptTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha256CryptTest.trace org.apache.commons.codec.digest.Sha256CryptTest.testSha256CryptStrings:36:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha256CryptTest/Sha256CryptTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha256CryptTest.trace org.apache.commons.codec.digest.Sha256CryptTest.testSha256CryptStrings:37:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha256CryptTest/Sha256CryptTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha256CryptTest.trace org.apache.commons.codec.digest.Sha256CryptTest.testSha256CryptStrings:39:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha256CryptTest/Sha256CryptTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha256CryptTest.trace org.apache.commons.codec.digest.Sha256CryptTest.testSha256CryptStrings:40:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha256CryptTest/Sha256CryptTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha256CryptTest.trace org.apache.commons.codec.digest.Sha256CryptTest.testSha256CryptBytes:46:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha256CryptTest/Sha256CryptTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha256CryptTest.trace org.apache.commons.codec.digest.Sha256CryptTest.testSha256CryptBytes:48:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha256CryptTest/Sha256CryptTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha256CryptTest.trace org.apache.commons.codec.digest.Sha256CryptTest.testSha256CryptBytes:50:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha256CryptTest/Sha256CryptTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha256CryptTest.trace org.apache.commons.codec.digest.Sha256CryptTest.testSha2CryptRounds:56:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha256CryptTest/Sha256CryptTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha256CryptTest.trace org.apache.commons.codec.digest.Sha256CryptTest.testSha2CryptRounds:57:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha256CryptTest/Sha256CryptTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha256CryptTest.trace org.apache.commons.codec.digest.Sha256CryptTest.testSha2CryptRounds:58:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha256CryptTest/Sha256CryptTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha256CryptTest.trace org.apache.commons.codec.digest.Sha256CryptTest.testSha2CryptRoundsThreadLocalRandom:65:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha256CryptTest/Sha256CryptTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha256CryptTest.trace org.apache.commons.codec.digest.Sha256CryptTest.testSha2CryptRoundsThreadLocalRandom:66:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha256CryptTest/Sha256CryptTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha256CryptTest.trace org.apache.commons.codec.digest.Sha256CryptTest.testSha2CryptRoundsThreadLocalRandom:67:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha256CryptTest/Sha256CryptTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha256CryptTest.trace org.apache.commons.codec.digest.Sha256CryptTest.testSha256CryptExplicitCall:72:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha256CryptTest/Sha256CryptTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha256CryptTest.trace org.apache.commons.codec.digest.Sha256CryptTest.testSha256CryptExplicitCall:73:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha256CryptTest/Sha256CryptTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Sha256CryptTest.trace org.apache.commons.codec.digest.Sha256CryptTest.testSha256LargetThanBlocksize:90:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Sha256CryptTest/Sha256CryptTest18.txt

#Total Asserts in org.apache.commons.codec.digest/Sha256CryptTest=============18
#Total Tests in org.apache.commons.codec.digest/Sha256CryptTest=============0
