#!/bin/bash

echo "computing slice for Md5CryptTest"

mkdir -p /home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Md5CryptTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Md5CryptTest.trace org.apache.commons.codec.digest.Md5CryptTest.testCtor:32:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Md5CryptTest/Md5CryptTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Md5CryptTest.trace org.apache.commons.codec.digest.Md5CryptTest.testMd5CryptStrings:38:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Md5CryptTest/Md5CryptTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Md5CryptTest.trace org.apache.commons.codec.digest.Md5CryptTest.testMd5CryptStrings:40:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Md5CryptTest/Md5CryptTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Md5CryptTest.trace org.apache.commons.codec.digest.Md5CryptTest.testMd5CryptStrings:41:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Md5CryptTest/Md5CryptTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Md5CryptTest.trace org.apache.commons.codec.digest.Md5CryptTest.testMd5CryptStrings:42:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Md5CryptTest/Md5CryptTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Md5CryptTest.trace org.apache.commons.codec.digest.Md5CryptTest.testMd5CryptStrings:44:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Md5CryptTest/Md5CryptTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Md5CryptTest.trace org.apache.commons.codec.digest.Md5CryptTest.testMd5CryptStrings:45:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Md5CryptTest/Md5CryptTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Md5CryptTest.trace org.apache.commons.codec.digest.Md5CryptTest.testMd5CryptBytes:51:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Md5CryptTest/Md5CryptTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Md5CryptTest.trace org.apache.commons.codec.digest.Md5CryptTest.testMd5CryptBytes:53:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Md5CryptTest/Md5CryptTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Md5CryptTest.trace org.apache.commons.codec.digest.Md5CryptTest.testMd5CryptBytes:55:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Md5CryptTest/Md5CryptTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Md5CryptTest.trace org.apache.commons.codec.digest.Md5CryptTest.testMd5CryptExplicitCall:60:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Md5CryptTest/Md5CryptTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Md5CryptTest.trace org.apache.commons.codec.digest.Md5CryptTest.testMd5CryptExplicitCall:61:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Md5CryptTest/Md5CryptTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Md5CryptTest.trace org.apache.commons.codec.digest.Md5CryptTest.testMd5CryptExplicitCallWithThreadLocalRandom:67:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Md5CryptTest/Md5CryptTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Md5CryptTest.trace org.apache.commons.codec.digest.Md5CryptTest.testMd5CryptExplicitCallWithThreadLocalRandom:68:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Md5CryptTest/Md5CryptTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/digest_traces/Md5CryptTest.trace org.apache.commons.codec.digest.Md5CryptTest.testMd5CryptLongInput:73:*>/home/stg/omc_experiments/slices/commons-codec-1.12/digest_slices/Md5CryptTest/Md5CryptTest15.txt

#Total Asserts in org.apache.commons.codec.digest/Md5CryptTest=============15
#Total Tests in org.apache.commons.codec.digest/Md5CryptTest=============0
