#!/bin/bash

echo "computing slice for OptionGroupTest"

mkdir -p /home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testSingleOptionFromGroup:71:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testSingleOptionFromGroup:72:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testSingleOptionFromGroup:73:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testSingleOptionFromGroup:74:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testSingleOptionFromGroup:75:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testSingleOptionFromGroup:76:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testSingleOption:86:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testSingleOption:87:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testSingleOption:88:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testSingleOption:89:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testSingleOption:90:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testSingleOption:91:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testTwoValidOptions:101:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testTwoValidOptions:102:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testTwoValidOptions:103:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testTwoValidOptions:104:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testTwoValidOptions:105:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testTwoValidOptions:106:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testSingleLongOption:116:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testSingleLongOption:117:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testSingleLongOption:118:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testSingleLongOption:119:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testSingleLongOption:120:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testSingleLongOption:121:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testTwoValidLongOptions:131:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testTwoValidLongOptions:132:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testTwoValidLongOptions:133:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testTwoValidLongOptions:134:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testTwoValidLongOptions:135:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testTwoValidLongOptions:136:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testNoOptionsExtraArgs:146:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testNoOptionsExtraArgs:147:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest32.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testNoOptionsExtraArgs:148:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest33.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testNoOptionsExtraArgs:149:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest34.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testNoOptionsExtraArgs:150:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest35.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testNoOptionsExtraArgs:151:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest36.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testTwoOptionsFromGroup:166:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest37.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testTwoOptionsFromGroup:167:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest38.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testTwoOptionsFromGroup:168:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest39.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testTwoLongOptionsFromGroup:184:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest40.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testTwoLongOptionsFromGroup:185:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest41.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testTwoLongOptionsFromGroup:186:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest42.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testTwoOptionsFromDifferentGroup:196:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest43.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testTwoOptionsFromDifferentGroup:197:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest44.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testTwoOptionsFromDifferentGroup:198:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest45.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testTwoOptionsFromDifferentGroup:199:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest46.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testTwoOptionsFromDifferentGroup:200:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest47.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testTwoOptionsFromDifferentGroup:201:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest48.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testTwoOptionsFromGroupWithProperties:213:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest49.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testTwoOptionsFromGroupWithProperties:214:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest50.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testValidLongOnlyOptions:221:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest51.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testValidLongOnlyOptions:224:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest52.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testToString:235:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest53.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testToString:243:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest54.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testGetNames:254:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest55.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testGetNames:255:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest56.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testGetNames:256:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest57.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-cli/cli_traces/OptionGroupTest.trace org.apache.commons.cli.OptionGroupTest.testGetNames:257:*>/home/stg/omc_experiments/slices/commons-cli/cli_slices/OptionGroupTest/OptionGroupTest58.txt

#Total Asserts in org.apache.commons.cli/OptionGroupTest=============58
#Total Tests in org.apache.commons.cli/OptionGroupTest=============0
