#!/bin/bash

echo "computing slice for PolymorphicTypesTest"

mkdir -p /home/stg/omc_experiments/slices/jackson-dataformat-xml/misc_slices/PolymorphicTypesTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/misc_traces/PolymorphicTypesTest.trace com.fasterxml.jackson.dataformat.xml.misc.PolymorphicTypesTest.testAsClassProperty:87:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/misc_slices/PolymorphicTypesTest/PolymorphicTypesTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/misc_traces/PolymorphicTypesTest.trace com.fasterxml.jackson.dataformat.xml.misc.PolymorphicTypesTest.testAsClassProperty:90:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/misc_slices/PolymorphicTypesTest/PolymorphicTypesTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/misc_traces/PolymorphicTypesTest.trace com.fasterxml.jackson.dataformat.xml.misc.PolymorphicTypesTest.testAsClassProperty:91:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/misc_slices/PolymorphicTypesTest/PolymorphicTypesTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/misc_traces/PolymorphicTypesTest.trace com.fasterxml.jackson.dataformat.xml.misc.PolymorphicTypesTest.testAsClassProperty:92:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/misc_slices/PolymorphicTypesTest/PolymorphicTypesTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/misc_traces/PolymorphicTypesTest.trace com.fasterxml.jackson.dataformat.xml.misc.PolymorphicTypesTest.testAsClassObject:99:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/misc_slices/PolymorphicTypesTest/PolymorphicTypesTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/misc_traces/PolymorphicTypesTest.trace com.fasterxml.jackson.dataformat.xml.misc.PolymorphicTypesTest.testAsClassObject:100:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/misc_slices/PolymorphicTypesTest/PolymorphicTypesTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/misc_traces/PolymorphicTypesTest.trace com.fasterxml.jackson.dataformat.xml.misc.PolymorphicTypesTest.testAsClassObject:101:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/misc_slices/PolymorphicTypesTest/PolymorphicTypesTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/misc_traces/PolymorphicTypesTest.trace com.fasterxml.jackson.dataformat.xml.misc.PolymorphicTypesTest.testAsPropertyWithObjectId:116:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/misc_slices/PolymorphicTypesTest/PolymorphicTypesTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/misc_traces/PolymorphicTypesTest.trace com.fasterxml.jackson.dataformat.xml.misc.PolymorphicTypesTest.testAsPropertyWithObjectId:117:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/misc_slices/PolymorphicTypesTest/PolymorphicTypesTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/misc_traces/PolymorphicTypesTest.trace com.fasterxml.jackson.dataformat.xml.misc.PolymorphicTypesTest.testAsPropertyWithObjectId:118:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/misc_slices/PolymorphicTypesTest/PolymorphicTypesTest10.txt

#Total Asserts in com.fasterxml.jackson.dataformat.xml.misc/PolymorphicTypesTest=============10
#Total Tests in com.fasterxml.jackson.dataformat.xml.misc/PolymorphicTypesTest=============0
