#!/bin/bash

echo "computing slice for LabelBlockTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/block_slices/LabelBlockTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/LabelBlockTest.trace org.jfree.chart.block.LabelBlockTest.testEquals:73:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/LabelBlockTest/LabelBlockTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/LabelBlockTest.trace org.jfree.chart.block.LabelBlockTest.testEquals:74:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/LabelBlockTest/LabelBlockTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/LabelBlockTest.trace org.jfree.chart.block.LabelBlockTest.testEquals:78:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/LabelBlockTest/LabelBlockTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/LabelBlockTest.trace org.jfree.chart.block.LabelBlockTest.testEquals:81:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/LabelBlockTest/LabelBlockTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/LabelBlockTest.trace org.jfree.chart.block.LabelBlockTest.testEquals:85:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/LabelBlockTest/LabelBlockTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/LabelBlockTest.trace org.jfree.chart.block.LabelBlockTest.testEquals:88:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/LabelBlockTest/LabelBlockTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/LabelBlockTest.trace org.jfree.chart.block.LabelBlockTest.testEquals:92:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/LabelBlockTest/LabelBlockTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/LabelBlockTest.trace org.jfree.chart.block.LabelBlockTest.testEquals:95:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/LabelBlockTest/LabelBlockTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/LabelBlockTest.trace org.jfree.chart.block.LabelBlockTest.testEquals:98:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/LabelBlockTest/LabelBlockTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/LabelBlockTest.trace org.jfree.chart.block.LabelBlockTest.testEquals:100:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/LabelBlockTest/LabelBlockTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/LabelBlockTest.trace org.jfree.chart.block.LabelBlockTest.testEquals:103:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/LabelBlockTest/LabelBlockTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/LabelBlockTest.trace org.jfree.chart.block.LabelBlockTest.testEquals:105:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/LabelBlockTest/LabelBlockTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/LabelBlockTest.trace org.jfree.chart.block.LabelBlockTest.testEquals:108:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/LabelBlockTest/LabelBlockTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/LabelBlockTest.trace org.jfree.chart.block.LabelBlockTest.testEquals:110:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/LabelBlockTest/LabelBlockTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/LabelBlockTest.trace org.jfree.chart.block.LabelBlockTest.testEquals:113:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/LabelBlockTest/LabelBlockTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/LabelBlockTest.trace org.jfree.chart.block.LabelBlockTest.testEquals:115:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/LabelBlockTest/LabelBlockTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/LabelBlockTest.trace org.jfree.chart.block.LabelBlockTest.testCloning:126:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/LabelBlockTest/LabelBlockTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/LabelBlockTest.trace org.jfree.chart.block.LabelBlockTest.testCloning:127:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/LabelBlockTest/LabelBlockTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/LabelBlockTest.trace org.jfree.chart.block.LabelBlockTest.testCloning:128:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/LabelBlockTest/LabelBlockTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/LabelBlockTest.trace org.jfree.chart.block.LabelBlockTest.testSerialization:141:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/LabelBlockTest/LabelBlockTest20.txt

#Total Asserts in org.jfree.chart.block/LabelBlockTest=============20
#Total Tests in org.jfree.chart.block/LabelBlockTest=============0
