#!/bin/bash

echo "computing slice for GridArrangementTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testEquals:66:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testEquals:67:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testEquals:70:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testEquals:72:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testEquals:75:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testEquals:77:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testCloning:86:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testSerialization:96:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testNN:108:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testNN:109:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testFN:122:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testFN:123:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testNF:135:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testNF:136:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testRF:148:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testRF:149:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testRR:161:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testRR:162:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testRN:174:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testRN:175:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testNR:187:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testNR:188:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testNullBlock_FF:210:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testNullBlock_FF:211:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testNullBlock_FN:222:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testNullBlock_FN:223:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testNullBlock_FR:235:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testNullBlock_FR:236:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testNullBlock_NN:247:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testNullBlock_NN:248:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testGridNotFull_FF:260:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testGridNotFull_FF:261:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest32.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testGridNotFull_FN:273:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest33.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testGridNotFull_FN:274:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest34.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testGridNotFull_FR:287:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest35.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testGridNotFull_FR:288:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest36.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testGridNotFull_NN:300:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest37.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/GridArrangementTest.trace org.jfree.chart.block.GridArrangementTest.testGridNotFull_NN:301:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/GridArrangementTest/GridArrangementTest38.txt

#Total Asserts in org.jfree.chart.block/GridArrangementTest=============38
#Total Tests in org.jfree.chart.block/GridArrangementTest=============0
