#!/bin/bash

echo "computing slice for AbstractBlockTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/block_slices/AbstractBlockTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/AbstractBlockTest.trace org.jfree.chart.block.AbstractBlockTest.testEquals:68:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/AbstractBlockTest/AbstractBlockTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/AbstractBlockTest.trace org.jfree.chart.block.AbstractBlockTest.testEquals:69:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/AbstractBlockTest/AbstractBlockTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/AbstractBlockTest.trace org.jfree.chart.block.AbstractBlockTest.testEquals:72:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/AbstractBlockTest/AbstractBlockTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/AbstractBlockTest.trace org.jfree.chart.block.AbstractBlockTest.testEquals:74:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/AbstractBlockTest/AbstractBlockTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/AbstractBlockTest.trace org.jfree.chart.block.AbstractBlockTest.testEquals:77:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/AbstractBlockTest/AbstractBlockTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/AbstractBlockTest.trace org.jfree.chart.block.AbstractBlockTest.testEquals:79:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/AbstractBlockTest/AbstractBlockTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/AbstractBlockTest.trace org.jfree.chart.block.AbstractBlockTest.testEquals:82:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/AbstractBlockTest/AbstractBlockTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/AbstractBlockTest.trace org.jfree.chart.block.AbstractBlockTest.testEquals:84:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/AbstractBlockTest/AbstractBlockTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/AbstractBlockTest.trace org.jfree.chart.block.AbstractBlockTest.testEquals:87:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/AbstractBlockTest/AbstractBlockTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/AbstractBlockTest.trace org.jfree.chart.block.AbstractBlockTest.testEquals:89:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/AbstractBlockTest/AbstractBlockTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/AbstractBlockTest.trace org.jfree.chart.block.AbstractBlockTest.testEquals:92:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/AbstractBlockTest/AbstractBlockTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/AbstractBlockTest.trace org.jfree.chart.block.AbstractBlockTest.testEquals:94:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/AbstractBlockTest/AbstractBlockTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/AbstractBlockTest.trace org.jfree.chart.block.AbstractBlockTest.testEquals:97:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/AbstractBlockTest/AbstractBlockTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/AbstractBlockTest.trace org.jfree.chart.block.AbstractBlockTest.testEquals:99:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/AbstractBlockTest/AbstractBlockTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/AbstractBlockTest.trace org.jfree.chart.block.AbstractBlockTest.testEquals:102:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/AbstractBlockTest/AbstractBlockTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/AbstractBlockTest.trace org.jfree.chart.block.AbstractBlockTest.testEquals:104:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/AbstractBlockTest/AbstractBlockTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/AbstractBlockTest.trace org.jfree.chart.block.AbstractBlockTest.testEquals:107:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/AbstractBlockTest/AbstractBlockTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/AbstractBlockTest.trace org.jfree.chart.block.AbstractBlockTest.testEquals:109:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/AbstractBlockTest/AbstractBlockTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/AbstractBlockTest.trace org.jfree.chart.block.AbstractBlockTest.testEquals:112:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/AbstractBlockTest/AbstractBlockTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/AbstractBlockTest.trace org.jfree.chart.block.AbstractBlockTest.testEquals:114:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/AbstractBlockTest/AbstractBlockTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/AbstractBlockTest.trace org.jfree.chart.block.AbstractBlockTest.testCloning:133:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/AbstractBlockTest/AbstractBlockTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/AbstractBlockTest.trace org.jfree.chart.block.AbstractBlockTest.testCloning:134:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/AbstractBlockTest/AbstractBlockTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/AbstractBlockTest.trace org.jfree.chart.block.AbstractBlockTest.testCloning:135:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/AbstractBlockTest/AbstractBlockTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/AbstractBlockTest.trace org.jfree.chart.block.AbstractBlockTest.testCloning:138:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/AbstractBlockTest/AbstractBlockTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/AbstractBlockTest.trace org.jfree.chart.block.AbstractBlockTest.testCloning:140:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/AbstractBlockTest/AbstractBlockTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/block_traces/AbstractBlockTest.trace org.jfree.chart.block.AbstractBlockTest.testSerialization:150:*>/home/stg/omc_experiments/slices/jfreechart/block_slices/AbstractBlockTest/AbstractBlockTest26.txt

#Total Asserts in org.jfree.chart.block/AbstractBlockTest=============26
#Total Tests in org.jfree.chart.block/AbstractBlockTest=============0
