#!/bin/bash

echo "computing slice for StringUtilsEmptyBlankTest"

mkdir -p /home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsEmpty:45:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsEmpty:46:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsEmpty:47:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsEmpty:48:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsEmpty:49:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsNotEmpty:54:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsNotEmpty:55:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsNotEmpty:56:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsNotEmpty:57:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsNotEmpty:58:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAnyEmpty:63:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAnyEmpty:64:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAnyEmpty:65:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAnyEmpty:66:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest14.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAnyEmpty:67:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest15.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAnyEmpty:68:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest16.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAnyEmpty:69:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest17.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAnyEmpty:70:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest18.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsNoneEmpty:75:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest19.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsNoneEmpty:76:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest20.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsNoneEmpty:77:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest21.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsNoneEmpty:78:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest22.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsNoneEmpty:79:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest23.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsNoneEmpty:80:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest24.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsNoneEmpty:81:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest25.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsNoneEmpty:82:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest26.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAllEmpty:87:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest27.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAllEmpty:88:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest28.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAllEmpty:89:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest29.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAllEmpty:90:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest30.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAllEmpty:91:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest31.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAllEmpty:92:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest32.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAllEmpty:93:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest33.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAllEmpty:94:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest34.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAllEmpty:95:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest35.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAllEmpty:96:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest36.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAllEmpty:97:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest37.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsBlank:102:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest38.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsBlank:103:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest39.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsBlank:104:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest40.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsBlank:105:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest41.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsBlank:106:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest42.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsNotBlank:111:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest43.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsNotBlank:112:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest44.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsNotBlank:113:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest45.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsNotBlank:114:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest46.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsNotBlank:115:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest47.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAnyBlank:120:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest48.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAnyBlank:121:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest49.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAnyBlank:122:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest50.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAnyBlank:123:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest51.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAnyBlank:124:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest52.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAnyBlank:125:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest53.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAnyBlank:126:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest54.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAnyBlank:127:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest55.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAnyBlank:128:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest56.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsNoneBlank:133:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest57.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsNoneBlank:134:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest58.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsNoneBlank:135:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest59.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsNoneBlank:136:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest60.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsNoneBlank:137:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest61.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsNoneBlank:138:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest62.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsNoneBlank:139:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest63.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsNoneBlank:140:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest64.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsNoneBlank:141:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest65.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAllBlank:146:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest66.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAllBlank:147:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest67.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAllBlank:148:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest68.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAllBlank:149:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest69.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAllBlank:150:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest70.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAllBlank:151:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest71.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAllBlank:152:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest72.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAllBlank:153:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest73.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAllBlank:154:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest74.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/StringUtilsEmptyBlankTest.trace org.apache.commons.lang3.StringUtilsEmptyBlankTest.testIsAllBlank:155:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/StringUtilsEmptyBlankTest/StringUtilsEmptyBlankTest75.txt

#Total Asserts in org.apache.commons.lang3/StringUtilsEmptyBlankTest=============75
#Total Tests in org.apache.commons.lang3/StringUtilsEmptyBlankTest=============0
