#!/bin/bash

echo "computing slice for JavaVersionTest"

mkdir -p /home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/JavaVersionTest

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/JavaVersionTest.trace org.apache.commons.lang3.JavaVersionTest.testGetJavaVersion:55:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/JavaVersionTest/JavaVersionTest1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/JavaVersionTest.trace org.apache.commons.lang3.JavaVersionTest.testGetJavaVersion:56:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/JavaVersionTest/JavaVersionTest2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/JavaVersionTest.trace org.apache.commons.lang3.JavaVersionTest.testGetJavaVersion:57:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/JavaVersionTest/JavaVersionTest3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/JavaVersionTest.trace org.apache.commons.lang3.JavaVersionTest.testGetJavaVersion:58:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/JavaVersionTest/JavaVersionTest4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/JavaVersionTest.trace org.apache.commons.lang3.JavaVersionTest.testGetJavaVersion:59:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/JavaVersionTest/JavaVersionTest5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/JavaVersionTest.trace org.apache.commons.lang3.JavaVersionTest.testGetJavaVersion:60:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/JavaVersionTest/JavaVersionTest6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/JavaVersionTest.trace org.apache.commons.lang3.JavaVersionTest.testGetJavaVersion:61:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/JavaVersionTest/JavaVersionTest7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/JavaVersionTest.trace org.apache.commons.lang3.JavaVersionTest.testGetJavaVersion:62:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/JavaVersionTest/JavaVersionTest8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/JavaVersionTest.trace org.apache.commons.lang3.JavaVersionTest.testGetJavaVersion:63:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/JavaVersionTest/JavaVersionTest9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/JavaVersionTest.trace org.apache.commons.lang3.JavaVersionTest.testGetJavaVersion:64:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/JavaVersionTest/JavaVersionTest10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/JavaVersionTest.trace org.apache.commons.lang3.JavaVersionTest.testGetJavaVersion:65:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/JavaVersionTest/JavaVersionTest11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/JavaVersionTest.trace org.apache.commons.lang3.JavaVersionTest.testGetJavaVersion:67:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/JavaVersionTest/JavaVersionTest12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/JavaVersionTest.trace org.apache.commons.lang3.JavaVersionTest.testAtLeast:72:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/JavaVersionTest/JavaVersionTest13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/JavaVersionTest.trace org.apache.commons.lang3.JavaVersionTest.testAtLeast:73:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/JavaVersionTest/JavaVersionTest14.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/JavaVersionTest.trace org.apache.commons.lang3.JavaVersionTest.testAtLeast:74:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/JavaVersionTest/JavaVersionTest15.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/JavaVersionTest.trace org.apache.commons.lang3.JavaVersionTest.testAtLeast:76:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/JavaVersionTest/JavaVersionTest16.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/JavaVersionTest.trace org.apache.commons.lang3.JavaVersionTest.testAtLeast:77:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/JavaVersionTest/JavaVersionTest17.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/JavaVersionTest.trace org.apache.commons.lang3.JavaVersionTest.testToString:82:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/JavaVersionTest/JavaVersionTest18.txt

#Total Asserts in org.apache.commons.lang3/JavaVersionTest=============18
#Total Tests in org.apache.commons.lang3/JavaVersionTest=============0
