#!/bin/bash

echo "computing slice for LocaleUtilsTest"

mkdir -p /home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.testConstructor:93:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.testConstructor:95:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.testConstructor:96:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.testConstructor:97:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.testConstructor:98:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.assertValidToLocale:110:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.assertValidToLocale:111:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.assertValidToLocale:113:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.assertValidToLocale:114:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.assertValidToLocale:126:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.assertValidToLocale:127:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.assertValidToLocale:128:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.assertValidToLocale:130:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.assertValidToLocale:145:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest14.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.assertValidToLocale:146:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest15.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.assertValidToLocale:147:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest16.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.assertValidToLocale:148:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest17.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.testToLocale_1Part:156:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest18.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.assertLocaleLookupList:284:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest19.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.assertLocaleLookupList:285:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest20.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.testAvailableLocaleList:374:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest21.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.testAvailableLocaleList:375:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest22.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.testAvailableLocaleList:380:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest23.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.testAvailableLocaleSet:392:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest24.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.testAvailableLocaleSet:393:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest25.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.testAvailableLocaleSet:399:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest26.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.testIsAvailableLocale:411:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest27.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.testIsAvailableLocale:412:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest28.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.testIsAvailableLocale:413:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest29.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.testIsAvailableLocale:414:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest30.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.testIsAvailableLocale:415:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest31.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.testIsAvailableLocale:416:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest32.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.testIsAvailableLocale:417:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest33.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.testThreeCharsLocale:427:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest34.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.testThreeCharsLocale:428:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest35.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.testThreeCharsLocale:429:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest36.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.testThreeCharsLocale:430:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest37.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.assertLanguageByCountry:448:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest38.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.assertLanguageByCountry:449:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest39.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.assertLanguageByCountry:458:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest40.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.assertLanguageByCountry:460:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest41.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.assertCountriesByLanguage:499:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest42.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.assertCountriesByLanguage:500:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest43.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.assertCountriesByLanguage:509:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest44.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/lang3_traces/LocaleUtilsTest.trace org.apache.commons.lang3.LocaleUtilsTest.assertCountriesByLanguage:511:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/lang3_slices/LocaleUtilsTest/LocaleUtilsTest45.txt

#Total Asserts in org.apache.commons.lang3/LocaleUtilsTest=============45
#Total Tests in org.apache.commons.lang3/LocaleUtilsTest=============0
