#!/bin/bash

echo "computing slice for TestReadableInstantConverter"

mkdir -p /home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableInstantConverter

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableInstantConverter.trace org.joda.time.convert.TestReadableInstantConverter.testSingleton:90:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableInstantConverter/TestReadableInstantConverter1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableInstantConverter.trace org.joda.time.convert.TestReadableInstantConverter.testSingleton:91:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableInstantConverter/TestReadableInstantConverter2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableInstantConverter.trace org.joda.time.convert.TestReadableInstantConverter.testSingleton:92:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableInstantConverter/TestReadableInstantConverter3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableInstantConverter.trace org.joda.time.convert.TestReadableInstantConverter.testSingleton:95:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableInstantConverter/TestReadableInstantConverter4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableInstantConverter.trace org.joda.time.convert.TestReadableInstantConverter.testSingleton:96:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableInstantConverter/TestReadableInstantConverter5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableInstantConverter.trace org.joda.time.convert.TestReadableInstantConverter.testSingleton:99:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableInstantConverter/TestReadableInstantConverter6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableInstantConverter.trace org.joda.time.convert.TestReadableInstantConverter.testSingleton:100:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableInstantConverter/TestReadableInstantConverter7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableInstantConverter.trace org.joda.time.convert.TestReadableInstantConverter.testSingleton:101:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableInstantConverter/TestReadableInstantConverter8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableInstantConverter.trace org.joda.time.convert.TestReadableInstantConverter.testSupportedType:106:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableInstantConverter/TestReadableInstantConverter9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableInstantConverter.trace org.joda.time.convert.TestReadableInstantConverter.testGetInstantMillis_Object_Chronology:111:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableInstantConverter/TestReadableInstantConverter10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableInstantConverter.trace org.joda.time.convert.TestReadableInstantConverter.testGetInstantMillis_Object_Chronology:112:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableInstantConverter/TestReadableInstantConverter11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableInstantConverter.trace org.joda.time.convert.TestReadableInstantConverter.testGetInstantMillis_Object_Chronology:113:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableInstantConverter/TestReadableInstantConverter12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableInstantConverter.trace org.joda.time.convert.TestReadableInstantConverter.testGetInstantMillis_Object_Chronology:114:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableInstantConverter/TestReadableInstantConverter13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableInstantConverter.trace org.joda.time.convert.TestReadableInstantConverter.testGetChronology_Object_Zone:119:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableInstantConverter/TestReadableInstantConverter14.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableInstantConverter.trace org.joda.time.convert.TestReadableInstantConverter.testGetChronology_Object_Zone:120:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableInstantConverter/TestReadableInstantConverter15.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableInstantConverter.trace org.joda.time.convert.TestReadableInstantConverter.testGetChronology_Object_Zone:121:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableInstantConverter/TestReadableInstantConverter16.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableInstantConverter.trace org.joda.time.convert.TestReadableInstantConverter.testGetChronology_Object_Zone:122:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableInstantConverter/TestReadableInstantConverter17.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableInstantConverter.trace org.joda.time.convert.TestReadableInstantConverter.testGetChronology_Object_Zone:123:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableInstantConverter/TestReadableInstantConverter18.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableInstantConverter.trace org.joda.time.convert.TestReadableInstantConverter.testGetChronology_Object_Zone:124:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableInstantConverter/TestReadableInstantConverter19.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableInstantConverter.trace org.joda.time.convert.TestReadableInstantConverter.testGetChronology_Object_Zone:126:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableInstantConverter/TestReadableInstantConverter20.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableInstantConverter.trace org.joda.time.convert.TestReadableInstantConverter.getChronology:133:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableInstantConverter/TestReadableInstantConverter21.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableInstantConverter.trace org.joda.time.convert.TestReadableInstantConverter.testGetChronology_Object_nullChronology:137:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableInstantConverter/TestReadableInstantConverter22.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableInstantConverter.trace org.joda.time.convert.TestReadableInstantConverter.testGetChronology_Object_nullChronology:138:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableInstantConverter/TestReadableInstantConverter23.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableInstantConverter.trace org.joda.time.convert.TestReadableInstantConverter.getChronology:145:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableInstantConverter/TestReadableInstantConverter24.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableInstantConverter.trace org.joda.time.convert.TestReadableInstantConverter.testGetChronology_Object_Chronology:149:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableInstantConverter/TestReadableInstantConverter25.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableInstantConverter.trace org.joda.time.convert.TestReadableInstantConverter.testGetChronology_Object_Chronology:150:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableInstantConverter/TestReadableInstantConverter26.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableInstantConverter.trace org.joda.time.convert.TestReadableInstantConverter.testGetPartialValues:158:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableInstantConverter/TestReadableInstantConverter27.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableInstantConverter.trace org.joda.time.convert.TestReadableInstantConverter.testToString:163:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableInstantConverter/TestReadableInstantConverter28.txt

#Total Asserts in org.joda.time.convert/TestReadableInstantConverter=============28
#Total Tests in org.joda.time.convert/TestReadableInstantConverter=============0
