#!/bin/bash

echo "computing slice for TestReadableIntervalConverter"

mkdir -p /home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSingleton:97:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSingleton:98:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSingleton:99:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSingleton:102:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSingleton:103:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSingleton:106:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSingleton:107:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSingleton:108:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSupportedType:113:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testGetDurationMillis_Object:119:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testGetPeriodType_Object:125:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSetIntoPeriod_Object1:133:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSetIntoPeriod_Object1:134:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSetIntoPeriod_Object1:135:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter14.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSetIntoPeriod_Object1:136:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter15.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSetIntoPeriod_Object1:137:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter16.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSetIntoPeriod_Object1:138:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter17.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSetIntoPeriod_Object1:139:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter18.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSetIntoPeriod_Object1:140:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter19.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSetIntoPeriod_Object2:147:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter20.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSetIntoPeriod_Object2:148:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter21.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSetIntoPeriod_Object2:149:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter22.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSetIntoPeriod_Object2:150:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter23.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSetIntoPeriod_Object2:151:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter24.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSetIntoPeriod_Object2:152:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter25.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSetIntoPeriod_Object2:153:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter26.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSetIntoPeriod_Object2:154:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter27.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testIsReadableInterval_Object_Chronology:160:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter28.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSetIntoInterval_Object1:167:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter29.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSetIntoInterval_Object1:168:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter30.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSetIntoInterval_Object1:169:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter31.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSetIntoInterval_Object2:176:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter32.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSetIntoInterval_Object2:177:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter33.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testSetIntoInterval_Object2:178:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter34.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.getChronology:189:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter35.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.getChronology:190:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter36.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.getChronology:191:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter37.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.getChronology:202:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter38.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.getChronology:203:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter39.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.getChronology:204:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter40.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/convert_traces/TestReadableIntervalConverter.trace org.joda.time.convert.TestReadableIntervalConverter.testToString:209:*>/home/stg/omc_experiments/slices/fse-joda-time/convert_slices/TestReadableIntervalConverter/TestReadableIntervalConverter41.txt

#Total Asserts in org.joda.time.convert/TestReadableIntervalConverter=============41
#Total Tests in org.joda.time.convert/TestReadableIntervalConverter=============0
