#!/bin/bash

echo "computing slice for IBANValidatorTest"

mkdir -p /home/stg/omc_experiments/slices/commons-validator/routines_slices/IBANValidatorTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/IBANValidatorTest.trace org.apache.commons.validator.routines.IBANValidatorTest.testValid:140:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/IBANValidatorTest/IBANValidatorTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/IBANValidatorTest.trace org.apache.commons.validator.routines.IBANValidatorTest.testValid:141:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/IBANValidatorTest/IBANValidatorTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/IBANValidatorTest.trace org.apache.commons.validator.routines.IBANValidatorTest.testValid:142:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/IBANValidatorTest/IBANValidatorTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/IBANValidatorTest.trace org.apache.commons.validator.routines.IBANValidatorTest.testInValid:149:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/IBANValidatorTest/IBANValidatorTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/IBANValidatorTest.trace org.apache.commons.validator.routines.IBANValidatorTest.testNull:155:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/IBANValidatorTest/IBANValidatorTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/IBANValidatorTest.trace org.apache.commons.validator.routines.IBANValidatorTest.testHasValidator:160:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/IBANValidatorTest/IBANValidatorTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/IBANValidatorTest.trace org.apache.commons.validator.routines.IBANValidatorTest.testHasValidator:161:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/IBANValidatorTest/IBANValidatorTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/IBANValidatorTest.trace org.apache.commons.validator.routines.IBANValidatorTest.testGetValidator:166:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/IBANValidatorTest/IBANValidatorTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/IBANValidatorTest.trace org.apache.commons.validator.routines.IBANValidatorTest.testGetValidator:167:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/IBANValidatorTest/IBANValidatorTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/IBANValidatorTest.trace org.apache.commons.validator.routines.IBANValidatorTest.testSetDefaultValidator1:172:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/IBANValidatorTest/IBANValidatorTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/IBANValidatorTest.trace org.apache.commons.validator.routines.IBANValidatorTest.testSetDefaultValidator2:177:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/IBANValidatorTest/IBANValidatorTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/IBANValidatorTest.trace org.apache.commons.validator.routines.IBANValidatorTest.testSetValidatorLC:183:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/IBANValidatorTest/IBANValidatorTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/IBANValidatorTest.trace org.apache.commons.validator.routines.IBANValidatorTest.testSetValidatorLen7:189:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/IBANValidatorTest/IBANValidatorTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/IBANValidatorTest.trace org.apache.commons.validator.routines.IBANValidatorTest.testSetValidatorLen35:195:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/IBANValidatorTest/IBANValidatorTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/IBANValidatorTest.trace org.apache.commons.validator.routines.IBANValidatorTest.testSetValidatorLen_1:201:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/IBANValidatorTest/IBANValidatorTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/IBANValidatorTest.trace org.apache.commons.validator.routines.IBANValidatorTest.testSetValidatorLen_1:202:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/IBANValidatorTest/IBANValidatorTest16.txt

#Total Asserts in org.apache.commons.validator.routines/IBANValidatorTest=============16
#Total Tests in org.apache.commons.validator.routines/IBANValidatorTest=============0
