#!/bin/bash

echo "computing slice for FloatValidatorTest"

mkdir -p /home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatValidatorMethods:89:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatValidatorMethods:90:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatValidatorMethods:91:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatValidatorMethods:92:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatValidatorMethods:94:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatValidatorMethods:95:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatValidatorMethods:96:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatValidatorMethods:97:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatValidatorMethods:99:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatValidatorMethods:100:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatValidatorMethods:101:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatValidatorMethods:102:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatValidatorMethods:104:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatValidatorMethods:105:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatValidatorMethods:106:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatValidatorMethods:107:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatSmallestValues:121:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatSmallestValues:126:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatSmallestValues:131:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatSmallestValues:136:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatRangeMinMax:152:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatRangeMinMax:153:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatRangeMinMax:154:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatRangeMinMax:155:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatRangeMinMax:156:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatRangeMinMax:159:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatRangeMinMax:160:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatRangeMinMax:161:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatRangeMinMax:164:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatRangeMinMax:165:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/FloatValidatorTest.trace org.apache.commons.validator.routines.FloatValidatorTest.testFloatRangeMinMax:166:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/FloatValidatorTest/FloatValidatorTest31.txt

#Total Asserts in org.apache.commons.validator.routines/FloatValidatorTest=============31
#Total Tests in org.apache.commons.validator.routines/FloatValidatorTest=============0
