#!/bin/bash

echo "computing slice for ISSNValidatorTest"

mkdir -p /home/stg/omc_experiments/slices/commons-validator/routines_slices/ISSNValidatorTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/ISSNValidatorTest.trace org.apache.commons.validator.routines.ISSNValidatorTest.testIsValidISSN:79:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/ISSNValidatorTest/ISSNValidatorTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/ISSNValidatorTest.trace org.apache.commons.validator.routines.ISSNValidatorTest.testNull:87:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/ISSNValidatorTest/ISSNValidatorTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/ISSNValidatorTest.trace org.apache.commons.validator.routines.ISSNValidatorTest.testInvalid:95:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/ISSNValidatorTest/ISSNValidatorTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/ISSNValidatorTest.trace org.apache.commons.validator.routines.ISSNValidatorTest.testIsValidISSNConvertNull:100:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/ISSNValidatorTest/ISSNValidatorTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/ISSNValidatorTest.trace org.apache.commons.validator.routines.ISSNValidatorTest.testIsValidISSNConvertSuffix:105:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/ISSNValidatorTest/ISSNValidatorTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/ISSNValidatorTest.trace org.apache.commons.validator.routines.ISSNValidatorTest.testIsValidISSNConvertSuffix:111:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/ISSNValidatorTest/ISSNValidatorTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/ISSNValidatorTest.trace org.apache.commons.validator.routines.ISSNValidatorTest.testIsValidISSNConvertSuffix:117:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/ISSNValidatorTest/ISSNValidatorTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/ISSNValidatorTest.trace org.apache.commons.validator.routines.ISSNValidatorTest.testIsValidISSNConvertSuffix:123:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/ISSNValidatorTest/ISSNValidatorTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/ISSNValidatorTest.trace org.apache.commons.validator.routines.ISSNValidatorTest.testIsValidISSNConvertSuffix:129:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/ISSNValidatorTest/ISSNValidatorTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/ISSNValidatorTest.trace org.apache.commons.validator.routines.ISSNValidatorTest.testIsValidISSNConvertSuffix:135:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/ISSNValidatorTest/ISSNValidatorTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/ISSNValidatorTest.trace org.apache.commons.validator.routines.ISSNValidatorTest.testIsValidISSNConvert:151:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/ISSNValidatorTest/ISSNValidatorTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/ISSNValidatorTest.trace org.apache.commons.validator.routines.ISSNValidatorTest.testIsValidISSNConvert:154:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/ISSNValidatorTest/ISSNValidatorTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/ISSNValidatorTest.trace org.apache.commons.validator.routines.ISSNValidatorTest.testIsValidISSNConvert:155:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/ISSNValidatorTest/ISSNValidatorTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-validator/routines_traces/ISSNValidatorTest.trace org.apache.commons.validator.routines.ISSNValidatorTest.testIsValidISSNConvert:156:*>/home/stg/omc_experiments/slices/commons-validator/routines_slices/ISSNValidatorTest/ISSNValidatorTest14.txt

#Total Asserts in org.apache.commons.validator.routines/ISSNValidatorTest=============14
#Total Tests in org.apache.commons.validator.routines/ISSNValidatorTest=============0
