#!/bin/bash

echo "computing slice for SecurityMapperTest"

mkdir -p /home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testAnyType:61:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testAnyType:62:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testAnyType:63:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testNoType:73:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testNoType:79:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testNullType:86:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testNullType:87:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testNullType:92:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testPrimitiveTypes:99:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testPrimitiveTypes:100:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testPrimitiveTypes:105:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testPrimitiveTypes:111:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testPrimitiveTypes:117:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testArrayTypes:124:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testArrayTypes:125:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testArrayTypes:130:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testArrayTypes:136:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testArrayTypes:142:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testExplicitTypes:149:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testExplicitTypes:150:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testExplicitTypes:155:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testNamesWithRegExps:166:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testNamesWithRegExps:167:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testNamesWithRegExps:168:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testNamesWithRegExps:169:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testNamesWithRegExps:170:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testNamesWithRegExps:175:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testNamesWithWildcardPatterns:186:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testNamesWithWildcardPatterns:187:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testNamesWithWildcardPatterns:188:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testNamesWithWildcardPatterns:193:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testNamesWithWildcardPatterns:199:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest32.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/SecurityMapperTest.trace com.thoughtworks.xstream.mapper.SecurityMapperTest.testNamesWithWildcardPatterns:205:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/SecurityMapperTest/SecurityMapperTest33.txt

#Total Asserts in com.thoughtworks.xstream.mapper/SecurityMapperTest=============33
#Total Tests in com.thoughtworks.xstream.mapper/SecurityMapperTest=============0
