#!/bin/bash

echo "computing slice for DefaultClassMapperTest"

mkdir -p /home/stg/omc_experiments/slices/xstream/mapper_slices/DefaultClassMapperTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/DefaultClassMapperTest.trace com.thoughtworks.xstream.mapper.DefaultClassMapperTest.testAppendsArraySuffixOnArrays:30:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/DefaultClassMapperTest/DefaultClassMapperTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/DefaultClassMapperTest.trace com.thoughtworks.xstream.mapper.DefaultClassMapperTest.testAppendsMultipleArraySuffixesOnMultidimensionalArrays:35:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/DefaultClassMapperTest/DefaultClassMapperTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/DefaultClassMapperTest.trace com.thoughtworks.xstream.mapper.DefaultClassMapperTest.testCreatesInstancesOfArrays:40:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/DefaultClassMapperTest/DefaultClassMapperTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/DefaultClassMapperTest.trace com.thoughtworks.xstream.mapper.DefaultClassMapperTest.testCreatesInstancesOfArrays:41:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/DefaultClassMapperTest/DefaultClassMapperTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/DefaultClassMapperTest.trace com.thoughtworks.xstream.mapper.DefaultClassMapperTest.testSupportsAllPrimitiveArrayTypes:45:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/DefaultClassMapperTest/DefaultClassMapperTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/DefaultClassMapperTest.trace com.thoughtworks.xstream.mapper.DefaultClassMapperTest.testSupportsAllPrimitiveArrayTypes:46:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/DefaultClassMapperTest/DefaultClassMapperTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/DefaultClassMapperTest.trace com.thoughtworks.xstream.mapper.DefaultClassMapperTest.testSupportsAllPrimitiveArrayTypes:47:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/DefaultClassMapperTest/DefaultClassMapperTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/DefaultClassMapperTest.trace com.thoughtworks.xstream.mapper.DefaultClassMapperTest.testSupportsAllPrimitiveArrayTypes:48:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/DefaultClassMapperTest/DefaultClassMapperTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/DefaultClassMapperTest.trace com.thoughtworks.xstream.mapper.DefaultClassMapperTest.testSupportsAllPrimitiveArrayTypes:49:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/DefaultClassMapperTest/DefaultClassMapperTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/DefaultClassMapperTest.trace com.thoughtworks.xstream.mapper.DefaultClassMapperTest.testSupportsAllPrimitiveArrayTypes:50:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/DefaultClassMapperTest/DefaultClassMapperTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/DefaultClassMapperTest.trace com.thoughtworks.xstream.mapper.DefaultClassMapperTest.testSupportsAllPrimitiveArrayTypes:51:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/DefaultClassMapperTest/DefaultClassMapperTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/DefaultClassMapperTest.trace com.thoughtworks.xstream.mapper.DefaultClassMapperTest.testSupportsAllPrimitiveArrayTypes:52:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/DefaultClassMapperTest/DefaultClassMapperTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/DefaultClassMapperTest.trace com.thoughtworks.xstream.mapper.DefaultClassMapperTest.testCreatesInstancesOfMultidimensionalArrays:57:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/DefaultClassMapperTest/DefaultClassMapperTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/DefaultClassMapperTest.trace com.thoughtworks.xstream.mapper.DefaultClassMapperTest.testCreatesInstancesOfMultidimensionalArrays:58:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/DefaultClassMapperTest/DefaultClassMapperTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/DefaultClassMapperTest.trace com.thoughtworks.xstream.mapper.DefaultClassMapperTest.testCreatesInstancesOfMultidimensionalArrays:59:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/DefaultClassMapperTest/DefaultClassMapperTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/DefaultClassMapperTest.trace com.thoughtworks.xstream.mapper.DefaultClassMapperTest.testCreatesInstancesOfMultidimensionalArrays:61:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/DefaultClassMapperTest/DefaultClassMapperTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/DefaultClassMapperTest.trace com.thoughtworks.xstream.mapper.DefaultClassMapperTest.testCreatesInstancesOfMultidimensionalArrays:62:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/DefaultClassMapperTest/DefaultClassMapperTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/DefaultClassMapperTest.trace com.thoughtworks.xstream.mapper.DefaultClassMapperTest.testCreatesInstancesOfMultidimensionalArrays:65:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/DefaultClassMapperTest/DefaultClassMapperTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/DefaultClassMapperTest.trace com.thoughtworks.xstream.mapper.DefaultClassMapperTest.testCreatesInstancesOfMultidimensionalArrays:66:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/DefaultClassMapperTest/DefaultClassMapperTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/DefaultClassMapperTest.trace com.thoughtworks.xstream.mapper.DefaultClassMapperTest.testCreatesInstancesOfMultidimensionalArrays:67:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/DefaultClassMapperTest/DefaultClassMapperTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/DefaultClassMapperTest.trace com.thoughtworks.xstream.mapper.DefaultClassMapperTest.testCreatesInstancesOfMultidimensionalArrays:69:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/DefaultClassMapperTest/DefaultClassMapperTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/mapper_traces/DefaultClassMapperTest.trace com.thoughtworks.xstream.mapper.DefaultClassMapperTest.testCreatesInstancesOfMultidimensionalArrays:70:*>/home/stg/omc_experiments/slices/xstream/mapper_slices/DefaultClassMapperTest/DefaultClassMapperTest22.txt

#Total Asserts in com.thoughtworks.xstream.mapper/DefaultClassMapperTest=============22
#Total Tests in com.thoughtworks.xstream.mapper/DefaultClassMapperTest=============0
