#!/bin/bash

echo "computing slice for ScatterRendererTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/category_slices/ScatterRendererTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/ScatterRendererTest.trace org.jfree.chart.renderer.category.ScatterRendererTest.testEquals:73:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/ScatterRendererTest/ScatterRendererTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/ScatterRendererTest.trace org.jfree.chart.renderer.category.ScatterRendererTest.testEquals:76:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/ScatterRendererTest/ScatterRendererTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/ScatterRendererTest.trace org.jfree.chart.renderer.category.ScatterRendererTest.testEquals:78:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/ScatterRendererTest/ScatterRendererTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/ScatterRendererTest.trace org.jfree.chart.renderer.category.ScatterRendererTest.testEquals:81:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/ScatterRendererTest/ScatterRendererTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/ScatterRendererTest.trace org.jfree.chart.renderer.category.ScatterRendererTest.testEquals:83:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/ScatterRendererTest/ScatterRendererTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/ScatterRendererTest.trace org.jfree.chart.renderer.category.ScatterRendererTest.testEquals:86:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/ScatterRendererTest/ScatterRendererTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/ScatterRendererTest.trace org.jfree.chart.renderer.category.ScatterRendererTest.testEquals:88:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/ScatterRendererTest/ScatterRendererTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/ScatterRendererTest.trace org.jfree.chart.renderer.category.ScatterRendererTest.testEquals:91:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/ScatterRendererTest/ScatterRendererTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/ScatterRendererTest.trace org.jfree.chart.renderer.category.ScatterRendererTest.testEquals:93:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/ScatterRendererTest/ScatterRendererTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/ScatterRendererTest.trace org.jfree.chart.renderer.category.ScatterRendererTest.testEquals:96:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/ScatterRendererTest/ScatterRendererTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/ScatterRendererTest.trace org.jfree.chart.renderer.category.ScatterRendererTest.testEquals:98:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/ScatterRendererTest/ScatterRendererTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/ScatterRendererTest.trace org.jfree.chart.renderer.category.ScatterRendererTest.testEquals:101:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/ScatterRendererTest/ScatterRendererTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/ScatterRendererTest.trace org.jfree.chart.renderer.category.ScatterRendererTest.testEquals:103:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/ScatterRendererTest/ScatterRendererTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/ScatterRendererTest.trace org.jfree.chart.renderer.category.ScatterRendererTest.testHashcode:114:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/ScatterRendererTest/ScatterRendererTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/ScatterRendererTest.trace org.jfree.chart.renderer.category.ScatterRendererTest.testHashcode:117:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/ScatterRendererTest/ScatterRendererTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/ScatterRendererTest.trace org.jfree.chart.renderer.category.ScatterRendererTest.testCloning:127:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/ScatterRendererTest/ScatterRendererTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/ScatterRendererTest.trace org.jfree.chart.renderer.category.ScatterRendererTest.testCloning:128:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/ScatterRendererTest/ScatterRendererTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/ScatterRendererTest.trace org.jfree.chart.renderer.category.ScatterRendererTest.testCloning:129:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/ScatterRendererTest/ScatterRendererTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/ScatterRendererTest.trace org.jfree.chart.renderer.category.ScatterRendererTest.testCloning:131:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/ScatterRendererTest/ScatterRendererTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/ScatterRendererTest.trace org.jfree.chart.renderer.category.ScatterRendererTest.testPublicCloneable:140:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/ScatterRendererTest/ScatterRendererTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/ScatterRendererTest.trace org.jfree.chart.renderer.category.ScatterRendererTest.testSerialization:189:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/ScatterRendererTest/ScatterRendererTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/ScatterRendererTest.trace org.jfree.chart.renderer.category.ScatterRendererTest.testFindRangeBounds:198:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/ScatterRendererTest/ScatterRendererTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/ScatterRendererTest.trace org.jfree.chart.renderer.category.ScatterRendererTest.testFindRangeBounds:203:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/ScatterRendererTest/ScatterRendererTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/ScatterRendererTest.trace org.jfree.chart.renderer.category.ScatterRendererTest.testFindRangeBounds:207:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/ScatterRendererTest/ScatterRendererTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/ScatterRendererTest.trace org.jfree.chart.renderer.category.ScatterRendererTest.testFindRangeBounds:211:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/ScatterRendererTest/ScatterRendererTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/ScatterRendererTest.trace org.jfree.chart.renderer.category.ScatterRendererTest.testFindRangeBounds:216:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/ScatterRendererTest/ScatterRendererTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/ScatterRendererTest.trace org.jfree.chart.renderer.category.ScatterRendererTest.testFindRangeBounds:220:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/ScatterRendererTest/ScatterRendererTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/ScatterRendererTest.trace org.jfree.chart.renderer.category.ScatterRendererTest.testFindRangeBounds:223:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/ScatterRendererTest/ScatterRendererTest28.txt

#Total Asserts in org.jfree.chart.renderer.category/ScatterRendererTest=============28
#Total Tests in org.jfree.chart.renderer.category/ScatterRendererTest=============0
