#!/bin/bash

echo "computing slice for StackedBarRendererTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/category_slices/StackedBarRendererTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StackedBarRendererTest.trace org.jfree.chart.renderer.category.StackedBarRendererTest.testEquals:68:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StackedBarRendererTest/StackedBarRendererTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StackedBarRendererTest.trace org.jfree.chart.renderer.category.StackedBarRendererTest.testEquals:69:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StackedBarRendererTest/StackedBarRendererTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StackedBarRendererTest.trace org.jfree.chart.renderer.category.StackedBarRendererTest.testEquals:72:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StackedBarRendererTest/StackedBarRendererTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StackedBarRendererTest.trace org.jfree.chart.renderer.category.StackedBarRendererTest.testEquals:74:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StackedBarRendererTest/StackedBarRendererTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StackedBarRendererTest.trace org.jfree.chart.renderer.category.StackedBarRendererTest.testHashCode:84:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StackedBarRendererTest/StackedBarRendererTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StackedBarRendererTest.trace org.jfree.chart.renderer.category.StackedBarRendererTest.testHashCode:87:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StackedBarRendererTest/StackedBarRendererTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StackedBarRendererTest.trace org.jfree.chart.renderer.category.StackedBarRendererTest.testCloning:97:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StackedBarRendererTest/StackedBarRendererTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StackedBarRendererTest.trace org.jfree.chart.renderer.category.StackedBarRendererTest.testCloning:98:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StackedBarRendererTest/StackedBarRendererTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StackedBarRendererTest.trace org.jfree.chart.renderer.category.StackedBarRendererTest.testCloning:99:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StackedBarRendererTest/StackedBarRendererTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StackedBarRendererTest.trace org.jfree.chart.renderer.category.StackedBarRendererTest.testPublicCloneable:108:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StackedBarRendererTest/StackedBarRendererTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StackedBarRendererTest.trace org.jfree.chart.renderer.category.StackedBarRendererTest.testSerialization:119:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StackedBarRendererTest/StackedBarRendererTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StackedBarRendererTest.trace org.jfree.chart.renderer.category.StackedBarRendererTest.testFindRangeBounds:128:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StackedBarRendererTest/StackedBarRendererTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StackedBarRendererTest.trace org.jfree.chart.renderer.category.StackedBarRendererTest.testFindRangeBounds:132:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StackedBarRendererTest/StackedBarRendererTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StackedBarRendererTest.trace org.jfree.chart.renderer.category.StackedBarRendererTest.testFindRangeBounds:135:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StackedBarRendererTest/StackedBarRendererTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StackedBarRendererTest.trace org.jfree.chart.renderer.category.StackedBarRendererTest.testFindRangeBounds:138:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StackedBarRendererTest/StackedBarRendererTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StackedBarRendererTest.trace org.jfree.chart.renderer.category.StackedBarRendererTest.testFindRangeBounds:141:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StackedBarRendererTest/StackedBarRendererTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StackedBarRendererTest.trace org.jfree.chart.renderer.category.StackedBarRendererTest.testFindRangeBounds:144:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StackedBarRendererTest/StackedBarRendererTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StackedBarRendererTest.trace org.jfree.chart.renderer.category.StackedBarRendererTest.testFindRangeBounds:147:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StackedBarRendererTest/StackedBarRendererTest18.txt

#Total Asserts in org.jfree.chart.renderer.category/StackedBarRendererTest=============18
#Total Tests in org.jfree.chart.renderer.category/StackedBarRendererTest=============0
