#!/bin/bash

echo "computing slice for StatisticalLineAndShapeRendererTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/category_slices/StatisticalLineAndShapeRendererTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StatisticalLineAndShapeRendererTest.trace org.jfree.chart.renderer.category.StatisticalLineAndShapeRendererTest.testEquals:78:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StatisticalLineAndShapeRendererTest/StatisticalLineAndShapeRendererTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StatisticalLineAndShapeRendererTest.trace org.jfree.chart.renderer.category.StatisticalLineAndShapeRendererTest.testEquals:79:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StatisticalLineAndShapeRendererTest/StatisticalLineAndShapeRendererTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StatisticalLineAndShapeRendererTest.trace org.jfree.chart.renderer.category.StatisticalLineAndShapeRendererTest.testEquals:82:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StatisticalLineAndShapeRendererTest/StatisticalLineAndShapeRendererTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StatisticalLineAndShapeRendererTest.trace org.jfree.chart.renderer.category.StatisticalLineAndShapeRendererTest.testEquals:84:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StatisticalLineAndShapeRendererTest/StatisticalLineAndShapeRendererTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StatisticalLineAndShapeRendererTest.trace org.jfree.chart.renderer.category.StatisticalLineAndShapeRendererTest.testHashcode:96:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StatisticalLineAndShapeRendererTest/StatisticalLineAndShapeRendererTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StatisticalLineAndShapeRendererTest.trace org.jfree.chart.renderer.category.StatisticalLineAndShapeRendererTest.testHashcode:99:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StatisticalLineAndShapeRendererTest/StatisticalLineAndShapeRendererTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StatisticalLineAndShapeRendererTest.trace org.jfree.chart.renderer.category.StatisticalLineAndShapeRendererTest.testCloning:111:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StatisticalLineAndShapeRendererTest/StatisticalLineAndShapeRendererTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StatisticalLineAndShapeRendererTest.trace org.jfree.chart.renderer.category.StatisticalLineAndShapeRendererTest.testCloning:112:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StatisticalLineAndShapeRendererTest/StatisticalLineAndShapeRendererTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StatisticalLineAndShapeRendererTest.trace org.jfree.chart.renderer.category.StatisticalLineAndShapeRendererTest.testCloning:113:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StatisticalLineAndShapeRendererTest/StatisticalLineAndShapeRendererTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StatisticalLineAndShapeRendererTest.trace org.jfree.chart.renderer.category.StatisticalLineAndShapeRendererTest.testPublicCloneable:123:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StatisticalLineAndShapeRendererTest/StatisticalLineAndShapeRendererTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StatisticalLineAndShapeRendererTest.trace org.jfree.chart.renderer.category.StatisticalLineAndShapeRendererTest.testSerialization:135:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StatisticalLineAndShapeRendererTest/StatisticalLineAndShapeRendererTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StatisticalLineAndShapeRendererTest.trace org.jfree.chart.renderer.category.StatisticalLineAndShapeRendererTest.test1562759:168:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StatisticalLineAndShapeRendererTest/StatisticalLineAndShapeRendererTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StatisticalLineAndShapeRendererTest.trace org.jfree.chart.renderer.category.StatisticalLineAndShapeRendererTest.test1562759:169:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StatisticalLineAndShapeRendererTest/StatisticalLineAndShapeRendererTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StatisticalLineAndShapeRendererTest.trace org.jfree.chart.renderer.category.StatisticalLineAndShapeRendererTest.test1562759:172:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StatisticalLineAndShapeRendererTest/StatisticalLineAndShapeRendererTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StatisticalLineAndShapeRendererTest.trace org.jfree.chart.renderer.category.StatisticalLineAndShapeRendererTest.test1562759:173:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StatisticalLineAndShapeRendererTest/StatisticalLineAndShapeRendererTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StatisticalLineAndShapeRendererTest.trace org.jfree.chart.renderer.category.StatisticalLineAndShapeRendererTest.testFindRangeBounds:183:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StatisticalLineAndShapeRendererTest/StatisticalLineAndShapeRendererTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StatisticalLineAndShapeRendererTest.trace org.jfree.chart.renderer.category.StatisticalLineAndShapeRendererTest.testFindRangeBounds:188:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StatisticalLineAndShapeRendererTest/StatisticalLineAndShapeRendererTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StatisticalLineAndShapeRendererTest.trace org.jfree.chart.renderer.category.StatisticalLineAndShapeRendererTest.testFindRangeBounds:191:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StatisticalLineAndShapeRendererTest/StatisticalLineAndShapeRendererTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StatisticalLineAndShapeRendererTest.trace org.jfree.chart.renderer.category.StatisticalLineAndShapeRendererTest.testFindRangeBounds:194:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StatisticalLineAndShapeRendererTest/StatisticalLineAndShapeRendererTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StatisticalLineAndShapeRendererTest.trace org.jfree.chart.renderer.category.StatisticalLineAndShapeRendererTest.testFindRangeBounds:197:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StatisticalLineAndShapeRendererTest/StatisticalLineAndShapeRendererTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StatisticalLineAndShapeRendererTest.trace org.jfree.chart.renderer.category.StatisticalLineAndShapeRendererTest.testFindRangeBounds:200:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StatisticalLineAndShapeRendererTest/StatisticalLineAndShapeRendererTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/StatisticalLineAndShapeRendererTest.trace org.jfree.chart.renderer.category.StatisticalLineAndShapeRendererTest.testFindRangeBounds:204:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/StatisticalLineAndShapeRendererTest/StatisticalLineAndShapeRendererTest22.txt

#Total Asserts in org.jfree.chart.renderer.category/StatisticalLineAndShapeRendererTest=============22
#Total Tests in org.jfree.chart.renderer.category/StatisticalLineAndShapeRendererTest=============0
