#!/bin/bash

echo "computing slice for LevelRendererTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/category_slices/LevelRendererTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/LevelRendererTest.trace org.jfree.chart.renderer.category.LevelRendererTest.testEquals:71:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/LevelRendererTest/LevelRendererTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/LevelRendererTest.trace org.jfree.chart.renderer.category.LevelRendererTest.testEquals:72:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/LevelRendererTest/LevelRendererTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/LevelRendererTest.trace org.jfree.chart.renderer.category.LevelRendererTest.testEquals:75:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/LevelRendererTest/LevelRendererTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/LevelRendererTest.trace org.jfree.chart.renderer.category.LevelRendererTest.testEquals:77:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/LevelRendererTest/LevelRendererTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/LevelRendererTest.trace org.jfree.chart.renderer.category.LevelRendererTest.testEquals:80:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/LevelRendererTest/LevelRendererTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/LevelRendererTest.trace org.jfree.chart.renderer.category.LevelRendererTest.testEquals:82:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/LevelRendererTest/LevelRendererTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/LevelRendererTest.trace org.jfree.chart.renderer.category.LevelRendererTest.testHashcode:93:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/LevelRendererTest/LevelRendererTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/LevelRendererTest.trace org.jfree.chart.renderer.category.LevelRendererTest.testHashcode:96:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/LevelRendererTest/LevelRendererTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/LevelRendererTest.trace org.jfree.chart.renderer.category.LevelRendererTest.testCloning:108:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/LevelRendererTest/LevelRendererTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/LevelRendererTest.trace org.jfree.chart.renderer.category.LevelRendererTest.testCloning:109:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/LevelRendererTest/LevelRendererTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/LevelRendererTest.trace org.jfree.chart.renderer.category.LevelRendererTest.testCloning:110:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/LevelRendererTest/LevelRendererTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/LevelRendererTest.trace org.jfree.chart.renderer.category.LevelRendererTest.testCloning:112:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/LevelRendererTest/LevelRendererTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/LevelRendererTest.trace org.jfree.chart.renderer.category.LevelRendererTest.testPublicCloneable:122:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/LevelRendererTest/LevelRendererTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/LevelRendererTest.trace org.jfree.chart.renderer.category.LevelRendererTest.testSerialization:155:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/LevelRendererTest/LevelRendererTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/LevelRendererTest.trace org.jfree.chart.renderer.category.LevelRendererTest.testGetLegendItemSeriesIndex:198:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/LevelRendererTest/LevelRendererTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/LevelRendererTest.trace org.jfree.chart.renderer.category.LevelRendererTest.testGetLegendItemSeriesIndex:199:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/LevelRendererTest/LevelRendererTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/category_traces/LevelRendererTest.trace org.jfree.chart.renderer.category.LevelRendererTest.testGetLegendItemSeriesIndex:200:*>/home/stg/omc_experiments/slices/jfreechart/category_slices/LevelRendererTest/LevelRendererTest17.txt

#Total Asserts in org.jfree.chart.renderer.category/LevelRendererTest=============17
#Total Tests in org.jfree.chart.renderer.category/LevelRendererTest=============0
