#!/bin/bash

echo "computing slice for PathTrackingWriterTest"

mkdir -p /home/stg/omc_experiments/slices/xstream/path_slices/PathTrackingWriterTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/path_traces/PathTrackingWriterTest.trace com.thoughtworks.xstream.io.path.PathTrackingWriterTest.testDecoratesXmlWriterProxyingAllInvocations:42:*>/home/stg/omc_experiments/slices/xstream/path_slices/PathTrackingWriterTest/PathTrackingWriterTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/path_traces/PathTrackingWriterTest.trace com.thoughtworks.xstream.io.path.PathTrackingWriterTest.testInterceptsWhenWriterMovesLocationInDocumentAndUpdatesPathTracker:47:*>/home/stg/omc_experiments/slices/xstream/path_slices/PathTrackingWriterTest/PathTrackingWriterTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/path_traces/PathTrackingWriterTest.trace com.thoughtworks.xstream.io.path.PathTrackingWriterTest.testInterceptsWhenWriterMovesLocationInDocumentAndUpdatesPathTracker:50:*>/home/stg/omc_experiments/slices/xstream/path_slices/PathTrackingWriterTest/PathTrackingWriterTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/path_traces/PathTrackingWriterTest.trace com.thoughtworks.xstream.io.path.PathTrackingWriterTest.testInterceptsWhenWriterMovesLocationInDocumentAndUpdatesPathTracker:53:*>/home/stg/omc_experiments/slices/xstream/path_slices/PathTrackingWriterTest/PathTrackingWriterTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/path_traces/PathTrackingWriterTest.trace com.thoughtworks.xstream.io.path.PathTrackingWriterTest.testInterceptsWhenWriterMovesLocationInDocumentAndUpdatesPathTracker:56:*>/home/stg/omc_experiments/slices/xstream/path_slices/PathTrackingWriterTest/PathTrackingWriterTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/path_traces/PathTrackingWriterTest.trace com.thoughtworks.xstream.io.path.PathTrackingWriterTest.testInterceptsWhenWriterMovesLocationInDocumentAndUpdatesPathTracker:59:*>/home/stg/omc_experiments/slices/xstream/path_slices/PathTrackingWriterTest/PathTrackingWriterTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/path_traces/PathTrackingWriterTest.trace com.thoughtworks.xstream.io.path.PathTrackingWriterTest.testEncodesPathInTracker:63:*>/home/stg/omc_experiments/slices/xstream/path_slices/PathTrackingWriterTest/PathTrackingWriterTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/path_traces/PathTrackingWriterTest.trace com.thoughtworks.xstream.io.path.PathTrackingWriterTest.testEncodesPathInTracker:66:*>/home/stg/omc_experiments/slices/xstream/path_slices/PathTrackingWriterTest/PathTrackingWriterTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/path_traces/PathTrackingWriterTest.trace com.thoughtworks.xstream.io.path.PathTrackingWriterTest.testEncodesPathInTracker:69:*>/home/stg/omc_experiments/slices/xstream/path_slices/PathTrackingWriterTest/PathTrackingWriterTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/path_traces/PathTrackingWriterTest.trace com.thoughtworks.xstream.io.path.PathTrackingWriterTest.testEncodesPathInTracker:70:*>/home/stg/omc_experiments/slices/xstream/path_slices/PathTrackingWriterTest/PathTrackingWriterTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/path_traces/PathTrackingWriterTest.trace com.thoughtworks.xstream.io.path.PathTrackingWriterTest.testEncodesPathInTracker:73:*>/home/stg/omc_experiments/slices/xstream/path_slices/PathTrackingWriterTest/PathTrackingWriterTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/xstream/path_traces/PathTrackingWriterTest.trace com.thoughtworks.xstream.io.path.PathTrackingWriterTest.testEncodesPathInTracker:76:*>/home/stg/omc_experiments/slices/xstream/path_slices/PathTrackingWriterTest/PathTrackingWriterTest12.txt

#Total Asserts in com.thoughtworks.xstream.io.path/PathTrackingWriterTest=============12
#Total Tests in com.thoughtworks.xstream.io.path/PathTrackingWriterTest=============0
