#!/bin/bash

echo "computing slice for TestPreciseDurationField"

mkdir -p /home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getType:99:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getName:103:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_isSupported:107:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_isPrecise:111:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getUnitMillis:115:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_toString:119:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getValue_long:124:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getValue_long:125:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getValue_long:126:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getValue_long:127:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getValueAsLong_long:135:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getValueAsLong_long:136:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getValueAsLong_long:137:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getValueAsLong_long:138:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField14.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getValue_long_long:142:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField15.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getValue_long_long:143:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField16.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getValue_long_long:144:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField17.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getValue_long_long:145:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField18.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getValueAsLong_long_long:153:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField19.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getValueAsLong_long_long:154:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField20.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getValueAsLong_long_long:155:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField21.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getValueAsLong_long_long:156:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField22.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getMillis_int:161:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField23.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getMillis_int:162:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField24.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getMillis_int:163:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField25.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getMillis_int:164:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField26.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getMillis_long:168:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField27.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getMillis_long:169:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField28.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getMillis_long:170:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField29.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getMillis_int_long:178:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField30.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getMillis_int_long:179:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField31.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getMillis_int_long:180:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField32.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getMillis_int_long:181:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField33.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getMillis_long_long:185:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField34.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getMillis_long_long:186:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField35.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getMillis_long_long:187:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField36.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_add_long_int:196:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField37.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_add_long_int:197:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField38.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_add_long_int:198:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField39.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_add_long_long:206:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField40.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_add_long_long:207:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField41.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_add_long_long:208:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField42.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getDifference_long_int:221:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField43.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getDifference_long_int:222:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField44.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getDifference_long_int:223:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField45.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getDifference_long_int:224:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField46.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getDifferenceAsLong_long_long:232:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField47.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getDifferenceAsLong_long_long:233:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField48.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getDifferenceAsLong_long_long:234:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField49.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_getDifferenceAsLong_long_long:235:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField50.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_equals:244:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField51.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_equals:245:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField52.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_equals:247:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField53.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_equals:249:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField54.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_equals:251:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField55.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_equals:252:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField56.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_equals:253:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField57.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_hashCode:257:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField58.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_hashCode:258:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField59.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_hashCode:260:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField60.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_hashCode:262:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField61.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_hashCode:264:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField62.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_compareTo:269:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField63.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_compareTo:270:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField64.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.test_compareTo:272:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField65.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestPreciseDurationField.trace org.joda.time.field.TestPreciseDurationField.testSerialization:298:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestPreciseDurationField/TestPreciseDurationField66.txt

#Total Asserts in org.joda.time.field/TestPreciseDurationField=============66
#Total Tests in org.joda.time.field/TestPreciseDurationField=============0
