#!/bin/bash

echo "computing slice for TestMillisDurationField"

mkdir -p /home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getType:80:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getName:84:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_isSupported:88:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_isPrecise:92:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getUnitMillis:96:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_toString:100:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getValue_long:105:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getValue_long:106:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getValue_long:107:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getValueAsLong_long:115:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getValueAsLong_long:116:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getValueAsLong_long:117:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getValueAsLong_long:118:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getValue_long_long:122:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField14.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getValue_long_long:123:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField15.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getValue_long_long:124:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField16.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getValueAsLong_long_long:132:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField17.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getValueAsLong_long_long:133:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField18.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getValueAsLong_long_long:134:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField19.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getValueAsLong_long_long:135:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField20.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getMillis_int:140:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField21.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getMillis_int:141:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField22.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getMillis_int:142:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField23.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getMillis_long:146:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField24.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getMillis_long:147:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField25.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getMillis_long:148:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField26.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getMillis_int_long:152:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField27.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getMillis_int_long:153:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField28.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getMillis_int_long:154:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField29.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getMillis_long_long:158:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField30.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getMillis_long_long:159:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField31.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getMillis_long_long:160:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField32.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_add_long_int:165:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField33.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_add_long_int:166:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField34.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_add_long_int:167:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField35.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_add_long_long:175:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField36.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_add_long_long:176:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField37.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_add_long_long:177:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField38.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getDifference_long_int:186:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField39.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getDifference_long_int:187:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField40.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getDifference_long_int:188:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField41.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getDifferenceAsLong_long_long:196:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField42.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getDifferenceAsLong_long_long:197:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField43.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_getDifferenceAsLong_long_long:198:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField44.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_compareTo:207:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField45.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_compareTo:208:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField46.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.test_compareTo:210:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField47.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/field_traces/TestMillisDurationField.trace org.joda.time.field.TestMillisDurationField.testSerialization:236:*>/home/stg/omc_experiments/slices/fse-joda-time/field_slices/TestMillisDurationField/TestMillisDurationField48.txt

#Total Asserts in org.joda.time.field/TestMillisDurationField=============48
#Total Tests in org.joda.time.field/TestMillisDurationField=============0
