#!/bin/bash

echo "computing slice for RelativeDateFormatTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/util_traces/RelativeDateFormatTest.trace org.jfree.chart.util.RelativeDateFormatTest.testFormat:88:*>/home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest/RelativeDateFormatTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/util_traces/RelativeDateFormatTest.trace org.jfree.chart.util.RelativeDateFormatTest.test2033092:119:*>/home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest/RelativeDateFormatTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/util_traces/RelativeDateFormatTest.trace org.jfree.chart.util.RelativeDateFormatTest.testEquals:129:*>/home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest/RelativeDateFormatTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/util_traces/RelativeDateFormatTest.trace org.jfree.chart.util.RelativeDateFormatTest.testEquals:132:*>/home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest/RelativeDateFormatTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/util_traces/RelativeDateFormatTest.trace org.jfree.chart.util.RelativeDateFormatTest.testEquals:134:*>/home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest/RelativeDateFormatTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/util_traces/RelativeDateFormatTest.trace org.jfree.chart.util.RelativeDateFormatTest.testEquals:137:*>/home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest/RelativeDateFormatTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/util_traces/RelativeDateFormatTest.trace org.jfree.chart.util.RelativeDateFormatTest.testEquals:139:*>/home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest/RelativeDateFormatTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/util_traces/RelativeDateFormatTest.trace org.jfree.chart.util.RelativeDateFormatTest.testEquals:142:*>/home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest/RelativeDateFormatTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/util_traces/RelativeDateFormatTest.trace org.jfree.chart.util.RelativeDateFormatTest.testEquals:144:*>/home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest/RelativeDateFormatTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/util_traces/RelativeDateFormatTest.trace org.jfree.chart.util.RelativeDateFormatTest.testEquals:147:*>/home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest/RelativeDateFormatTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/util_traces/RelativeDateFormatTest.trace org.jfree.chart.util.RelativeDateFormatTest.testEquals:149:*>/home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest/RelativeDateFormatTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/util_traces/RelativeDateFormatTest.trace org.jfree.chart.util.RelativeDateFormatTest.testEquals:152:*>/home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest/RelativeDateFormatTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/util_traces/RelativeDateFormatTest.trace org.jfree.chart.util.RelativeDateFormatTest.testEquals:154:*>/home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest/RelativeDateFormatTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/util_traces/RelativeDateFormatTest.trace org.jfree.chart.util.RelativeDateFormatTest.testEquals:157:*>/home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest/RelativeDateFormatTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/util_traces/RelativeDateFormatTest.trace org.jfree.chart.util.RelativeDateFormatTest.testEquals:159:*>/home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest/RelativeDateFormatTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/util_traces/RelativeDateFormatTest.trace org.jfree.chart.util.RelativeDateFormatTest.testEquals:162:*>/home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest/RelativeDateFormatTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/util_traces/RelativeDateFormatTest.trace org.jfree.chart.util.RelativeDateFormatTest.testEquals:164:*>/home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest/RelativeDateFormatTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/util_traces/RelativeDateFormatTest.trace org.jfree.chart.util.RelativeDateFormatTest.testEquals:167:*>/home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest/RelativeDateFormatTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/util_traces/RelativeDateFormatTest.trace org.jfree.chart.util.RelativeDateFormatTest.testEquals:169:*>/home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest/RelativeDateFormatTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/util_traces/RelativeDateFormatTest.trace org.jfree.chart.util.RelativeDateFormatTest.testEquals:172:*>/home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest/RelativeDateFormatTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/util_traces/RelativeDateFormatTest.trace org.jfree.chart.util.RelativeDateFormatTest.testEquals:174:*>/home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest/RelativeDateFormatTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/util_traces/RelativeDateFormatTest.trace org.jfree.chart.util.RelativeDateFormatTest.testEquals:177:*>/home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest/RelativeDateFormatTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/util_traces/RelativeDateFormatTest.trace org.jfree.chart.util.RelativeDateFormatTest.testEquals:179:*>/home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest/RelativeDateFormatTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/util_traces/RelativeDateFormatTest.trace org.jfree.chart.util.RelativeDateFormatTest.testHashCode:189:*>/home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest/RelativeDateFormatTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/util_traces/RelativeDateFormatTest.trace org.jfree.chart.util.RelativeDateFormatTest.testHashCode:192:*>/home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest/RelativeDateFormatTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/util_traces/RelativeDateFormatTest.trace org.jfree.chart.util.RelativeDateFormatTest.testCloning:205:*>/home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest/RelativeDateFormatTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/util_traces/RelativeDateFormatTest.trace org.jfree.chart.util.RelativeDateFormatTest.testCloning:206:*>/home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest/RelativeDateFormatTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/util_traces/RelativeDateFormatTest.trace org.jfree.chart.util.RelativeDateFormatTest.testCloning:207:*>/home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest/RelativeDateFormatTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/util_traces/RelativeDateFormatTest.trace org.jfree.chart.util.RelativeDateFormatTest.testCloning:211:*>/home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest/RelativeDateFormatTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/util_traces/RelativeDateFormatTest.trace org.jfree.chart.util.RelativeDateFormatTest.testNegative:222:*>/home/stg/omc_experiments/slices/jfreechart/util_slices/RelativeDateFormatTest/RelativeDateFormatTest30.txt

#Total Asserts in org.jfree.chart.util/RelativeDateFormatTest=============30
#Total Tests in org.jfree.chart.util/RelativeDateFormatTest=============0
