#!/bin/bash

echo "computing slice for LineOrientedInterpolatingReaderTest"

mkdir -p /home/stg/omc_experiments/slices/plexus-utils/util_slices/LineOrientedInterpolatingReaderTest

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/LineOrientedInterpolatingReaderTest.trace org.codehaus.plexus.util.LineOrientedInterpolatingReaderTest.testShouldInterpolateExpressionAtEndOfDataWithInvalidEndToken:71:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/LineOrientedInterpolatingReaderTest/LineOrientedInterpolatingReaderTest1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/LineOrientedInterpolatingReaderTest.trace org.codehaus.plexus.util.LineOrientedInterpolatingReaderTest.testDefaultInterpolationWithNonInterpolatedValueAtEnd:87:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/LineOrientedInterpolatingReaderTest/LineOrientedInterpolatingReaderTest2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/LineOrientedInterpolatingReaderTest.trace org.codehaus.plexus.util.LineOrientedInterpolatingReaderTest.testDefaultInterpolationWithEscapedExpression:111:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/LineOrientedInterpolatingReaderTest/LineOrientedInterpolatingReaderTest3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/LineOrientedInterpolatingReaderTest.trace org.codehaus.plexus.util.LineOrientedInterpolatingReaderTest.testDefaultInterpolationWithInterpolatedValueAtEnd:127:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/LineOrientedInterpolatingReaderTest/LineOrientedInterpolatingReaderTest4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/LineOrientedInterpolatingReaderTest.trace org.codehaus.plexus.util.LineOrientedInterpolatingReaderTest.testInterpolationWithSpecifiedBoundaryTokens:144:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/LineOrientedInterpolatingReaderTest/LineOrientedInterpolatingReaderTest5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/LineOrientedInterpolatingReaderTest.trace org.codehaus.plexus.util.LineOrientedInterpolatingReaderTest.testInterpolationWithSpecifiedBoundaryTokensWithNonInterpolatedValueAtEnd:161:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/LineOrientedInterpolatingReaderTest/LineOrientedInterpolatingReaderTest6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/LineOrientedInterpolatingReaderTest.trace org.codehaus.plexus.util.LineOrientedInterpolatingReaderTest.testInterpolationWithSpecifiedBoundaryTokensWithInterpolatedValueAtEnd:178:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/LineOrientedInterpolatingReaderTest/LineOrientedInterpolatingReaderTest7.txt

#Total Asserts in org.codehaus.plexus.util/LineOrientedInterpolatingReaderTest=============7
#Total Tests in org.codehaus.plexus.util/LineOrientedInterpolatingReaderTest=============0
