#!/bin/bash

echo "computing slice for InterpolationFilterReaderTest"

mkdir -p /home/stg/omc_experiments/slices/plexus-utils/util_slices/InterpolationFilterReaderTest

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/InterpolationFilterReaderTest.trace org.codehaus.plexus.util.InterpolationFilterReaderTest.testShouldNotInterpolateExpressionAtEndOfDataWithInvalidEndToken:40:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/InterpolationFilterReaderTest/InterpolationFilterReaderTest1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/InterpolationFilterReaderTest.trace org.codehaus.plexus.util.InterpolationFilterReaderTest.testShouldNotInterpolateExpressionWithMissingEndToken:54:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/InterpolationFilterReaderTest/InterpolationFilterReaderTest2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/InterpolationFilterReaderTest.trace org.codehaus.plexus.util.InterpolationFilterReaderTest.testShouldNotInterpolateWithMalformedStartToken:65:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/InterpolationFilterReaderTest/InterpolationFilterReaderTest3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/InterpolationFilterReaderTest.trace org.codehaus.plexus.util.InterpolationFilterReaderTest.testShouldNotInterpolateWithMalformedEndToken:76:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/InterpolationFilterReaderTest/InterpolationFilterReaderTest4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/InterpolationFilterReaderTest.trace org.codehaus.plexus.util.InterpolationFilterReaderTest.testInterpolationWithMulticharDelimiters:87:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/InterpolationFilterReaderTest/InterpolationFilterReaderTest5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/InterpolationFilterReaderTest.trace org.codehaus.plexus.util.InterpolationFilterReaderTest.testDefaultInterpolationWithNonInterpolatedValueAtEnd:99:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/InterpolationFilterReaderTest/InterpolationFilterReaderTest6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/InterpolationFilterReaderTest.trace org.codehaus.plexus.util.InterpolationFilterReaderTest.testDefaultInterpolationWithInterpolatedValueAtEnd:111:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/InterpolationFilterReaderTest/InterpolationFilterReaderTest7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/InterpolationFilterReaderTest.trace org.codehaus.plexus.util.InterpolationFilterReaderTest.testInterpolationWithSpecifiedBoundaryTokens:123:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/InterpolationFilterReaderTest/InterpolationFilterReaderTest8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/InterpolationFilterReaderTest.trace org.codehaus.plexus.util.InterpolationFilterReaderTest.testInterpolationWithSpecifiedBoundaryTokensWithNonInterpolatedValueAtEnd:135:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/InterpolationFilterReaderTest/InterpolationFilterReaderTest9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/InterpolationFilterReaderTest.trace org.codehaus.plexus.util.InterpolationFilterReaderTest.testInterpolationWithSpecifiedBoundaryTokensWithInterpolatedValueAtEnd:147:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/InterpolationFilterReaderTest/InterpolationFilterReaderTest10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/InterpolationFilterReaderTest.trace org.codehaus.plexus.util.InterpolationFilterReaderTest.testInterpolationWithSpecifiedBoundaryTokensAndAdditionalTokenCharacter:159:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/InterpolationFilterReaderTest/InterpolationFilterReaderTest11.txt

#Total Asserts in org.codehaus.plexus.util/InterpolationFilterReaderTest=============11
#Total Tests in org.codehaus.plexus.util/InterpolationFilterReaderTest=============0
