#!/bin/bash

echo "computing slice for CollectionUtilsTest"

mkdir -p /home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testMergeMaps:51:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testMergeMaps:54:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testMergeMaps:55:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testMergeMaps:56:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testMergeMaps:57:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testMergeMaps:58:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testMergeMaps:59:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testMergeMaps:60:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testMergeMaps:61:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testMergeMaps:62:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testMergeMapArray:71:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testMergeMapArray:79:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testMergeMapArray:88:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testMergeMapArray:89:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest14.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testMergeMapArray:94:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest15.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testMergeMapArray:95:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest16.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testMergeMapArray:105:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest17.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testMergeMapArray:106:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest18.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testMergeMapArray:107:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest19.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testMergeMapArray:112:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest20.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testMergeMapArray:113:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest21.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testMergeMapArray:114:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest22.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testMavenPropertiesLoading:159:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest23.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testMavenPropertiesLoading:162:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest24.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testMavenPropertiesLoading:163:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest25.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testMavenPropertiesLoading:164:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest26.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testMavenPropertiesLoading:167:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest27.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testMavenPropertiesLoading:170:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest28.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testIteratorToListWithAPopulatedList:183:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest29.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testIteratorToListWithAPopulatedList:185:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest30.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testIteratorToListWithAPopulatedList:187:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest31.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testIteratorToListWithAPopulatedList:188:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest32.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testIteratorToListWithAPopulatedList:189:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest33.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testIteratorToListWithAEmptyList:198:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest34.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/CollectionUtilsTest.trace org.codehaus.plexus.util.CollectionUtilsTest.testIteratorToListWithAEmptyList:200:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/CollectionUtilsTest/CollectionUtilsTest35.txt

#Total Asserts in org.codehaus.plexus.util/CollectionUtilsTest=============35
#Total Tests in org.codehaus.plexus.util/CollectionUtilsTest=============0
