#!/bin/bash

echo "computing slice for OsTest"

mkdir -p /home/stg/omc_experiments/slices/plexus-utils/util_slices/OsTest

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/OsTest.trace org.codehaus.plexus.util.OsTest.testUndefinedFamily:31:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/OsTest/OsTest1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/OsTest.trace org.codehaus.plexus.util.OsTest.testOs:53:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/OsTest/OsTest2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/OsTest.trace org.codehaus.plexus.util.OsTest.testOs:56:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/OsTest/OsTest3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/OsTest.trace org.codehaus.plexus.util.OsTest.testOs:57:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/OsTest/OsTest4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/OsTest.trace org.codehaus.plexus.util.OsTest.testOs:60:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/OsTest/OsTest5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/OsTest.trace org.codehaus.plexus.util.OsTest.testOs:63:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/OsTest/OsTest6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/OsTest.trace org.codehaus.plexus.util.OsTest.testOs:66:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/OsTest/OsTest7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/OsTest.trace org.codehaus.plexus.util.OsTest.testOs:69:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/OsTest/OsTest8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/OsTest.trace org.codehaus.plexus.util.OsTest.testOs:70:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/OsTest/OsTest9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/OsTest.trace org.codehaus.plexus.util.OsTest.testOs:73:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/OsTest/OsTest10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/OsTest.trace org.codehaus.plexus.util.OsTest.testOs:74:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/OsTest/OsTest11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/OsTest.trace org.codehaus.plexus.util.OsTest.testValidList:79:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/OsTest/OsTest12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/OsTest.trace org.codehaus.plexus.util.OsTest.testValidList:81:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/OsTest/OsTest13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/OsTest.trace org.codehaus.plexus.util.OsTest.testValidList:82:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/OsTest/OsTest14.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/OsTest.trace org.codehaus.plexus.util.OsTest.testValidList:83:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/OsTest/OsTest15.txt

#Total Asserts in org.codehaus.plexus.util/OsTest=============15
#Total Tests in org.codehaus.plexus.util/OsTest=============0
