#!/bin/bash

echo "computing slice for DirectoryScannerTest"

mkdir -p /home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testCrossPlatformIncludesString:59:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testCrossPlatformExcludesString:84:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testGeneral:123:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testGeneral:124:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testGeneral:125:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testGeneral:126:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testIncludesExcludesWithWhiteSpaces:141:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testIncludesExcludesWithWhiteSpaces:142:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testIncludesExcludesWithWhiteSpaces:143:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testIncludesExcludesWithWhiteSpaces:144:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testFollowSymlinksFalse:155:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testFollowSymlinksFalse:157:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testFollowSymlinksFalse:158:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testFollowSymlinksFalse:159:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest14.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testFollowSymlinksFalse:160:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest15.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testFollowSymlinksFalse:161:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest16.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testFollowSymlinksFalse:162:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest17.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.assertAlwaysIncluded:167:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest18.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.assertAlwaysIncluded:168:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest19.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.assertAlwaysIncluded:169:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest20.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.assertAlwaysIncluded:170:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest21.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.assertAlwaysIncluded:171:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest22.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.assertAlwaysIncluded:172:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest23.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.assertAlwaysIncluded:173:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest24.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.assertAlwaysIncluded:174:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest25.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.assertAlwaysIncluded:175:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest26.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testFollowSymlinks:186:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest27.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testFollowSymlinks:187:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest28.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testFollowSymlinks:188:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest29.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testFollowSymlinks:191:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest30.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testFollowSymlinks:192:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest31.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testFollowSymlinks:193:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest32.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testFollowSymlinks:194:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest33.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testFollowSymlinks:195:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest34.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testFollowSymlinks:196:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest35.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testDirectoriesWithHyphens:229:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest36.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testIsSymbolicLink:419:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest37.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testIsSymbolicLink:420:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest38.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testIsSymbolicLink:421:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest39.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testIsSymbolicLink:422:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest40.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testIsParentSymbolicLink:436:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest41.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testIsParentSymbolicLink:437:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest42.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testIsParentSymbolicLink:438:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest43.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testIsParentSymbolicLink:439:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest44.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testIsParentSymbolicLink:440:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest45.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testIsParentSymbolicLink:441:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest46.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/DirectoryScannerTest.trace org.codehaus.plexus.util.DirectoryScannerTest.testIsParentSymbolicLink:442:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/DirectoryScannerTest/DirectoryScannerTest47.txt

#Total Asserts in org.codehaus.plexus.util/DirectoryScannerTest=============47
#Total Tests in org.codehaus.plexus.util/DirectoryScannerTest=============0
