#!/bin/bash

echo "computing slice for PathToolTest"

mkdir -p /home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativePath:34:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativePath:35:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativePath:36:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativePath:37:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativePath:38:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativePath:39:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetDirectoryComponent:48:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetDirectoryComponent:49:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetDirectoryComponent:50:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetDirectoryComponent:51:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testCalculateLink:60:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testCalculateLink:61:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testCalculateLink:63:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testCalculateLink:65:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest14.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testCalculateLink:67:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest15.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativeWebPath:77:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest16.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativeWebPath:78:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest17.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativeWebPath:79:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest18.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativeWebPath:80:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest19.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativeWebPath:83:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest20.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativeFilePath:111:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest21.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativeFilePath:112:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest22.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativeFilePath:113:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest23.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativeFilePath:114:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest24.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativeFilePath:115:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest25.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativeFilePath:116:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest26.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativeFilePath:117:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest27.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativeFilePath:119:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest28.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativeFilePath:120:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest29.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativeFilePath:121:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest30.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativeFilePath:122:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest31.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativeFilePath:96:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest32.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativeFilePath:97:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest33.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativeFilePath:98:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest34.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativeFilePath:99:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest35.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativeFilePath:100:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest36.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativeFilePath:101:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest37.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativeFilePath:102:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest38.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativeFilePath:104:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest39.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativeFilePath:105:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest40.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativeFilePath:106:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest41.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/plexus-utils/util_traces/PathToolTest.trace org.codehaus.plexus.util.PathToolTest.testGetRelativeFilePath:107:*>/home/stg/omc_experiments/slices/plexus-utils/util_slices/PathToolTest/PathToolTest42.txt

#Total Asserts in org.codehaus.plexus.util/PathToolTest=============42
#Total Tests in org.codehaus.plexus.util/PathToolTest=============0
