#!/bin/bash

echo "computing slice for CustomCategoryURLGeneratorTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/urls_slices/CustomCategoryURLGeneratorTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/urls_traces/CustomCategoryURLGeneratorTest.trace org.jfree.chart.urls.CustomCategoryURLGeneratorTest.testEquals:66:*>/home/stg/omc_experiments/slices/jfreechart/urls_slices/CustomCategoryURLGeneratorTest/CustomCategoryURLGeneratorTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/urls_traces/CustomCategoryURLGeneratorTest.trace org.jfree.chart.urls.CustomCategoryURLGeneratorTest.testEquals:72:*>/home/stg/omc_experiments/slices/jfreechart/urls_slices/CustomCategoryURLGeneratorTest/CustomCategoryURLGeneratorTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/urls_traces/CustomCategoryURLGeneratorTest.trace org.jfree.chart.urls.CustomCategoryURLGeneratorTest.testEquals:78:*>/home/stg/omc_experiments/slices/jfreechart/urls_slices/CustomCategoryURLGeneratorTest/CustomCategoryURLGeneratorTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/urls_traces/CustomCategoryURLGeneratorTest.trace org.jfree.chart.urls.CustomCategoryURLGeneratorTest.testCloning:93:*>/home/stg/omc_experiments/slices/jfreechart/urls_slices/CustomCategoryURLGeneratorTest/CustomCategoryURLGeneratorTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/urls_traces/CustomCategoryURLGeneratorTest.trace org.jfree.chart.urls.CustomCategoryURLGeneratorTest.testCloning:94:*>/home/stg/omc_experiments/slices/jfreechart/urls_slices/CustomCategoryURLGeneratorTest/CustomCategoryURLGeneratorTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/urls_traces/CustomCategoryURLGeneratorTest.trace org.jfree.chart.urls.CustomCategoryURLGeneratorTest.testCloning:95:*>/home/stg/omc_experiments/slices/jfreechart/urls_slices/CustomCategoryURLGeneratorTest/CustomCategoryURLGeneratorTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/urls_traces/CustomCategoryURLGeneratorTest.trace org.jfree.chart.urls.CustomCategoryURLGeneratorTest.testCloning:101:*>/home/stg/omc_experiments/slices/jfreechart/urls_slices/CustomCategoryURLGeneratorTest/CustomCategoryURLGeneratorTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/urls_traces/CustomCategoryURLGeneratorTest.trace org.jfree.chart.urls.CustomCategoryURLGeneratorTest.testCloning:103:*>/home/stg/omc_experiments/slices/jfreechart/urls_slices/CustomCategoryURLGeneratorTest/CustomCategoryURLGeneratorTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/urls_traces/CustomCategoryURLGeneratorTest.trace org.jfree.chart.urls.CustomCategoryURLGeneratorTest.testPublicCloneable:112:*>/home/stg/omc_experiments/slices/jfreechart/urls_slices/CustomCategoryURLGeneratorTest/CustomCategoryURLGeneratorTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/urls_traces/CustomCategoryURLGeneratorTest.trace org.jfree.chart.urls.CustomCategoryURLGeneratorTest.testSerialization:136:*>/home/stg/omc_experiments/slices/jfreechart/urls_slices/CustomCategoryURLGeneratorTest/CustomCategoryURLGeneratorTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/urls_traces/CustomCategoryURLGeneratorTest.trace org.jfree.chart.urls.CustomCategoryURLGeneratorTest.testAddURLSeries:148:*>/home/stg/omc_experiments/slices/jfreechart/urls_slices/CustomCategoryURLGeneratorTest/CustomCategoryURLGeneratorTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/urls_traces/CustomCategoryURLGeneratorTest.trace org.jfree.chart.urls.CustomCategoryURLGeneratorTest.testAddURLSeries:149:*>/home/stg/omc_experiments/slices/jfreechart/urls_slices/CustomCategoryURLGeneratorTest/CustomCategoryURLGeneratorTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/urls_traces/CustomCategoryURLGeneratorTest.trace org.jfree.chart.urls.CustomCategoryURLGeneratorTest.testAddURLSeries:154:*>/home/stg/omc_experiments/slices/jfreechart/urls_slices/CustomCategoryURLGeneratorTest/CustomCategoryURLGeneratorTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/urls_traces/CustomCategoryURLGeneratorTest.trace org.jfree.chart.urls.CustomCategoryURLGeneratorTest.testAddURLSeries:155:*>/home/stg/omc_experiments/slices/jfreechart/urls_slices/CustomCategoryURLGeneratorTest/CustomCategoryURLGeneratorTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/urls_traces/CustomCategoryURLGeneratorTest.trace org.jfree.chart.urls.CustomCategoryURLGeneratorTest.testAddURLSeries:156:*>/home/stg/omc_experiments/slices/jfreechart/urls_slices/CustomCategoryURLGeneratorTest/CustomCategoryURLGeneratorTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/urls_traces/CustomCategoryURLGeneratorTest.trace org.jfree.chart.urls.CustomCategoryURLGeneratorTest.testAddURLSeries:157:*>/home/stg/omc_experiments/slices/jfreechart/urls_slices/CustomCategoryURLGeneratorTest/CustomCategoryURLGeneratorTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/urls_traces/CustomCategoryURLGeneratorTest.trace org.jfree.chart.urls.CustomCategoryURLGeneratorTest.testAddURLSeries:162:*>/home/stg/omc_experiments/slices/jfreechart/urls_slices/CustomCategoryURLGeneratorTest/CustomCategoryURLGeneratorTest17.txt

#Total Asserts in org.jfree.chart.urls/CustomCategoryURLGeneratorTest=============17
#Total Tests in org.jfree.chart.urls/CustomCategoryURLGeneratorTest=============0
