#!/bin/bash

echo "computing slice for InheritanceUtilsTest"

mkdir -p /home/stg/omc_experiments/slices/fse-commons-lang-3.6/reflect_slices/InheritanceUtilsTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/reflect_traces/InheritanceUtilsTest.trace org.apache.commons.lang3.reflect.InheritanceUtilsTest.testConstructor:48:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/reflect_slices/InheritanceUtilsTest/InheritanceUtilsTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/reflect_traces/InheritanceUtilsTest.trace org.apache.commons.lang3.reflect.InheritanceUtilsTest.testDistanceGreaterThanZero:53:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/reflect_slices/InheritanceUtilsTest/InheritanceUtilsTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/reflect_traces/InheritanceUtilsTest.trace org.apache.commons.lang3.reflect.InheritanceUtilsTest.testDistanceGreaterThanZero:54:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/reflect_slices/InheritanceUtilsTest/InheritanceUtilsTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/reflect_traces/InheritanceUtilsTest.trace org.apache.commons.lang3.reflect.InheritanceUtilsTest.testDistanceGreaterThanZero:55:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/reflect_slices/InheritanceUtilsTest/InheritanceUtilsTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/reflect_traces/InheritanceUtilsTest.trace org.apache.commons.lang3.reflect.InheritanceUtilsTest.testDistanceGreaterThanZero:56:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/reflect_slices/InheritanceUtilsTest/InheritanceUtilsTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/reflect_traces/InheritanceUtilsTest.trace org.apache.commons.lang3.reflect.InheritanceUtilsTest.testDistanceEqual:61:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/reflect_slices/InheritanceUtilsTest/InheritanceUtilsTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/reflect_traces/InheritanceUtilsTest.trace org.apache.commons.lang3.reflect.InheritanceUtilsTest.testDistanceEqualObject:66:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/reflect_slices/InheritanceUtilsTest/InheritanceUtilsTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/reflect_traces/InheritanceUtilsTest.trace org.apache.commons.lang3.reflect.InheritanceUtilsTest.testDistanceNullChild:71:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/reflect_slices/InheritanceUtilsTest/InheritanceUtilsTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/reflect_traces/InheritanceUtilsTest.trace org.apache.commons.lang3.reflect.InheritanceUtilsTest.testDistanceNullParent:76:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/reflect_slices/InheritanceUtilsTest/InheritanceUtilsTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/reflect_traces/InheritanceUtilsTest.trace org.apache.commons.lang3.reflect.InheritanceUtilsTest.testDistanceNullParentNullChild:81:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/reflect_slices/InheritanceUtilsTest/InheritanceUtilsTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/reflect_traces/InheritanceUtilsTest.trace org.apache.commons.lang3.reflect.InheritanceUtilsTest.testDistanceDisjoint:86:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/reflect_slices/InheritanceUtilsTest/InheritanceUtilsTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/reflect_traces/InheritanceUtilsTest.trace org.apache.commons.lang3.reflect.InheritanceUtilsTest.testDistanceReverseParentChild:91:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/reflect_slices/InheritanceUtilsTest/InheritanceUtilsTest12.txt

#Total Asserts in org.apache.commons.lang3.reflect/InheritanceUtilsTest=============12
#Total Tests in org.apache.commons.lang3.reflect/InheritanceUtilsTest=============0
