#!/bin/bash

echo "computing slice for MutableLongTest"

mkdir -p /home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testConstructors:61:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testConstructors:63:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testConstructors:65:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testConstructors:66:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testConstructors:68:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testGetSet:80:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testGetSet:81:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testGetSet:84:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testGetSet:85:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testGetSet:88:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testGetSet:89:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testGetSet:92:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testGetSet:93:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testEquals:108:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testEquals:109:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testEquals:110:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testEquals:111:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testEquals:112:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testEquals:113:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testEquals:114:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testEquals:115:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testEquals:116:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testEquals:117:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testHashCode:126:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testHashCode:127:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testHashCode:128:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testHashCode:129:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testCompareTo:136:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testCompareTo:137:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testCompareTo:138:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testPrimitiveValues:151:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testPrimitiveValues:152:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest32.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testPrimitiveValues:153:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest33.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testPrimitiveValues:154:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest34.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testPrimitiveValues:155:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest35.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testPrimitiveValues:156:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest36.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testToLong:161:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest37.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testToLong:162:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest38.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testIncrement:170:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest39.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testIncrement:171:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest40.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testIncrementAndGet:179:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest41.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testIncrementAndGet:180:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest42.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testIncrementAndGet:181:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest43.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testGetAndIncrement:189:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest44.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testGetAndIncrement:190:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest45.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testGetAndIncrement:191:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest46.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testDecrement:199:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest47.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testDecrement:200:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest48.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testDecrementAndGet:208:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest49.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testDecrementAndGet:209:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest50.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testDecrementAndGet:210:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest51.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testGetAndDecrement:218:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest52.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testGetAndDecrement:219:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest53.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testGetAndDecrement:220:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest54.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testAddValuePrimitive:228:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest55.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testAddValuePrimitive:229:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest56.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testAddValueObject:237:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest57.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testAddValueObject:238:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest58.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testGetAndAddValuePrimitive:246:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest59.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testGetAndAddValuePrimitive:247:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest60.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testGetAndAddValueObject:255:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest61.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testGetAndAddValueObject:256:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest62.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testAddAndGetValuePrimitive:264:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest63.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testAddAndGetValuePrimitive:265:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest64.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testAddAndGetValueObject:273:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest65.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testAddAndGetValueObject:274:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest66.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testSubtractValuePrimitive:282:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest67.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testSubtractValuePrimitive:283:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest68.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testSubtractValueObject:291:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest69.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testSubtractValueObject:292:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest70.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testToString:297:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest71.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testToString:298:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest72.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableLongTest.trace org.apache.commons.lang3.mutable.MutableLongTest.testToString:299:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableLongTest/MutableLongTest73.txt

#Total Asserts in org.apache.commons.lang3.mutable/MutableLongTest=============73
#Total Tests in org.apache.commons.lang3.mutable/MutableLongTest=============0
