#!/bin/bash

echo "computing slice for MutableFloatTest"

mkdir -p /home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testConstructors:62:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testConstructors:64:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testConstructors:66:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testConstructors:67:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testConstructors:69:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testGetSet:81:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testGetSet:82:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testGetSet:85:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testGetSet:86:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testGetSet:89:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testGetSet:90:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testGetSet:93:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testGetSet:94:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testNanInfinite:106:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testNanInfinite:109:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testNanInfinite:112:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testEquals:121:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testEquals:122:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testEquals:123:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testEquals:124:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testEquals:125:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testEquals:126:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testEquals:127:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testEquals:128:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testEquals:129:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testEquals:130:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testHashCode:139:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testHashCode:140:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testHashCode:141:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testHashCode:142:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testCompareTo:149:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testCompareTo:150:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest32.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testCompareTo:151:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest33.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testPrimitiveValues:164:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest34.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testPrimitiveValues:165:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest35.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testPrimitiveValues:166:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest36.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testPrimitiveValues:167:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest37.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testPrimitiveValues:168:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest38.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testPrimitiveValues:169:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest39.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testToFloat:174:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest40.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testToFloat:175:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest41.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testIncrement:183:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest42.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testIncrement:184:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest43.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testIncrementAndGet:192:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest44.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testIncrementAndGet:193:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest45.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testIncrementAndGet:194:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest46.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testGetAndIncrement:202:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest47.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testGetAndIncrement:203:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest48.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testGetAndIncrement:204:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest49.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testDecrement:212:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest50.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testDecrement:213:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest51.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testDecrementAndGet:221:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest52.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testDecrementAndGet:222:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest53.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testDecrementAndGet:223:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest54.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testGetAndDecrement:231:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest55.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testGetAndDecrement:232:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest56.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testGetAndDecrement:233:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest57.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testAddValuePrimitive:241:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest58.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testAddValueObject:249:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest59.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testGetAndAddValuePrimitive:257:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest60.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testGetAndAddValuePrimitive:258:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest61.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testGetAndAddValueObject:266:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest62.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testGetAndAddValueObject:267:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest63.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testAddAndGetValuePrimitive:275:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest64.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testAddAndGetValuePrimitive:276:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest65.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testAddAndGetValueObject:284:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest66.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testAddAndGetValueObject:285:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest67.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testSubtractValuePrimitive:293:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest68.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testSubtractValueObject:301:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest69.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testToString:306:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest70.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testToString:307:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest71.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/mutable_traces/MutableFloatTest.trace org.apache.commons.lang3.mutable.MutableFloatTest.testToString:308:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/mutable_slices/MutableFloatTest/MutableFloatTest72.txt

#Total Asserts in org.apache.commons.lang3.mutable/MutableFloatTest=============72
#Total Tests in org.apache.commons.lang3.mutable/MutableFloatTest=============0
