#!/bin/bash

echo "computing slice for TripleTest"

mkdir -p /home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testTripleOf:50:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testTripleOf:51:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testTripleOf:52:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testTripleOf:53:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testTripleOf:55:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testTripleOf:56:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testTripleOf:57:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testTripleOf:58:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testCompatibilityBetweenTriples:65:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testCompatibilityBetweenTriples:66:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testCompatibilityBetweenTriples:69:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testComparable1:76:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testComparable1:77:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testComparable1:78:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testComparable1:79:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testComparable2:86:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testComparable2:87:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testComparable2:88:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testComparable2:89:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testComparable3:96:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testComparable3:97:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testComparable3:98:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testComparable3:99:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testComparable4:106:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testComparable4:107:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testComparable4:108:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testComparable4:109:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testToString:115:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testToStringCustom:123:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testFormattable_simple:129:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/TripleTest.trace org.apache.commons.lang3.tuple.TripleTest.testFormattable_padded:135:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/TripleTest/TripleTest31.txt

#Total Asserts in org.apache.commons.lang3.tuple/TripleTest=============31
#Total Tests in org.apache.commons.lang3.tuple/TripleTest=============0
