#!/bin/bash

echo "computing slice for PairTest"

mkdir -p /home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/PairTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/PairTest.trace org.apache.commons.lang3.tuple.PairTest.testPairOf:52:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/PairTest/PairTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/PairTest.trace org.apache.commons.lang3.tuple.PairTest.testPairOf:53:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/PairTest/PairTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/PairTest.trace org.apache.commons.lang3.tuple.PairTest.testPairOf:54:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/PairTest/PairTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/PairTest.trace org.apache.commons.lang3.tuple.PairTest.testPairOf:56:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/PairTest/PairTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/PairTest.trace org.apache.commons.lang3.tuple.PairTest.testPairOf:57:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/PairTest/PairTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/PairTest.trace org.apache.commons.lang3.tuple.PairTest.testPairOf:58:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/PairTest/PairTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/PairTest.trace org.apache.commons.lang3.tuple.PairTest.testCompatibilityBetweenPairs:65:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/PairTest/PairTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/PairTest.trace org.apache.commons.lang3.tuple.PairTest.testCompatibilityBetweenPairs:66:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/PairTest/PairTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/PairTest.trace org.apache.commons.lang3.tuple.PairTest.testCompatibilityBetweenPairs:69:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/PairTest/PairTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/PairTest.trace org.apache.commons.lang3.tuple.PairTest.testCompatibilityBetweenPairs:72:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/PairTest/PairTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/PairTest.trace org.apache.commons.lang3.tuple.PairTest.testCompatibilityBetweenPairs:73:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/PairTest/PairTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/PairTest.trace org.apache.commons.lang3.tuple.PairTest.testMapEntry:82:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/PairTest/PairTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/PairTest.trace org.apache.commons.lang3.tuple.PairTest.testMapEntry:83:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/PairTest/PairTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/PairTest.trace org.apache.commons.lang3.tuple.PairTest.testComparable1:90:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/PairTest/PairTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/PairTest.trace org.apache.commons.lang3.tuple.PairTest.testComparable1:91:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/PairTest/PairTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/PairTest.trace org.apache.commons.lang3.tuple.PairTest.testComparable1:92:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/PairTest/PairTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/PairTest.trace org.apache.commons.lang3.tuple.PairTest.testComparable1:93:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/PairTest/PairTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/PairTest.trace org.apache.commons.lang3.tuple.PairTest.testComparable2:100:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/PairTest/PairTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/PairTest.trace org.apache.commons.lang3.tuple.PairTest.testComparable2:101:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/PairTest/PairTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/PairTest.trace org.apache.commons.lang3.tuple.PairTest.testComparable2:102:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/PairTest/PairTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/PairTest.trace org.apache.commons.lang3.tuple.PairTest.testComparable2:103:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/PairTest/PairTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/PairTest.trace org.apache.commons.lang3.tuple.PairTest.testToString:109:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/PairTest/PairTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/PairTest.trace org.apache.commons.lang3.tuple.PairTest.testToStringCustom:117:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/PairTest/PairTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/PairTest.trace org.apache.commons.lang3.tuple.PairTest.testFormattable_simple:123:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/PairTest/PairTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/tuple_traces/PairTest.trace org.apache.commons.lang3.tuple.PairTest.testFormattable_padded:129:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/tuple_slices/PairTest/PairTest25.txt

#Total Asserts in org.apache.commons.lang3.tuple/PairTest=============25
#Total Tests in org.apache.commons.lang3.tuple/PairTest=============0
