#!/bin/bash

echo "computing slice for CustomDeserializerTest"

mkdir -p /home/stg/omc_experiments/slices/gson/functional_slices/CustomDeserializerTest

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/CustomDeserializerTest.trace com.google.gson.functional.CustomDeserializerTest.testDefaultConstructorNotCalledOnObject:56:*>/home/stg/omc_experiments/slices/gson/functional_slices/CustomDeserializerTest/CustomDeserializerTest1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/CustomDeserializerTest.trace com.google.gson.functional.CustomDeserializerTest.testDefaultConstructorNotCalledOnField:64:*>/home/stg/omc_experiments/slices/gson/functional_slices/CustomDeserializerTest/CustomDeserializerTest2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/CustomDeserializerTest.trace com.google.gson.functional.CustomDeserializerTest.testJsonTypeFieldBasedDeserialization:123:*>/home/stg/omc_experiments/slices/gson/functional_slices/CustomDeserializerTest/CustomDeserializerTest3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/CustomDeserializerTest.trace com.google.gson.functional.CustomDeserializerTest.testCustomDeserializerReturnsNullForTopLevelObject:162:*>/home/stg/omc_experiments/slices/gson/functional_slices/CustomDeserializerTest/CustomDeserializerTest4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/CustomDeserializerTest.trace com.google.gson.functional.CustomDeserializerTest.testCustomDeserializerReturnsNull:176:*>/home/stg/omc_experiments/slices/gson/functional_slices/CustomDeserializerTest/CustomDeserializerTest5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/CustomDeserializerTest.trace com.google.gson.functional.CustomDeserializerTest.testCustomDeserializerReturnsNullForArrayElements:190:*>/home/stg/omc_experiments/slices/gson/functional_slices/CustomDeserializerTest/CustomDeserializerTest6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/CustomDeserializerTest.trace com.google.gson.functional.CustomDeserializerTest.testCustomDeserializerReturnsNullForArrayElements:191:*>/home/stg/omc_experiments/slices/gson/functional_slices/CustomDeserializerTest/CustomDeserializerTest7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/CustomDeserializerTest.trace com.google.gson.functional.CustomDeserializerTest.testCustomDeserializerReturnsNullForArrayElementsForArrayField:205:*>/home/stg/omc_experiments/slices/gson/functional_slices/CustomDeserializerTest/CustomDeserializerTest8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/CustomDeserializerTest.trace com.google.gson.functional.CustomDeserializerTest.testCustomDeserializerReturnsNullForArrayElementsForArrayField:206:*>/home/stg/omc_experiments/slices/gson/functional_slices/CustomDeserializerTest/CustomDeserializerTest9.txt

#Total Asserts in com.google.gson.functional/CustomDeserializerTest=============9
#Total Tests in com.google.gson.functional/CustomDeserializerTest=============0
