#!/bin/bash

echo "computing slice for ReadersWritersTest"

mkdir -p /home/stg/omc_experiments/slices/gson/functional_slices/ReadersWritersTest

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ReadersWritersTest.trace com.google.gson.functional.ReadersWritersTest.testWriterForSerialization:55:*>/home/stg/omc_experiments/slices/gson/functional_slices/ReadersWritersTest/ReadersWritersTest1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ReadersWritersTest.trace com.google.gson.functional.ReadersWritersTest.testReaderForDeserialization:62:*>/home/stg/omc_experiments/slices/gson/functional_slices/ReadersWritersTest/ReadersWritersTest2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ReadersWritersTest.trace com.google.gson.functional.ReadersWritersTest.testTopLevelNullObjectSerializationWithWriter:68:*>/home/stg/omc_experiments/slices/gson/functional_slices/ReadersWritersTest/ReadersWritersTest3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ReadersWritersTest.trace com.google.gson.functional.ReadersWritersTest.testTopLevelNullObjectDeserializationWithReader:74:*>/home/stg/omc_experiments/slices/gson/functional_slices/ReadersWritersTest/ReadersWritersTest4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ReadersWritersTest.trace com.google.gson.functional.ReadersWritersTest.testTopLevelNullObjectSerializationWithWriterAndSerializeNulls:81:*>/home/stg/omc_experiments/slices/gson/functional_slices/ReadersWritersTest/ReadersWritersTest5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ReadersWritersTest.trace com.google.gson.functional.ReadersWritersTest.testTopLevelNullObjectDeserializationWithReaderAndSerializeNulls:88:*>/home/stg/omc_experiments/slices/gson/functional_slices/ReadersWritersTest/ReadersWritersTest6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ReadersWritersTest.trace com.google.gson.functional.ReadersWritersTest.testReadWriteTwoStrings:99:*>/home/stg/omc_experiments/slices/gson/functional_slices/ReadersWritersTest/ReadersWritersTest7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ReadersWritersTest.trace com.google.gson.functional.ReadersWritersTest.testReadWriteTwoStrings:101:*>/home/stg/omc_experiments/slices/gson/functional_slices/ReadersWritersTest/ReadersWritersTest8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ReadersWritersTest.trace com.google.gson.functional.ReadersWritersTest.testReadWriteTwoObjects:114:*>/home/stg/omc_experiments/slices/gson/functional_slices/ReadersWritersTest/ReadersWritersTest9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ReadersWritersTest.trace com.google.gson.functional.ReadersWritersTest.testReadWriteTwoObjects:116:*>/home/stg/omc_experiments/slices/gson/functional_slices/ReadersWritersTest/ReadersWritersTest10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ReadersWritersTest.trace com.google.gson.functional.ReadersWritersTest.testReadWriteTwoObjects:117:*>/home/stg/omc_experiments/slices/gson/functional_slices/ReadersWritersTest/ReadersWritersTest11.txt

#Total Asserts in com.google.gson.functional/ReadersWritersTest=============11
#Total Tests in com.google.gson.functional/ReadersWritersTest=============0
