#!/bin/bash

echo "computing slice for InheritanceTest"

mkdir -p /home/stg/omc_experiments/slices/gson/functional_slices/InheritanceTest

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/InheritanceTest.trace com.google.gson.functional.InheritanceTest.testSubClassSerialization:60:*>/home/stg/omc_experiments/slices/gson/functional_slices/InheritanceTest/InheritanceTest1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/InheritanceTest.trace com.google.gson.functional.InheritanceTest.testSubClassDeserialization:69:*>/home/stg/omc_experiments/slices/gson/functional_slices/InheritanceTest/InheritanceTest2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/InheritanceTest.trace com.google.gson.functional.InheritanceTest.testClassWithBaseFieldSerialization:76:*>/home/stg/omc_experiments/slices/gson/functional_slices/InheritanceTest/InheritanceTest3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/InheritanceTest.trace com.google.gson.functional.InheritanceTest.testClassWithBaseArrayFieldSerialization:85:*>/home/stg/omc_experiments/slices/gson/functional_slices/InheritanceTest/InheritanceTest4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/InheritanceTest.trace com.google.gson.functional.InheritanceTest.testClassWithBaseCollectionFieldSerialization:97:*>/home/stg/omc_experiments/slices/gson/functional_slices/InheritanceTest/InheritanceTest5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/InheritanceTest.trace com.google.gson.functional.InheritanceTest.testBaseSerializedAsSub:104:*>/home/stg/omc_experiments/slices/gson/functional_slices/InheritanceTest/InheritanceTest6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/InheritanceTest.trace com.google.gson.functional.InheritanceTest.testBaseSerializedAsSubForToJsonMethod:110:*>/home/stg/omc_experiments/slices/gson/functional_slices/InheritanceTest/InheritanceTest7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/InheritanceTest.trace com.google.gson.functional.InheritanceTest.testBaseSerializedAsBaseWhenSpecifiedWithExplicitType:116:*>/home/stg/omc_experiments/slices/gson/functional_slices/InheritanceTest/InheritanceTest8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/InheritanceTest.trace com.google.gson.functional.InheritanceTest.testBaseSerializedAsBaseWhenSpecifiedWithExplicitType:117:*>/home/stg/omc_experiments/slices/gson/functional_slices/InheritanceTest/InheritanceTest9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/InheritanceTest.trace com.google.gson.functional.InheritanceTest.testBaseSerializedAsBaseWhenSpecifiedWithExplicitTypeForToJsonMethod:123:*>/home/stg/omc_experiments/slices/gson/functional_slices/InheritanceTest/InheritanceTest10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/InheritanceTest.trace com.google.gson.functional.InheritanceTest.testBaseSerializedAsBaseWhenSpecifiedWithExplicitTypeForToJsonMethod:124:*>/home/stg/omc_experiments/slices/gson/functional_slices/InheritanceTest/InheritanceTest11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/InheritanceTest.trace com.google.gson.functional.InheritanceTest.testBaseSerializedAsSubWhenSpecifiedWithExplicitType:130:*>/home/stg/omc_experiments/slices/gson/functional_slices/InheritanceTest/InheritanceTest12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/InheritanceTest.trace com.google.gson.functional.InheritanceTest.testBaseSerializedAsSubWhenSpecifiedWithExplicitTypeForToJsonMethod:136:*>/home/stg/omc_experiments/slices/gson/functional_slices/InheritanceTest/InheritanceTest13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/InheritanceTest.trace com.google.gson.functional.InheritanceTest.testSubInterfacesOfCollectionSerialization:176:*>/home/stg/omc_experiments/slices/gson/functional_slices/InheritanceTest/InheritanceTest14.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/InheritanceTest.trace com.google.gson.functional.InheritanceTest.testSubInterfacesOfCollectionDeserialization:185:*>/home/stg/omc_experiments/slices/gson/functional_slices/InheritanceTest/InheritanceTest15.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/InheritanceTest.trace com.google.gson.functional.InheritanceTest.testSubInterfacesOfCollectionDeserialization:186:*>/home/stg/omc_experiments/slices/gson/functional_slices/InheritanceTest/InheritanceTest16.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/InheritanceTest.trace com.google.gson.functional.InheritanceTest.testSubInterfacesOfCollectionDeserialization:187:*>/home/stg/omc_experiments/slices/gson/functional_slices/InheritanceTest/InheritanceTest17.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/InheritanceTest.trace com.google.gson.functional.InheritanceTest.testSubInterfacesOfCollectionDeserialization:188:*>/home/stg/omc_experiments/slices/gson/functional_slices/InheritanceTest/InheritanceTest18.txt

#Total Asserts in com.google.gson.functional/InheritanceTest=============18
#Total Tests in com.google.gson.functional/InheritanceTest=============0
