#!/bin/bash

echo "computing slice for NullObjectAndFieldTest"

mkdir -p /home/stg/omc_experiments/slices/gson/functional_slices/NullObjectAndFieldTest

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/NullObjectAndFieldTest.trace com.google.gson.functional.NullObjectAndFieldTest.testTopLevelNullObjectSerialization:54:*>/home/stg/omc_experiments/slices/gson/functional_slices/NullObjectAndFieldTest/NullObjectAndFieldTest1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/NullObjectAndFieldTest.trace com.google.gson.functional.NullObjectAndFieldTest.testTopLevelNullObjectSerialization:57:*>/home/stg/omc_experiments/slices/gson/functional_slices/NullObjectAndFieldTest/NullObjectAndFieldTest2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/NullObjectAndFieldTest.trace com.google.gson.functional.NullObjectAndFieldTest.testTopLevelNullObjectDeserialization:63:*>/home/stg/omc_experiments/slices/gson/functional_slices/NullObjectAndFieldTest/NullObjectAndFieldTest3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/NullObjectAndFieldTest.trace com.google.gson.functional.NullObjectAndFieldTest.testExplicitSerializationOfNulls:71:*>/home/stg/omc_experiments/slices/gson/functional_slices/NullObjectAndFieldTest/NullObjectAndFieldTest4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/NullObjectAndFieldTest.trace com.google.gson.functional.NullObjectAndFieldTest.testExplicitDeserializationOfNulls:77:*>/home/stg/omc_experiments/slices/gson/functional_slices/NullObjectAndFieldTest/NullObjectAndFieldTest5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/NullObjectAndFieldTest.trace com.google.gson.functional.NullObjectAndFieldTest.testExplicitSerializationOfNullArrayMembers:84:*>/home/stg/omc_experiments/slices/gson/functional_slices/NullObjectAndFieldTest/NullObjectAndFieldTest6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/NullObjectAndFieldTest.trace com.google.gson.functional.NullObjectAndFieldTest.testNullWrappedPrimitiveMemberSerialization:94:*>/home/stg/omc_experiments/slices/gson/functional_slices/NullObjectAndFieldTest/NullObjectAndFieldTest7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/NullObjectAndFieldTest.trace com.google.gson.functional.NullObjectAndFieldTest.testNullWrappedPrimitiveMemberDeserialization:104:*>/home/stg/omc_experiments/slices/gson/functional_slices/NullObjectAndFieldTest/NullObjectAndFieldTest8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/NullObjectAndFieldTest.trace com.google.gson.functional.NullObjectAndFieldTest.testExplicitSerializationOfNullCollectionMembers:111:*>/home/stg/omc_experiments/slices/gson/functional_slices/NullObjectAndFieldTest/NullObjectAndFieldTest9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/NullObjectAndFieldTest.trace com.google.gson.functional.NullObjectAndFieldTest.testExplicitSerializationOfNullStringMembers:118:*>/home/stg/omc_experiments/slices/gson/functional_slices/NullObjectAndFieldTest/NullObjectAndFieldTest10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/NullObjectAndFieldTest.trace com.google.gson.functional.NullObjectAndFieldTest.testCustomSerializationOfNulls:127:*>/home/stg/omc_experiments/slices/gson/functional_slices/NullObjectAndFieldTest/NullObjectAndFieldTest11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/NullObjectAndFieldTest.trace com.google.gson.functional.NullObjectAndFieldTest.testPrintPrintingObjectWithNulls:134:*>/home/stg/omc_experiments/slices/gson/functional_slices/NullObjectAndFieldTest/NullObjectAndFieldTest12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/NullObjectAndFieldTest.trace com.google.gson.functional.NullObjectAndFieldTest.testPrintPrintingObjectWithNulls:138:*>/home/stg/omc_experiments/slices/gson/functional_slices/NullObjectAndFieldTest/NullObjectAndFieldTest13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/NullObjectAndFieldTest.trace com.google.gson.functional.NullObjectAndFieldTest.testPrintPrintingArraysWithNulls:145:*>/home/stg/omc_experiments/slices/gson/functional_slices/NullObjectAndFieldTest/NullObjectAndFieldTest14.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/NullObjectAndFieldTest.trace com.google.gson.functional.NullObjectAndFieldTest.testPrintPrintingArraysWithNulls:149:*>/home/stg/omc_experiments/slices/gson/functional_slices/NullObjectAndFieldTest/NullObjectAndFieldTest15.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/NullObjectAndFieldTest.trace com.google.gson.functional.NullObjectAndFieldTest.testAbsentJsonElementsAreSetToNull:157:*>/home/stg/omc_experiments/slices/gson/functional_slices/NullObjectAndFieldTest/NullObjectAndFieldTest16.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/NullObjectAndFieldTest.trace com.google.gson.functional.NullObjectAndFieldTest.testAbsentJsonElementsAreSetToNull:158:*>/home/stg/omc_experiments/slices/gson/functional_slices/NullObjectAndFieldTest/NullObjectAndFieldTest17.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/NullObjectAndFieldTest.trace com.google.gson.functional.NullObjectAndFieldTest.testAbsentJsonElementsAreSetToNull:159:*>/home/stg/omc_experiments/slices/gson/functional_slices/NullObjectAndFieldTest/NullObjectAndFieldTest18.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/NullObjectAndFieldTest.trace com.google.gson.functional.NullObjectAndFieldTest.testAbsentJsonElementsAreSetToNull:160:*>/home/stg/omc_experiments/slices/gson/functional_slices/NullObjectAndFieldTest/NullObjectAndFieldTest19.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/NullObjectAndFieldTest.trace com.google.gson.functional.NullObjectAndFieldTest.testAbsentJsonElementsAreSetToNull:161:*>/home/stg/omc_experiments/slices/gson/functional_slices/NullObjectAndFieldTest/NullObjectAndFieldTest20.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/NullObjectAndFieldTest.trace com.google.gson.functional.NullObjectAndFieldTest.testAbsentJsonElementsAreSetToNull:162:*>/home/stg/omc_experiments/slices/gson/functional_slices/NullObjectAndFieldTest/NullObjectAndFieldTest21.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/NullObjectAndFieldTest.trace com.google.gson.functional.NullObjectAndFieldTest.testAbsentJsonElementsAreSetToNull:163:*>/home/stg/omc_experiments/slices/gson/functional_slices/NullObjectAndFieldTest/NullObjectAndFieldTest22.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/NullObjectAndFieldTest.trace com.google.gson.functional.NullObjectAndFieldTest.testExplicitNullSetsFieldToNullDuringDeserialization:207:*>/home/stg/omc_experiments/slices/gson/functional_slices/NullObjectAndFieldTest/NullObjectAndFieldTest23.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/NullObjectAndFieldTest.trace com.google.gson.functional.NullObjectAndFieldTest.testCustomTypeAdapterPassesNullSerialization:221:*>/home/stg/omc_experiments/slices/gson/functional_slices/NullObjectAndFieldTest/NullObjectAndFieldTest24.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/NullObjectAndFieldTest.trace com.google.gson.functional.NullObjectAndFieldTest.testCustomTypeAdapterPassesNullDesrialization:234:*>/home/stg/omc_experiments/slices/gson/functional_slices/NullObjectAndFieldTest/NullObjectAndFieldTest25.txt

#Total Asserts in com.google.gson.functional/NullObjectAndFieldTest=============25
#Total Tests in com.google.gson.functional/NullObjectAndFieldTest=============0
