#!/bin/bash

echo "computing slice for VersioningTest"

mkdir -p /home/stg/omc_experiments/slices/gson/functional_slices/VersioningTest

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/VersioningTest.trace com.google.gson.functional.VersioningTest.testVersionedUntilSerialization:50:*>/home/stg/omc_experiments/slices/gson/functional_slices/VersioningTest/VersioningTest1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/VersioningTest.trace com.google.gson.functional.VersioningTest.testVersionedUntilSerialization:54:*>/home/stg/omc_experiments/slices/gson/functional_slices/VersioningTest/VersioningTest2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/VersioningTest.trace com.google.gson.functional.VersioningTest.testVersionedUntilDeserialization:61:*>/home/stg/omc_experiments/slices/gson/functional_slices/VersioningTest/VersioningTest3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/VersioningTest.trace com.google.gson.functional.VersioningTest.testVersionedClassesSerialization:68:*>/home/stg/omc_experiments/slices/gson/functional_slices/VersioningTest/VersioningTest4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/VersioningTest.trace com.google.gson.functional.VersioningTest.testVersionedClassesDeserialization:75:*>/home/stg/omc_experiments/slices/gson/functional_slices/VersioningTest/VersioningTest5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/VersioningTest.trace com.google.gson.functional.VersioningTest.testVersionedClassesDeserialization:76:*>/home/stg/omc_experiments/slices/gson/functional_slices/VersioningTest/VersioningTest6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/VersioningTest.trace com.google.gson.functional.VersioningTest.testVersionedClassesDeserialization:78:*>/home/stg/omc_experiments/slices/gson/functional_slices/VersioningTest/VersioningTest7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/VersioningTest.trace com.google.gson.functional.VersioningTest.testVersionedClassesDeserialization:79:*>/home/stg/omc_experiments/slices/gson/functional_slices/VersioningTest/VersioningTest8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/VersioningTest.trace com.google.gson.functional.VersioningTest.testVersionedClassesDeserialization:80:*>/home/stg/omc_experiments/slices/gson/functional_slices/VersioningTest/VersioningTest9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/VersioningTest.trace com.google.gson.functional.VersioningTest.testIgnoreLaterVersionClassSerialization:85:*>/home/stg/omc_experiments/slices/gson/functional_slices/VersioningTest/VersioningTest10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/VersioningTest.trace com.google.gson.functional.VersioningTest.testIgnoreLaterVersionClassDeserialization:94:*>/home/stg/omc_experiments/slices/gson/functional_slices/VersioningTest/VersioningTest11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/VersioningTest.trace com.google.gson.functional.VersioningTest.testVersionedGsonWithUnversionedClassesSerialization:100:*>/home/stg/omc_experiments/slices/gson/functional_slices/VersioningTest/VersioningTest12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/VersioningTest.trace com.google.gson.functional.VersioningTest.testVersionedGsonWithUnversionedClassesDeserialization:112:*>/home/stg/omc_experiments/slices/gson/functional_slices/VersioningTest/VersioningTest13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/VersioningTest.trace com.google.gson.functional.VersioningTest.testVersionedGsonMixingSinceAndUntilSerialization:119:*>/home/stg/omc_experiments/slices/gson/functional_slices/VersioningTest/VersioningTest14.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/VersioningTest.trace com.google.gson.functional.VersioningTest.testVersionedGsonMixingSinceAndUntilSerialization:123:*>/home/stg/omc_experiments/slices/gson/functional_slices/VersioningTest/VersioningTest15.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/VersioningTest.trace com.google.gson.functional.VersioningTest.testVersionedGsonMixingSinceAndUntilSerialization:127:*>/home/stg/omc_experiments/slices/gson/functional_slices/VersioningTest/VersioningTest16.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/VersioningTest.trace com.google.gson.functional.VersioningTest.testVersionedGsonMixingSinceAndUntilDeserialization:134:*>/home/stg/omc_experiments/slices/gson/functional_slices/VersioningTest/VersioningTest17.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/VersioningTest.trace com.google.gson.functional.VersioningTest.testVersionedGsonMixingSinceAndUntilDeserialization:135:*>/home/stg/omc_experiments/slices/gson/functional_slices/VersioningTest/VersioningTest18.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/VersioningTest.trace com.google.gson.functional.VersioningTest.testVersionedGsonMixingSinceAndUntilDeserialization:139:*>/home/stg/omc_experiments/slices/gson/functional_slices/VersioningTest/VersioningTest19.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/VersioningTest.trace com.google.gson.functional.VersioningTest.testVersionedGsonMixingSinceAndUntilDeserialization:140:*>/home/stg/omc_experiments/slices/gson/functional_slices/VersioningTest/VersioningTest20.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/VersioningTest.trace com.google.gson.functional.VersioningTest.testVersionedGsonMixingSinceAndUntilDeserialization:144:*>/home/stg/omc_experiments/slices/gson/functional_slices/VersioningTest/VersioningTest21.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/VersioningTest.trace com.google.gson.functional.VersioningTest.testVersionedGsonMixingSinceAndUntilDeserialization:145:*>/home/stg/omc_experiments/slices/gson/functional_slices/VersioningTest/VersioningTest22.txt

#Total Asserts in com.google.gson.functional/VersioningTest=============22
#Total Tests in com.google.gson.functional/VersioningTest=============0
