#!/bin/bash

echo "computing slice for ParameterizedTypesTest"

mkdir -p /home/stg/omc_experiments/slices/gson/functional_slices/ParameterizedTypesTest

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ParameterizedTypesTest.trace com.google.gson.functional.ParameterizedTypesTest.testParameterizedTypesSerialization:58:*>/home/stg/omc_experiments/slices/gson/functional_slices/ParameterizedTypesTest/ParameterizedTypesTest1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ParameterizedTypesTest.trace com.google.gson.functional.ParameterizedTypesTest.testParameterizedTypeDeserialization:72:*>/home/stg/omc_experiments/slices/gson/functional_slices/ParameterizedTypesTest/ParameterizedTypesTest2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ParameterizedTypesTest.trace com.google.gson.functional.ParameterizedTypesTest.testTypesWithMultipleParametersSerialization:84:*>/home/stg/omc_experiments/slices/gson/functional_slices/ParameterizedTypesTest/ParameterizedTypesTest3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ParameterizedTypesTest.trace com.google.gson.functional.ParameterizedTypesTest.testTypesWithMultipleParametersDeserialization:97:*>/home/stg/omc_experiments/slices/gson/functional_slices/ParameterizedTypesTest/ParameterizedTypesTest4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ParameterizedTypesTest.trace com.google.gson.functional.ParameterizedTypesTest.testParameterizedTypeWithCustomSerializer:109:*>/home/stg/omc_experiments/slices/gson/functional_slices/ParameterizedTypesTest/ParameterizedTypesTest5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ParameterizedTypesTest.trace com.google.gson.functional.ParameterizedTypesTest.testParameterizedTypeWithCustomSerializer:113:*>/home/stg/omc_experiments/slices/gson/functional_slices/ParameterizedTypesTest/ParameterizedTypesTest6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ParameterizedTypesTest.trace com.google.gson.functional.ParameterizedTypesTest.testParameterizedTypesWithCustomDeserializer:130:*>/home/stg/omc_experiments/slices/gson/functional_slices/ParameterizedTypesTest/ParameterizedTypesTest7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ParameterizedTypesTest.trace com.google.gson.functional.ParameterizedTypesTest.testParameterizedTypesWithCustomDeserializer:135:*>/home/stg/omc_experiments/slices/gson/functional_slices/ParameterizedTypesTest/ParameterizedTypesTest8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ParameterizedTypesTest.trace com.google.gson.functional.ParameterizedTypesTest.testParameterizedTypesWithWriterSerialization:143:*>/home/stg/omc_experiments/slices/gson/functional_slices/ParameterizedTypesTest/ParameterizedTypesTest9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ParameterizedTypesTest.trace com.google.gson.functional.ParameterizedTypesTest.testParameterizedTypeWithReaderDeserialization:157:*>/home/stg/omc_experiments/slices/gson/functional_slices/ParameterizedTypesTest/ParameterizedTypesTest10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ParameterizedTypesTest.trace com.google.gson.functional.ParameterizedTypesTest.testVariableTypeFieldsAndGenericArraysSerialization:174:*>/home/stg/omc_experiments/slices/gson/functional_slices/ParameterizedTypesTest/ParameterizedTypesTest11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ParameterizedTypesTest.trace com.google.gson.functional.ParameterizedTypesTest.testVariableTypeFieldsAndGenericArraysDeserialization:192:*>/home/stg/omc_experiments/slices/gson/functional_slices/ParameterizedTypesTest/ParameterizedTypesTest12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ParameterizedTypesTest.trace com.google.gson.functional.ParameterizedTypesTest.testVariableTypeDeserialization:202:*>/home/stg/omc_experiments/slices/gson/functional_slices/ParameterizedTypesTest/ParameterizedTypesTest13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ParameterizedTypesTest.trace com.google.gson.functional.ParameterizedTypesTest.testVariableTypeArrayDeserialization:214:*>/home/stg/omc_experiments/slices/gson/functional_slices/ParameterizedTypesTest/ParameterizedTypesTest14.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ParameterizedTypesTest.trace com.google.gson.functional.ParameterizedTypesTest.testParameterizedTypeWithVariableTypeDeserialization:228:*>/home/stg/omc_experiments/slices/gson/functional_slices/ParameterizedTypesTest/ParameterizedTypesTest15.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ParameterizedTypesTest.trace com.google.gson.functional.ParameterizedTypesTest.testParameterizedTypeGenericArraysSerialization:242:*>/home/stg/omc_experiments/slices/gson/functional_slices/ParameterizedTypesTest/ParameterizedTypesTest16.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ParameterizedTypesTest.trace com.google.gson.functional.ParameterizedTypesTest.testParameterizedTypeGenericArraysDeserialization:258:*>/home/stg/omc_experiments/slices/gson/functional_slices/ParameterizedTypesTest/ParameterizedTypesTest17.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ParameterizedTypesTest.trace com.google.gson.functional.ParameterizedTypesTest.testDeepParameterizedTypeSerialization:492:*>/home/stg/omc_experiments/slices/gson/functional_slices/ParameterizedTypesTest/ParameterizedTypesTest18.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ParameterizedTypesTest.trace com.google.gson.functional.ParameterizedTypesTest.testDeepParameterizedTypeSerialization:493:*>/home/stg/omc_experiments/slices/gson/functional_slices/ParameterizedTypesTest/ParameterizedTypesTest19.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ParameterizedTypesTest.trace com.google.gson.functional.ParameterizedTypesTest.testDeepParameterizedTypeDeserialization:500:*>/home/stg/omc_experiments/slices/gson/functional_slices/ParameterizedTypesTest/ParameterizedTypesTest20.txt

#Total Asserts in com.google.gson.functional/ParameterizedTypesTest=============20
#Total Tests in com.google.gson.functional/ParameterizedTypesTest=============0
