#!/bin/bash

echo "computing slice for ObjectTest"

mkdir -p /home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testJsonInSingleQuotesDeserialization:75:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testJsonInSingleQuotesDeserialization:76:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testJsonInSingleQuotesDeserialization:77:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testJsonInMixedQuotesDeserialization:83:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testJsonInMixedQuotesDeserialization:84:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testJsonInMixedQuotesDeserialization:85:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testBagOfPrimitivesSerialization:90:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testBagOfPrimitivesDeserialization:97:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testBagOfPrimitiveWrappersSerialization:102:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testBagOfPrimitiveWrappersDeserialization:109:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testClassWithTransientFieldsSerialization:114:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testClassWithTransientFieldsDeserialization:121:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testClassWithTransientFieldsDeserializationTransientFieldsPassedInJsonAreIgnored:129:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testClassWithNoFieldsSerialization:133:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest14.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testClassWithNoFieldsDeserialization:140:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest15.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testNestedSerialization:146:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest16.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testNestedDeserialization:154:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest17.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testNullSerialization:157:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest18.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testEmptyStringDeserialization:162:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest19.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testNullDeserialization:176:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest20.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testNullFieldsSerialization:181:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest21.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testNullFieldsDeserialization:188:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest22.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testArrayOfObjectsSerialization:193:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest23.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testArrayOfObjectsDeserialization:199:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest24.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testArrayOfArraysSerialization:204:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest25.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testArrayOfArraysDeserialization:210:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest26.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testArrayOfObjectsAsFields:224:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest27.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testArrayOfObjectsAsFields:225:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest28.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testArrayOfObjectsAsFields:226:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest29.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testNullArraysDeserialization:235:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest30.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testNullObjectFieldsDeserialization:244:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest31.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testEmptyCollectionInAnObjectDeserialization:250:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest32.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testEmptyCollectionInAnObjectDeserialization:251:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest33.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testPrimitiveArrayInAnObjectDeserialization:261:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest34.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testNullPrimitiveFieldsDeserialization:270:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest35.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testEmptyCollectionInAnObjectSerialization:275:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest36.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testPrivateNoArgConstructorDeserialization:281:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest37.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testAnonymousLocalClassesSerialization:285:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest38.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testAnonymousLocalClassesCustomSerialization:300:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest39.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testPrimitiveArrayFieldSerialization:307:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest40.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testClassWithObjectFieldSerialization:318:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest41.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testInnerClassSerialization:330:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest42.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testInnerClassSerialization:331:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest43.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testInnerClassDeserialization:344:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest44.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testObjectFieldNamesWithoutQuotesDeserialization:405:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest45.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testObjectFieldNamesWithoutQuotesDeserialization:406:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest46.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testObjectFieldNamesWithoutQuotesDeserialization:407:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest47.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testStringFieldWithNumberValueDeserialization:413:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest48.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testStringFieldWithNumberValueDeserialization:417:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest49.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testStringFieldWithNumberValueDeserialization:421:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest50.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testStringFieldWithEmptyValueSerialization:431:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest51.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testStringFieldWithEmptyValueSerialization:432:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest52.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testStringFieldWithEmptyValueSerialization:433:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest53.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testStringFieldWithEmptyValueDeserialization:442:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest54.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testStringFieldWithEmptyValueDeserialization:443:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest55.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testStringFieldWithEmptyValueDeserialization:444:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest56.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testJsonObjectSerialization:457:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest57.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testSingletonLists:466:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest58.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testSingletonLists:471:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest59.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testSingletonLists:476:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest60.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ObjectTest.trace com.google.gson.functional.ObjectTest.testDateAsMapObjectField:485:*>/home/stg/omc_experiments/slices/gson/functional_slices/ObjectTest/ObjectTest61.txt

#Total Asserts in com.google.gson.functional/ObjectTest=============61
#Total Tests in com.google.gson.functional/ObjectTest=============0
