#!/bin/bash

echo "computing slice for MoreSpecificTypeSerializationTest"

mkdir -p /home/stg/omc_experiments/slices/gson/functional_slices/MoreSpecificTypeSerializationTest

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/MoreSpecificTypeSerializationTest.trace com.google.gson.functional.MoreSpecificTypeSerializationTest.testSubclassFields:47:*>/home/stg/omc_experiments/slices/gson/functional_slices/MoreSpecificTypeSerializationTest/MoreSpecificTypeSerializationTest1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/MoreSpecificTypeSerializationTest.trace com.google.gson.functional.MoreSpecificTypeSerializationTest.testSubclassFields:48:*>/home/stg/omc_experiments/slices/gson/functional_slices/MoreSpecificTypeSerializationTest/MoreSpecificTypeSerializationTest2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/MoreSpecificTypeSerializationTest.trace com.google.gson.functional.MoreSpecificTypeSerializationTest.testListOfSubclassFields:57:*>/home/stg/omc_experiments/slices/gson/functional_slices/MoreSpecificTypeSerializationTest/MoreSpecificTypeSerializationTest3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/MoreSpecificTypeSerializationTest.trace com.google.gson.functional.MoreSpecificTypeSerializationTest.testListOfSubclassFields:58:*>/home/stg/omc_experiments/slices/gson/functional_slices/MoreSpecificTypeSerializationTest/MoreSpecificTypeSerializationTest4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/MoreSpecificTypeSerializationTest.trace com.google.gson.functional.MoreSpecificTypeSerializationTest.testMapOfSubclassFields:67:*>/home/stg/omc_experiments/slices/gson/functional_slices/MoreSpecificTypeSerializationTest/MoreSpecificTypeSerializationTest5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/MoreSpecificTypeSerializationTest.trace com.google.gson.functional.MoreSpecificTypeSerializationTest.testMapOfSubclassFields:69:*>/home/stg/omc_experiments/slices/gson/functional_slices/MoreSpecificTypeSerializationTest/MoreSpecificTypeSerializationTest6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/MoreSpecificTypeSerializationTest.trace com.google.gson.functional.MoreSpecificTypeSerializationTest.testMapOfSubclassFields:70:*>/home/stg/omc_experiments/slices/gson/functional_slices/MoreSpecificTypeSerializationTest/MoreSpecificTypeSerializationTest7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/MoreSpecificTypeSerializationTest.trace com.google.gson.functional.MoreSpecificTypeSerializationTest.testParameterizedSubclassFields:80:*>/home/stg/omc_experiments/slices/gson/functional_slices/MoreSpecificTypeSerializationTest/MoreSpecificTypeSerializationTest8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/MoreSpecificTypeSerializationTest.trace com.google.gson.functional.MoreSpecificTypeSerializationTest.testParameterizedSubclassFields:81:*>/home/stg/omc_experiments/slices/gson/functional_slices/MoreSpecificTypeSerializationTest/MoreSpecificTypeSerializationTest9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/MoreSpecificTypeSerializationTest.trace com.google.gson.functional.MoreSpecificTypeSerializationTest.testListOfParameterizedSubclassFields:95:*>/home/stg/omc_experiments/slices/gson/functional_slices/MoreSpecificTypeSerializationTest/MoreSpecificTypeSerializationTest10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/MoreSpecificTypeSerializationTest.trace com.google.gson.functional.MoreSpecificTypeSerializationTest.testListOfParameterizedSubclassFields:96:*>/home/stg/omc_experiments/slices/gson/functional_slices/MoreSpecificTypeSerializationTest/MoreSpecificTypeSerializationTest11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/MoreSpecificTypeSerializationTest.trace com.google.gson.functional.MoreSpecificTypeSerializationTest.testMapOfParameterizedSubclassFields:110:*>/home/stg/omc_experiments/slices/gson/functional_slices/MoreSpecificTypeSerializationTest/MoreSpecificTypeSerializationTest12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/MoreSpecificTypeSerializationTest.trace com.google.gson.functional.MoreSpecificTypeSerializationTest.testMapOfParameterizedSubclassFields:112:*>/home/stg/omc_experiments/slices/gson/functional_slices/MoreSpecificTypeSerializationTest/MoreSpecificTypeSerializationTest13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/MoreSpecificTypeSerializationTest.trace com.google.gson.functional.MoreSpecificTypeSerializationTest.testMapOfParameterizedSubclassFields:113:*>/home/stg/omc_experiments/slices/gson/functional_slices/MoreSpecificTypeSerializationTest/MoreSpecificTypeSerializationTest14.txt

#Total Asserts in com.google.gson.functional/MoreSpecificTypeSerializationTest=============14
#Total Tests in com.google.gson.functional/MoreSpecificTypeSerializationTest=============0
