#!/bin/bash

echo "computing slice for ExposeFieldsTest"

mkdir -p /home/stg/omc_experiments/slices/gson/functional_slices/ExposeFieldsTest

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ExposeFieldsTest.trace com.google.gson.functional.ExposeFieldsTest.testNullExposeFieldSerialization:50:*>/home/stg/omc_experiments/slices/gson/functional_slices/ExposeFieldsTest/ExposeFieldsTest1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ExposeFieldsTest.trace com.google.gson.functional.ExposeFieldsTest.testArrayWithOneNullExposeFieldObjectSerialization:66:*>/home/stg/omc_experiments/slices/gson/functional_slices/ExposeFieldsTest/ExposeFieldsTest2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ExposeFieldsTest.trace com.google.gson.functional.ExposeFieldsTest.testExposeAnnotationSerialization:71:*>/home/stg/omc_experiments/slices/gson/functional_slices/ExposeFieldsTest/ExposeFieldsTest3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ExposeFieldsTest.trace com.google.gson.functional.ExposeFieldsTest.testExposeAnnotationDeserialization:78:*>/home/stg/omc_experiments/slices/gson/functional_slices/ExposeFieldsTest/ExposeFieldsTest4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ExposeFieldsTest.trace com.google.gson.functional.ExposeFieldsTest.testExposeAnnotationDeserialization:79:*>/home/stg/omc_experiments/slices/gson/functional_slices/ExposeFieldsTest/ExposeFieldsTest5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ExposeFieldsTest.trace com.google.gson.functional.ExposeFieldsTest.testExposeAnnotationDeserialization:80:*>/home/stg/omc_experiments/slices/gson/functional_slices/ExposeFieldsTest/ExposeFieldsTest6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ExposeFieldsTest.trace com.google.gson.functional.ExposeFieldsTest.testNoExposedFieldSerialization:87:*>/home/stg/omc_experiments/slices/gson/functional_slices/ExposeFieldsTest/ExposeFieldsTest7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ExposeFieldsTest.trace com.google.gson.functional.ExposeFieldsTest.testNoExposedFieldDeserialization:94:*>/home/stg/omc_experiments/slices/gson/functional_slices/ExposeFieldsTest/ExposeFieldsTest8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ExposeFieldsTest.trace com.google.gson.functional.ExposeFieldsTest.testNoExposedFieldDeserialization:95:*>/home/stg/omc_experiments/slices/gson/functional_slices/ExposeFieldsTest/ExposeFieldsTest9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ExposeFieldsTest.trace com.google.gson.functional.ExposeFieldsTest.testExposedInterfaceFieldSerialization:103:*>/home/stg/omc_experiments/slices/gson/functional_slices/ExposeFieldsTest/ExposeFieldsTest10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ExposeFieldsTest.trace com.google.gson.functional.ExposeFieldsTest.testExposedInterfaceFieldDeserialization:110:*>/home/stg/omc_experiments/slices/gson/functional_slices/ExposeFieldsTest/ExposeFieldsTest11.txt

#Total Asserts in com.google.gson.functional/ExposeFieldsTest=============11
#Total Tests in com.google.gson.functional/ExposeFieldsTest=============0
