#!/bin/bash

echo "computing slice for ArrayTest"

mkdir -p /home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testTopLevelArrayOfIntsSerialization:50:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testTopLevelArrayOfIntsDeserialization:56:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testEmptyArraySerialization:70:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testEmptyArrayDeserialization:75:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testEmptyArrayDeserialization:78:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testEmptyArrayDeserialization:81:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testNullsInArraySerialization:88:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testNullsInArrayDeserialization:96:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testSingleNullInArraySerialization:104:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testSingleNullInArrayDeserialization:109:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testNullsInArrayWithSerializeNullPropertySetSerialization:117:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testArrayOfStringsSerialization:122:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testArrayOfStringsDeserialization:128:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testArrayOfStringsDeserialization:129:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest14.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testSingleStringArraySerialization:135:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest15.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testSingleStringArrayDeserialization:141:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest16.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testSingleStringArrayDeserialization:142:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest17.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testArrayOfCollectionSerialization:167:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest18.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testArrayOfCollectionDeserialization:175:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest19.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testArrayOfCollectionDeserialization:176:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest20.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testArrayOfCollectionDeserialization:177:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest21.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testArrayOfPrimitivesAsObjectsSerialization:183:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest22.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testArrayOfPrimitivesAsObjectsSerialization:184:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest23.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testArrayOfPrimitivesAsObjectsSerialization:185:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest24.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testArrayOfPrimitivesAsObjectsDeserialization:191:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest25.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testArrayOfPrimitivesAsObjectsDeserialization:192:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest26.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testArrayOfPrimitivesAsObjectsDeserialization:193:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest27.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testArrayOfPrimitivesAsObjectsDeserialization:194:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest28.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testArrayOfPrimitivesAsObjectsDeserialization:195:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest29.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testObjectArrayWithNonPrimitivesSerialization:207:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest30.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testObjectArrayWithNonPrimitivesSerialization:208:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest31.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testArrayOfNullSerialization:214:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest32.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testArrayOfNullDeserialization:219:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest33.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testMultidimenstionalArraysSerialization:231:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest34.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testMultidimenstionalArraysSerialization:232:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest35.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testMultiDimenstionalObjectArraysSerialization:237:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest36.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testMixingTypesInObjectArraySerialization:245:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest37.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testMultidimenstionalArraysDeserialization:255:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest38.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testMultidimenstionalArraysDeserialization:256:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest39.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/ArrayTest.trace com.google.gson.functional.ArrayTest.testArrayElementsAreArrays:265:*>/home/stg/omc_experiments/slices/gson/functional_slices/ArrayTest/ArrayTest40.txt

#Total Asserts in com.google.gson.functional/ArrayTest=============40
#Total Tests in com.google.gson.functional/ArrayTest=============0
