#!/bin/bash

echo "computing slice for JsonAdapterAnnotationOnClassesTest"

mkdir -p /home/stg/omc_experiments/slices/gson/functional_slices/JsonAdapterAnnotationOnClassesTest

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/JsonAdapterAnnotationOnClassesTest.trace com.google.gson.functional.JsonAdapterAnnotationOnClassesTest.testJsonAdapterInvoked:47:*>/home/stg/omc_experiments/slices/gson/functional_slices/JsonAdapterAnnotationOnClassesTest/JsonAdapterAnnotationOnClassesTest1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/JsonAdapterAnnotationOnClassesTest.trace com.google.gson.functional.JsonAdapterAnnotationOnClassesTest.testJsonAdapterInvoked:51:*>/home/stg/omc_experiments/slices/gson/functional_slices/JsonAdapterAnnotationOnClassesTest/JsonAdapterAnnotationOnClassesTest2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/JsonAdapterAnnotationOnClassesTest.trace com.google.gson.functional.JsonAdapterAnnotationOnClassesTest.testJsonAdapterInvoked:53:*>/home/stg/omc_experiments/slices/gson/functional_slices/JsonAdapterAnnotationOnClassesTest/JsonAdapterAnnotationOnClassesTest3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/JsonAdapterAnnotationOnClassesTest.trace com.google.gson.functional.JsonAdapterAnnotationOnClassesTest.testJsonAdapterInvoked:54:*>/home/stg/omc_experiments/slices/gson/functional_slices/JsonAdapterAnnotationOnClassesTest/JsonAdapterAnnotationOnClassesTest4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/JsonAdapterAnnotationOnClassesTest.trace com.google.gson.functional.JsonAdapterAnnotationOnClassesTest.testJsonAdapterInvoked:57:*>/home/stg/omc_experiments/slices/gson/functional_slices/JsonAdapterAnnotationOnClassesTest/JsonAdapterAnnotationOnClassesTest5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/JsonAdapterAnnotationOnClassesTest.trace com.google.gson.functional.JsonAdapterAnnotationOnClassesTest.testJsonAdapterInvoked:59:*>/home/stg/omc_experiments/slices/gson/functional_slices/JsonAdapterAnnotationOnClassesTest/JsonAdapterAnnotationOnClassesTest6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/JsonAdapterAnnotationOnClassesTest.trace com.google.gson.functional.JsonAdapterAnnotationOnClassesTest.testJsonAdapterFactoryInvoked:65:*>/home/stg/omc_experiments/slices/gson/functional_slices/JsonAdapterAnnotationOnClassesTest/JsonAdapterAnnotationOnClassesTest7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/JsonAdapterAnnotationOnClassesTest.trace com.google.gson.functional.JsonAdapterAnnotationOnClassesTest.testJsonAdapterFactoryInvoked:67:*>/home/stg/omc_experiments/slices/gson/functional_slices/JsonAdapterAnnotationOnClassesTest/JsonAdapterAnnotationOnClassesTest8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/JsonAdapterAnnotationOnClassesTest.trace com.google.gson.functional.JsonAdapterAnnotationOnClassesTest.read:83:*>/home/stg/omc_experiments/slices/gson/functional_slices/JsonAdapterAnnotationOnClassesTest/JsonAdapterAnnotationOnClassesTest9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/JsonAdapterAnnotationOnClassesTest.trace com.google.gson.functional.JsonAdapterAnnotationOnClassesTest.serialize:100:*>/home/stg/omc_experiments/slices/gson/functional_slices/JsonAdapterAnnotationOnClassesTest/JsonAdapterAnnotationOnClassesTest10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/JsonAdapterAnnotationOnClassesTest.trace com.google.gson.functional.JsonAdapterAnnotationOnClassesTest.serialize:102:*>/home/stg/omc_experiments/slices/gson/functional_slices/JsonAdapterAnnotationOnClassesTest/JsonAdapterAnnotationOnClassesTest11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/JsonAdapterAnnotationOnClassesTest.trace com.google.gson.functional.JsonAdapterAnnotationOnClassesTest.deserialize:119:*>/home/stg/omc_experiments/slices/gson/functional_slices/JsonAdapterAnnotationOnClassesTest/JsonAdapterAnnotationOnClassesTest12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/JsonAdapterAnnotationOnClassesTest.trace com.google.gson.functional.JsonAdapterAnnotationOnClassesTest.deserialize:121:*>/home/stg/omc_experiments/slices/gson/functional_slices/JsonAdapterAnnotationOnClassesTest/JsonAdapterAnnotationOnClassesTest13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/JsonAdapterAnnotationOnClassesTest.trace com.google.gson.functional.JsonAdapterAnnotationOnClassesTest.testSuperclassTypeAdapterNotInvoked:133:*>/home/stg/omc_experiments/slices/gson/functional_slices/JsonAdapterAnnotationOnClassesTest/JsonAdapterAnnotationOnClassesTest14.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/JsonAdapterAnnotationOnClassesTest.trace com.google.gson.functional.JsonAdapterAnnotationOnClassesTest.testNullSafeObjectFromJson:139:*>/home/stg/omc_experiments/slices/gson/functional_slices/JsonAdapterAnnotationOnClassesTest/JsonAdapterAnnotationOnClassesTest15.txt

#Total Asserts in com.google.gson.functional/JsonAdapterAnnotationOnClassesTest=============15
#Total Tests in com.google.gson.functional/JsonAdapterAnnotationOnClassesTest=============0
