#!/bin/bash

echo "computing slice for TypeHierarchyAdapterTest"

mkdir -p /home/stg/omc_experiments/slices/gson/functional_slices/TypeHierarchyAdapterTest

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/TypeHierarchyAdapterTest.trace com.google.gson.functional.TypeHierarchyAdapterTest.testTypeHierarchy:67:*>/home/stg/omc_experiments/slices/gson/functional_slices/TypeHierarchyAdapterTest/TypeHierarchyAdapterTest1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/TypeHierarchyAdapterTest.trace com.google.gson.functional.TypeHierarchyAdapterTest.testTypeHierarchy:107:*>/home/stg/omc_experiments/slices/gson/functional_slices/TypeHierarchyAdapterTest/TypeHierarchyAdapterTest2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/TypeHierarchyAdapterTest.trace com.google.gson.functional.TypeHierarchyAdapterTest.testTypeHierarchy:108:*>/home/stg/omc_experiments/slices/gson/functional_slices/TypeHierarchyAdapterTest/TypeHierarchyAdapterTest3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/TypeHierarchyAdapterTest.trace com.google.gson.functional.TypeHierarchyAdapterTest.testTypeHierarchy:109:*>/home/stg/omc_experiments/slices/gson/functional_slices/TypeHierarchyAdapterTest/TypeHierarchyAdapterTest4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/TypeHierarchyAdapterTest.trace com.google.gson.functional.TypeHierarchyAdapterTest.testTypeHierarchy:110:*>/home/stg/omc_experiments/slices/gson/functional_slices/TypeHierarchyAdapterTest/TypeHierarchyAdapterTest5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/TypeHierarchyAdapterTest.trace com.google.gson.functional.TypeHierarchyAdapterTest.testTypeHierarchy:111:*>/home/stg/omc_experiments/slices/gson/functional_slices/TypeHierarchyAdapterTest/TypeHierarchyAdapterTest6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/TypeHierarchyAdapterTest.trace com.google.gson.functional.TypeHierarchyAdapterTest.testTypeHierarchy:112:*>/home/stg/omc_experiments/slices/gson/functional_slices/TypeHierarchyAdapterTest/TypeHierarchyAdapterTest7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/TypeHierarchyAdapterTest.trace com.google.gson.functional.TypeHierarchyAdapterTest.testTypeHierarchy:113:*>/home/stg/omc_experiments/slices/gson/functional_slices/TypeHierarchyAdapterTest/TypeHierarchyAdapterTest8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/TypeHierarchyAdapterTest.trace com.google.gson.functional.TypeHierarchyAdapterTest.testTypeHierarchy:115:*>/home/stg/omc_experiments/slices/gson/functional_slices/TypeHierarchyAdapterTest/TypeHierarchyAdapterTest9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/TypeHierarchyAdapterTest.trace com.google.gson.functional.TypeHierarchyAdapterTest.testRegisterSuperTypeFirst:129:*>/home/stg/omc_experiments/slices/gson/functional_slices/TypeHierarchyAdapterTest/TypeHierarchyAdapterTest10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/gson/functional_traces/TypeHierarchyAdapterTest.trace com.google.gson.functional.TypeHierarchyAdapterTest.testRegisterSuperTypeFirst:131:*>/home/stg/omc_experiments/slices/gson/functional_slices/TypeHierarchyAdapterTest/TypeHierarchyAdapterTest11.txt

#Total Asserts in com.google.gson.functional/TypeHierarchyAdapterTest=============11
#Total Tests in com.google.gson.functional/TypeHierarchyAdapterTest=============0
