#!/bin/bash

echo "computing slice for TestMutableInterval_Updates"

mkdir -p /home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testTest:142:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testTest:143:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testTest:144:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetInterval_long_long1:151:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetInterval_long_long1:152:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetInterval_RI_RI1:167:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetInterval_RI_RI1:168:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetInterval_RI_RI3:182:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetInterval_RI_RI3:183:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetInterval_RI_RI4:189:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetInterval_RI_RI4:190:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetInterval_RI_RI5:196:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetInterval_RI_RI5:197:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetInterval_RInterval1:204:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates14.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetInterval_RInterval1:205:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates15.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetStartMillis_long1:240:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates16.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetStartMillis_long1:241:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates17.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetStart_RI1:256:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates18.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetStart_RI1:257:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates19.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetStart_RI3:271:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates20.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetStart_RI3:272:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates21.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetEndMillis_long1:279:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates22.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetEndMillis_long1:280:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates23.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetEnd_RI1:295:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates24.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetEnd_RI1:296:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates25.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetEnd_RI3:310:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates26.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetEnd_RI3:311:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates27.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetDurationAfterStart_long1:318:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates28.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetDurationAfterStart_long1:319:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates29.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetDurationAfterStart_RI1:334:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates30.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetDurationAfterStart_RI1:335:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates31.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetDurationAfterStart_RI3:349:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates32.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetDurationAfterStart_RI3:350:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates33.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetDurationBeforeEnd_long1:357:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates34.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetDurationBeforeEnd_long1:358:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates35.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetDurationBeforeEnd_RI1:373:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates36.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetDurationBeforeEnd_RI1:374:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates37.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetDurationBeforeEnd_RI3:388:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates38.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetDurationBeforeEnd_RI3:389:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates39.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetPeriodAfterStart_RI1:396:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates40.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetPeriodAfterStart_RI1:397:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates41.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetPeriodAfterStart_RI3:411:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates42.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetPeriodAfterStart_RI3:412:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates43.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetPeriodBeforeEnd_RI1:419:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates44.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetPeriodBeforeEnd_RI1:420:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates45.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetPeriodBeforeEnd_RI3:434:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates46.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutableInterval_Updates.trace org.joda.time.TestMutableInterval_Updates.testSetPeriodBeforeEnd_RI3:435:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutableInterval_Updates/TestMutableInterval_Updates47.txt

#Total Asserts in org.joda.time/TestMutableInterval_Updates=============47
#Total Tests in org.joda.time/TestMutableInterval_Updates=============0
