#!/bin/bash

echo "computing slice for TestBasePartial"

mkdir -p /home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestBasePartial

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestBasePartial.trace org.joda.time.TestBasePartial.testSetMethods:79:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestBasePartial/TestBasePartial1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestBasePartial.trace org.joda.time.TestBasePartial.testSetMethods:80:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestBasePartial/TestBasePartial2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestBasePartial.trace org.joda.time.TestBasePartial.testSetMethods:83:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestBasePartial/TestBasePartial3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestBasePartial.trace org.joda.time.TestBasePartial.testSetMethods:84:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestBasePartial/TestBasePartial4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestBasePartial.trace org.joda.time.TestBasePartial.testSetMethods:87:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestBasePartial/TestBasePartial5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestBasePartial.trace org.joda.time.TestBasePartial.testSetMethods:88:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestBasePartial/TestBasePartial6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestBasePartial.trace org.joda.time.TestBasePartial.testSetMethods:91:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestBasePartial/TestBasePartial7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestBasePartial.trace org.joda.time.TestBasePartial.testSetMethods:92:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestBasePartial/TestBasePartial8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestBasePartial.trace org.joda.time.TestBasePartial.testSetMethods:98:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestBasePartial/TestBasePartial9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestBasePartial.trace org.joda.time.TestBasePartial.testSetMethods:99:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestBasePartial/TestBasePartial10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestBasePartial.trace org.joda.time.TestBasePartial.testSetMethods:105:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestBasePartial/TestBasePartial11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestBasePartial.trace org.joda.time.TestBasePartial.testSetMethods:106:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestBasePartial/TestBasePartial12.txt

#Total Asserts in org.joda.time/TestBasePartial=============12
#Total Tests in org.joda.time/TestBasePartial=============0
