#!/bin/bash

echo "computing slice for TestAbstractPartial"

mkdir -p /home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestAbstractPartial

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestAbstractPartial.trace org.joda.time.TestAbstractPartial.testGetValue:87:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestAbstractPartial/TestAbstractPartial1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestAbstractPartial.trace org.joda.time.TestAbstractPartial.testGetValue:88:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestAbstractPartial/TestAbstractPartial2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestAbstractPartial.trace org.joda.time.TestAbstractPartial.testGetValues:103:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestAbstractPartial/TestAbstractPartial3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestAbstractPartial.trace org.joda.time.TestAbstractPartial.testGetValues:104:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestAbstractPartial/TestAbstractPartial4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestAbstractPartial.trace org.joda.time.TestAbstractPartial.testGetValues:105:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestAbstractPartial/TestAbstractPartial5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestAbstractPartial.trace org.joda.time.TestAbstractPartial.testGetField:110:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestAbstractPartial/TestAbstractPartial6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestAbstractPartial.trace org.joda.time.TestAbstractPartial.testGetField:111:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestAbstractPartial/TestAbstractPartial7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestAbstractPartial.trace org.joda.time.TestAbstractPartial.testGetFieldType:125:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestAbstractPartial/TestAbstractPartial8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestAbstractPartial.trace org.joda.time.TestAbstractPartial.testGetFieldType:126:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestAbstractPartial/TestAbstractPartial9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestAbstractPartial.trace org.joda.time.TestAbstractPartial.testGetFieldTypes:141:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestAbstractPartial/TestAbstractPartial10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestAbstractPartial.trace org.joda.time.TestAbstractPartial.testGetFieldTypes:142:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestAbstractPartial/TestAbstractPartial11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestAbstractPartial.trace org.joda.time.TestAbstractPartial.testGetFieldTypes:143:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestAbstractPartial/TestAbstractPartial12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestAbstractPartial.trace org.joda.time.TestAbstractPartial.testGetPropertyEquals:148:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestAbstractPartial/TestAbstractPartial13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestAbstractPartial.trace org.joda.time.TestAbstractPartial.testGetPropertyEquals:149:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestAbstractPartial/TestAbstractPartial14.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestAbstractPartial.trace org.joda.time.TestAbstractPartial.testGetPropertyEquals:150:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestAbstractPartial/TestAbstractPartial15.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestAbstractPartial.trace org.joda.time.TestAbstractPartial.testGetPropertyEquals:151:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestAbstractPartial/TestAbstractPartial16.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestAbstractPartial.trace org.joda.time.TestAbstractPartial.testGetPropertyEquals:152:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestAbstractPartial/TestAbstractPartial17.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestAbstractPartial.trace org.joda.time.TestAbstractPartial.testGetPropertyEquals:153:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestAbstractPartial/TestAbstractPartial18.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestAbstractPartial.trace org.joda.time.TestAbstractPartial.testGetPropertyEquals:154:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestAbstractPartial/TestAbstractPartial19.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestAbstractPartial.trace org.joda.time.TestAbstractPartial.testGetPropertyEquals:155:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestAbstractPartial/TestAbstractPartial20.txt

#Total Asserts in org.joda.time/TestAbstractPartial=============20
#Total Tests in org.joda.time/TestAbstractPartial=============0
