#!/bin/bash

echo "computing slice for TestChronology"

mkdir -p /home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testTest:120:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testTest:121:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testTest:122:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_ISO:131:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_ISO:132:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_ISO:138:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_ISO:139:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_ISO:141:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_ISO:142:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_Lenient:151:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_Lenient:152:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_Lenient:158:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_Lenient:159:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_Lenient:161:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology14.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_Lenient:162:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology15.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_Strict:171:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology16.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_Strict:172:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology17.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_Strict:178:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology18.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_Strict:179:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology19.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_Strict:181:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology20.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_Strict:182:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology21.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_Limit:196:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology22.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_Limit:197:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology23.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_Limit:198:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology24.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_Limit:205:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology25.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_Limit:206:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology26.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_Limit:207:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology27.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_Limit:209:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology28.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_Limit:210:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology29.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_Limit:211:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology30.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_Zoned:223:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology31.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_Zoned:224:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology32.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_Zoned:230:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology33.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_Zoned:231:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology34.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_Zoned:233:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology35.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testEqualsHashCode_Zoned:234:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology36.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testToString:242:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology37.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testToString:243:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology38.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testToString:244:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology39.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testToString:245:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology40.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testToString:246:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology41.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testToString:247:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology42.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testToString:248:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology43.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testToString:249:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology44.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testToString:251:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology45.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testToString:252:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology46.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testToString:253:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology47.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestChronology.trace org.joda.time.TestChronology.testToString:254:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestChronology/TestChronology48.txt

#Total Asserts in org.joda.time/TestChronology=============48
#Total Tests in org.joda.time/TestChronology=============0
