#!/bin/bash

echo "computing slice for TestStringConvert"

mkdir -p /home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testDateMidnight:80:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testDateMidnight:81:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testDateTime:87:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testDateTime:88:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testMutableDateTime:94:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testMutableDateTime:95:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testLocalDateTime:101:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testLocalDateTime:102:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testLocalDate:108:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testLocalDate:109:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testLocalTime:115:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testLocalTime:116:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testYearMonth:122:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testYearMonth:123:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert14.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testMonthDay:129:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert15.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testMonthDay:130:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert16.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testMonthDay_leapDay:136:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert17.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testMonthDay_leapDay:137:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert18.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testTimeZone:144:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert19.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testTimeZone:145:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert20.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testDuration:160:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert21.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testDuration:161:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert22.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testPeriod:167:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert23.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testPeriod:168:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert24.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testMutablePeriod:174:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert25.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testMutablePeriod:175:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert26.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testYears:181:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert27.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testYears:182:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert28.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testMonths:188:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert29.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testMonths:189:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert30.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testWeeks:195:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert31.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testWeeks:196:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert32.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testDays:202:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert33.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testDays:203:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert34.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testHours:209:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert35.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testHours:210:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert36.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testMinutes:216:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert37.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testMinutes:217:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert38.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testSeconds:223:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert39.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestStringConvert.trace org.joda.time.TestStringConvert.testSeconds:224:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestStringConvert/TestStringConvert40.txt

#Total Asserts in org.joda.time/TestStringConvert=============40
#Total Tests in org.joda.time/TestStringConvert=============0
