#!/bin/bash

echo "computing slice for TestMutablePeriod_Basics"

mkdir -p /home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testTest:163:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testTest:164:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testTest:165:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testGetPeriodType:172:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testGetMethods:178:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testGetMethods:179:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testGetMethods:180:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testGetMethods:181:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testGetMethods:182:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testGetMethods:183:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testGetMethods:184:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testGetMethods:185:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testGetMethods:186:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testEqualsHashCode:193:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics14.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testEqualsHashCode:194:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics15.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testEqualsHashCode:195:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics16.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testEqualsHashCode:196:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics17.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testEqualsHashCode:197:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics18.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testEqualsHashCode:198:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics19.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testEqualsHashCode:199:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics20.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testEqualsHashCode:202:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics21.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testEqualsHashCode:203:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics22.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testEqualsHashCode:204:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics23.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testEqualsHashCode:205:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics24.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testEqualsHashCode:206:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics25.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testEqualsHashCode:207:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics26.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testEqualsHashCode:209:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics27.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testEqualsHashCode:210:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics28.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testEqualsHashCode:211:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics29.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testSerialization:236:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics30.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testToString:468:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics31.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testToString:471:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics32.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testToString:474:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics33.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testToPeriod:482:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics34.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testToMutablePeriod:489:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics35.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testToDurationFrom:501:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics36.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testCopy:509:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics37.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testCopy:510:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics38.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testClone:518:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics39.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestMutablePeriod_Basics.trace org.joda.time.TestMutablePeriod_Basics.testClone:519:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestMutablePeriod_Basics/TestMutablePeriod_Basics40.txt

#Total Asserts in org.joda.time/TestMutablePeriod_Basics=============40
#Total Tests in org.joda.time/TestMutablePeriod_Basics=============0
