#!/bin/bash

echo "computing slice for TestDuration_Constructors"

mkdir -p /home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestDuration_Constructors

timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestDuration_Constructors.trace org.joda.time.TestDuration_Constructors.testZERO:128:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestDuration_Constructors/TestDuration_Constructors1.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestDuration_Constructors.trace org.joda.time.TestDuration_Constructors.testParse_noFormatter:133:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestDuration_Constructors/TestDuration_Constructors2.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestDuration_Constructors.trace org.joda.time.TestDuration_Constructors.testParse_noFormatter:134:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestDuration_Constructors/TestDuration_Constructors3.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestDuration_Constructors.trace org.joda.time.TestDuration_Constructors.testFactory_standardDays_long:140:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestDuration_Constructors/TestDuration_Constructors4.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestDuration_Constructors.trace org.joda.time.TestDuration_Constructors.testFactory_standardDays_long:143:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestDuration_Constructors/TestDuration_Constructors5.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestDuration_Constructors.trace org.joda.time.TestDuration_Constructors.testFactory_standardDays_long:146:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestDuration_Constructors/TestDuration_Constructors6.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestDuration_Constructors.trace org.joda.time.TestDuration_Constructors.testFactory_standardHours_long:152:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestDuration_Constructors/TestDuration_Constructors7.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestDuration_Constructors.trace org.joda.time.TestDuration_Constructors.testFactory_standardHours_long:155:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestDuration_Constructors/TestDuration_Constructors8.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestDuration_Constructors.trace org.joda.time.TestDuration_Constructors.testFactory_standardHours_long:158:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestDuration_Constructors/TestDuration_Constructors9.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestDuration_Constructors.trace org.joda.time.TestDuration_Constructors.testFactory_standardMinutes_long:164:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestDuration_Constructors/TestDuration_Constructors10.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestDuration_Constructors.trace org.joda.time.TestDuration_Constructors.testFactory_standardMinutes_long:167:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestDuration_Constructors/TestDuration_Constructors11.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestDuration_Constructors.trace org.joda.time.TestDuration_Constructors.testFactory_standardMinutes_long:170:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestDuration_Constructors/TestDuration_Constructors12.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestDuration_Constructors.trace org.joda.time.TestDuration_Constructors.testFactory_standardSeconds_long:176:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestDuration_Constructors/TestDuration_Constructors13.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestDuration_Constructors.trace org.joda.time.TestDuration_Constructors.testFactory_standardSeconds_long:179:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestDuration_Constructors/TestDuration_Constructors14.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestDuration_Constructors.trace org.joda.time.TestDuration_Constructors.testFactory_standardSeconds_long:182:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestDuration_Constructors/TestDuration_Constructors15.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestDuration_Constructors.trace org.joda.time.TestDuration_Constructors.testFactory_millis_long:188:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestDuration_Constructors/TestDuration_Constructors16.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestDuration_Constructors.trace org.joda.time.TestDuration_Constructors.testFactory_millis_long:191:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestDuration_Constructors/TestDuration_Constructors17.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestDuration_Constructors.trace org.joda.time.TestDuration_Constructors.testFactory_millis_long:194:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestDuration_Constructors/TestDuration_Constructors18.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestDuration_Constructors.trace org.joda.time.TestDuration_Constructors.testConstructor_long1:204:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestDuration_Constructors/TestDuration_Constructors19.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestDuration_Constructors.trace org.joda.time.TestDuration_Constructors.testConstructor_long_long1:212:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestDuration_Constructors/TestDuration_Constructors20.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestDuration_Constructors.trace org.joda.time.TestDuration_Constructors.testConstructor_RI_RI1:220:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestDuration_Constructors/TestDuration_Constructors21.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestDuration_Constructors.trace org.joda.time.TestDuration_Constructors.testConstructor_RI_RI2:227:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestDuration_Constructors/TestDuration_Constructors22.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestDuration_Constructors.trace org.joda.time.TestDuration_Constructors.testConstructor_RI_RI3:234:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestDuration_Constructors/TestDuration_Constructors23.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestDuration_Constructors.trace org.joda.time.TestDuration_Constructors.testConstructor_RI_RI4:241:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestDuration_Constructors/TestDuration_Constructors24.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestDuration_Constructors.trace org.joda.time.TestDuration_Constructors.testConstructor_Object1:250:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestDuration_Constructors/TestDuration_Constructors25.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestDuration_Constructors.trace org.joda.time.TestDuration_Constructors.testConstructor_Object2:255:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestDuration_Constructors/TestDuration_Constructors26.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestDuration_Constructors.trace org.joda.time.TestDuration_Constructors.testConstructor_Object3:265:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestDuration_Constructors/TestDuration_Constructors27.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestDuration_Constructors.trace org.joda.time.TestDuration_Constructors.testConstructor_Object4:273:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestDuration_Constructors/TestDuration_Constructors28.txt
timeout $OMC_TRACE_TIMEOUT_SEC java -Xmx30g  -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-joda-time/time_traces/TestDuration_Constructors.trace org.joda.time.TestDuration_Constructors.testConstructor_Object5:281:*>/home/stg/omc_experiments/slices/fse-joda-time/time_slices/TestDuration_Constructors/TestDuration_Constructors29.txt

#Total Asserts in org.joda.time/TestDuration_Constructors=============29
#Total Tests in org.joda.time/TestDuration_Constructors=============0
