#!/bin/bash

echo "computing slice for PlotTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/plot_slices/PlotTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PlotTest.trace org.jfree.chart.plot.PlotTest.testEquals:75:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PlotTest/PlotTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PlotTest.trace org.jfree.chart.plot.PlotTest.testEquals:76:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PlotTest/PlotTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PlotTest.trace org.jfree.chart.plot.PlotTest.testEquals:80:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PlotTest/PlotTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PlotTest.trace org.jfree.chart.plot.PlotTest.testEquals:82:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PlotTest/PlotTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PlotTest.trace org.jfree.chart.plot.PlotTest.testEquals:86:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PlotTest/PlotTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PlotTest.trace org.jfree.chart.plot.PlotTest.testEquals:88:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PlotTest/PlotTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PlotTest.trace org.jfree.chart.plot.PlotTest.testEquals:93:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PlotTest/PlotTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PlotTest.trace org.jfree.chart.plot.PlotTest.testEquals:96:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PlotTest/PlotTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PlotTest.trace org.jfree.chart.plot.PlotTest.testEquals:100:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PlotTest/PlotTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PlotTest.trace org.jfree.chart.plot.PlotTest.testEquals:102:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PlotTest/PlotTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PlotTest.trace org.jfree.chart.plot.PlotTest.testEquals:106:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PlotTest/PlotTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PlotTest.trace org.jfree.chart.plot.PlotTest.testEquals:108:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PlotTest/PlotTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PlotTest.trace org.jfree.chart.plot.PlotTest.testEquals:113:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PlotTest/PlotTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PlotTest.trace org.jfree.chart.plot.PlotTest.testEquals:115:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PlotTest/PlotTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PlotTest.trace org.jfree.chart.plot.PlotTest.testEquals:120:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PlotTest/PlotTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PlotTest.trace org.jfree.chart.plot.PlotTest.testEquals:123:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PlotTest/PlotTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PlotTest.trace org.jfree.chart.plot.PlotTest.testEquals:128:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PlotTest/PlotTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PlotTest.trace org.jfree.chart.plot.PlotTest.testEquals:131:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PlotTest/PlotTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PlotTest.trace org.jfree.chart.plot.PlotTest.testEquals:141:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PlotTest/PlotTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PlotTest.trace org.jfree.chart.plot.PlotTest.testEquals:143:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PlotTest/PlotTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PlotTest.trace org.jfree.chart.plot.PlotTest.testEquals:147:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PlotTest/PlotTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PlotTest.trace org.jfree.chart.plot.PlotTest.testEquals:149:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PlotTest/PlotTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PlotTest.trace org.jfree.chart.plot.PlotTest.testEquals:153:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PlotTest/PlotTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PlotTest.trace org.jfree.chart.plot.PlotTest.testEquals:155:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PlotTest/PlotTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PlotTest.trace org.jfree.chart.plot.PlotTest.testEquals:159:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PlotTest/PlotTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PlotTest.trace org.jfree.chart.plot.PlotTest.testEquals:161:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PlotTest/PlotTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PlotTest.trace org.jfree.chart.plot.PlotTest.testEquals:169:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PlotTest/PlotTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PlotTest.trace org.jfree.chart.plot.PlotTest.testEquals:175:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PlotTest/PlotTest28.txt

#Total Asserts in org.jfree.chart.plot/PlotTest=============28
#Total Tests in org.jfree.chart.plot/PlotTest=============0
