#!/bin/bash

echo "computing slice for FastScatterPlotTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals:74:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals:75:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals:79:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals:82:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals:85:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals:87:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals:91:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals:94:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals:98:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals:100:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals:103:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals:105:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals:109:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals:112:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals:116:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals:118:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals:121:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals:123:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals:126:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals:128:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals2:139:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals2:140:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals2:145:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals2:147:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals2:150:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals2:152:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals2:155:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals2:157:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals2:160:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals2:162:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals2:165:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals2:167:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest32.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals2:170:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest33.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testEquals2:172:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest34.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testCloning:182:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest35.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testCloning:183:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest36.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testCloning:184:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest37.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/FastScatterPlotTest.trace org.jfree.chart.plot.FastScatterPlotTest.testSerialization:197:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/FastScatterPlotTest/FastScatterPlotTest38.txt

#Total Asserts in org.jfree.chart.plot/FastScatterPlotTest=============38
#Total Tests in org.jfree.chart.plot/FastScatterPlotTest=============0
