#!/bin/bash

echo "computing slice for DefaultDrawingSupplierTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/plot_slices/DefaultDrawingSupplierTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/DefaultDrawingSupplierTest.trace org.jfree.chart.plot.DefaultDrawingSupplierTest.testEquals:69:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/DefaultDrawingSupplierTest/DefaultDrawingSupplierTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/DefaultDrawingSupplierTest.trace org.jfree.chart.plot.DefaultDrawingSupplierTest.testEquals:70:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/DefaultDrawingSupplierTest/DefaultDrawingSupplierTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/DefaultDrawingSupplierTest.trace org.jfree.chart.plot.DefaultDrawingSupplierTest.testEquals:110:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/DefaultDrawingSupplierTest/DefaultDrawingSupplierTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/DefaultDrawingSupplierTest.trace org.jfree.chart.plot.DefaultDrawingSupplierTest.testEquals:114:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/DefaultDrawingSupplierTest/DefaultDrawingSupplierTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/DefaultDrawingSupplierTest.trace org.jfree.chart.plot.DefaultDrawingSupplierTest.testEquals:116:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/DefaultDrawingSupplierTest/DefaultDrawingSupplierTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/DefaultDrawingSupplierTest.trace org.jfree.chart.plot.DefaultDrawingSupplierTest.testEquals:119:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/DefaultDrawingSupplierTest/DefaultDrawingSupplierTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/DefaultDrawingSupplierTest.trace org.jfree.chart.plot.DefaultDrawingSupplierTest.testEquals:121:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/DefaultDrawingSupplierTest/DefaultDrawingSupplierTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/DefaultDrawingSupplierTest.trace org.jfree.chart.plot.DefaultDrawingSupplierTest.testEquals:124:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/DefaultDrawingSupplierTest/DefaultDrawingSupplierTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/DefaultDrawingSupplierTest.trace org.jfree.chart.plot.DefaultDrawingSupplierTest.testEquals:126:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/DefaultDrawingSupplierTest/DefaultDrawingSupplierTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/DefaultDrawingSupplierTest.trace org.jfree.chart.plot.DefaultDrawingSupplierTest.testEquals:129:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/DefaultDrawingSupplierTest/DefaultDrawingSupplierTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/DefaultDrawingSupplierTest.trace org.jfree.chart.plot.DefaultDrawingSupplierTest.testEquals:131:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/DefaultDrawingSupplierTest/DefaultDrawingSupplierTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/DefaultDrawingSupplierTest.trace org.jfree.chart.plot.DefaultDrawingSupplierTest.testEquals:134:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/DefaultDrawingSupplierTest/DefaultDrawingSupplierTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/DefaultDrawingSupplierTest.trace org.jfree.chart.plot.DefaultDrawingSupplierTest.testEquals:136:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/DefaultDrawingSupplierTest/DefaultDrawingSupplierTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/DefaultDrawingSupplierTest.trace org.jfree.chart.plot.DefaultDrawingSupplierTest.testEquals:140:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/DefaultDrawingSupplierTest/DefaultDrawingSupplierTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/DefaultDrawingSupplierTest.trace org.jfree.chart.plot.DefaultDrawingSupplierTest.testEquals:142:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/DefaultDrawingSupplierTest/DefaultDrawingSupplierTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/DefaultDrawingSupplierTest.trace org.jfree.chart.plot.DefaultDrawingSupplierTest.testEquals:146:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/DefaultDrawingSupplierTest/DefaultDrawingSupplierTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/DefaultDrawingSupplierTest.trace org.jfree.chart.plot.DefaultDrawingSupplierTest.testEquals:148:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/DefaultDrawingSupplierTest/DefaultDrawingSupplierTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/DefaultDrawingSupplierTest.trace org.jfree.chart.plot.DefaultDrawingSupplierTest.testEquals:152:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/DefaultDrawingSupplierTest/DefaultDrawingSupplierTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/DefaultDrawingSupplierTest.trace org.jfree.chart.plot.DefaultDrawingSupplierTest.testEquals:154:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/DefaultDrawingSupplierTest/DefaultDrawingSupplierTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/DefaultDrawingSupplierTest.trace org.jfree.chart.plot.DefaultDrawingSupplierTest.testEquals:158:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/DefaultDrawingSupplierTest/DefaultDrawingSupplierTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/DefaultDrawingSupplierTest.trace org.jfree.chart.plot.DefaultDrawingSupplierTest.testEquals:160:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/DefaultDrawingSupplierTest/DefaultDrawingSupplierTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/DefaultDrawingSupplierTest.trace org.jfree.chart.plot.DefaultDrawingSupplierTest.testEquals:164:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/DefaultDrawingSupplierTest/DefaultDrawingSupplierTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/DefaultDrawingSupplierTest.trace org.jfree.chart.plot.DefaultDrawingSupplierTest.testEquals:166:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/DefaultDrawingSupplierTest/DefaultDrawingSupplierTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/DefaultDrawingSupplierTest.trace org.jfree.chart.plot.DefaultDrawingSupplierTest.testCloning:176:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/DefaultDrawingSupplierTest/DefaultDrawingSupplierTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/DefaultDrawingSupplierTest.trace org.jfree.chart.plot.DefaultDrawingSupplierTest.testCloning:177:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/DefaultDrawingSupplierTest/DefaultDrawingSupplierTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/DefaultDrawingSupplierTest.trace org.jfree.chart.plot.DefaultDrawingSupplierTest.testCloning:178:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/DefaultDrawingSupplierTest/DefaultDrawingSupplierTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/DefaultDrawingSupplierTest.trace org.jfree.chart.plot.DefaultDrawingSupplierTest.testSerialization:189:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/DefaultDrawingSupplierTest/DefaultDrawingSupplierTest27.txt

#Total Asserts in org.jfree.chart.plot/DefaultDrawingSupplierTest=============27
#Total Tests in org.jfree.chart.plot/DefaultDrawingSupplierTest=============0
