#!/bin/bash

echo "computing slice for MeterPlotTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:74:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:78:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:80:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:84:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:86:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:90:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:92:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:97:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:100:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:104:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:106:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:111:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:114:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:119:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:122:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:127:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:130:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:134:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:136:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:141:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:144:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:148:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:150:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:154:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:156:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:160:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:162:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:166:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:168:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:172:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:174:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:178:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest32.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:180:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest33.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:184:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest34.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:186:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest35.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:190:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest36.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testEquals:192:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest37.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testCloning:203:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest38.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testCloning:204:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest39.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testCloning:205:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest40.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testCloning:208:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest41.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testCloning:213:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest42.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testCloning:215:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest43.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testCloning:218:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest44.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testCloning:220:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest45.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testSerialization1:241:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest46.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/MeterPlotTest.trace org.jfree.chart.plot.MeterPlotTest.testSerialization2:251:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/MeterPlotTest/MeterPlotTest47.txt

#Total Asserts in org.jfree.chart.plot/MeterPlotTest=============47
#Total Tests in org.jfree.chart.plot/MeterPlotTest=============0
