#!/bin/bash

echo "computing slice for CategoryMarkerTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/plot_slices/CategoryMarkerTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/CategoryMarkerTest.trace org.jfree.chart.plot.CategoryMarkerTest.testEquals:82:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/CategoryMarkerTest/CategoryMarkerTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/CategoryMarkerTest.trace org.jfree.chart.plot.CategoryMarkerTest.testEquals:83:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/CategoryMarkerTest/CategoryMarkerTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/CategoryMarkerTest.trace org.jfree.chart.plot.CategoryMarkerTest.testEquals:87:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/CategoryMarkerTest/CategoryMarkerTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/CategoryMarkerTest.trace org.jfree.chart.plot.CategoryMarkerTest.testEquals:89:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/CategoryMarkerTest/CategoryMarkerTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/CategoryMarkerTest.trace org.jfree.chart.plot.CategoryMarkerTest.testEquals:94:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/CategoryMarkerTest/CategoryMarkerTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/CategoryMarkerTest.trace org.jfree.chart.plot.CategoryMarkerTest.testEquals:97:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/CategoryMarkerTest/CategoryMarkerTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/CategoryMarkerTest.trace org.jfree.chart.plot.CategoryMarkerTest.testEquals:102:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/CategoryMarkerTest/CategoryMarkerTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/CategoryMarkerTest.trace org.jfree.chart.plot.CategoryMarkerTest.testEquals:105:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/CategoryMarkerTest/CategoryMarkerTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/CategoryMarkerTest.trace org.jfree.chart.plot.CategoryMarkerTest.testEquals:111:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/CategoryMarkerTest/CategoryMarkerTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/CategoryMarkerTest.trace org.jfree.chart.plot.CategoryMarkerTest.testEquals:115:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/CategoryMarkerTest/CategoryMarkerTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/CategoryMarkerTest.trace org.jfree.chart.plot.CategoryMarkerTest.testEquals:121:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/CategoryMarkerTest/CategoryMarkerTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/CategoryMarkerTest.trace org.jfree.chart.plot.CategoryMarkerTest.testEquals:125:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/CategoryMarkerTest/CategoryMarkerTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/CategoryMarkerTest.trace org.jfree.chart.plot.CategoryMarkerTest.testEquals:131:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/CategoryMarkerTest/CategoryMarkerTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/CategoryMarkerTest.trace org.jfree.chart.plot.CategoryMarkerTest.testEquals:135:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/CategoryMarkerTest/CategoryMarkerTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/CategoryMarkerTest.trace org.jfree.chart.plot.CategoryMarkerTest.testCloning:148:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/CategoryMarkerTest/CategoryMarkerTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/CategoryMarkerTest.trace org.jfree.chart.plot.CategoryMarkerTest.testCloning:149:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/CategoryMarkerTest/CategoryMarkerTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/CategoryMarkerTest.trace org.jfree.chart.plot.CategoryMarkerTest.testCloning:150:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/CategoryMarkerTest/CategoryMarkerTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/CategoryMarkerTest.trace org.jfree.chart.plot.CategoryMarkerTest.testSerialization:162:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/CategoryMarkerTest/CategoryMarkerTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/CategoryMarkerTest.trace org.jfree.chart.plot.CategoryMarkerTest.testGetSetKey:173:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/CategoryMarkerTest/CategoryMarkerTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/CategoryMarkerTest.trace org.jfree.chart.plot.CategoryMarkerTest.testGetSetKey:175:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/CategoryMarkerTest/CategoryMarkerTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/CategoryMarkerTest.trace org.jfree.chart.plot.CategoryMarkerTest.testGetSetKey:176:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/CategoryMarkerTest/CategoryMarkerTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/CategoryMarkerTest.trace org.jfree.chart.plot.CategoryMarkerTest.testGetSetKey:184:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/CategoryMarkerTest/CategoryMarkerTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/CategoryMarkerTest.trace org.jfree.chart.plot.CategoryMarkerTest.testGetSetDrawAsLine:196:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/CategoryMarkerTest/CategoryMarkerTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/CategoryMarkerTest.trace org.jfree.chart.plot.CategoryMarkerTest.testGetSetDrawAsLine:198:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/CategoryMarkerTest/CategoryMarkerTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/CategoryMarkerTest.trace org.jfree.chart.plot.CategoryMarkerTest.testGetSetDrawAsLine:199:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/CategoryMarkerTest/CategoryMarkerTest25.txt

#Total Asserts in org.jfree.chart.plot/CategoryMarkerTest=============25
#Total Tests in org.jfree.chart.plot/CategoryMarkerTest=============0
