#!/bin/bash

echo "computing slice for IntervalMarkerTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/plot_slices/IntervalMarkerTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/IntervalMarkerTest.trace org.jfree.chart.plot.IntervalMarkerTest.testEquals:82:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/IntervalMarkerTest/IntervalMarkerTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/IntervalMarkerTest.trace org.jfree.chart.plot.IntervalMarkerTest.testEquals:83:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/IntervalMarkerTest/IntervalMarkerTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/IntervalMarkerTest.trace org.jfree.chart.plot.IntervalMarkerTest.testEquals:86:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/IntervalMarkerTest/IntervalMarkerTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/IntervalMarkerTest.trace org.jfree.chart.plot.IntervalMarkerTest.testEquals:88:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/IntervalMarkerTest/IntervalMarkerTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/IntervalMarkerTest.trace org.jfree.chart.plot.IntervalMarkerTest.testEquals:91:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/IntervalMarkerTest/IntervalMarkerTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/IntervalMarkerTest.trace org.jfree.chart.plot.IntervalMarkerTest.testEquals:93:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/IntervalMarkerTest/IntervalMarkerTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/IntervalMarkerTest.trace org.jfree.chart.plot.IntervalMarkerTest.testEquals:98:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/IntervalMarkerTest/IntervalMarkerTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/IntervalMarkerTest.trace org.jfree.chart.plot.IntervalMarkerTest.testEquals:100:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/IntervalMarkerTest/IntervalMarkerTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/IntervalMarkerTest.trace org.jfree.chart.plot.IntervalMarkerTest.testCloning:111:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/IntervalMarkerTest/IntervalMarkerTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/IntervalMarkerTest.trace org.jfree.chart.plot.IntervalMarkerTest.testCloning:112:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/IntervalMarkerTest/IntervalMarkerTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/IntervalMarkerTest.trace org.jfree.chart.plot.IntervalMarkerTest.testCloning:113:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/IntervalMarkerTest/IntervalMarkerTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/IntervalMarkerTest.trace org.jfree.chart.plot.IntervalMarkerTest.testSerialization:123:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/IntervalMarkerTest/IntervalMarkerTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/IntervalMarkerTest.trace org.jfree.chart.plot.IntervalMarkerTest.testGetSetStartValue:136:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/IntervalMarkerTest/IntervalMarkerTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/IntervalMarkerTest.trace org.jfree.chart.plot.IntervalMarkerTest.testGetSetStartValue:138:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/IntervalMarkerTest/IntervalMarkerTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/IntervalMarkerTest.trace org.jfree.chart.plot.IntervalMarkerTest.testGetSetStartValue:139:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/IntervalMarkerTest/IntervalMarkerTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/IntervalMarkerTest.trace org.jfree.chart.plot.IntervalMarkerTest.testGetSetEndValue:150:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/IntervalMarkerTest/IntervalMarkerTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/IntervalMarkerTest.trace org.jfree.chart.plot.IntervalMarkerTest.testGetSetEndValue:152:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/IntervalMarkerTest/IntervalMarkerTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/IntervalMarkerTest.trace org.jfree.chart.plot.IntervalMarkerTest.testGetSetEndValue:153:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/IntervalMarkerTest/IntervalMarkerTest18.txt

#Total Asserts in org.jfree.chart.plot/IntervalMarkerTest=============18
#Total Tests in org.jfree.chart.plot/IntervalMarkerTest=============0
