#!/bin/bash

echo "computing slice for PolarPlotTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testGetLegendItems:92:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testGetLegendItems:94:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testGetLegendItems:96:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testGetLegendItems2:117:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testGetLegendItems2:119:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testGetLegendItems2:121:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testGetLegendItems2:123:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testGetLegendItems2:125:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:135:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:136:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:140:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:143:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:147:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:149:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:152:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:154:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:157:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:159:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:162:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:164:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:168:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:171:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:174:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:176:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:179:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:181:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:185:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:188:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:191:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:193:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:196:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:198:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest32.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:201:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest33.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:203:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest34.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:206:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest35.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:208:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest36.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:211:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest37.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:213:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest38.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:218:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest39.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testEquals:222:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest40.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testCloning:232:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest41.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testCloning:233:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest42.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testCloning:234:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest43.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testCloning:238:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest44.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testCloning:240:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest45.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testCloning:245:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest46.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testCloning:246:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest47.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testCloning:247:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest48.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testCloning:251:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest49.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testCloning:253:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest50.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testSerialization:269:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest51.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxis:284:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest52.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxis:285:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest53.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxis:288:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest54.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxis:289:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest55.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxis:292:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest56.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxis:293:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest57.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxis:296:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest58.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxis:297:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest59.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxis:300:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest60.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxis:301:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest61.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxis:304:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest62.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxis:305:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest63.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxis:308:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest64.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxis:309:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest65.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxis:312:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest66.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxis:313:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest67.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxisAndMargin:328:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest68.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxisAndMargin:329:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest69.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxisAndMargin:332:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest70.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxisAndMargin:333:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest71.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxisAndMargin:336:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest72.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxisAndMargin:337:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest73.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxisAndMargin:340:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest74.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxisAndMargin:341:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest75.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxisAndMargin:344:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest76.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxisAndMargin:345:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest77.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxisAndMargin:348:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest78.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxisAndMargin:349:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest79.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxisAndMargin:352:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest80.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxisAndMargin:353:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest81.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxisAndMargin:356:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest82.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_NumberAxisAndMargin:357:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest83.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_LogAxis:373:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest84.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_LogAxis:374:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest85.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_LogAxis:377:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest86.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_LogAxis:378:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest87.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_LogAxis:381:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest88.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/plot_traces/PolarPlotTest.trace org.jfree.chart.plot.PolarPlotTest.testTranslateToJava2D_LogAxis:382:*>/home/stg/omc_experiments/slices/jfreechart/plot_slices/PolarPlotTest/PolarPlotTest89.txt

#Total Asserts in org.jfree.chart.plot/PolarPlotTest=============89
#Total Tests in org.jfree.chart.plot/PolarPlotTest=============0
