#!/bin/bash

echo "computing slice for CategoryPointerAnnotationTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/CategoryPointerAnnotationTest.trace org.jfree.chart.annotations.CategoryPointerAnnotationTest.testEquals:71:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest/CategoryPointerAnnotationTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/CategoryPointerAnnotationTest.trace org.jfree.chart.annotations.CategoryPointerAnnotationTest.testEquals:74:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest/CategoryPointerAnnotationTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/CategoryPointerAnnotationTest.trace org.jfree.chart.annotations.CategoryPointerAnnotationTest.testEquals:76:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest/CategoryPointerAnnotationTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/CategoryPointerAnnotationTest.trace org.jfree.chart.annotations.CategoryPointerAnnotationTest.testEquals:79:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest/CategoryPointerAnnotationTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/CategoryPointerAnnotationTest.trace org.jfree.chart.annotations.CategoryPointerAnnotationTest.testEquals:81:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest/CategoryPointerAnnotationTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/CategoryPointerAnnotationTest.trace org.jfree.chart.annotations.CategoryPointerAnnotationTest.testEquals:84:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest/CategoryPointerAnnotationTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/CategoryPointerAnnotationTest.trace org.jfree.chart.annotations.CategoryPointerAnnotationTest.testEquals:86:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest/CategoryPointerAnnotationTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/CategoryPointerAnnotationTest.trace org.jfree.chart.annotations.CategoryPointerAnnotationTest.testEquals:90:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest/CategoryPointerAnnotationTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/CategoryPointerAnnotationTest.trace org.jfree.chart.annotations.CategoryPointerAnnotationTest.testEquals:92:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest/CategoryPointerAnnotationTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/CategoryPointerAnnotationTest.trace org.jfree.chart.annotations.CategoryPointerAnnotationTest.testEquals:96:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest/CategoryPointerAnnotationTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/CategoryPointerAnnotationTest.trace org.jfree.chart.annotations.CategoryPointerAnnotationTest.testEquals:98:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest/CategoryPointerAnnotationTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/CategoryPointerAnnotationTest.trace org.jfree.chart.annotations.CategoryPointerAnnotationTest.testEquals:102:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest/CategoryPointerAnnotationTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/CategoryPointerAnnotationTest.trace org.jfree.chart.annotations.CategoryPointerAnnotationTest.testEquals:104:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest/CategoryPointerAnnotationTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/CategoryPointerAnnotationTest.trace org.jfree.chart.annotations.CategoryPointerAnnotationTest.testEquals:108:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest/CategoryPointerAnnotationTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/CategoryPointerAnnotationTest.trace org.jfree.chart.annotations.CategoryPointerAnnotationTest.testEquals:110:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest/CategoryPointerAnnotationTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/CategoryPointerAnnotationTest.trace org.jfree.chart.annotations.CategoryPointerAnnotationTest.testEquals:114:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest/CategoryPointerAnnotationTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/CategoryPointerAnnotationTest.trace org.jfree.chart.annotations.CategoryPointerAnnotationTest.testEquals:116:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest/CategoryPointerAnnotationTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/CategoryPointerAnnotationTest.trace org.jfree.chart.annotations.CategoryPointerAnnotationTest.testEquals:121:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest/CategoryPointerAnnotationTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/CategoryPointerAnnotationTest.trace org.jfree.chart.annotations.CategoryPointerAnnotationTest.testEquals:123:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest/CategoryPointerAnnotationTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/CategoryPointerAnnotationTest.trace org.jfree.chart.annotations.CategoryPointerAnnotationTest.testEquals:127:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest/CategoryPointerAnnotationTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/CategoryPointerAnnotationTest.trace org.jfree.chart.annotations.CategoryPointerAnnotationTest.testEquals:129:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest/CategoryPointerAnnotationTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/CategoryPointerAnnotationTest.trace org.jfree.chart.annotations.CategoryPointerAnnotationTest.testEquals:133:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest/CategoryPointerAnnotationTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/CategoryPointerAnnotationTest.trace org.jfree.chart.annotations.CategoryPointerAnnotationTest.testEquals:135:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest/CategoryPointerAnnotationTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/CategoryPointerAnnotationTest.trace org.jfree.chart.annotations.CategoryPointerAnnotationTest.testHashCode:147:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest/CategoryPointerAnnotationTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/CategoryPointerAnnotationTest.trace org.jfree.chart.annotations.CategoryPointerAnnotationTest.testHashCode:150:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest/CategoryPointerAnnotationTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/CategoryPointerAnnotationTest.trace org.jfree.chart.annotations.CategoryPointerAnnotationTest.testCloning:161:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest/CategoryPointerAnnotationTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/CategoryPointerAnnotationTest.trace org.jfree.chart.annotations.CategoryPointerAnnotationTest.testCloning:162:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest/CategoryPointerAnnotationTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/CategoryPointerAnnotationTest.trace org.jfree.chart.annotations.CategoryPointerAnnotationTest.testCloning:163:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest/CategoryPointerAnnotationTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/CategoryPointerAnnotationTest.trace org.jfree.chart.annotations.CategoryPointerAnnotationTest.testPublicCloneable:173:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest/CategoryPointerAnnotationTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/CategoryPointerAnnotationTest.trace org.jfree.chart.annotations.CategoryPointerAnnotationTest.testSerialization:185:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/CategoryPointerAnnotationTest/CategoryPointerAnnotationTest30.txt

#Total Asserts in org.jfree.chart.annotations/CategoryPointerAnnotationTest=============30
#Total Tests in org.jfree.chart.annotations/CategoryPointerAnnotationTest=============0
