#!/bin/bash

echo "computing slice for XYTitleAnnotationTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYTitleAnnotationTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYTitleAnnotationTest.trace org.jfree.chart.annotations.XYTitleAnnotationTest.testEquals:72:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYTitleAnnotationTest/XYTitleAnnotationTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYTitleAnnotationTest.trace org.jfree.chart.annotations.XYTitleAnnotationTest.testEquals:75:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYTitleAnnotationTest/XYTitleAnnotationTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYTitleAnnotationTest.trace org.jfree.chart.annotations.XYTitleAnnotationTest.testEquals:77:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYTitleAnnotationTest/XYTitleAnnotationTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYTitleAnnotationTest.trace org.jfree.chart.annotations.XYTitleAnnotationTest.testEquals:80:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYTitleAnnotationTest/XYTitleAnnotationTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYTitleAnnotationTest.trace org.jfree.chart.annotations.XYTitleAnnotationTest.testEquals:82:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYTitleAnnotationTest/XYTitleAnnotationTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYTitleAnnotationTest.trace org.jfree.chart.annotations.XYTitleAnnotationTest.testEquals:86:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYTitleAnnotationTest/XYTitleAnnotationTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYTitleAnnotationTest.trace org.jfree.chart.annotations.XYTitleAnnotationTest.testEquals:88:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYTitleAnnotationTest/XYTitleAnnotationTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYTitleAnnotationTest.trace org.jfree.chart.annotations.XYTitleAnnotationTest.testHashCode:99:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYTitleAnnotationTest/XYTitleAnnotationTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYTitleAnnotationTest.trace org.jfree.chart.annotations.XYTitleAnnotationTest.testHashCode:102:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYTitleAnnotationTest/XYTitleAnnotationTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYTitleAnnotationTest.trace org.jfree.chart.annotations.XYTitleAnnotationTest.testCloning:113:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYTitleAnnotationTest/XYTitleAnnotationTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYTitleAnnotationTest.trace org.jfree.chart.annotations.XYTitleAnnotationTest.testCloning:114:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYTitleAnnotationTest/XYTitleAnnotationTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYTitleAnnotationTest.trace org.jfree.chart.annotations.XYTitleAnnotationTest.testCloning:115:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYTitleAnnotationTest/XYTitleAnnotationTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYTitleAnnotationTest.trace org.jfree.chart.annotations.XYTitleAnnotationTest.testSerialization:126:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYTitleAnnotationTest/XYTitleAnnotationTest13.txt

#Total Asserts in org.jfree.chart.annotations/XYTitleAnnotationTest=============13
#Total Tests in org.jfree.chart.annotations/XYTitleAnnotationTest=============0
