#!/bin/bash

echo "computing slice for XYDrawableAnnotationTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYDrawableAnnotationTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYDrawableAnnotationTest.trace org.jfree.chart.annotations.XYDrawableAnnotationTest.testEquals:117:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYDrawableAnnotationTest/XYDrawableAnnotationTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYDrawableAnnotationTest.trace org.jfree.chart.annotations.XYDrawableAnnotationTest.testEquals:121:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYDrawableAnnotationTest/XYDrawableAnnotationTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYDrawableAnnotationTest.trace org.jfree.chart.annotations.XYDrawableAnnotationTest.testEquals:124:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYDrawableAnnotationTest/XYDrawableAnnotationTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYDrawableAnnotationTest.trace org.jfree.chart.annotations.XYDrawableAnnotationTest.testEquals:128:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYDrawableAnnotationTest/XYDrawableAnnotationTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYDrawableAnnotationTest.trace org.jfree.chart.annotations.XYDrawableAnnotationTest.testEquals:131:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYDrawableAnnotationTest/XYDrawableAnnotationTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYDrawableAnnotationTest.trace org.jfree.chart.annotations.XYDrawableAnnotationTest.testEquals:135:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYDrawableAnnotationTest/XYDrawableAnnotationTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYDrawableAnnotationTest.trace org.jfree.chart.annotations.XYDrawableAnnotationTest.testEquals:138:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYDrawableAnnotationTest/XYDrawableAnnotationTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYDrawableAnnotationTest.trace org.jfree.chart.annotations.XYDrawableAnnotationTest.testEquals:142:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYDrawableAnnotationTest/XYDrawableAnnotationTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYDrawableAnnotationTest.trace org.jfree.chart.annotations.XYDrawableAnnotationTest.testEquals:145:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYDrawableAnnotationTest/XYDrawableAnnotationTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYDrawableAnnotationTest.trace org.jfree.chart.annotations.XYDrawableAnnotationTest.testEquals:149:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYDrawableAnnotationTest/XYDrawableAnnotationTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYDrawableAnnotationTest.trace org.jfree.chart.annotations.XYDrawableAnnotationTest.testEquals:152:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYDrawableAnnotationTest/XYDrawableAnnotationTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYDrawableAnnotationTest.trace org.jfree.chart.annotations.XYDrawableAnnotationTest.testHashCode:164:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYDrawableAnnotationTest/XYDrawableAnnotationTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYDrawableAnnotationTest.trace org.jfree.chart.annotations.XYDrawableAnnotationTest.testHashCode:167:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYDrawableAnnotationTest/XYDrawableAnnotationTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYDrawableAnnotationTest.trace org.jfree.chart.annotations.XYDrawableAnnotationTest.testCloning:178:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYDrawableAnnotationTest/XYDrawableAnnotationTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYDrawableAnnotationTest.trace org.jfree.chart.annotations.XYDrawableAnnotationTest.testCloning:179:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYDrawableAnnotationTest/XYDrawableAnnotationTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYDrawableAnnotationTest.trace org.jfree.chart.annotations.XYDrawableAnnotationTest.testCloning:180:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYDrawableAnnotationTest/XYDrawableAnnotationTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYDrawableAnnotationTest.trace org.jfree.chart.annotations.XYDrawableAnnotationTest.testPublicCloneable:190:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYDrawableAnnotationTest/XYDrawableAnnotationTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/annotations_traces/XYDrawableAnnotationTest.trace org.jfree.chart.annotations.XYDrawableAnnotationTest.testSerialization:201:*>/home/stg/omc_experiments/slices/jfreechart/annotations_slices/XYDrawableAnnotationTest/XYDrawableAnnotationTest18.txt

#Total Asserts in org.jfree.chart.annotations/XYDrawableAnnotationTest=============18
#Total Tests in org.jfree.chart.annotations/XYDrawableAnnotationTest=============0
