#!/bin/bash

echo "computing slice for TestIndentation"

mkdir -p /home/stg/omc_experiments/slices/jackson-dataformat-xml/ser_slices/TestIndentation

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/ser_traces/TestIndentation.trace com.fasterxml.jackson.dataformat.xml.ser.TestIndentation.testSimpleStringBean:108:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/ser_slices/TestIndentation/TestIndentation1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/ser_traces/TestIndentation.trace com.fasterxml.jackson.dataformat.xml.ser.TestIndentation.testSimpleStringBean:109:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/ser_slices/TestIndentation/TestIndentation2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/ser_traces/TestIndentation.trace com.fasterxml.jackson.dataformat.xml.ser.TestIndentation.testSimpleStringBean:117:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/ser_slices/TestIndentation/TestIndentation3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/ser_traces/TestIndentation.trace com.fasterxml.jackson.dataformat.xml.ser.TestIndentation.testSimpleStringBean:118:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/ser_slices/TestIndentation/TestIndentation4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/ser_traces/TestIndentation.trace com.fasterxml.jackson.dataformat.xml.ser.TestIndentation.testSimpleIntBean:130:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/ser_slices/TestIndentation/TestIndentation5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/ser_traces/TestIndentation.trace com.fasterxml.jackson.dataformat.xml.ser.TestIndentation.testSimpleIntBean:131:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/ser_slices/TestIndentation/TestIndentation6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/ser_traces/TestIndentation.trace com.fasterxml.jackson.dataformat.xml.ser.TestIndentation.testSimpleMap:147:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/ser_slices/TestIndentation/TestIndentation7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/ser_traces/TestIndentation.trace com.fasterxml.jackson.dataformat.xml.ser.TestIndentation.testSimpleMap:148:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/ser_slices/TestIndentation/TestIndentation8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/ser_traces/TestIndentation.trace com.fasterxml.jackson.dataformat.xml.ser.TestIndentation.testSimpleMap:149:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/ser_slices/TestIndentation/TestIndentation9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/ser_traces/TestIndentation.trace com.fasterxml.jackson.dataformat.xml.ser.TestIndentation.testWithAttr:156:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/ser_slices/TestIndentation/TestIndentation10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/ser_traces/TestIndentation.trace com.fasterxml.jackson.dataformat.xml.ser.TestIndentation.testWithAttr:158:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/ser_slices/TestIndentation/TestIndentation11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/ser_traces/TestIndentation.trace com.fasterxml.jackson.dataformat.xml.ser.TestIndentation.testEmptyElem:165:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/ser_slices/TestIndentation/TestIndentation12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jackson-dataformat-xml/ser_traces/TestIndentation.trace com.fasterxml.jackson.dataformat.xml.ser.TestIndentation.testMultiLevel172:178:*>/home/stg/omc_experiments/slices/jackson-dataformat-xml/ser_slices/TestIndentation/TestIndentation13.txt

#Total Asserts in com.fasterxml.jackson.dataformat.xml.ser/TestIndentation=============13
#Total Tests in com.fasterxml.jackson.dataformat.xml.ser/TestIndentation=============0
