#!/bin/bash

echo "computing slice for StringUtilsTest"

mkdir -p /home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testGetBytesIso8859_1:58:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testGetBytesUnchecked:64:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testGetBytesUsAscii:73:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testGetBytesUtf16:82:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testGetBytesUtf16Be:91:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testGetBytesUtf16Le:100:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testGetBytesUtf8:109:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testGetBytesUncheckedNullInput:124:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testNewString:130:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testNewStringNullInput:145:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testNewStringNullInput_CODEC229:150:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testNewStringNullInput_CODEC229:151:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testNewStringNullInput_CODEC229:152:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testNewStringNullInput_CODEC229:153:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testNewStringNullInput_CODEC229:154:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testNewStringNullInput_CODEC229:155:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testNewStringIso8859_1:164:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testNewStringUsAscii:173:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testNewStringUtf16:182:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testNewStringUtf16Be:191:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testNewStringUtf16Le:200:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testNewStringUtf8:209:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testEqualsString:214:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testEqualsString:215:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testEqualsString:216:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testEqualsString:217:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testEqualsString:218:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testEqualsString:219:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testEqualsString:220:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testEqualsCS1:225:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testEqualsCS1:226:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testEqualsCS1:227:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest32.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testEqualsCS1:228:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest33.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testEqualsCS1:229:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest34.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testEqualsCS1:230:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest35.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testEqualsCS2:235:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest36.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testEqualsCS2:236:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest37.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testEqualsCS2:237:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest38.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/binary_traces/StringUtilsTest.trace org.apache.commons.codec.binary.StringUtilsTest.testEqualsCS2:238:*>/home/stg/omc_experiments/slices/commons-codec-1.12/binary_slices/StringUtilsTest/StringUtilsTest39.txt

#Total Asserts in org.apache.commons.codec.binary/StringUtilsTest=============39
#Total Tests in org.apache.commons.codec.binary/StringUtilsTest=============0
