#!/bin/bash

echo "computing slice for ExtendedMessageFormatTest"

mkdir -p /home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/ExtendedMessageFormatTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.lang3.text.ExtendedMessageFormatTest.testExtendedFormats:76:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.lang3.text.ExtendedMessageFormatTest.testExtendedFormats:77:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.lang3.text.ExtendedMessageFormatTest.testExtendedFormats:78:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.lang3.text.ExtendedMessageFormatTest.testExtendedFormats:79:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.lang3.text.ExtendedMessageFormatTest.testExtendedFormats:80:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.lang3.text.ExtendedMessageFormatTest.testExtendedFormats:81:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.lang3.text.ExtendedMessageFormatTest.testEscapedQuote_LANG_477:91:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.lang3.text.ExtendedMessageFormatTest.testEmbeddedPatternInChoice:101:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.lang3.text.ExtendedMessageFormatTest.testEscapedBraces_LANG_948:112:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.lang3.text.ExtendedMessageFormatTest.testEscapedBraces_LANG_948:117:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.lang3.text.ExtendedMessageFormatTest.testExtendedAndBuiltInFormats:159:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.lang3.text.ExtendedMessageFormatTest.testExtendedAndBuiltInFormats:160:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.lang3.text.ExtendedMessageFormatTest.testOverriddenBuiltinFormat:284:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.lang3.text.ExtendedMessageFormatTest.testOverriddenBuiltinFormat:285:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.lang3.text.ExtendedMessageFormatTest.testEqualsHashcode:317:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.lang3.text.ExtendedMessageFormatTest.testEqualsHashcode:318:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.lang3.text.ExtendedMessageFormatTest.testEqualsHashcode:322:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.lang3.text.ExtendedMessageFormatTest.testEqualsHashcode:323:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.lang3.text.ExtendedMessageFormatTest.testEqualsHashcode:327:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.lang3.text.ExtendedMessageFormatTest.testEqualsHashcode:328:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.lang3.text.ExtendedMessageFormatTest.testEqualsHashcode:332:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.lang3.text.ExtendedMessageFormatTest.testEqualsHashcode:333:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.lang3.text.ExtendedMessageFormatTest.testEqualsHashcode:337:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.lang3.text.ExtendedMessageFormatTest.testEqualsHashcode:338:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.lang3.text.ExtendedMessageFormatTest.testEqualsHashcode:342:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.lang3.text.ExtendedMessageFormatTest.testEqualsHashcode:343:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.lang3.text.ExtendedMessageFormatTest.checkBuiltInFormat:396:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/ExtendedMessageFormatTest.trace org.apache.commons.lang3.text.ExtendedMessageFormatTest.checkBuiltInFormat:397:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/ExtendedMessageFormatTest/ExtendedMessageFormatTest28.txt

#Total Asserts in org.apache.commons.lang3.text/ExtendedMessageFormatTest=============28
#Total Tests in org.apache.commons.lang3.text/ExtendedMessageFormatTest=============0
