#!/bin/bash

echo "computing slice for StrLookupTest"

mkdir -p /home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/StrLookupTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/StrLookupTest.trace org.apache.commons.lang3.text.StrLookupTest.testNoneLookup:48:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/StrLookupTest/StrLookupTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/StrLookupTest.trace org.apache.commons.lang3.text.StrLookupTest.testNoneLookup:49:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/StrLookupTest/StrLookupTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/StrLookupTest.trace org.apache.commons.lang3.text.StrLookupTest.testNoneLookup:50:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/StrLookupTest/StrLookupTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/StrLookupTest.trace org.apache.commons.lang3.text.StrLookupTest.testSystemPropertiesLookup:55:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/StrLookupTest/StrLookupTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/StrLookupTest.trace org.apache.commons.lang3.text.StrLookupTest.testSystemPropertiesLookup:56:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/StrLookupTest/StrLookupTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/StrLookupTest.trace org.apache.commons.lang3.text.StrLookupTest.testSystemPropertiesLookup:57:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/StrLookupTest/StrLookupTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/StrLookupTest.trace org.apache.commons.lang3.text.StrLookupTest.testSystemPropertiesLookupReplacedProperties:82:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/StrLookupTest/StrLookupTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/StrLookupTest.trace org.apache.commons.lang3.text.StrLookupTest.testSystemPropertiesLookupUpdatedProperty:101:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/StrLookupTest/StrLookupTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/StrLookupTest.trace org.apache.commons.lang3.text.StrLookupTest.testMapLookup:112:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/StrLookupTest/StrLookupTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/StrLookupTest.trace org.apache.commons.lang3.text.StrLookupTest.testMapLookup:113:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/StrLookupTest/StrLookupTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/StrLookupTest.trace org.apache.commons.lang3.text.StrLookupTest.testMapLookup:114:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/StrLookupTest/StrLookupTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/StrLookupTest.trace org.apache.commons.lang3.text.StrLookupTest.testMapLookup:115:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/StrLookupTest/StrLookupTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/StrLookupTest.trace org.apache.commons.lang3.text.StrLookupTest.testMapLookup:116:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/StrLookupTest/StrLookupTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/StrLookupTest.trace org.apache.commons.lang3.text.StrLookupTest.testMapLookup_nullMap:122:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/StrLookupTest/StrLookupTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/StrLookupTest.trace org.apache.commons.lang3.text.StrLookupTest.testMapLookup_nullMap:123:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/StrLookupTest/StrLookupTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/fse-commons-lang-3.6/text_traces/StrLookupTest.trace org.apache.commons.lang3.text.StrLookupTest.testMapLookup_nullMap:124:*>/home/stg/omc_experiments/slices/fse-commons-lang-3.6/text_slices/StrLookupTest/StrLookupTest16.txt

#Total Asserts in org.apache.commons.lang3.text/StrLookupTest=============16
#Total Tests in org.apache.commons.lang3.text/StrLookupTest=============0
