#!/bin/bash

echo "computing slice for PercentCodecTest"

mkdir -p /home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/PercentCodecTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/PercentCodecTest.trace org.apache.commons.codec.net.PercentCodecTest.testBasicEncodeDecode:45:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/PercentCodecTest/PercentCodecTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/PercentCodecTest.trace org.apache.commons.codec.net.PercentCodecTest.testBasicEncodeDecode:46:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/PercentCodecTest/PercentCodecTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/PercentCodecTest.trace org.apache.commons.codec.net.PercentCodecTest.testBasicSpace:55:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/PercentCodecTest/PercentCodecTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/PercentCodecTest.trace org.apache.commons.codec.net.PercentCodecTest.testConfigurablePercentEncoder:64:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/PercentCodecTest/PercentCodecTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/PercentCodecTest.trace org.apache.commons.codec.net.PercentCodecTest.testConfigurablePercentEncoder:66:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/PercentCodecTest/PercentCodecTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/PercentCodecTest.trace org.apache.commons.codec.net.PercentCodecTest.testDecodeInvalidEncodedResultDecoding:77:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/PercentCodecTest/PercentCodecTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/PercentCodecTest.trace org.apache.commons.codec.net.PercentCodecTest.testDecodeNullObject:85:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/PercentCodecTest/PercentCodecTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/PercentCodecTest.trace org.apache.commons.codec.net.PercentCodecTest.testEncodeNullObject:97:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/PercentCodecTest/PercentCodecTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/PercentCodecTest.trace org.apache.commons.codec.net.PercentCodecTest.testPercentEncoderDecoderWithNullOrEmptyInput:109:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/PercentCodecTest/PercentCodecTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/PercentCodecTest.trace org.apache.commons.codec.net.PercentCodecTest.testPercentEncoderDecoderWithNullOrEmptyInput:110:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/PercentCodecTest/PercentCodecTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/PercentCodecTest.trace org.apache.commons.codec.net.PercentCodecTest.testPercentEncoderDecoderWithNullOrEmptyInput:112:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/PercentCodecTest/PercentCodecTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/PercentCodecTest.trace org.apache.commons.codec.net.PercentCodecTest.testPercentEncoderDecoderWithNullOrEmptyInput:113:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/PercentCodecTest/PercentCodecTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/PercentCodecTest.trace org.apache.commons.codec.net.PercentCodecTest.testPercentEncoderDecoderWithPlusForSpace:122:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/PercentCodecTest/PercentCodecTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/PercentCodecTest.trace org.apache.commons.codec.net.PercentCodecTest.testPercentEncoderDecoderWithPlusForSpace:124:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/PercentCodecTest/PercentCodecTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/PercentCodecTest.trace org.apache.commons.codec.net.PercentCodecTest.testSafeCharEncodeDecodeObject:135:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/PercentCodecTest/PercentCodecTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/PercentCodecTest.trace org.apache.commons.codec.net.PercentCodecTest.testSafeCharEncodeDecodeObject:136:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/PercentCodecTest/PercentCodecTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/PercentCodecTest.trace org.apache.commons.codec.net.PercentCodecTest.testUnsafeCharEncodeDecode:147:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/PercentCodecTest/PercentCodecTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/PercentCodecTest.trace org.apache.commons.codec.net.PercentCodecTest.testUnsafeCharEncodeDecode:148:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/PercentCodecTest/PercentCodecTest18.txt

#Total Asserts in org.apache.commons.codec.net/PercentCodecTest=============18
#Total Tests in org.apache.commons.codec.net/PercentCodecTest=============0
