#!/bin/bash

echo "computing slice for URLCodecTest"

mkdir -p /home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/URLCodecTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/URLCodecTest.trace org.apache.commons.codec.net.URLCodecTest.testUTF8RoundTrip:71:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/URLCodecTest/URLCodecTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/URLCodecTest.trace org.apache.commons.codec.net.URLCodecTest.testUTF8RoundTrip:75:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/URLCodecTest/URLCodecTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/URLCodecTest.trace org.apache.commons.codec.net.URLCodecTest.testUTF8RoundTrip:77:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/URLCodecTest/URLCodecTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/URLCodecTest.trace org.apache.commons.codec.net.URLCodecTest.testUTF8RoundTrip:78:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/URLCodecTest/URLCodecTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/URLCodecTest.trace org.apache.commons.codec.net.URLCodecTest.testBasicEncodeDecode:87:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/URLCodecTest/URLCodecTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/URLCodecTest.trace org.apache.commons.codec.net.URLCodecTest.testBasicEncodeDecode:89:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/URLCodecTest/URLCodecTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/URLCodecTest.trace org.apache.commons.codec.net.URLCodecTest.testSafeCharEncodeDecode:100:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/URLCodecTest/URLCodecTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/URLCodecTest.trace org.apache.commons.codec.net.URLCodecTest.testSafeCharEncodeDecode:102:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/URLCodecTest/URLCodecTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/URLCodecTest.trace org.apache.commons.codec.net.URLCodecTest.testUnsafeEncodeDecode:113:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/URLCodecTest/URLCodecTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/URLCodecTest.trace org.apache.commons.codec.net.URLCodecTest.testUnsafeEncodeDecode:115:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/URLCodecTest/URLCodecTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/URLCodecTest.trace org.apache.commons.codec.net.URLCodecTest.testEncodeDecodeNull:124:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/URLCodecTest/URLCodecTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/URLCodecTest.trace org.apache.commons.codec.net.URLCodecTest.testEncodeDecodeNull:126:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/URLCodecTest/URLCodecTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/URLCodecTest.trace org.apache.commons.codec.net.URLCodecTest.testDecodeInvalidContent:170:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/URLCodecTest/URLCodecTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/URLCodecTest.trace org.apache.commons.codec.net.URLCodecTest.testDecodeInvalidContent:172:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/URLCodecTest/URLCodecTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/URLCodecTest.trace org.apache.commons.codec.net.URLCodecTest.testEncodeNull:182:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/URLCodecTest/URLCodecTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/URLCodecTest.trace org.apache.commons.codec.net.URLCodecTest.testEncodeUrlWithNullBitSet:192:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/URLCodecTest/URLCodecTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/URLCodecTest.trace org.apache.commons.codec.net.URLCodecTest.testEncodeUrlWithNullBitSet:194:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/URLCodecTest/URLCodecTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/URLCodecTest.trace org.apache.commons.codec.net.URLCodecTest.testDecodeWithNullArray:203:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/URLCodecTest/URLCodecTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/URLCodecTest.trace org.apache.commons.codec.net.URLCodecTest.testEncodeStringWithNull:211:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/URLCodecTest/URLCodecTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/URLCodecTest.trace org.apache.commons.codec.net.URLCodecTest.testDecodeStringWithNull:219:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/URLCodecTest/URLCodecTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/URLCodecTest.trace org.apache.commons.codec.net.URLCodecTest.testEncodeObjects:227:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/URLCodecTest/URLCodecTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/URLCodecTest.trace org.apache.commons.codec.net.URLCodecTest.testEncodeObjects:233:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/URLCodecTest/URLCodecTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/URLCodecTest.trace org.apache.commons.codec.net.URLCodecTest.testEncodeObjects:237:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/URLCodecTest/URLCodecTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/URLCodecTest.trace org.apache.commons.codec.net.URLCodecTest.testDecodeObjects:273:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/URLCodecTest/URLCodecTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/URLCodecTest.trace org.apache.commons.codec.net.URLCodecTest.testDecodeObjects:279:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/URLCodecTest/URLCodecTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/URLCodecTest.trace org.apache.commons.codec.net.URLCodecTest.testDecodeObjects:283:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/URLCodecTest/URLCodecTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/URLCodecTest.trace org.apache.commons.codec.net.URLCodecTest.testDefaultEncoding:302:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/URLCodecTest/URLCodecTest27.txt

#Total Asserts in org.apache.commons.codec.net/URLCodecTest=============27
#Total Tests in org.apache.commons.codec.net/URLCodecTest=============0
