#!/bin/bash

echo "computing slice for QCodecTest"

mkdir -p /home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QCodecTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QCodecTest.trace org.apache.commons.codec.net.QCodecTest.testNullInput:63:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QCodecTest/QCodecTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QCodecTest.trace org.apache.commons.codec.net.QCodecTest.testNullInput:64:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QCodecTest/QCodecTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QCodecTest.trace org.apache.commons.codec.net.QCodecTest.testUTF8RoundTrip:75:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QCodecTest/QCodecTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QCodecTest.trace org.apache.commons.codec.net.QCodecTest.testUTF8RoundTrip:79:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QCodecTest/QCodecTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QCodecTest.trace org.apache.commons.codec.net.QCodecTest.testUTF8RoundTrip:81:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QCodecTest/QCodecTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QCodecTest.trace org.apache.commons.codec.net.QCodecTest.testUTF8RoundTrip:82:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QCodecTest/QCodecTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QCodecTest.trace org.apache.commons.codec.net.QCodecTest.testBasicEncodeDecode:91:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QCodecTest/QCodecTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QCodecTest.trace org.apache.commons.codec.net.QCodecTest.testBasicEncodeDecode:93:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QCodecTest/QCodecTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QCodecTest.trace org.apache.commons.codec.net.QCodecTest.testUnsafeEncodeDecode:102:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QCodecTest/QCodecTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QCodecTest.trace org.apache.commons.codec.net.QCodecTest.testUnsafeEncodeDecode:104:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QCodecTest/QCodecTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QCodecTest.trace org.apache.commons.codec.net.QCodecTest.testEncodeDecodeNull:111:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QCodecTest/QCodecTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QCodecTest.trace org.apache.commons.codec.net.QCodecTest.testEncodeDecodeNull:113:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QCodecTest/QCodecTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QCodecTest.trace org.apache.commons.codec.net.QCodecTest.testEncodeStringWithNull:122:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QCodecTest/QCodecTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QCodecTest.trace org.apache.commons.codec.net.QCodecTest.testDecodeStringWithNull:130:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QCodecTest/QCodecTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QCodecTest.trace org.apache.commons.codec.net.QCodecTest.testEncodeObjects:139:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QCodecTest/QCodecTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QCodecTest.trace org.apache.commons.codec.net.QCodecTest.testEncodeObjects:143:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QCodecTest/QCodecTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QCodecTest.trace org.apache.commons.codec.net.QCodecTest.testDecodeObjects:165:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QCodecTest/QCodecTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QCodecTest.trace org.apache.commons.codec.net.QCodecTest.testDecodeObjects:169:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QCodecTest/QCodecTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QCodecTest.trace org.apache.commons.codec.net.QCodecTest.testEncodeDecodeBlanks:189:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QCodecTest/QCodecTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QCodecTest.trace org.apache.commons.codec.net.QCodecTest.testEncodeDecodeBlanks:192:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QCodecTest/QCodecTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QCodecTest.trace org.apache.commons.codec.net.QCodecTest.testEncodeDecodeBlanks:194:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QCodecTest/QCodecTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QCodecTest.trace org.apache.commons.codec.net.QCodecTest.testEncodeDecodeBlanks:196:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QCodecTest/QCodecTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QCodecTest.trace org.apache.commons.codec.net.QCodecTest.testLetUsMakeCloverHappy:204:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QCodecTest/QCodecTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QCodecTest.trace org.apache.commons.codec.net.QCodecTest.testLetUsMakeCloverHappy:206:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QCodecTest/QCodecTest24.txt

#Total Asserts in org.apache.commons.codec.net/QCodecTest=============24
#Total Tests in org.apache.commons.codec.net/QCodecTest=============0
