#!/bin/bash

echo "computing slice for QuotedPrintableCodecTest"

mkdir -p /home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testUTF8RoundTrip:64:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testUTF8RoundTrip:68:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testUTF8RoundTrip:70:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testUTF8RoundTrip:71:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testBasicEncodeDecode:79:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testBasicEncodeDecode:81:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testSafeCharEncodeDecode:90:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testSafeCharEncodeDecode:92:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testUnsafeEncodeDecode:102:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testUnsafeEncodeDecode:104:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testEncodeDecodeNull:111:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testEncodeDecodeNull:113:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testEncodeNull:146:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testEncodeUrlWithNullBitSet:156:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testEncodeUrlWithNullBitSet:158:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testDecodeWithNullArray:167:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testEncodeStringWithNull:175:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testDecodeStringWithNull:183:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testEncodeObjects:191:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testEncodeObjects:197:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testEncodeObjects:201:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testDecodeObjects:222:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testDecodeObjects:228:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testDecodeObjects:232:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testDefaultEncoding:250:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testSoftLineBreakDecode:259:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testSoftLineBreakDecode:262:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testSoftLineBreakEncode:271:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testSoftLineBreakEncode:274:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testSkipNotEncodedCRLF:283:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testSkipNotEncodedCRLF:286:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testTrailingSpecial:295:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest32.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testTrailingSpecial:299:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest33.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testUltimateSoftBreak:309:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest34.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testUltimateSoftBreak:314:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest35.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testUltimateSoftBreak:320:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest36.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testUltimateSoftBreak:326:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest37.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/commons-codec-1.12/net_traces/QuotedPrintableCodecTest.trace org.apache.commons.codec.net.QuotedPrintableCodecTest.testFinalBytes:335:*>/home/stg/omc_experiments/slices/commons-codec-1.12/net_slices/QuotedPrintableCodecTest/QuotedPrintableCodecTest38.txt

#Total Asserts in org.apache.commons.codec.net/QuotedPrintableCodecTest=============38
#Total Tests in org.apache.commons.codec.net/QuotedPrintableCodecTest=============0
