#!/bin/bash

echo "computing slice for CompositeTitleTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/title_slices/CompositeTitleTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/CompositeTitleTest.trace org.jfree.chart.title.CompositeTitleTest.testConstructor:71:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/CompositeTitleTest/CompositeTitleTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/CompositeTitleTest.trace org.jfree.chart.title.CompositeTitleTest.testEquals:81:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/CompositeTitleTest/CompositeTitleTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/CompositeTitleTest.trace org.jfree.chart.title.CompositeTitleTest.testEquals:82:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/CompositeTitleTest/CompositeTitleTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/CompositeTitleTest.trace org.jfree.chart.title.CompositeTitleTest.testEquals:86:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/CompositeTitleTest/CompositeTitleTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/CompositeTitleTest.trace org.jfree.chart.title.CompositeTitleTest.testEquals:88:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/CompositeTitleTest/CompositeTitleTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/CompositeTitleTest.trace org.jfree.chart.title.CompositeTitleTest.testEquals:92:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/CompositeTitleTest/CompositeTitleTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/CompositeTitleTest.trace org.jfree.chart.title.CompositeTitleTest.testEquals:94:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/CompositeTitleTest/CompositeTitleTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/CompositeTitleTest.trace org.jfree.chart.title.CompositeTitleTest.testEquals:98:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/CompositeTitleTest/CompositeTitleTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/CompositeTitleTest.trace org.jfree.chart.title.CompositeTitleTest.testEquals:100:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/CompositeTitleTest/CompositeTitleTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/CompositeTitleTest.trace org.jfree.chart.title.CompositeTitleTest.testEquals:104:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/CompositeTitleTest/CompositeTitleTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/CompositeTitleTest.trace org.jfree.chart.title.CompositeTitleTest.testEquals:106:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/CompositeTitleTest/CompositeTitleTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/CompositeTitleTest.trace org.jfree.chart.title.CompositeTitleTest.testEquals:110:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/CompositeTitleTest/CompositeTitleTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/CompositeTitleTest.trace org.jfree.chart.title.CompositeTitleTest.testEquals:113:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/CompositeTitleTest/CompositeTitleTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/CompositeTitleTest.trace org.jfree.chart.title.CompositeTitleTest.testHashcode:126:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/CompositeTitleTest/CompositeTitleTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/CompositeTitleTest.trace org.jfree.chart.title.CompositeTitleTest.testHashcode:129:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/CompositeTitleTest/CompositeTitleTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/CompositeTitleTest.trace org.jfree.chart.title.CompositeTitleTest.testCloning:148:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/CompositeTitleTest/CompositeTitleTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/CompositeTitleTest.trace org.jfree.chart.title.CompositeTitleTest.testCloning:149:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/CompositeTitleTest/CompositeTitleTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/CompositeTitleTest.trace org.jfree.chart.title.CompositeTitleTest.testCloning:150:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/CompositeTitleTest/CompositeTitleTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/CompositeTitleTest.trace org.jfree.chart.title.CompositeTitleTest.testSerialization:163:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/CompositeTitleTest/CompositeTitleTest19.txt

#Total Asserts in org.jfree.chart.title/CompositeTitleTest=============19
#Total Tests in org.jfree.chart.title/CompositeTitleTest=============0
