#!/bin/bash

echo "computing slice for PaintScaleLegendTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/title_slices/PaintScaleLegendTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/PaintScaleLegendTest.trace org.jfree.chart.title.PaintScaleLegendTest.testEquals:76:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/PaintScaleLegendTest/PaintScaleLegendTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/PaintScaleLegendTest.trace org.jfree.chart.title.PaintScaleLegendTest.testEquals:77:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/PaintScaleLegendTest/PaintScaleLegendTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/PaintScaleLegendTest.trace org.jfree.chart.title.PaintScaleLegendTest.testEquals:81:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/PaintScaleLegendTest/PaintScaleLegendTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/PaintScaleLegendTest.trace org.jfree.chart.title.PaintScaleLegendTest.testEquals:83:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/PaintScaleLegendTest/PaintScaleLegendTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/PaintScaleLegendTest.trace org.jfree.chart.title.PaintScaleLegendTest.testEquals:87:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/PaintScaleLegendTest/PaintScaleLegendTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/PaintScaleLegendTest.trace org.jfree.chart.title.PaintScaleLegendTest.testEquals:89:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/PaintScaleLegendTest/PaintScaleLegendTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/PaintScaleLegendTest.trace org.jfree.chart.title.PaintScaleLegendTest.testEquals:93:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/PaintScaleLegendTest/PaintScaleLegendTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/PaintScaleLegendTest.trace org.jfree.chart.title.PaintScaleLegendTest.testEquals:95:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/PaintScaleLegendTest/PaintScaleLegendTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/PaintScaleLegendTest.trace org.jfree.chart.title.PaintScaleLegendTest.testEquals:99:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/PaintScaleLegendTest/PaintScaleLegendTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/PaintScaleLegendTest.trace org.jfree.chart.title.PaintScaleLegendTest.testEquals:101:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/PaintScaleLegendTest/PaintScaleLegendTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/PaintScaleLegendTest.trace org.jfree.chart.title.PaintScaleLegendTest.testEquals:105:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/PaintScaleLegendTest/PaintScaleLegendTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/PaintScaleLegendTest.trace org.jfree.chart.title.PaintScaleLegendTest.testEquals:107:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/PaintScaleLegendTest/PaintScaleLegendTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/PaintScaleLegendTest.trace org.jfree.chart.title.PaintScaleLegendTest.testEquals:111:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/PaintScaleLegendTest/PaintScaleLegendTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/PaintScaleLegendTest.trace org.jfree.chart.title.PaintScaleLegendTest.testEquals:113:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/PaintScaleLegendTest/PaintScaleLegendTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/PaintScaleLegendTest.trace org.jfree.chart.title.PaintScaleLegendTest.testEquals:118:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/PaintScaleLegendTest/PaintScaleLegendTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/PaintScaleLegendTest.trace org.jfree.chart.title.PaintScaleLegendTest.testEquals:121:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/PaintScaleLegendTest/PaintScaleLegendTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/PaintScaleLegendTest.trace org.jfree.chart.title.PaintScaleLegendTest.testEquals:125:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/PaintScaleLegendTest/PaintScaleLegendTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/PaintScaleLegendTest.trace org.jfree.chart.title.PaintScaleLegendTest.testEquals:127:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/PaintScaleLegendTest/PaintScaleLegendTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/PaintScaleLegendTest.trace org.jfree.chart.title.PaintScaleLegendTest.testEquals:132:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/PaintScaleLegendTest/PaintScaleLegendTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/PaintScaleLegendTest.trace org.jfree.chart.title.PaintScaleLegendTest.testEquals:135:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/PaintScaleLegendTest/PaintScaleLegendTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/PaintScaleLegendTest.trace org.jfree.chart.title.PaintScaleLegendTest.testEquals:138:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/PaintScaleLegendTest/PaintScaleLegendTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/PaintScaleLegendTest.trace org.jfree.chart.title.PaintScaleLegendTest.testEquals:140:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/PaintScaleLegendTest/PaintScaleLegendTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/PaintScaleLegendTest.trace org.jfree.chart.title.PaintScaleLegendTest.testHashcode:153:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/PaintScaleLegendTest/PaintScaleLegendTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/PaintScaleLegendTest.trace org.jfree.chart.title.PaintScaleLegendTest.testHashcode:156:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/PaintScaleLegendTest/PaintScaleLegendTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/PaintScaleLegendTest.trace org.jfree.chart.title.PaintScaleLegendTest.testCloning:167:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/PaintScaleLegendTest/PaintScaleLegendTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/PaintScaleLegendTest.trace org.jfree.chart.title.PaintScaleLegendTest.testCloning:168:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/PaintScaleLegendTest/PaintScaleLegendTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/PaintScaleLegendTest.trace org.jfree.chart.title.PaintScaleLegendTest.testCloning:169:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/PaintScaleLegendTest/PaintScaleLegendTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/title_traces/PaintScaleLegendTest.trace org.jfree.chart.title.PaintScaleLegendTest.testSerialization:180:*>/home/stg/omc_experiments/slices/jfreechart/title_slices/PaintScaleLegendTest/PaintScaleLegendTest28.txt

#Total Asserts in org.jfree.chart.title/PaintScaleLegendTest=============28
#Total Tests in org.jfree.chart.title/PaintScaleLegendTest=============0
