#!/bin/bash

echo "computing slice for JFreeChartTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testEquals:112:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testEquals:113:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testEquals:119:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testEquals:123:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testEquals:127:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testEquals:129:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testEquals:134:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testEquals:136:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testEquals:140:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testEquals:142:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testEquals:146:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testEquals:148:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testEquals:152:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testEquals:154:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testEquals:158:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testEquals:160:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testEquals:167:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testEquals:170:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testEquals:175:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testEquals:178:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testEquals:188:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testEquals:190:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testEquals:194:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testEquals:196:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testEquals2:209:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testEquals2:210:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testSubtitleCount:219:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testGetSubtitle:230:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testGetSubtitle:237:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testGetSubtitle:245:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testGetSubtitle:253:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testSerialization1:270:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest32.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testSerialization1:272:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest33.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testSerialization2:286:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest34.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testSerialization3:344:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest35.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testSerialization4:364:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest36.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testAddSubtitle:377:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest37.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testAddSubtitle:381:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest38.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testAddSubtitle:388:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest39.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testAddSubtitle:396:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest40.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testAddSubtitle:404:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest41.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testGetSubtitles:418:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest42.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testGetSubtitles:422:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest43.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testLegendEvents:436:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest44.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testTitleChangeEvent:450:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest45.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testTitleChangeEvent:461:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest46.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testTitleChangeEvent:465:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest47.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testTitleChangeEvent:469:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest48.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/JFreeChartTest.trace org.jfree.chart.JFreeChartTest.testBug942:476:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/JFreeChartTest/JFreeChartTest49.txt

#Total Asserts in org.jfree.chart/JFreeChartTest=============49
#Total Tests in org.jfree.chart/JFreeChartTest=============0
