#!/bin/bash

echo "computing slice for LegendItemTest"

mkdir -p /home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest

java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:90:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest1.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:91:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest2.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:98:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest3.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:104:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest4.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:111:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest5.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:117:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest6.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:124:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest7.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:130:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest8.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:137:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest9.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:143:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest10.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:150:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest11.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:156:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest12.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:163:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest13.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:169:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest14.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:176:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest15.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:182:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest16.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:189:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest17.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:195:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest18.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:202:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest19.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:208:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest20.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:215:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest21.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:221:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest22.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:228:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest23.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:234:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest24.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:241:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest25.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:247:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest26.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:255:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest27.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:262:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest28.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:267:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest29.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:270:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest30.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:274:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest31.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:276:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest32.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:280:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest33.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:282:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest34.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:287:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest35.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:290:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest36.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:295:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest37.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:298:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest38.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:303:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest39.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testEquals:306:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest40.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testSerialization:326:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest41.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testSerialization2:339:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest42.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testCloning:350:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest43.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testCloning:351:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest44.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testCloning:352:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest45.txt
java -Xmx30g -XX:-UseGCOverheadLimit  -XX:+UseG1GC -jar /home/stg/omcj/lib/slicer.jar -m=1 -p /home/stg/omc_experiments/traces/jfreechart/chart_traces/LegendItemTest.trace org.jfree.chart.LegendItemTest.testCloning:355:*>/home/stg/omc_experiments/slices/jfreechart/chart_slices/LegendItemTest/LegendItemTest46.txt

#Total Asserts in org.jfree.chart/LegendItemTest=============46
#Total Tests in org.jfree.chart/LegendItemTest=============0
